### ISSUE TITLE
Printer - Which one should we get?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hq#1]
@iteles As you know, our Samsung Printer has been playing up for a while.
Question is: should we take it into PC World (*today*) and see if they can repair it?
***or***... simply cut our losses and order a new one?

Inkjet vs Laser: http://www.theguardian.com/money/2013/mar/30/inkjet-or-laser-printing-cost-effective

**Comment by nelsonic** [comment]
My idea would be to buy a ***good*** **InkJet** printer (with reasonably priced ink cartridges) that can print high quality photos. And start plastering our walls with all the amazing photos *you* have taken...!

**Comment by nelsonic** [comment]
Best InkJet for photos in 2015: http://www.alphr.com/printers/1000167/best-printers-for-professional-prints-2015

**Comment by nelsonic** [comment]
The **Epson Expression Photo XP-950 A3 All-In-One Printer** does pretty much everything... and *crucially* the inks are *cheap*.
http://www.amazon.co.uk/Epson-Expression-Printer-Printing-Touchscreen/dp/B00ECBS5B4/

**Comment by nelsonic** [comment]
The **XP-960** has been announced but isn't yet available to buy... https://www.epson.co.uk/gb/en/viewcon/corporatesite/products/mainunits/overview/15975
Main difference is a **bigger touch-screen** for interacting with the printer...

**Comment by iteles** [comment]
I didn't think it was possible, but the bigger screen is pretty much the main difference. I don't think the differences are worth £70 (the price of a 4G portable router #2 ).

I haven't been able to hook Macs up to the old printer for about a year, it's just impossible to find the right drivers (and I've wasted hours on it - even when it looks like the right one... turns out not to be!).

**Comment by nelsonic** [comment]
@iteles You don't need *drivers* to connect to the Samsung printer... Its a network printer you can add using "AppleTalk"...

**Comment by nelsonic** [comment]
Should we just order the **XP-950** to PC World (click-and-collect) and go pick it up some time this week?

**Comment by iteles** [comment]
Sounds like a plan :+1:

**Comment by nelsonic** [comment]
Marvellously. Both the XP-950 and XP-960 are out-of-stock *everywhere* now ...

<img width="1102" alt="xp-950-out-of-stock" src="https://cloud.githubusercontent.com/assets/194400/9932674/ae6d9bbc-5d3d-11e5-84a4-aa031f2533c3.png">

**Comment by nelsonic** [comment]
The **Epson EcoTank L455** could be an option...
<img width="995" alt="epson-ecotank-l455-amazon" src="https://cloud.githubusercontent.com/assets/194400/9974940/e5798922-5ea0-11e5-953f-542c463c3c28.png">

http://www.amazon.co.uk/Epson-EcoTank-Multifunction-InkTank-Printer/dp/B00WX5T9HA/

**Comment by nelsonic** [comment]
Like the look of the **Canon PIXMA iP8750**
<img width="936" alt="canon-pixma-ip8750" src="https://cloud.githubusercontent.com/assets/194400/9974960/82fbd93e-5ea1-11e5-9b98-757a5922ea13.png">
http://www.amazon.co.uk/computers/dp/B00I3ZISVW/

Especially the *cheap* ink: http://www.amazon.co.uk/dp/B00P6JLL6C
<img width="965" alt="canon-pixma-ip8750-cheap-ink" src="https://cloud.githubusercontent.com/assets/194400/9974967/c17c34e2-5ea1-11e5-897f-091aaabbbcee.png">

But the lack of an LCD is off-putting because we won't know what's going on and it might be hard to setup on the wifi network without any form of input ...

**Comment by nelsonic** [comment]
Another option is **EPSON Workforce WF-7620 DTWF** 
<img width="1254" alt="epson-workforce-wf-7620-pc-world" src="https://cloud.githubusercontent.com/assets/194400/9975167/ccee6a40-5ea9-11e5-88ec-145814b9ce0b.png">

Which is £199 at PC World (but £229 on Amazon!)
http://www.pcworld.co.uk/gbuk/computing-accessories/printers-scanners-and-ink/printers/epson-workforce-wf-7620-dtwf-all-in-one-wireless-a3-inkjet-printer-with-fax-22067011-pdt.html

And *also* has cheap inks:

<img width="1052" alt="epson-workforce-wf-7620-cheap-inks" src="https://cloud.githubusercontent.com/assets/194400/9975068/4a6775a2-5ea5-11e5-95f8-c7ff2172468a.png">

**Comment by nelsonic** [comment]
@iteles i'm a bit undecided here ... I would *really* like to have an *impressively* good ***Photo*** **Printer** which we could use to *plaster* our walls with amaze photos https://github.com/dwyl/summer-2015/issues/45#issuecomment-136034401 On that note should we just get the Canon https://github.com/dwyl/hq/issues/1#issuecomment-141631126 which by many accounts has *great* quality photos?

**Comment by iteles** [comment]
I would always lean towards Canons over other printers if the aim is _great photographic quality_, but this is just because I've seen **a lot** of proof of how great Canon printer photos can be. They partner with a ton of craft bloggers on photo projects and they're intelligent about getting the quality photo word out there.

The _one thing **that puts me off the Canon**_ is that it doesn't do double sided printing.

**Comment by nelsonic** [comment]
@iteles do you consider the double-sided printing to be a useful feature? are you going to be duplexing a lot...?

**Comment by iteles** [comment]
@nelsonic I think most of our printing will be to put stuff on walls _if we have to_. I'd like to discourage printing off documents to read for example, but should we need to print off contracts etc, that [should _always_ be double sided](https://raw.githubusercontent.com/dwyl/start-here/master/manifesto.md).

**Comment by nelsonic** [comment]
Ok... sounds like the Epson (*with duplex*) might be the one to go for then ...

**Comment by iteles** [comment]
[Epson Expression XP-960](http://www.epson.co.uk/gb/en/viewcon/corporatesite/products/mainunits/specs/15975) assuming we can find cheap inks for it. If not, Canon Pixma :+1:

**Comment by nelsonic** [comment]
Right, I'm thinking Canon Pixma for *Photos* and then a *cheap-er* A4 Duplex ?

**Comment by iteles** [comment]
:+1: Get the Pixma. 

The second we find a need to start printing _documents_ (which as we mentioned, we discourage unless required :evergreen_tree:), we'll look into a cheaper A4 duplex. 

Let me know if you want company going to the shops! :kissing_heart:

**Comment by nelsonic** [comment]
Ordered the Canon. I bit of a *Joke* that its going to take till ***FRIDAY*** to be available ...

![pc-world-processing-order](https://cloud.githubusercontent.com/assets/194400/9977445/5b5d43c2-5f00-11e5-8744-09a1bdcce2f8.png)

But what-evs. means we can do a Printing and Collage Fun Times Hour *next* Saturday morning ... :wink:

**Comment by iteles** [comment]
:heart: :wink:

**Comment by iteles** [comment]
@nelsonic Are you ordering the inks from Amazon or am I? :kissing_heart:

**Comment by nelsonic** [comment]
The printer will come with inks. what we *should* order is [***A3 Photo Paper***](http://www.amazon.co.uk/s/ref=nb_sb_noss?url=search-alias%3Daps&field-keywords=A3+Photo+Paper) ... :open_mouth: :wink:

**Comment by iteles** [comment]
For the record we have about 3 boxes of _A4_ photo paper :stuck_out_tongue:

**Comment by nelsonic** [comment]
Yeah, we should get down some of that too.

**Comment by nelsonic** [comment]
Good news! :package: *early*!
![pcworld-printer](https://cloud.githubusercontent.com/assets/194400/9989988/392c580a-6055-11e5-8bfe-3ba8fa6e8ec7.png)
Shop closes 20:00 so we can grab it on our way home or pick up a ZipCar and collect that way.

**Comment by nelsonic** [comment]
@iteles ordering this Paper: http://www.amazon.co.uk/Epson-Archival-Matte-Paper-Sheets/dp/B000092QYW

**Comment by iteles** [comment]
@nelsonic The A3 version would be great (thought archival is maybe unnecessary, it's great quality :wink: )

**Comment by iteles** [comment]
Done! Oops! Late in closing this one :100:

**Comment by nelsonic** [comment]
Sucks that it takes *ages* to "*warm up*" ... :snail: 
really need to print off some "*mood board*" pics soon... :wink:

**Comment by iteles** [comment]
Good thing to do for the ART project!
