### ISSUE TITLE
Unlimited Fruit & Veg

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hq#10]
What it would it cost us to offer everyone on the "_core_" team unlimited Fruit & Veg every day?

We've both worked in places with "free" fruit, often there would be 50 pieces for 150 staff members so on a first-come-first-served basis the early birds would get all the fruit (_often like a swarm-of-locusts!_) but the point is there is/was never enough to go around...

**_What if**_ as one of the perks for working with **dwyl** people got **_unlimited fresh ingredients**_...?

**Comment by iteles** [comment]
I've _always_ thought this would be amazing and we've talked about providing this for as long as I can remember. Will put some thought into costs this weekend once I scope out our local markets :+1:

**Comment by nelsonic** [comment]
We can make people a pretty compelling offer with Unlimited Free Healthy Food + All the Appliances to turn them into anything else (Smoothies, Juices, Dehydrated Snacks!)
I'm *excited*! relates to #7

**Comment by markwilliamfirth** [comment]
:+1:

**Comment by markwilliamfirth** [comment]
@nelsonic is this something we still want to offer?

**Comment by nelsonic** [comment]
@markwilliamfirth _want_ to, _yes_. But only once #321 is done. 👍

**Comment by markwilliamfirth** [comment]
Links to #146

**Comment by markwilliamfirth** [comment]
Closed in favour of https://github.com/dwyl/focushub/issues/115

**Comment by iteles** [comment]
This is not about fruit and vegetables for the whole of focus hub, it's about the "core team" as Nelson says in the issue description. Whilst dwyl/focushub#115 is relevant in its own right, it seems different to this one to me.

Did you close this by mistake @markwilliamfirth ?

**Comment by iteles** [comment]
@markwilliamfirth That's not what I was suggesting. As I said, I think you're right to have it in focus hub as we also need to consider it for the office space as a whole.
My question was just about checking whether you had read the original description and whether it might be useful to have it in hq as well as a 'just for members' version of the issue.

**Comment by markwilliamfirth** [comment]
I assumed Nelson was only suggesting that dwyl people who used the office would have access to this (i.e. we're not going to arrange separate deliveries of fruits to people's houses), so it doesn't seem like a dwyl benefit, it seems like a focus hub benefit (and dwyl people have access to the office and therefore access to the fruit) - am I missing something?
