### ISSUE TITLE
New Monitors for #16 ?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hq#102]
@iteles given that many of FAC7 have stayed @14, while dwyl have moved to QuiteSpace™, we need to _consider_ getting a few new monitors for the team(s) ...

I tend to prefer a 27-inch monitor (the size of the Mac Cinema/Thunderbolt Display) and I am (_a little_) biassed towards **Iiyama** because they have _great_ viewing angles, brightness/contrast and color. And certain models have hight-adjustable stands which are good for keeping your laptop infront or using in portrait mode e.g: https://www.amazon.co.uk/dp/B00HY77VPO/
![iiyama-prolite-xub2790hs-b1-27-inch](https://cloud.githubusercontent.com/assets/194400/15991360/ad9a9304-30a8-11e6-8923-d13d605cd0ed.png)
Watch: https://www.youtube.com/watch?v=JvkQfIo84J0 (_overview video_)

> I'm happy for someone else to look into this, _especially_ if someone feels strongly about a particular, brand, screen size or resolution and want to take ownership of ordering the hardware...

@SimonLab & @heron2014 you have used the monitors upstairs a lot, especially the Samsung 4K monitor, do you have any insights into the requirements we have for good monitors...? Do we need 4K or is the same size with FullHD "_enough_" ?

**Comment by iteles** [comment]
As a note, we _need_ 2 monitors, possibly even 3 in the near future.

I think either @sohilpandya and @minaorangina or @Conorc1000 and @roryc89 have also used this monitor in the last week!

**Comment by sohilpandya** [comment]
@nelsonic 4K would be nice, but not sure if its needed FullHD should be good IMO. The one you've posted above looks great! 

couple of others 
https://www.amazon.co.uk/Asus-VC279H-27-Inch-IPS-Monitor/dp/B00WGD2958/ref=sr_1_5?s=computers&ie=UTF8&qid=1465756945&sr=1-5&keywords=27+inch+monitor

https://www.amazon.co.uk/Samsung-S27E390HS-Inch-HDMI-Monitor/dp/B00UHAXAKK/ref=sr_1_4?s=computers&ie=UTF8&qid=1465756945&sr=1-4&keywords=27+inch+monitor
![screen shot 2016-06-12 at 19 44 19](https://cloud.githubusercontent.com/assets/2305591/15993206/2da72968-30d6-11e6-8735-b5eb42cb3ebb.png)


I like the look of Samsung. 💯

**Comment by nelsonic** [comment]
@sohilpandya that Samsung is stylish and I ❤️ the quality, color, viewing angles. 
Just not a fan of the stand (not height-adjustable) so we would need to put some sort of stand or box under it to raise it to an ergonomic height. ⬆️ 
Happy to order one and let people try it. 👍

**Comment by sohilpandya** [comment]
@nelsonic I'd rather go with the one you've posted above as the adjustable stand is a very neat feature! 😄

**Comment by iteles** [comment]
@nelsonic One of each and then we can order a third monitor of the preferred kind after people have trialled them?

**Comment by nelsonic** [comment]
Ordered one of each as discussed:
![screenshot_20160615-143919](https://cloud.githubusercontent.com/assets/194400/16081796/009a27da-3307-11e6-8a73-c77485fd2865.png)
Please test them both when they arrive. (and confirm if we need any adaptors to use with Macs...)

**Comment by sohilpandya** [comment]
Cheers @nelsonic :raised_hands:

**Comment by nelsonic** [comment]
@iteles you're @16 today, right? can you please confirm the new monitors are setup and working? (_or if anything else is required_)

**Comment by iteles** [comment]
Just seen this - but they arrived! We'll get them set up on thursday.

**Comment by sohilpandya** [comment]
Just played around with the Samsung monitor, what a great choice it was. 😉 

It came with a VGA cable, so potentially need a HDMI cable or an adapter from VGA to HDMI/Thunderbolt.

**Comment by nelsonic** [comment]
@sohilpandya ah, should we order a VGA to Thunderbolt adapter for it?

**Comment by iteles** [comment]
@sohilpandya If you find one we should order, drop in a link and I'll get it done!
Being the expert, could you just double-check the other one too please? ☺️

**Comment by nelsonic** [comment]
@sohilpandya we don't need to buy the "_cheapest_" adapter, prefer to buy one that won't break after a few weeks/months ... durability is better than cheap.

**Comment by sohilpandya** [comment]
![screen shot 2016-06-28 at 23 05 50](https://cloud.githubusercontent.com/assets/2305591/16433980/e769d700-3d84-11e6-8d6b-85e89447e221.png)

What do you guys think of these? love the fact that it can go from VGA, HDMI or DVI to display port.

could get a couple?

**Comment by nelsonic** [comment]
@sohilpandya _link_...? 😉

**Comment by iteles** [comment]
@nelsonic Let's get 1 for now? If we need more, we can get more.

**Comment by nelsonic** [comment]
<img width="831" alt="1-click-order-placed" src="https://cloud.githubusercontent.com/assets/194400/16542515/48f23d5c-40a3-11e6-9cf7-ae8431144d0e.png">

**Comment by sohilpandya** [comment]
@nelsonic oops! forgot to add the link! but you found it. 👍

**Comment by nelsonic** [comment]
@sohilpandya what about trying out one of these: https://www.amazon.co.uk/Iiyama-X4071UHSU-B1-40-Inch-LED-Monitor/dp/B016UPDKIW ? 😉

**Comment by iteles** [comment]
Do we not have enough monitors at 16 for now?

**Comment by nelsonic** [comment]
@iteles _good question_. When ever I see someone squinting at a tiny screen I feel like they aren't being _productive_... I would prefer to `#SpendTheMoney` on a _few_ of these _or other "**nice**" monitors_ so people can ❤️  ✅  ... 😉

**Comment by sohilpandya** [comment]
Someone once said: "We can never have enough monitors. everyone loves new monitors!"

We have 3 downstairs at 16 (out of which 2 belong in 14 as downstairs only has 2 monitors and the new cohort starts next week, so 2 will have to go back.)

Let me do a total count of all the monitors in 14 and 16. 😨

**Comment by nelsonic** [comment]
@sohilpandya thanks for doing the count. 
I'm a _huge_ fan of **_Big_ Monitors** because they are good for pairing and I just love seeing more code at once while I'm doing my work... 
I strongly suspect most people at the _start_ of their career would not pony up £500 for a monitor when they can get a "_decent_" one for £200 ... but I would _suggest_ that the investment will pay for it's self pretty quickly if it helps you get your work done quicker and/or enjoy your tools more...

**Comment by nelsonic** [comment]
@sohilpandya the _negative_ review on https://www.scan.co.uk/products/40-iiyama-x4071uhsu-b1-mva-4k-3840x2160-3ms-350cd-m-120000001-2x6w-speakers-dp-2x-hdmi-1x-hdmi-mhl-v has me _conflicted_ ... I usually ***trust iiyama*** to make good monitors ... _thoughts_ ? **cc**: @jackcarlisle

**Comment by sohilpandya** [comment]
@nelsonic Hmmm that's the second one. I'm not so sure now. I have to say the one thing going for LG is that they make the best panels in the industry.

**Comment by nelsonic** [comment]
@sohilpandya yeah, I think LG make the Panels used in the iMac & Thunderbolt Displays ... also, https://www.amazon.co.uk/LG-86BH5C-86-Ultra-IPS/dp/B01CG177FQ 😆 

But seriously, if we order the **iiyama "_beast_"** will you do an Unboxing + Review (_for ur YT Channel_) and if its "_crap_" take care of sending it back? 
or if it's amazing, look after (_use_) it while its at "_Quite Space_" ...?

I don't have ⌛️  to do all of those things but think it would make a _decent_ review piece and if its _any_ good at all it could be a "hit" for fellow developers needing an _amazing_ amount of screen real-estate for being productive ...

**Comment by sohilpandya** [comment]
@nelsonic I can certainly do the unboxing and review! And if it is crap, am willing to send it back (although will require a few eyes on the screen before making that decision) 

Also I would be happy looking after it at 16 too, that's not a problem. 

In terms of usage, sure most of us would love more screen real estate, so I don't think it'll go unused in the space either. 

What are your thoughts? @iteles @nelsonic 

I think we should get it if there's a need for it. For me it's difficult to gauge this need as monitors are being moved about everyday and there are days when we have too many monitors and yet other days where it feels like we are short on them.

**Comment by nelsonic** [comment]
Final Price Check: 💸 
![iiyama-x4071uhsu-b1-price-check](https://cloud.githubusercontent.com/assets/194400/19512872/e6ae0962-95e5-11e6-9451-711abe06cc50.png)

Ordered: 📦 
![iiyama-x4071uhsu-b1-ordered-from-box co uk-447](https://cloud.githubusercontent.com/assets/194400/19512970/3d20bfce-95e6-11e6-80cc-cd8a68d6fcbc.png)

@sohilpandya thanks for agreeing to do the un-boxing and initial test. 🎥 
We may need to print new "_Big Stickers_" https://github.com/dwyl/print-me#stickers for the back ... but that's _after_ the review. 👍

**Comment by sohilpandya** [comment]
@nelsonic looking forward to this! 😄

**Comment by sohilpandya** [comment]
LG UltraFine 4K Display
http://store.apple.com/xc/product/HKMY2B/A

**We do not need this, but mine and Ines' laptop work so well with this. 😹** 

### Screen for the future... One day! 

Also a lot of usb-c screens coming out at CES this week - https://www.google.co.uk/amp/appleinsider.com/articles/17/01/04/lg-dell-and-lenovo-debut-new-usb-c-monitors-compatible-with-apples-latest-macbooks/amp/?client=safari

**Comment by nelsonic** [comment]
@sohilpandya **£471** for **21.5-inch** display...? what is this 2001...? 😮 
![lg-4k-display](https://cloud.githubusercontent.com/assets/194400/21691940/8a963d8c-d372-11e6-807a-6c5ebf77954f.png)

> I would _absolutely_ get a **USB-C Monitor** if they offered _value-for-money_... 
But the **manufacturers** are still thining: "***Let's rip-off the Apple Early Addopters/Fanboys***" ... 
Have you _tried_ the [4k iiyama monitor](https://github.com/dwyl/hq/issues/102#issuecomment-252881408) with your new MacBookPro? what were your thoughts?

Yesterday I saw  the **HP Envy 32** in the shop and it's _sick_! 😻 
and while not 4K, QHD is still decent, and it's a _lot_ better _value-for-money_:
https://www.amazon.com/HP-32-Inch-Display-Olufsen-Speakers/dp/B0159BSB6E
![hp-envy-32-qhd](https://cloud.githubusercontent.com/assets/194400/21692706/05fe0bc8-d376-11e6-82d4-10d0def50e7b.png)

The _only_ reason I'm not in a _rush_ to buy the **HP Envy 32** is because they aren't **VESA mountable** which means we can tidy up our desks. 

We need to have a catch up toward the end of Jan to review our Tech and decide what works so we can _standardise_ and have one table full with the same monitors rather than a "_hotchpotch_".

**Comment by sohilpandya** [comment]
Totally agree that all monitor(usb-c) makers are just ripping us off at the moment. Although Dell just released an 8k monitor! 😳

Can't wait for them to come down in price. ☺️

I've been using the iiyama for the first time this week and will be doing a review of it soon. 🎉
So far:
- finding it really good to use in terms of space/screen management 
- just need to find the perfect distance between me and the monitor as it feels too close at the moment. 
- @nelsonic would it be possible to order this cable for the monitor please? 😬
  - Plugable USB-C to DisplayPort Adapter Cable (6'/1.8m) for 2016 MacBook Pro, MacBook Retina 2015 / 2016, Chromebook Pixel 2015, Thunderbolt 3 & More (Supports 4K / UHD Displays up to 3840x2160@60Hz) https://www.amazon.co.uk/dp/B01EXKDRAC/ref=cm_sw_r_cp_api_Bb5BybMWB6N49
- just looking to get 60hz out of the monitor and I know my laptop can handle output at 4K in 60hz. 

Let's catch up with regards to the space when you are back! ☺️

**Comment by nelsonic** [comment]
Yeah, saw the 8k 32" Monitor announcement. $5k tho... 
maybe if we were a video production company and needed to _edit_ 4k content... hey? 😜 

> it will be _sick_ to have a monitor that is also a Hub and charges the device(s). 🌈 
(_we kinda have that with the Apple Thunderbolt display which has MagSafe... but it's **two cables** which is frankly offensive!_ 🤣 )

I've _ordered_ the cable you requested. It should arrive by Monday on Prime.
Checked the Spec: https://iiyama.com/gb_en/products/prolite-x4071uhsu-b1/ to confirm that it will work (_as I'm sure you did too..._)
![amazon-cable-monday-delivery](https://cloud.githubusercontent.com/assets/194400/21721396/181dd144-d420-11e6-8d13-1d2c307f0338.png)

Can't wait to watch your review as the only decent one on YT for the monitor is in German 
https://www.youtube.com/watch?v=zHZyiwjDdB0
so I'm sure you'll have a hit on your hands when you publish. 🎥  🚀 

Yeah, We need to figure out the space a _lot_ better for how ever long we end up staying it needs to be the _best_ it can be. We should organise a "_Task Force_" for it week-after-next once we're back into the swing of things... 😉

**Comment by sohilpandya** [comment]
@nelsonic could you please DM me the amazon order ID, Plugable want to send over another cable to us, to see if it was the cable that was causing the issue. 

Thanks 👍

**Comment by nelsonic** [comment]
@sohilpandya Dang...  30hz  is _weak_! 😞 
![image](https://cloud.githubusercontent.com/assets/194400/21930334/716f913e-d98d-11e6-84a1-0991f798ccdd.png)

Is that enough for you to make progress...

**Comment by sohilpandya** [comment]
So, I am not sure if it was my computer or the screen but this is what I see now. **Magic**
<img width="376" alt="screen shot 2017-01-13 at 16 51 50" src="https://cloud.githubusercontent.com/assets/2305591/21938000/545916c8-d9b1-11e6-80f9-e68e099509b2.png">

🎉

**Comment by nelsonic** [comment]
@sohilpandya boom is it _smoother_? 😍

**Comment by sohilpandya** [comment]
4k Movie Night every Friday from now on! 😆

**Comment by nelsonic** [comment]
@sohilpandya are you _organising_ it...? 😍  📆  🚀

**Comment by nelsonic** [comment]
Moved to: https://github.com/dwyl/quietspace/issues/10

**Comment by nelsonic** [comment]
Hi @sohilpandya, hope your day is going well at the photography show! 📸  😉 

Just checked your channel on YouTube https://www.youtube.com/user/TheSocialPandas/videos
and did not find a review for the [Iiyama X4071UHSU-B1 40-Inch LCD Monitor](https://www.amazon.co.uk/gp/product/B016UPDKIW) (_AKA "The Beast"..._)
(_did you upload the footage you took somewhere?_)

Can you give us a few words of ***feedback*** on the monitor?
I know @jackcarlisle and @heron2014 also used it a bit did you get their feedback? 🤔 

If "a friend" was on the market for a monitor for "creative work" would you recommend it?
(_thanks!_)

> _Side note_: the **price** has ***increased***: (_thanks to brexit!_)
![image](https://cloud.githubusercontent.com/assets/194400/24071457/1d427a4e-0bca-11e7-8c0c-4dc37f1bbc1a.png)

**Comment by iteles** [comment]
@shouston3 I've seen you use it before too but no longer, let us know your thoughts!

I haven't used it, but my only bug-bear with it is it takes up so much space on the table you can't really get anyone sitting on the other side of it. They might work better wall-mounted!

**Comment by shouston3** [comment]
I'm probably not a good person to ask about these things as I don't really like using monitors in general. I'd say it was probably the best monitor I've tried out though.

**Comment by heron2014** [comment]
The huge screen has its good sides and bad. Lets start with the positive sides:
- great for presentation
- good to work in pair
- great colours
- clarity of code and designs

The bad sides:
- hard to fit number of people at the same desk
- its an unnecessary huge size when working alone
- I personally have noticed tiredness and sometimes headaches when working all day in front of one - this reason completely put me off on continue working on one

From my opinion I would only use these screen on the wall and for certain purpose, e.g:
- meeting with clients
- presentation
- possibly standup meetings 
- workshops 

@nelsonic hope that helps :)

**Comment by sohilpandya** [comment]
Just to update everyone on this thread, I've not yet done a video review but have been collating evidence for it! 😊 Promise the video will go up soon! 

My general thoughts:
**Pros**
- great for pairing;
- got a ton of screen real estate leading to a customized workspace;
- awesome for video editing too!

**Cons**
- need space for such a big monitor, I literally take up half a desk! (sometimes the whole desk, but I don't think that's because of the screen.... 😉 )
- I have to increase the default font size on my editor and browser as 4k is a bit too small and leads to eye strain. 
- On a technical note, I've noticed ghosting on the screen when you have fast moving items on the screen...

Would I recommend it... It really depends. (also will post my recommendation on the YT Video 💛)
