### ISSUE TITLE
Next dwyl lunch - Saturday 16th July!

### ISSUE THREAD

**Issue by iteles** [dwyl/hq#104]
July proved more popular than August so let us know if you're interested in coming along this weekend for lunch at ours in Camberwell. If we get enough numbers, we'll do it - if not, we'll have to leave it til September :)

@NataliaLKB @benjaminlees @SimonLab @heron2014 @jrans @des-des @naazy @msmichellegar @jackcarlisle @beechware @rorysedgwick @Jbarget @minaorangina @hdrdavies @katkelemen @rub1e @mk4111 @Conorc1000 @sohilpandya @nofootnotes @jrans @markwilliamfirth @thegsi @tormod17 @rug1 @katpas @mantagen @rjmk @msmichellegar @tsop14  and everyone else!

**Comment by Jbarget** [comment]
im in +1

**Comment by NataliaLKB** [comment]
Me too! 👍

**Comment by naazy** [comment]
I'm hoping I'll be able to make this but not 100% yet because I have a friend that I need to see who is over from Angola so won't be able to let you know until relatively last minute!

**Comment by jackcarlisle** [comment]
I won't be able to make it unfortunately! I'm flying back home for the weekend ✈️

**Comment by beechware** [comment]
Can't make it this time 👎  Hopefully catch the next one...

**Comment by sohilpandya** [comment]
Won't be able to make this one. 😢 But definitely the next one! X

**Comment by mk4111** [comment]
@iteles please count me in! :)

**Comment by iteles** [comment]
@mk4111, @nataliaLKB , @jbarget - we're very happy to have you over (you know we :heart: you) but it looks like most people are busy this weekend after all so it might not be the full dwyl experience :wink: I'll leave it to you on whether we should reschedule :blush:

**Comment by katkelemen** [comment]
@iteles I'm so sorry, I didn't noticed this in time:( I'll pay more attention to the gitter notifications from now on. Hope we can make it for the next one, we are doing the ultimate frisbee thing and its hard to reschedule the group again. Have a lovely lunch if its still happening! X

**Comment by Jbarget** [comment]
Id be up for rescheduling for a big ol' meal :)

**Comment by heron2014** [comment]
@iteles I also will be up for reschedule, I have planned to go camping this weekend :)

**Comment by hdrdavies** [comment]
phew! I wasn't going to be able to come. Look forward to the rescheduled date 😎

**Comment by jrans** [comment]
eek! I put my attendance in the gitter but yeah @katbow I hope you've seen this too! No problem though, hopefully see y'all soon!

**Comment by katbow** [comment]
Yes, thanks @jrans! Looking forward to the next one ☺
