### ISSUE TITLE
Office Fan

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hq#105]
Looks like it's going to be pretty warm in London the next few days...
<img width="662" alt="london-weather-forecast" src="https://cloud.githubusercontent.com/assets/194400/17000603/2465bf4c-4ebb-11e6-9a3b-c0069c652425.png">

Could No. 16 use a Fan to keep cool?
<img width="836" alt="oscilating-fan" src="https://cloud.githubusercontent.com/assets/194400/17000596/1dee1a10-4ebb-11e6-997d-81d3e26d0a53.png">
https://www.amazon.co.uk/Honeywell-HO-5500RE-Oscillating-Control-Function/dp/B001AZ0KCC

**Comment by nelsonic** [comment]
Are people still overheating at Quiet Space...?

**Comment by iteles** [comment]
Not at the moment!

**Comment by des-des** [comment]
Update:
![image](https://cloud.githubusercontent.com/assets/12845233/17812386/c0db03f8-661e-11e6-8cbe-f7c407b2ccb6.png)

**Comment by nelsonic** [comment]
Looks like we are going back to London's "Business-as-Usual" Weather... oh well... it was good while it lasted. 😉 
(_re-open the issue if it gets hot again..._)

**Comment by des-des** [comment]
maybe we need to automate this? ie
```js
if (get('http://www.bbc.co.uk/weather/2643743').isTooHot) post(api.github/issues/...)
```
we can spin up a docker container to make this super simple

**Comment by nelsonic** [comment]
![rofl](http://www.reactiongifs.com/r/rofl.gif)

@des-des you should do *Tech*-Standup 😆

**Comment by nelsonic** [comment]
![rofl](https://cloud.githubusercontent.com/assets/194400/17853556/1b08b788-6865-11e6-9ec7-3427c76234e5.gif)

@des-des you should do *Tech*-Standup 😆 
❤️

**Comment by nelsonic** [comment]
@sohilpandya / @harrygfox if you gents are in the office today, feel free to open and use the Fan. ☀️ 

![fan-for-dwyl-fac](https://cloud.githubusercontent.com/assets/194400/18089935/2f580db4-6eba-11e6-8601-5f8a323ce5f2.png)

**Comment by sohilpandya** [comment]
No fan in as of yet. Will definitely test it out once it's in. 😀 @nelsonic

**Comment by nelsonic** [comment]
@sohilpandya it was delivered today:
![dwyl-office-fan-delivered-to-reception](https://cloud.githubusercontent.com/assets/194400/18102819/dd78026a-6eeb-11e6-8545-f839b85f30f4.png)

**Comment by sohilpandya** [comment]
@nelsonic. Yep we got it quite late in the afternoon. 

Tried to make it work but it doesn't turn on. 😢😢

**Comment by nelsonic** [comment]
![minions-whaaaaat](https://cloud.githubusercontent.com/assets/194400/18103494/c64fe708-6eee-11e6-9372-ab4819392902.jpg)

Does it come with Remote? 😕

**Comment by sohilpandya** [comment]
Yep. There's a remote with it. I'll give it another go tomorrow, but sure it's not working

**Comment by nelsonic** [comment]
@sohilpandya thanks for investigating... sorry to give you work. _really_ hope it works. 👍 
if not, we will arrange pickup/replacement. 😕

**Comment by sohilpandya** [comment]
@nelsonic no luck, I tried it with the remote and still no response. 😢
