### ISSUE TITLE
Wall Quotes

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hq#108]
We already have a couple of good ones:

![airbnb-mdc-wall-quotes](https://cloud.githubusercontent.com/assets/194400/18409264/fb522f3e-773a-11e6-9054-dae24cf37e85.jpg)

but I think we could add more:

![man who does not read poster](https://cloud.githubusercontent.com/assets/194400/18409304/a7aef51e-773b-11e6-8785-7cb510347f9c.jpg)

(_Yes_, it _can_ be seen as _gender-specific_, but I _prefer_ to think of it applying to all humans and hope nobody will be offended by it...) 

> If _anyone_ has any others please leave comments!! 🍭 

@iteles what is our _process_ for printing off more? :-)
http://www.zazzle.co.uk/the_man_who_does_not_read_good_books_poster-228248636832387006

![image](https://cloud.githubusercontent.com/assets/194400/18409260/f4767102-773a-11e6-9ec4-e91c74c078f9.png)

**Comment by iteles** [comment]
1. You determine what size you want it
2. You determine where it will go
3. I outsource making the type a little more interesting (I've done the 2 on our wall but don't have the time any more)
4. Order the relevant Ikea frame (ours are from the [RIBBA series](http://www.ikea.com/gb/en/catalog/categories/series/16456/)
5. Print on our printer 
6. Frame and hang

**Comment by markwilliamfirth** [comment]
Is this a company thing?

**Comment by iteles** [comment]
I think we can close this for now and re-raise in `quietspace` if we want 👍
