### ISSUE TITLE
Sketching With CSS ?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hq#110]
@iteles shared this link on the Gitters: http://www.sketchingwithcss.com

Promises to teach you how to "**_WRITE CSS AS FAST AS YOU CAN SKETCH**_" 😮 

Being able to (_Rapid_) Prototype in Code (CSS) as fast as you can drag pixels around your favourite image editor is the _holy grail_ of web (UI/UX) design ... if this is _possible_, it sounds like a _bargain_ at $249 and @sfioritto "_wins the internet_!"

@iteles / @harrygfox + (_any/everyone else interested in CSS/Design..._)
who has time to _investigating_ this...?

**Comment by iteles** [comment]
I already have the book - bought it at launch - so that might be a good starting point if anyone wants to borrow it 👍

**Comment by markwilliamfirth** [comment]
Closing as we are now using Tachyons

**Comment by nelsonic** [comment]
see: https://github.com/dwyl/learn-tachyons/issues/9
