### ISSUE TITLE
Quiet Space Raspberry Pi Decibel Meter (Mini Project)

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hq#113]
The noise levels in "Quiet Space" (_AKA "DWYL HQ"_) are _often_ silly ... which means some of us are unable to concentrate while other people are talking/laughing at the top of their voices ... 😢 

![image](https://cloud.githubusercontent.com/assets/194400/19453904/09a8db0a-94af-11e6-88d6-e42fbc157243.png)

We need a _device_ to _automatically_ monitor and report ("_police_") the noise level in real-time to _train_ people on using their "_inside voice_" and not engaging in "_shouting matches_" ... so that the _people_ who are _affected_ by the noise do not have to be "_The Bad Guy_" always complaining about the noise levels... 

This is a ***paid project*** for someone who has "available time" and want's to dive into hardware/IoT dev!

The "_deliverables_" are: 
+ [ ] A learn-xyz tutorial repository where the code is in `/example` documenting _everything_ you learned.
+ [ ] The sound-level-meter should minimise energy usage and have the following functions:
  + [ ] monitor/record the decibel level in real-time on the device (using reliable components).
  + [ ] display the level on a screen or set of LEDs (_which ever is quicker to implement_)
  + [ ] flash a clear warning when the sound level is too high so people are instantly aware.
+ [ ] Optional "bonus level" features: 
  + [ ] store the data locally in a time-series database for later analysis. (_This may require larger microSD cards..._) appending to a csv log should be more than enough. One log file per day.
  + [ ] Display a _graph_ so we know what times of the day are the most noisy/quiet

Here a couple of links that look like a _good place to start_: 
+ https://www.raspberrypi.org/forums/viewtopic.php?f=30&t=29061
+ http://raspberrypi.stackexchange.com/questions/4805/rpi-as-a-sound-level-meter
+ https://www.youtube.com/watch?v=eObSqbe9aqU

> Note: we could consider using other hardware e.g: Ardiuno, [Tessel](https://tessel.io/) or Beaglebone.
our objective however is to write the code in **JavaScript** so other people can extend it.

If you are _interested_ in working on this, please say so by commenting on this issue!! 💬

**Comment by mk4111** [comment]
@nelsonic, I'm really keen to do this project! Although, I'm not sure I'll be able to start for another week and a halfish... Is that ok?

**Comment by nelsonic** [comment]
@mk4111 the project is not "urgent", but it would be _really_ nice to get it started/done "_soon_". 
I spent the day in QS today and it was _noisy_! (_had noise-cancelling headphones on for much of the day and was often unable to concentrate..._) 😞 

if you are keen, it's yours! but you will need to prepare a brief and estimate the time required up-front, so take your time to fully understand the requirement before you "accept" the challenge... also you will need to follow the DWYL process _by the book_ so you can invoice us precisely for the time/materials.

Hope you are well. ❤️

**Comment by mk4111** [comment]
@nelsonic I can understand... :disappointed: 

I'm really _really_ keen to learn about hardware and think this would be a perfect opportunity :heart: Thank you!! Can I start reconnaissance tomorrow? Could you point me to where I might be able to find out about the DWYL process for creating a repo please? :)

Thank you for this opportunity - I'm going to have so much fun!! eek!! :musical_note:

**Comment by iteles** [comment]
@mk4111 So awesome that you're taking this on!

You should already see the option to create a repo when you go to https://github.com/dwyl (there should be a green 'New repository' button there).
<img width="738" alt="screen shot 2016-10-18 at 23 54 10" src="https://cloud.githubusercontent.com/assets/4185328/19499386/384e4672-958e-11e6-8d22-c58488446cf3.png">

The key thing when creating it is:
+ Use the `learn-xyz` format @nelsonic mentioned above
+ Always **initiate the repo with a readme** and add a **clear description** *upon creating it*
+ Test out https://github.com/dwyl/labels to get the label 'starter pack' in the repo (and add issues to the labels repo on your experience if you notice any enhancements that can be made please!)
+ Your very first commit (which should be its own independent PR so it can get merged in quickly) should be an update to the readme in our traditional `Why?`,`What?`,  `How?` style of learn tutorials (e.g. https://github.com/dwyl/learn-tdd) - @nelsonic has written a great first draft of the content in this issue!
+ Follow the contributing processes thereafter: https://github.com/dwyl/contributing

Hooray! You're off to the race 🏇 :tada: <3

**Comment by nelsonic** [comment]
Today we spent the _afternoon_ in "***QuietSpace***" _attempting_ to get work done but the space sounded like a "_frat house_".

![image](https://cloud.githubusercontent.com/assets/194400/19611404/7dd7fe0c-97d9-11e6-923a-f7322a798a38.png)

I'm _all_ for people enjoying their working environment - _it's in our company name_ - but my _understanding_ was that "***Quite Space***" was for focussed creative work where silence is _precious_ not a social club where "_brogrammers_" feel the need to include _everyone_ in their "_banter_"... 

![image](https://cloud.githubusercontent.com/assets/194400/19611400/75ed9daa-97d9-11e6-969f-463976c7967a.png)

> We could _really_ use a few devices around the office to monitor/alert for noise level ... 😢 

<hr />

while GitHub was "down" (_I couldn't post this comment..._) ...
Went on: https://angel.co/online-rental to see how many "rental" ideas are currently funded.

google was "up" ... so I did some googling ...

+ https://www.quora.com/Why-isnt-there-a-startup-that-allows-you-to-rent-stuff-you-want-or-own
+ http://www.thepennyhoarder.com/rent-your-stuff/
+ https://www.streetbank.com (_probably the most successful example of this_)
+ http://www.rentmyitems.com/ (_UK-based appears to have "tested" the idea. no visible traction..._)
+ http://uk.zilok.com/ (_clearly a zombie site_)
+ https://lumoid.com/ (_nice site. focussed on a specific niche: consumer tech. no visible traction. clearly bought twitter followers, because no re-tweets on any recent content._)
+ https://rentything.com/about/ (_after some initial press, the site seems abandoned..._)
+ http://neighborgoods.net/ (_nice landing page. last blog post March 2015. check http://neighborgoods.net/search where you will see zero activity in reviews. i.e. no usage_)
+ www.peerby.com (_looks nice and has some traction, but limited revenue_)

Then I got reading: https://www.cbinsights.com/blog/startup-failure-post-mortem/ and https://www.cbinsights.com/blog/biggest-startup-failures/ and http://autopsy.io/
which reminded me of: http://paulgraham.com/startupmistakes.html
and https://www.quora.com/Where-do-most-web-startups-fail

> Building the product and raising money is the fun/easy part; been there and watched the process... 
Getting _customers_ while ensuring **acquisition costs** are _**lower than life-time-value**_ and retaining the customers for long enough to _realise_ a return ... difficult. 

I would not touch the double-sided-rental-market with a _barge pole_.
The amount of capital required to reach critical mass is prohibitive. 

> What would _you_ do in their position? extrapolate and call it a day early?
Continue raising the "A Round" and then pivot to a better idea?

Check http://yclist.com/ ... lumoid.com is YC S13. 
 they've had **3 years** and all of YC's support to get press/publicity and while they appear to have "raised" some money: https://www.crunchbase.com/organization/lumoid#/entity (_probably entirely on the back of having been in YC_...!) it's _fairly obvious_ from the lack of _real_ "social media" interaction that the founders are just burning the cash... nice Instagram pics tho: https://www.instagram.com/lumoidit/ 📷  🌆  🗻  🌴  ...

**Comment by mk4111** [comment]
@iteles Thank you - sorry about the delay, but I'm planning on doing a decent amount of research over the weekend, and hope to note down my thoughts and findings on the repo I will create, following your instructions.

@nelsonic - the noise does noooot sound happy :( 
I'm really sorry if I'm being a tad think but is the 'rental' idea something that applies to the decibelmeter...?

**Comment by mk4111** [comment]
@nelsonic I'm struggling to think of a repo name following the format 'learn-xyz', largely because I wanted to think through and document choice on technology (arduino/raspberryPI)...  Thinking of calling the repo 'getting-started-with-hardware' instead - could I ask your thoughts on this?

I'd otherwise be happy to do the research on tech choice prior to creating a repo and document my thoughts in a text editor, and copy that over once I've been able to make a more informed choice (which could then be reflected in the repo name)

**Comment by nelsonic** [comment]
@mk4111 _don't apologize_, you've done nothing wrong! You're kindly taking on this mini-project and we're grateful for any time you are _able_ to devote to it. ❤️  
My comment was not directed at you at all. It was just out of frustration that we don't have a way of reminding people to be quiet while others are trying to concentrate ... 😕

**Comment by naazy** [comment]
Ahh this sounds like the coolest project! 

@mk4111 it might be worth checking out Johnny five - http://johnny-five.io/

They have a really great online community and there are loads of tutorials. Johnny-five communicates with arduino-**compatible** boards (you can use the cheapo £5 boards from eBay/Amazon). If you do end up following this route then let me know as I've had a play around with building some Johnny Five things in the past and would be happy to help get you started / write a repo with some basics 😄

**Comment by nelsonic** [comment]
@naazy this is our _first_ hardware mini-project, but we hope to follow it up with _many_ others. 
Our _plan_ is to build _secure_ IoT devices for: https://github.com/dwyl/learn-aquaponics/ next #dwylSummer 😉 
Last time we used johnny five was a [_long time ago_](https://github.com/nelsonic/lxjs-nodebots/blob/0b6a263314b8576817cd21bba1a9bda7f8a3ec68/package.json#L24) so it will be _really_ good to get some _fresh insight_ & practical experience! Did you make _notes_ when you were hardware hacking...? :thinking:

**Comment by naazy** [comment]
@nelsonic Amazing! No I did not write any notes but I should have done! Happy to try to re-familiarise myself and share the 💜 though with a basic learn-johnny-five repo though...

**Comment by naazy** [comment]
Amazing! No I did not write any notes but I should have done! Happy to try
to re-familiarise myself and share the 💜 though with a basic
learn-johnny-five repo though...

**Comment by mk4111** [comment]
Hi @nelsonic and @naazy!

So I did a bit of reading and was wondering if it was preferable for the project to be written in javascript?
The obvious option (given that you mentioned a raspberry pi) seems to be a raspberry pi + JS but I was wondering what your thoughts might be on arduino + sketch...

I was introduced to J5 at nodebots and although I really know nothing about it, I somewhat remember it needing to be attached to a computer so that it can talk to the microcontroller...?That would mean using _both_ arduino + raspberry pi... Given that either one can do the job, the two together might make it a wee more complex for a 'getting-started' repo... What are your thoughts on this? @naazy please correct me if I'm wrong about J5!

**Comment by naazy** [comment]
@mk4111 I'm not too sure. When I built the J5 project, I had the Arduino connected to a computer to run the JS script. However I believe J5 is also compatible with Raspberry Pis so I would guess you'd be able to use the Raspberry Pi both as a micro-controller (by executing the script on the SD card) and also to operate the lights/whatever? I may be completely wrong btw 😄

**Comment by mk4111** [comment]
Hi @naazy ! Thank you for replying!! Yeah so from what I've read, J5 uses the Firmata Protocol to talk to the arduino, so it needs a computer. You're right about J5 being compatible with Raspberry Pi though, although I read yesterday that we'd also need to use an IOt plugin (Raspi-IO) to let J5 talk to the Pi, which seems like it might be an extra layer of complexity...

I guess the choice just boils down to whether this repo should be created from a hardware/electronics perspective or from a software perspective? @nelsonic what would be more useful to you? I'm keen to learn either (...eventually both!)

**Comment by nelsonic** [comment]
@mk4111 _massive_ apologies for making the choice of Tech "_Ambiguous_"...
> https://github.com/dwyl/learn-raspberry-pi-iot _let's get this started_!

**Comment by nelsonic** [comment]
Moved to: https://github.com/dwyl/learn-raspberry-pi-iot/issues/2
