### ISSUE TITLE
Quiet Space Door/Wall Sign!

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hq#114]
# You are entering _Quiet Space_ ...

![image](https://cloud.githubusercontent.com/assets/194400/19454222/33fa74da-94b0-11e6-8c7f-e87104ec12e0.png)

The **_unique selling point**_ of this co-working space is that we **_all value silence**_ so we can get our work done with as little disruption as possible. Please use your inside voice (_whisper_) when having conversations to avoid distracting others from their work and if you need to have a team discussion or take a phone-call, please do so outside the QuietSpace.  Thanks!

@iteles / @harrygfox I'm _sure_ you can come up with _better_ copy. We really just need _something_ to make it clear that the office is for creative people who need to get focussed work done.

should we buy a couple of copies of this book:
https://www.amazon.co.uk/Quiet-Power-Introverts-World-Talking/dp/0141029196
and leave them on the desks to help people understand why Quiet is important...?

Until we have a Sound-Level-Measuring-Device https://github.com/dwyl/hq/issues/113 that _actively_ measures the noise levels in _real-time_, we need to at least have some signs to remind people...

**Comment by harrygfox** [comment]
@nelsonic I'm so down for 16 being a quiet space. SO DOWN!

**Comment by iteles** [comment]
We need a giant size sign or two.

**Comment by nelsonic** [comment]
@harrygfox read: http://www.npr.org/2016/10/26/498850659/what-s-more-distracting-than-a-noisy-coworker-not-much ... if you have time to prep a sign I can print off a few A3 Color and bring them in... 😉

**Comment by markwilliamfirth** [comment]
Should we move this to this QS repo?

**Comment by nelsonic** [comment]
Go for it. ✅

**Comment by nelsonic** [comment]
moved to: https://github.com/dwyl/focushub/issues/17
