### ISSUE TITLE
Company Motto Poster

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hq#115]
http://www.keepcalm-o-matic.co.uk/product/poster/learn-fast-and-make-things/
![learn-fast-and-make-things](https://cloud.githubusercontent.com/assets/194400/19600308/54d33d10-979c-11e6-90a0-c886444d82e0.jpg)

**Comment by markwilliamfirth** [comment]
Is this our motto?

**Comment by iteles** [comment]
Maybe not our 'motto' but might be a good thing for the wall in QS if we get around to it 👍
