### ISSUE TITLE
Noisy Shoes?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hq#116]
Why do people buy/wear noisy shoes in an office where others are trying to concentrate...? 😢 
![image](https://cloud.githubusercontent.com/assets/194400/19601516/91269848-97a1-11e6-99b1-ea621939cedc.png)

**Comment by markwilliamfirth** [comment]
ok to close?

**Comment by iteles** [comment]
@markwilliamfirth Might be a good wall sign for QS #114 #113 ;)

**Comment by markwilliamfirth** [comment]
lol
