### ISSUE TITLE
Order "A Mind For Numbers" book from US Amazon

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hq#117]
Hi @jrans  & @nikhilaravi, need to ask you two a _wee_ favour: 
this book: https://www.amazon.com/Mind-Numbers-Science-Flunked-Algebra/dp/039916524X 
is _silly_ expensive in the UK because it has to be shipped from US ... I want to buy 4 copies to give to people. 
Would it be possible for Nikhi to order them (send you the money via PayPal or bank transfer) and then Jack to bring them back to the UK...? Only if there is time to get it delivered to Nikhi before Jack visits and if Jack has _space_ in his bag to bring them home... ❤️

**Comment by nikhilaravi** [comment]
@nelsonic sure I'll check with Jack if he will have space in his bag and order the books!

**Comment by nelsonic** [comment]
@nikhilaravi _sweet_! thanks! 🍭

**Comment by jrans** [comment]
I have space! Order ahead!

**Comment by iteles** [comment]
@nikhilaravi Do you want to text me your address please so we know where to order to?

**Comment by nikhilaravi** [comment]
@iteles sure I've messaged it to you!

**Comment by yoonkim** [comment]
@nelsonic i'm sure you've done your research thoroughly already but I saw the book on amazon.co.k with free shipping in the uk? https://www.amazon.co.uk/Mind-Numbers-Science-Flunked-Algebra/dp/039916524X. It's $12.99 in the U.S or £11.99 in the U.K. 
Happy to still order it for your here but just wanted to check first!

**Comment by nelsonic** [comment]
@nikhilaravi I've managed to get a _reasonably_ priced copy for my Mom off the Amazon Marketplace: 
![mind-for-numbers](https://cloud.githubusercontent.com/assets/194400/20774581/dc895cfe-b74e-11e6-94b2-be11c944219a.png)

Thanks! ❤️
