### ISSUE TITLE
dwyl.io >> dwyl.co OR get .com then dwyl.io >> dwyl.com ?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hq#119]
At _present_ we are using dwyl.io for our website, email, stickers and [_clothing!_](https://github.com/dwyl/print-me/issues/17) 
`.io` domains are _fine_ in the "_Tech_" community, but not very "recognised" outside our little "bubble" ...
Last year @iteles registered the `.co` TLD and currently has `dwyl.co` _redirecting_ to http://www.dwyl.io 

> Twitter has made `.co` _universally recognizable_ with their [`t.co`](https://support.twitter.com/articles/109623) link shortening/checking service ...

My question is: _given_ that `.co` is more _recognizable_ outside of "Tech", should we switch to using our `.co` ...? **_Or**_... should we focus our energy on getting the `.com` and `.then` switch? https://github.com/dwyl/hq/issues/118

The counter-argument is that we should not use a `.co` domain at _all_ and should just attempt to get the `.com` TLD because `.co` "_looks like a **typo**_" (of) `.com` ... see: http://www.ronstauffer.com/blog/why-not-to-use-a-co-domain/ 

For reference:
- .co domains: https://en.wikipedia.org/wiki/.co
- In the **top 1 million sites** there are **2,698** sites ending with `.co` see: https://domaintyper.com/top-websites/most-popular-websites-with-co-domain
- In the **top 1 million sites** there are **218** sites ending with `.io` see: https://domaintyper.com/top-websites/most-popular-websites-with-io-domain
- Hilary Clinton's team has used `hrc.io` for "short" URLs during her presidential campaign. e.g: [hrc.io/2dyIL3B](https://hrc.io/2dyIL3B) so there is _some_ recognition for it.

Thoughts? _insights on this are very much welcome_!

**Comment by iteles** [comment]
I personally think that the typo argument is a very strong one, I would go straight for `.com` as a first option

**Comment by harrygfox** [comment]
I got asked about my email address at the Paradise Cycles just yesterday:
> .io what is that?
> _it's like the on / off switch. It's like a tech thing_
> Yeah I thought so

Even though I like that it was obvious we were a tech company of _some sort_ I think I'd rather the apparent legitimacy that comes with, and ubiquitous recognition of, a `.com`. 

Saying it out loud to someone: `.io` must be stressed `dot + eye + oh` where as you can pretty much say `.com` without moving your lips and people will know what you mean

**Comment by markwilliamfirth** [comment]
Providing DWYL is the name of the company and is not likely to change then 100% .com

The real question is what's the best way of acquiring the domain without paying a ridiculous price? Do we have any idea approximately how much the current domain owner wants for it? You probably know more about the most effective domain acquisition techniques than me though.

**Comment by markwilliamfirth** [comment]
Apparently .io has some policitical connotations for some people, which I didn't realise until today. 

https://gigaom.com/2014/06/30/the-dark-side-of-io-how-the-u-k-is-making-web-domain-profits-from-a-shady-cold-war-land-deal/

**Comment by iteles** [comment]
@markwilliamfirth It does! Hence: https://github.com/dwyl/dwyl.github.io/issues/146

**Comment by nelsonic** [comment]
@markwilliamfirth yeah, we _know_. it's _grim_! 😢 
scroll to the bottom of http://www.dwyl.io/ where we link to http://www.chagossupport.org.uk/ ... but we _agree_ that using the `.io` means we are "_part of the problem_" hence my wanting to move to `.co` or `.com` ...

**Comment by markwilliamfirth** [comment]
DWYL.com forwards to desiringgod.org

desiringgod.org is a website for John Piper

Assuming he is the domain holder, running an email search shows his email to be:
`john.piper@desiringgod.org`

**Comment by markwilliamfirth** [comment]
[Interesting read ](http://nominet-prod.s3.amazonaws.com/wp-content/uploads/2015/08/Expert_Overview.pdf) with regards to possibility of also acquiring `.co.uk`

**Comment by markwilliamfirth** [comment]
discussion continued on #118
