### ISSUE TITLE
Organise the next dinner @dwylhq

### ISSUE THREAD

**Issue by iteles** [dwyl/hq#12]
Sometime between 18th & 24th September!

**Comment by iteles** [comment]
Thinking the following weekend might actually be better.

@nikhilaravi @markwilliamfirth, can you both make it on 3rd October?

**Comment by iteles** [comment]
Or 2nd October :blush:

**Comment by markwilliamfirth** [comment]
@iteles 10th is good for me - thank you for the invite :smile:

**Comment by iteles** [comment]
Hooray! 10th it is. :tada: 

@nelsonic I think we might need to cap the number of people to 18 in terms of space and capacity to cook for that many people. I imagine you'll disagree :wink:

**Comment by nelsonic** [comment]
We are going to try and [*video*](https://github.com/dwyl/video/) the experience so others can enjoy it *vicariously*... :wink:

**Comment by iteles** [comment]
So far we have yeses from:
@nataliaLKB, @markwilliamfirth, @nikhilaravi, @filwisher, @jrans, @tsop14 and @minaorangina :star2:

**Comment by iteles** [comment]
Update! @danwhy and Anneka are also coming!

**Comment by nelsonic** [comment]
Sweet! :lollipop: 
Are we going to watch a *classic* movie film [*suggestions please*...] or just play ***set***? :wink: 
What time is it starting? what do I need to bring?

**Comment by iteles** [comment]
And also @jbarget! :tada: 

10 folks so far :)

**Comment by nelsonic** [comment]
@benjaminlees did you figure out if you will be in town...?

**Comment by iteles** [comment]
And @benjaminlees and @heron2014 (and maybe her fiancée but she's not too sure whether it might be too 'codey' for her - it won't be!).

13 or maybe 14 people so far.

**Comment by nelsonic** [comment]
@nikhilaravi menu ideas?

**Comment by iteles** [comment]
Final list: @nataliaLKB, @markwilliamfirth, @nikhilaravi, @filwisher, @jrans, @tsop14, @rjmk, @minaorangina, @danwhy, Anneka, @benjaminlees, @heron2014 + 1, @jbarget, @naazy, @mk4111, @RachBLondon + 1 = 18 people

So... plus @nelsonic and @iteles. I think we might need to close down the guest list rather than announcing it again? :grimacing:

**Comment by nelsonic** [comment]
Its going to be sweet! 
now... what are we going to *eat*...?

**Comment by iteles** [comment]
So @nikhilaravi and I have been talking and we think lentil and butternut squash curry with brown rice/quinoa and then for dessert I was seriously pondering both @nataliaLKB's date/coconut squares AND baked apples.

The appetiser is currently TBC.

**Comment by tsop14** [comment]
✨✨✨✨✨✨✨✨💫

**Comment by NataliaLKB** [comment]
@iteles @nelsonic Thank you so much for having us over on Saturday. It was so much fun! Can't wait for the next one :smile:

**Comment by nelsonic** [comment]
Thanks @NataliaLKB you made it fun! :tada: 
"*the next one*" is going to be *even* *betterer! :wink:

**Comment by naazy** [comment]
@iteles @nelsonic 

Thanks for having me yesterday! i had a scream. see you tomorrow!

**Comment by iteles** [comment]
@NataliaLKB @naazy We had such an awesome time, thanks for making our night! :star2: 

We'll have to open another issue like this one again soon :wink: 
![coconut-hands-dwylhq](https://cloud.githubusercontent.com/assets/4185328/10419508/c17e30ee-7071-11e5-83a1-bd2c1253c930.jpg)

**Comment by tsop14** [comment]
🌴THANK YOU🌴

What an amazing night!

**Comment by iteles** [comment]
@tsop14 🎉 thank you so much for coming!! 😘
