### ISSUE TITLE
Organise next dwylhq lunch - Sunday 11th December 2016

### ISSUE THREAD

**Issue by iteles** [dwyl/hq#121]
It's been a while since we've had one of these! We must do another.

Proposed lunch date: Sunday 27th November :tada: or Sunday 11th December :heart:.

## Please add a :tada: reaction to this comment if you can make 27th November and a :heart: if you can make the 11th December!

**It'll definitely be lunch and not dinner.** Looking to finalise numbers tomorrow!

Starting at 13h00!

**Comment by tonydaly** [comment]
Ahhh I actually can't make the 26th, going to see Trevor Noah.

**Comment by iteles** [comment]
Boooooooo @tonydaly ! Also, I can't believe you managed to get tickets for that!
Can you do the 27th?  I'm open to anything on that weekend really

**Comment by nelsonic** [comment]
@tonydaly are there still _Tickets_ available for Trevor Noah...?!?

**Comment by iteles** [comment]
@nelsonic no, I tried getting them the day after they were announced and we're on the waiting list...

**Comment by tonydaly** [comment]
@iteles @nelsonic my friend was already on the waiting list and she managed to grab some tickets, I didn't even know it was happening!

But yes 27th works 👍

**Comment by nelsonic** [comment]
@iteles `#NewHouse` or "Old"...? 😉

**Comment by nelsonic** [comment]
@eliascodes be there! 😉

**Comment by iteles** [comment]
@tonydaly @harrygfox @SimonLab @Danwhy @naazy @Conorc1000 @roryc89 @Jbarget @mantagen @NataliaLKB @benjaminlees @jackcarlisle @des-des @franzmoro @shouston3 @eliascodes @JMurphyWeb @mk4111 @markwilliamfirth @sohilpandya @minaorangina @beechware @rjmk (honourable mention to @nikhilaravi) :arrow_right: Please take a look at the top comment and vote for your preferred day!

Hoping to fix the date by tomorrow.

**Comment by NataliaLKB** [comment]
Woohoo! Looking forward to another one of these! 

Unfortunately I can only do the 27th if I can bring my flatmates with me and I can only come on the 11th if I can bring my parents with me. Either of those dates would have to be +2. Is that okay?

**Comment by Jbarget** [comment]
I cant come this Sunday so 11th December for me. (with a +1 if poss)

**Comment by naazy** [comment]
Can't do the 11th. I might be able to do the 27th (I thought it was on the saturday :()

**Comment by roryc89** [comment]
🎉 for @Conorc1000 and I. (we're away on the 11th)

**Comment by beechware** [comment]
Won't be able to make either date hopefully catch you all soon.. :(

**Comment by SimonLab** [comment]
Sorry I won't be able to be there this Sunday, I'm on the 11 team

**Comment by jrans** [comment]
Confirming my attendance for the 11th. I have to be somewhere at 6 so would be good to know start and end times.

**Comment by iteles** [comment]
List so far:
+ @katbow 
+ @jrans 
+ @NataliaLKB + ?
+ @tonydaly 
+ @SimonLab + 1
+ @Danwhy + 1
+ @Jbarget 
+ @eliascodes 
+ @shouston3 
+ @jackcarlisle 
+ @sohilpandya 
+ @andrewMacmurray 
+ @JMurphyWeb + 1
