### ISSUE TITLE
Industrial Heater for 16

### ISSUE THREAD

**Issue by sohilpandya** [dwyl/hq#122]
**Problem**
- It is absolutely freezing ❄️ in 16. 

**Solution**
1. _Kingavon_
 https://www.amazon.co.uk/Kingavon-BB-FH207-Industrial-Heater/dp/B002QO9AM2/ref=sr_1_2?ie=UTF8&qid=1479134958&sr=8-2&keywords=industrial+heater
<img width="1409" alt="screen shot 2016-11-14 at 14 52 48" src="https://cloud.githubusercontent.com/assets/2305591/20269183/11fe4cbe-aa7a-11e6-842b-d67608954b2d.png">

2. _Honeywell_
https://www.amazon.co.uk/d/9mn/Fan-Honeywell-HZ-510E1-HZ-510E-Heavy-Duty-Heater/B000LRC1WW/ref=sr_1_4?ie=UTF8&qid=1479134958&sr=8-4&keywords=industrial+heater
<img width="1400" alt="screen shot 2016-11-14 at 14 53 51" src="https://cloud.githubusercontent.com/assets/2305591/20269213/2eed6666-aa7a-11e6-95f5-80e8a65af072.png">

These seem to be good, going just off the reviews. (@iteles @nelsonic)

**Comment by iteles** [comment]
@sohilpandya *Energy-efficiency* is something we value quite highly. 

Are there any options that will heat the bottom floor but also are a bit more energy efficient than these?

**Comment by nelsonic** [comment]
@sohilpandya which of these two will "_dry_" the air out less? and what is the plan for where we would _put_ it?

**Comment by sohilpandya** [comment]
@iteles unfortunately, if we were to go with something which is more energy efficient such as https://www.amazon.co.uk/Aironic-Electric-Convector-Adjustable-Thermostat/dp/B00SONEBIC/ref=sr_1_3?ie=UTF8&qid=1479137844&sr=8-3&keywords=energy+efficient+heater then I think we may need a few of them due to the size of the room. 

@nelsonic I was thinking of just putting it next to the new fridge facing the two tables.

**Comment by nelsonic** [comment]
![img_1226](https://cloud.githubusercontent.com/assets/194400/20271020/3c2e7642-aa81-11e6-8a2b-9b25a29befe7.PNG)
@sohilpandya thanks for doing the research for this. 
Please confirm it works abs expected when it arrives. 😉

**Comment by iteles** [comment]
@sohilpandya Done! Can this be closed?
