### ISSUE TITLE
Broadband (Hyperoptic) Speed

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hq#124]
At DWYLHQ we recently got [Hyperoptic 1GB](https://www.hyperoptic.com/) installed.

I use https://fast.com/ to check broadband speed (_mostly because it has no adverts but also_) because it's comparably accurate to other speed checking services.

And on my MacBook Air (2012 Model) I get **81Mbps** over WiFi when the Mac is sitting _next_ to the ZTE Router: 

![hyperoptic-speed-test-81mb](https://cloud.githubusercontent.com/assets/194400/20644209/002898e6-b425-11e6-98b3-933a29a10cc1.png)

I don't know if this is a _limitation_ of _my_ Hardware ("_old mac_") or the router ...

@iteles can you please test on your 2016 MacBook to confirm what speed you are getting? (_thanks_)

(_sorry if this sounds like "first world problems"... but we **have** to make sure we are getting what we are **paying** for._)

Using http://beta.speedtest.net/ (_the non-flash version_) I get **67Mbps** under same conditions:
![hyperoptic-speedcheck-67mb](https://cloud.githubusercontent.com/assets/194400/20644225/ade212f0-b425-11e6-87e6-6d87b972f245.png)

**Comment by iteles** [comment]
Agreed. Ran it just now on my early 2016 model and got:

<img width="623" alt="screen shot 2016-11-27 at 16 01 23" src="https://cloud.githubusercontent.com/assets/4185328/20649576/d5abe5d2-b4ba-11e6-911b-f728eb2e8705.png">
<img width="855" alt="screen shot 2016-11-27 at 15 59 48" src="https://cloud.githubusercontent.com/assets/4185328/20649577/d5ac349c-b4ba-11e6-8c64-5559f1b1eed4.png">

Will call them on Monday.

**Comment by iteles** [comment]
Spoke to them and they confirmed that on wi-fi, we can't expect more than 70-80Mbps.
Wired, they emphasised it was [1 giga*bit* and not 1 giga*byte*](https://www.atlantic.net/blog/do-you-know-the-difference-between-a-gigabit-and-a-gigabyte/).

**Comment by nelsonic** [comment]
@iteles how much "_cheaper_" will the 100Mb plan be?

**Comment by iteles** [comment]
For the next 5 months, only £3 a month cheaper, but once the 6 month promotion period is over, £25 a month cheaper.

**Comment by nelsonic** [comment]
Sounds like a good idea... 
If we are paying for Gold and getting Silver we might as well pay for silver and not feel ripped off.

**Comment by raptortech-js** [comment]
It's probably worth noting that a) wifi speed is heavily dependent on the access point (router) you use, and b) even if it can only support 70 Mb/s to any single computer, it may still be able to support a total of 1 Gb/s to a number of devices connected at the same time. That being said, if you expect <25 devices to be connected at a time and you're not constantly transferring large files around, it sounds like 100 Mb/s would make a lot more sense.

**Comment by markwilliamfirth** [comment]
@iteles ok to close?

**Comment by iteles** [comment]
Thanks for the reminder @markwilliamfirth !

Yes, this has been done, after *much* back and forth and *without* a contract extension for a further 12 months:
<img width="612" alt="screen shot 2017-02-25 at 18 37 45" src="https://cloud.githubusercontent.com/assets/4185328/23333777/91cc4b34-fb89-11e6-86bb-70c40d895445.png">

**Comment by markwilliamfirth** [comment]
nice
