### ISSUE TITLE
company amazon account with spending limit

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hq#126]
at present we have an Amazon account that linked directly to the "_main_" DWYL bank account ...
the is not something we can "_share_" with everyone because if anyone's laptop was compromised the attacker would be able to _wipe_ us out by spinning up EC2 instances and mining bitcoin on our account ...

We need to:
+ [ ] determine what the spending limit needs to be
+ [ ] set up the account to go to `finance+amazon@dwyl.io`
+ [ ] determine `who` should get access to the account ...

> relates to: https://github.com/dwyl/hq/issues/125 (_company credit/debit cards_)
> also relates to: https://github.com/dwyl/hq/issues/90 (_restart audible subscription, as we can use this account to share our audio-book library with the team...!_)

**Comment by markwilliamfirth** [comment]
Linked to #49 #218

**Comment by iteles** [comment]
Closing in favour of #49 , where I've updated the top comment with the extra information.
