### ISSUE TITLE
New projects - should we be tracking our incoming project requests through Github?

### ISSUE THREAD

**Issue by iteles** [dwyl/hq#127]
Should we be tracking our incoming projects through Github?

Reasoning for this is:
+ It allows us to create a list of actions within GH (where everyone is dwyl usually spends most of their day) for people to follow up on, particularly when multiple people are involved (and I'm asked for updates all the time)
+ We ideally want to build our own tool which is accessible to everyone but this is the most transparent way we have of doing this at the moment.

Will trial this.

**Comment by markwilliamfirth** [comment]
Agreed
