### ISSUE TITLE
Content Promotion

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hq#13]
Which dwyl "*learn*" post should we submit for sharing?
![invitation-to-share-content](https://cloud.githubusercontent.com/assets/194400/9957042/fd7b3fe0-5df4-11e5-9a71-0f31913ebcd6.png)

**Comment by nelsonic** [comment]
Suggested https://github.com/dwyl/learn-tdd
![reply-to-harry-learn-tdd](https://cloud.githubusercontent.com/assets/194400/9957149/c029f1da-5df5-11e5-9916-bc4184415070.png)

**Comment by iteles** [comment]
Well that was a quick turn-around. Agreed TDD is :tada:
