### ISSUE TITLE
investigate opencollective.com ?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hq#130]
see: 
+ https://opencollective.com/about 
+ https://opencollective.com/#howitworks
+ https://github.com/OpenCollective/OpenCollective
+ https://medium.com/open-collective

## Task/Todo
+ [ ] can we become part of the community ?

**Comment by iteles** [comment]
Unassigning myself - happy for anyone to take on this research!

**Comment by markwilliamfirth** [comment]
@iteles the reason I assigned to you is because this comes under

biz dev -> partnerships

So I think it's your call as to whether we partner or not. Can probably tell from quickly scanning the website, no?

**Comment by markwilliamfirth** [comment]
@iteles see https://github.com/dwyl/hq/issues/130#issuecomment-282525578

Where should we progress with this issue? Do you want me to take it on?

**Comment by iteles** [comment]
We are already part of the Open Collective community as we give to folks through Open Collective as a thank you for the technology we use.

Closing this issue for the same reasons as https://github.com/dwyl/hq/issues/545#issuecomment-567980749
