### ISSUE TITLE
Supply Teachers (why DWYL is investing in Air Supply)

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hq#134]
Listen to the BBC radio Documentary on Supply Teachers: http://www.bbc.co.uk/programmes/b083r1zh

We are going to *systematically* solve this problem and once we "break-even" on our initial investment into the project we will re-invest all income into our education-related projects.

**Comment by markwilliamfirth** [comment]
@iteles lol

**Comment by iteles** [comment]
I'm particularly a fan of the bug label.

**Comment by nelsonic** [comment]
This is _still_ an _on-going_ problem. but I think we can _close_ the issue. @iteles thoughts?

**Comment by iteles** [comment]
Closing for now, it's so low priority that we'll be able to resurface it quickly with a search for 'blog' in the closed issues 👍
