### ISSUE TITLE
DMZ Network

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hq#135]
We need a DMZ for HQ to ensure that our _internal_ [NAS](https://en.wikipedia.org/wiki/Network-attached_storage) is "secure"...
+ https://en.wikipedia.org/wiki/DMZ_(computing)
+ http://superuser.com/questions/17572/whats-dmz-used-for-in-a-home-wireless-router
+ https://www.cnet.com/forums/discussions/here-is-a-not-so-quick-tip-low-cost-dmz-for-home-313024/

**Comment by nelsonic** [comment]
Considering getting the **Linksys WRT3200ACM** because it uses [**Open WRT**](https://en.wikipedia.org/wiki/OpenWrt) 

See: 
+ http://www.linksys.com/us/p/P-WRT3200ACM/
+ http://www.pcmag.com/review/349806/linksys-wrt3200acm-mu-mimo-gigabit-wi-fi-router
+ http://www.maplin.co.uk/p/linksys-wrt3200acm-ac3200-gigabit-wi-fi-cable-router-a49wr

They have them in-stock at Maplin and _surprisingly_ the cheapest price on the internet! 😮

**Comment by sohilpandya** [comment]
Setup at HQ: 
![img_0102](https://cloud.githubusercontent.com/assets/2305591/22512813/233cca68-e892-11e6-9bf0-93dbf5c2cd00.JPG)

I know **speed** wasn't the main reason for buying this product, but so far its looking good. 

**old**
<img width="1920" alt="screen shot 2017-02-01 at 14 59 03" src="https://cloud.githubusercontent.com/assets/2305591/22512922/7c87f264-e892-11e6-9c37-ac8316e6756e.png">

**Linksys**
<img width="1920" alt="screen shot 2017-02-01 at 15 05 03" src="https://cloud.githubusercontent.com/assets/2305591/22512935/87b58516-e892-11e6-81cd-8b1b258a39b7.png">

**Comment by nelsonic** [comment]
The DWYL **Linksys WRT3200ACM** is _temporarily_ being used for **QuietSpace** Wifi.
relates to: #195

**Comment by markwilliamfirth** [comment]
Now permanent as QS (now FH) is run by dwyl

**Comment by nelsonic** [comment]
@markwilliamfirth did you setup a DMZ network for FH?
or transfer the issue?
![image](https://cloud.githubusercontent.com/assets/194400/26149099/e3d9b2da-3af0-11e7-8ae6-43d0eb7a90a8.png)

Doesn't _look_ like _any **progress**_ was made on this, _why_ is the has the issue been closed...?
Is Network _Security_ not a Priority...?
Or are we _too busy_ to ask for "_more detailed requirements_" to get this done?

**Comment by markwilliamfirth** [comment]
@nelsonic I misunderstood your issue - I was under the impression that the router was the solution. Has been reopened in FH https://github.com/dwyl/focushub/issues/71

**Comment by nelsonic** [comment]
@markwilliamfirth thanks for opening the dedicated issue. 👍
