### ISSUE TITLE
Getting to Bristol for SL workshop

### ISSUE THREAD

**Issue by iteles** [dwyl/hq#136]
We're running a workshop on Tuesday 6th December with SL. Their offices are based at BS1 2NT.

**Attendees are:** @harrygfox @iteles so far. We need to be there at 10h00, and leave there at 17h00.

Going by train will be pretty pricey:

<img width="364" alt="screen shot 2016-12-03 at 11 53 18" src="https://cloud.githubusercontent.com/assets/4185328/20859182/6fd2e104-b94f-11e6-9101-1278fbdb0204.png">

Can we hire a car instead?

**Comment by nelsonic** [comment]
@iteles we could _rent_ a **car** for the day for about £60 and it would be about £30 of petrol (for 
https://ridelink.com/gb/mini/cooper-s/6cb375db-033d-4696-9bdf-986a1ad6a309 
![mini-cooper-s-ridelink](https://cloud.githubusercontent.com/assets/194400/20859195/df45aa3a-b94f-11e6-822d-dca17ec9e2db.png)

## Carbon Offset:

It's **124 miles** (_200 km_) from Palmers Road to their office:
https://www.google.co.uk/maps/dir/Bristol+BS1+2NT,+UK/14+Palmers+Rd,+London+E2+0SY/

A small car puts out **120g/km** so it would be ***48Kg*** of CO2. 
Which according to http://climatecare.org/calculator/ would cost us **£0.36** to off-set:
![carbon-calculator](https://cloud.githubusercontent.com/assets/194400/20859289/5046b574-b952-11e6-8374-f6bbba476e8f.png)

**Comment by iteles** [comment]
We can and should but we need someone who can rent a car and I managed to misplace my drivers license!!

**Comment by harrygfox** [comment]
I have a licence but am 24

**Comment by nelsonic** [comment]
@iteles I _don't mind_ driving and can either attend the workshop or sit in the library and work/read my elixir book... 😉 
Please let me know ASAP as if I need to book the car will need to tell the renter soon!

**Comment by iteles** [comment]
@nelsonic We need to confirm with AS tomorrow if they need you on Tuesday first!

**Comment by iteles** [comment]
@nelsonic Confirmed. Please book the car!

**Comment by nelsonic** [comment]
@iteles just to inform you that the car is booked for tomorrow.
![ridelink-booking-request-success](https://cloud.githubusercontent.com/assets/194400/20890429/c1f1ec54-bafe-11e6-912e-5d1721308705.png)

I'm just deciding if I should grab a book and go get the car by tube this evening or get it delivered to us for £30 ...
https://www.google.co.uk/maps/dir/14+Palmers+Road,+London+E2+0SY,+UK/Cavendish+Gardens,+Ilford+IG1+3EA,+UK
Obvs if I value my time (_cough! more than £30/h_) I should just pay to get it delievered, but if I value `frugality` I should minimise the _cash_ spent...

**Comment by nelsonic** [comment]
The chap _confirmed_ my rental of the Mini and then an hour later informed me that it had "broken down" and _cancelled_ my reservation. 😢 
![ridelink-reservation-cancelled](https://cloud.githubusercontent.com/assets/194400/20930506/7d0130ba-bbc5-11e6-846b-9bedae735427.png)


So I just got a ZipCar. which is _more expensive_ but less time wasting so actually saves money if the value of my time is taken into account...

**Comment by nelsonic** [comment]
For anyone following along remotely, the _reason_ I wanted to go to SL for the workshop and _really_ want to help them use technology effectively to achieve their mission/goal is because they are solving a ***real human problem***: https://youtu.be/V2XzvBXoNF4

**Comment by naazy** [comment]
Silent observer here! Out of interest what's SL? Are they building something to do with domestic abuse?

**Comment by nelsonic** [comment]
@naazy SL = http://www.safelives.org.uk 
and yes, we are going to help them _solve_ it. ❤️  ✅

**Comment by naazy** [comment]
Ahh SO COOL. Safe lives are awesome! No idea what the deal is but I would LITS LOVE<3 to be involved in some way if there's any possibility of that. :peace:

**Comment by nelsonic** [comment]
@naazy the _beauty_ of building a component-based-open-source system is that your work will be used in/for SL _by definition_. so you by being a part of DWYL you are a part of _saving lives_! 😮 
You will be also be a part of "_fixing_" the NHS https://github.com/dwyl/hq/issues/128 and solving "food" (_i.e world hunger!_) . 2017 is going to be a [_very exciting time_](https://youtu.be/GVUTiuPuxMc?t=6s) to be part of DWYL. ❤️  ✅  🎉 

We're trying to keep things on the "downlow" while still maintaining "_hyper transparency_" which are kinda oxymoronic ... but we are going to be doing a _much_ better job of communicating all projects with all members of the team/community in 2017 because our "[_secret weapon_](https://github.com/markwilliamfirth)" is going to systematically address community in DWYL. 💬

**Comment by naazy** [comment]
Thanks @nelsonic - Sorry for prying I was just excited for DWYL because it's such a great cause! 💟  👌

**Comment by nelsonic** [comment]
@naazy you aren't "_prying_" it's _fantastic_ that you're `curious`! ❤️ 

![image](https://cloud.githubusercontent.com/assets/194400/21265372/fe307cba-c398-11e6-8d05-e060c42d1213.png)

**Comment by nelsonic** [comment]
@naazy (re)_'member_ working for [GT](http://www.grantthornton.co.uk/careers/) ...?
'_member_ feeling _empowered_ with the knowledge/skills to make the world a better place...? 
Didn't think so...
DWYL is _different_. _By design_. ❤️ 

![cropped-betterbydesign-logo-black](https://cloud.githubusercontent.com/assets/194400/21282782/010fd7f2-c3f1-11e6-83a3-e10a71b44fb8.png)
