### ISSUE TITLE
Motion Detecting Lights ?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hq#14]
@iteles What do you think of installing a motion detecting lights?
The first one would be in the corridor upstairs and see if its any good.
e.g: http://www.amazon.co.uk/Frosted-Occupancy-Presence-Detector-Ceiling/dp/B00BEENO0Y

**Comment by nelsonic** [comment]
They *look* better than the dangling bulb on a chord, and mean that people (*guests*) wont have to *remember* to switch off the light.

**Comment by iteles** [comment]
I'm up for trying it out upstairs. I'll get this plus the required bulbs ordered tomorrow :+1:

**Comment by iteles** [comment]
Bought :+1: Arrived today.

**Comment by nelsonic** [comment]
Wouldn't be so hasty to *close* this issue. or does the fact that something is *purchased* mean that it's *assumed* installed/working...?

**Comment by iteles** [comment]
It's installed and working :+1: 

We keep switching it off because sometimes it detects movement _inside the rooms_ and not just in the corridor though... This model might be a bit _too_ sensitive!

**Comment by nelsonic** [comment]
We can reduce the sensitivity on the one in the upstairs corridor. What do you think about getting one for the entrance downstairs...?

**Comment by iteles** [comment]
I wouldn't want it to switch on every time someone walks past the downstairs corridor - let's measure the distance, reduce the sensitivity upstairs and see if we reckon it'll work :+1:

**Comment by nelsonic** [comment]
Ines the *entrance* is *below* the landing ... how would it detect Sam?

**Comment by iteles** [comment]
The bedroom is _behind_ a door and it detects my movement from across the room and through the gaps (I assume). I haven't looked into exactly how the sensor works or its placement on the light. I'm happy to either get another one for the entrance. 

Did you buy spare light bulbs?

**Comment by iteles** [comment]
Done @nelsonic ? These are working awesomely, thanks for putting them up 👍

**Comment by nelsonic** [comment]
Would prefer to have _more_ of them so we _never_ have to use another light switch. but not really a "_priority_" for now. 👍
