### ISSUE TITLE
Hyper Transparency?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hq#140]
What does "_**Hyper Transparency**_" _mean_ to _Us_ @DWYL ?

Thankfully this is not a term we are trying to "_coin_", it's already part of the ***Business for Social Responsibility*** nomenclature:
https://www.bsr.org/our-insights/blog-view/hyper-transparency-is-more-than-just-hype

**Comment by iteles** [comment]
Ha, was just talking about this to Founders & Coders students yesterday!

**Comment by markwilliamfirth** [comment]
http://www.inc.com/jeff-haden/inside-buffer-company-complete-transparency.html

**Comment by iteles** [comment]
@markwilliamfirth I'm thinking we need a `blog` label and this issue deserves one?

**Comment by markwilliamfirth** [comment]
@iteles good idea

**Comment by markwilliamfirth** [comment]
@iteles what steps do we need to take to allow us to action this as a value across the organisation?

- Review remuneration process
- Decide whether to keep discussions involving hiring private

**Comment by markwilliamfirth** [comment]
Transparent salaries / day rates currently blocked by #321 #92 and review of rates / pay scale restructuring

**Comment by harrygfox** [comment]
I am pro hyper transparency - to me it is conspicuously the only non transparent part of the company.

**Comment by markwilliamfirth** [comment]
Blog part of this issue moved to https://github.com/dwyl/blog/issues/11

Keeping open as there are still actionable points here

**Comment by markwilliamfirth** [comment]
Closed in favour of https://github.com/dwyl/values/issues/1

**Comment by nelsonic** [comment]
(_Old_) Values Copy for: https://dwyl.com/values

<hr />

# People 🤝
Our people are our primary focus, not profit. We have a worldwide community of over 400 creative technologists. We believe in inclusivity and accessibility and want to enrich the lives of everyone in our community.


# Transparency 🔎
Open-Source and Open-Kimono: we’re building dwyl for all to see! The vast majority of dwyl projects are written open-source. This allows code modules to improve and adapt over time allowing for a more robust and up-to-date application.


# Looking After the Planet 🌍
We recycle and are a carbon neutral organisation, but it’s not just the planet’s environment we want to improve. We love projects that have a positive effect on the world. Take a look at the kinds of project we love.


# Organic Growth 🌱
We are growing organically, without investment, to be flexible enough to move in the direction our community takes us! Want to be a part of our growth.
Sound like somewhere you’d like to work?
