### ISSUE TITLE
DWYL Company Registered Address

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hq#141]
At present the DWYL company registered address is set to our _residential home_ ...
https://beta.companieshouse.gov.uk/company/09525434

This has both a few `Pros` (_we can easily charge our home office expenses to P&L_) and we always receive any post promptly and _obvious_ `Cons` "bad" people know where we live and if we _tweet_ that we have nice things, they might burgle our place! 😢 

So ...

`Question 1`: should we re-open the "_registered address_" with mail scanning/forwarding discussion/investigation...?

`Question 2`: Should we _consider_ registering the company in a more _favourable_ regulatory/tax environment the way Ghost did by moving to Singapore: https://blog.ghost.org/moving-to-singapore/ which is an _amazing_ country BTW: https://youtu.be/ocg80OZvkMw and https://youtu.be/yDljUyfaqxA _and_ we have a _few_ [friends](https://www.linkedin.com/in/theohdavies) there.

**Comment by nelsonic** [comment]
Snapchat is basing its ops in London: In an unusual move for a US tech company, Snapchat is making the UK its international headquarters - Business Insider
https://apple.news/ArWrQPy3sSZ653DPIUQuO6Q

While there are obvious reasons for them to do so (WPP is also based in London, as are *many* ad agencies!) I would love to what *other* reasons they have to base their ops in London when there are *other* options which are *considerably* more "tax efficient*... 🤔

**Comment by markwilliamfirth** [comment]
Was decided to keep as MDC for the time being
