### ISSUE TITLE
Review Employee and Contractor Benefits

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hq#146]
# Are the _intrinsic_ rewards of working on a `"real human challenges"` _enough_...?

> Watch: https://youtu.be/rrkrvAUbU9Y 
and/or read: http://lateralaction.com/articles/dan-pink-rewards/

Beyond simply _paying_ people for their work or inviting people to [`#dwylsummer`](https://twitter.com/hashtag/dwylsummer?f=images&vertical=default&src=hash) ... what are the different types of "_now that_" `rewards` (_i.e. non-contingent_) we can give people to _thank_ them for their _contributions_ to dwyl's mission and [make people `feel` loved](https://github.com/dwyl/hq/issues/145) an a _daily_ basis.

It can be as simple as `#FreeFreshFruit` in the office or a Team/Company subscription to a learning resource or music streaming service...

# Please Share your Ideas!!

Relates to: #145 (_Best Place to Work!_)

**Comment by Jbarget** [comment]
Limited to non-remote workers but breakfast in the mornings at number 16 could be a nice addition, would be aware of waste though so maybe people could "sign up" for it

**Comment by markwilliamfirth** [comment]
@iteles what are your thoughts on making the following free for employees:

pp py = per person per year

- dwyl summer travel costs - £100 pp py
- large quarterly events e.g. crystal maze #292 - £240 pp py

Headphones with a 2-year warranty is equal to £8.33 pp py

We could also add benefits for:
- Birthdays £30 pp py
- 8 monthly get togethers a year in months without large quarterly staff events £240 pp py

Total comes to £618.33 pp py
**Which is £51.53 pp pm**

Research suggests other tech companies are offering employee benefits in the range of **£55 - £110 pp pm**

**Comment by iteles** [comment]
🎉 My thoughts are that we have been doing everything we've been able to do so far according to our revenue-funded and transparent model and as soon as #229 and #321 are done, we can figure out how much more we can do 😊 
Let's bump up the priority as soon as those are done!

**Comment by markwilliamfirth** [comment]
@iteles I don't see #229 #321 being a blocker to this as the revenue that is being taken out by yourself and Nelson in remuneration is being loaned back to the company and there is more than enough capitol there to ensure that we have a lengthy runway £300/month in employee benefits will hardly make a dent in that

**Comment by iteles** [comment]
You're right, Nelson and I are loaning money back into the business on an as-needed basis, but loans aren't a sustainable way to grow a company and provide for our community. 

Other than financial/expenses decisions that have already been made, we are not embarking on any additional expenditure until we have a *crystal clear* picture of our financial situation. The decision is very much not about a specific amount of money (and applies further than this issue) but about the informed way to run a sustainable business 👍

**Comment by iteles** [comment]
Note: #292 is already approved.

**Comment by nelsonic** [comment]
WHY did the title of this issue change...?!

**Comment by markwilliamfirth** [comment]
>loans aren't a sustainable way to grow a company and provide for our community

I was under the impression that revenue generated over the past two years was intended to further the business' growth, regardless of whether that revenue stayed in the company or was taken out in remuneration and loaned back in.

Are you saying that that capital is only available in emergencies, as opposed to being deployed into growing the business?

**Comment by markwilliamfirth** [comment]
@nelsonic the issue title changed because it reflects the discussion in the issue around non-contingent employee benefits

**Comment by iteles** [comment]
@markwilliamfirth The title change here has changed the nature of the discussion from open and collection of ideas to something more formal and less open. Certainly the tone of the discussion seems to have taken a turn.

[This](https://github.com/dwyl/hq/issues/146#issuecomment-301478888) also doesn't belong in this issue.

**Comment by markwilliamfirth** [comment]
@iteles should I create two separate issues as below?

1. Sharing ideas about employee benefits
2. Discussion around allocation of budget to employee benefits

**Comment by nelsonic** [comment]
I think there's a _gross_ misunderstanding around "employee" vs. "owner". 
I didn't start a company to be an Employee. 
if I wanted to be an Employee I would have taken the job with McKinsey or Google and wouldn't have to deal with any BS around how the money I make gets spent/invested.
Tax efficient expenditure is a _no brainer_. 
Wasting time questioning it is _distracting_ from building the product. 
This issue has been _hijacked_ for a _totally_ different purpose than it's original intent.
Please open a new issue and _never_ change the subject of an issue I create again. ❤️ ✅ ✨

**Comment by markwilliamfirth** [comment]
>if I wanted to be an Employee I would have taken the job with McKinsey or Google and wouldn't have to deal with any BS around how the money I make gets spent/invested.

@nelsonic this issue is a discussion around company money and therefore requires co-owners of the company to be in agreement. The discussion for the budgeting has been moved here (https://github.com/dwyl/hq/issues/331).

With regards to your personal remuneration that is a separate discussion that has been continued here (https://github.com/dwyl/hq/issues/332)
