### ISSUE TITLE
[Not Urgent] New Sofa for Lounge

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hq#15]
Our current lounge sofa is uncomfortable ... at some point we should upgrade it.

Possible options:

http://www.ikea.com/gb/en/catalog/products/S09897094/#/S89896986
<img width="995" alt="ikea-kivik" src="https://cloud.githubusercontent.com/assets/194400/9983963/f8ea366c-6005-11e5-9d3c-fced4e004548.png">

http://www.ikea.com/gb/en/catalog/products/S69124989/#/S99124978
<img width="1003" alt="ikea-norsborg" src="https://cloud.githubusercontent.com/assets/194400/9983953/a172ab44-6005-11e5-8634-f5a41f11ffda.png">

http://www.habitat.co.uk/hyde-charcoal-fabric-left-arm-chaise-sofa,-wooden-legs///fcp-product/435946
video: https://www.youtube.com/watch?v=Iy-TUKGtoM8
<img width="948" alt="habitat-hyde-sofa" src="https://cloud.githubusercontent.com/assets/194400/9983946/4157ef76-6005-11e5-9623-d03f588296a0.png">

http://www.made.com/halston-large-corner-sofa-charcoal-weave
<img width="997" alt="made-halston" src="https://cloud.githubusercontent.com/assets/194400/9983949/5f5f46a4-6005-11e5-95cd-8cb17d15732f.png">

**Comment by iteles** [comment]
`priority-5` but that Halston is drewl-worthy :heart_eyes:

**Comment by nelsonic** [comment]
`Priority-5` indeed ... its dependent on #6 (tidying the lounge)

**Comment by iteles** [comment]
We recently did another sweep of what was available and we're having trouble finding something 'small' enough to fit in the particular wall we want it to go against. The search continues...

**Comment by nelsonic** [comment]
I quite _liked_ the sofa at Ikea last week. but I think we don't _need_ to spend money, so closing.
