### ISSUE TITLE
Individual photos for profile pics

### ISSUE THREAD

**Issue by JMurphyWeb** [dwyl/hq#150]
As requested [here](https://github.com/dwyl/dwyl.github.io/pull/182#pullrequestreview-14345271) . 
I could do with a new profile picture and @nelsonic suggested I may not be the only one. 

Photo can be used for gh profile, linked in and dwyl website. This could be a job for the talented @sohilpandya ?

Ideally we need a _standard_ format for our profile pictures.
I would suggest taking a photo _outside_ in natural light with a Nature (_green_) background.
This is something _everyone_ has available 
and does not require any special studio lighting/backdrop or camera...
@katpas's photo: [team/katerina.jpg](https://github.com/dwyl/dwyl.github.io/blob/aa7a3c04244baad8ea1f0e446e80623a209c3109/public/img/common/team/katerina.jpg) 
![image](https://cloud.githubusercontent.com/assets/194400/21520558/14688006-cced-11e6-9e3f-2a0c8c03cc8b.png)
is a _good_ example. perhaps we could crop the background noise above her head...

**Comment by iteles** [comment]
Got some more of these at dwyl-summer.

Will open an issue in https://github.com/dwyl/dwyl-site if required
