### ISSUE TITLE
Organise Weekend Web Workshop for HL

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hq#151]
_last week_ at the intro workshop with ***HL*** we discussed the _possibility_ of doing a **workshop** with them to get them up-and-running with the technologies we are using to build the project. The _purpose_ of the workshop is to give the _designers_ (_and one developer_) the vocabulary & skills they need to _extend_ the work we are doing both during our engagement and beyond. 
I'm thinking we will need _at least_ **3 full days** (_pref Saturdays because that's when `#16` is "empty"_) but this may extend to a once-a-month thing where we do an in-depth review of everything we have built in the previous two sprints for HL and a features/code "_how we built it_" walk-through which we record as video for the project so we can _ensure_ success of the Open Source project!

> we need _help_ to make `#16` the "_**Ultimate Web Workshop Space**_": https://github.com/dwyl/video/issues/13

I'm thinking of _proposing_ that we do the workshop(s) for ***Free*** (_i.e. dwyl covers the cost of **our** team's time_) if they (HL) agree to be included in the video/footage which we can then use to promote the Training "_arm_" of the Biz... see: https://github.com/dwyl/dwyl.github.io/issues/185

![dwyl-offering-training-highlighted](https://cloud.githubusercontent.com/assets/194400/21466599/64757a22-c9c8-11e6-97af-bcf5f66a1dd3.png)

**Comment by Jbarget** [comment]
@nelsonic Whats HL stand for?

**Comment by nelsonic** [comment]
@Jbarget until the `contract` is _signed_ `HL = "HL"` ... (_opens Chat client to direct-message JB..._)
As _soon_ as we have a _formal_ engagement with them we will 🎉

**Comment by markwilliamfirth** [comment]
ok to close?

**Comment by iteles** [comment]
@markwilliamfirth Let's have a separate issue around the wider 'How shall we use/edit our training video content' in the video repo instead of this one 👍
