### ISSUE TITLE
"Cheap" iPhone for iOS Dev Testing

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hq#152]
@edwardcodes is joining us as ("Junior/Intern") Mobile Application Developer in March 2017. 🎉 
Right now he has a ("Retro" / "old school") phone ...

![edu-iphone](https://cloud.githubusercontent.com/assets/194400/21488344/6b3406e8-cbd6-11e6-91a1-0ee80a2eb138.png)

So... I have ordered him an [**iPhone 5C**](https://youtu.be/Mk_fHT1XLZA) on eBay for £100:
![ebay-order-iphone-5c](https://cloud.githubusercontent.com/assets/194400/21488138/ce186f40-cbd3-11e6-8480-f8d9448944e1.png)
Seems like a price point we can't really go "_wrong_"... 😉 
And, _unlike_ an **iPhone 7** it still has _all_ the features anyone could want! `#HeadphoneJack`

Given that PayPal does not _allow_ me to order anything to an "_unconfirmed_" address, 
we're getting it delivered to `#14 Palmers Road` at some point next week.
(_@jackcarlisle confirmed that he would be in the office next week ..._)

> _When it arrives, someone please inform me so I can request re-routing to our address in PT... thanks!_ ❤️

**Comment by markwilliamfirth** [comment]
ok to close?

**Comment by iteles** [comment]
I can confirm this has reached its destination!
