### ISSUE TITLE
Give Before You Get ?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hq#154]
![give-before-you-get](https://cloud.githubusercontent.com/assets/194400/21519568/15312e18-cce6-11e6-8107-93360c0e7a81.jpg)

> Watch: Ben's "***It's What You Can Contribute***" https://youtu.be/WRYRBGX4lVM 
"_you will be the greatest generation. because when we look back 50 years from now, 100 years from now, 500 years from now ... **You** will be the generation that **unlocked human potential**_"

Personally I _really_ like this mindset, and I would like it to be something everyone in the _team_ aspires to. Specifically if I _make_ time to help someone `else` and `PUT` "time" into their "bank" by helping them solve a problem/challenge in 5 minutes that it _could_ have taken them a _day_ without my input, then that's time _they_ can use to help someone `else` in turn...

Yes, I _know_ this sounds like the mantra of a https://en.wikipedia.org/wiki/Pyramid_scheme
"You have to give us your life savings so you can make even more..."
Watch: "Multilevel Marketing: Last Week Tonight with John Oliver" -> https://youtu.be/s6MwGeOm8iI
"_So everyone kinda gets their money back..._"
But that's _not_ what this is about ...! 
This is a _life philosophy_ not about money! 

This is the _mindset_ people have at Y-Combinator. Sharing their time/knowledge with others freely.
And it _seems_ to be working for them...

> If you're interested in the "long form" of this read: http://www.paulgraham.com/before.html

**Comment by markwilliamfirth** [comment]
@nelsonic should we continue to look into this?

**Comment by nelsonic** [comment]
@markwilliamfirth I don't understand the question ... "_look into_"...?
What is there to "_look into_"?
Has _everyone_ read Paul Graham's post? (_linked to in the original description_)
Does _everyone_ understand that we will _only_ succeed (_in the long run_) if we are all "_givers_"?

I ordered this: https://www.amazon.co.uk/Give-Take-Helping-Others-Success/dp/1780224729
![image](https://cloud.githubusercontent.com/assets/194400/26149594/b870dd42-3af2-11e7-98c2-a2d1d2476577.png)
Hope to read it in the summer.

I'm Still **100% Convinced** that _giving first_ is (_should be a priority_) for _everyone_,
because it _systematically_ makes the world a better place if people _take_ less.

**Comment by mantagen** [comment]
I like that mindset too, and think it's best way - for oneself and for others.

What are the aims of this issue? I see it's been labelled 'discussion', 'enhancement' and 'question' ...

@nelsonic were you thinking that people would discuss, then maybe something about 'giving' could go into DWYL's Vision, Mission, and Values?

**Comment by nelsonic** [comment]
@mantagen I opened the issue to _capture_ the sentiment, and _yes_, get feedback from others.  💬 ❤️

> I think this topic is one for a _personal_ "Blog Post" and then if people _comment_ on the blog that can be the discussion. 👍 

Sadly, a _lot_ of people are "_takers_". 
I've dealt/worked with _enough_ "_takers_" to know that they are _everything_ that is _wrong_ with the world.

> _Many_ people who have been through F&C have _taken_ the training and _run_!
> and yet, we haven't made _any_ progress in learning how to _identify_ "_takers_" _prospectively_
> (_and avoid letting them in the door in the first place!_)

I don't want _anything_ to do with "_takers_", they disappoint and distract me.
I was _gauging_ how may _other_ people in dwyl feel the same way.

What we need to _understand_ is how to _spot_ a "_taker_" 
and _politely_ ignore them.

How do _I_ (_Nelson_) _define_ a "_taker_"?
> _Someone who **expects** an **outcome** **without** making a (_significant_) **contribution**._
> Examples: 
> + people who _expect_ the kitchen to be tidy but don't wash up their dishes.
> + people who ride a bicycle but never maintain it and _wonder_ why it breaks down.
> + (_able-body_) people who _expect_ "handouts" without doing any work.
> + people who spend months learning for "_free_" and make no effort to contribute back by improving the leaning materials.

Closed.
(_blog post will follow soon_: https://github.com/nelsonic/nelsonic.github.io/issues/354 )

**Comment by markwilliamfirth** [comment]
@nelsonic to answer your question, by "look into" I meant further explore this topic and promote discussion surrounding it. The question arose because this issue is 5 months old and there hadn't been any discussion
