### ISSUE TITLE
Lighting @ #16 ?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hq#156]
Who `else` is _uninspired_ by the **Lighting** at `#16 Palmers Road` (DWYLHQ) ? 💡 😕  ❓ 

What can/should we _do_ about it?
+ [ ] ***Measure*** the current level of light and the _mood_ in the room ⚠️ 
+ [ ] ***How much*** of the **_Variable_ Overheads** are _attributable_ to lighting costs? 💸 
+ [ ] ***Who*** do we need to speak to about ***upgrading*** the lights? 💭 
+ [ ] ***Cost/Benefit Evaluate*** our options: 🤔 
  + [ ] **how long** do we have left on the **lease**? ⌛️ 
  + [ ] _Can_ we ***quantify*** the **lost productivity** of having poor lighting in the room? 🤖 
  + [ ] **How much** will it cost to "_re-do_" the lighting to have _daylight_/_full-spectrum_ ***bright*** _dimmable_ lights fitted downstairs? 💰 

Relates to: https://github.com/dwyl/video/issues/13#issuecomment-269859976
CC: @sohilpandya @sofer @iteles @markwilliamfirth

**Comment by nelsonic** [comment]
![40w-ceiling-mounted-led-panel](https://cloud.githubusercontent.com/assets/194400/21862790/9c858056-d832-11e6-8a84-a4c2a21f7bd1.png)

http://www.ebay.co.uk/itm/40W-Ceiling-Suspended-Recessed-LED-Panel-White-Light-Office-Salon-600-x-600-/291757870914

**Comment by sohilpandya** [comment]
@nelsonic great find! Is this the same as https://youtu.be/lMhG-TC8eh4

Do you think we can fix them ourselves or would we need an electrician for the wiring?

**Comment by nelsonic** [comment]
@sohilpandya "_we_" have an electrician we trust so that won't be a "_bottleneck_" we just need to decide how _much_ light we want in the space and whether we want it to be _dimmable_.  😉 

The most important thing we need do is check our lease/agreement to see if there's anything that forbids us from altering the lighting setup. It's kinda terrible. 

also, we need a https://en.wikipedia.org/wiki/Light_meter to _measure_ the quality/lux of the light in room so we can make the "_case_" to the landlord...

**Comment by naazy** [comment]
@nelsonic @sohilpandya Unsure if 2 or 3 of these would be bright enough but I bought one this week and they are SO GREAT. https://www.amazon.co.uk/gp/product/B00SX2FYGM/ref=oh_aui_detailpage_o01_s00?ie=UTF8&psc=1  Can control the lightbulb via your iPhone from anywhere you are in the world (not sure why DWYL would need this but still cool) and you can choose any RGB colour and set a timer so the lights automatically go on/off at a certain time. Some of the lighting options are v v v bright and are the same as the SAD light colours/brightness.

**Comment by sohilpandya** [comment]
@naazy that does look good! I might get one for myself to test it out! 👍 😊 

@nelsonic agreed, need to check the agreement, still keeping an eye out for alternatives in the mean time. 😄

**Comment by sohilpandya** [comment]
@nelsonic @iteles what's the latest on this? worth us looking into getting floor lamps - http://www.officedepot.com/a/browse/floor-lamps/N=5+531470/

Or investigate the costs for getting the the lights mentioned by @nelsonic above?

**Comment by nelsonic** [comment]
@sohilpandya we need to call an "all DWYLers meeting" soon to discuss future plans ...
this is in keeping with: https://github.com/dwyl/hq/issues/145#issuecomment-274768864 where a _few_ people have mentioned ***communication*** as a high priority! 👍 
we have an _open question_ about our London Offices: https://github.com/dwyl/hq/issues/179
which we need to _answer_ before anything `else`.
I am keen to use the space _much_ better once @otajor and his crew move to their shiny new office (_with private meeting rooms..._ `#lucky`😉  )
We could investigate getting a few floor lamps but to my mind at least these are a _Temporary_ solution at best and at worst one that _increases_ the clutter in the downstairs area.
I would _much_ prefer to upgrade the ceiling lights to something _really_ good even at _personal_ expense... our plans to do **Video** require _excellent_ lighting.
and running a co-working space with poor lighting is also _uninspiring_ ... we can fix it! 👍

**Comment by sohilpandya** [comment]
Found this hack at [Ikea hackers](http://www.ikeahackers.net/2015/11/rail-lighting-cheapest-way.html)
<img width="562" alt="screen shot 2017-02-02 at 14 13 46" src="https://cloud.githubusercontent.com/assets/2305591/22552683/e0c81fb4-e951-11e6-8707-d9be94f1f3dd.png">

Looks really interesting

**Comment by nelsonic** [comment]
My Desk Lamp at "Home" is a "SAD" light which produces "Full Spectrum" and helps me "wake up" and be productive at "Early'O'Clock" ... Could we install lights that fit the "SAD" criteria?
I've ordered one of these: https://www.amazon.co.uk/d/Light-Therapy/Compact-SAD-Daylight-Lamp-Seasonal-Affective-Disorder/B01IVMNMA8/
![image](https://cloud.githubusercontent.com/assets/194400/22682623/8f629218-ed0b-11e6-861e-0c1e51dbad64.png)
For use at "my" standing desk under the stairs @ QuietSpace... 
Let's see what people think of it when it arrives. 👍

**Comment by nelsonic** [comment]
What do we think about _trying_ one of these: http://www.lumie.com/products/brazil
![image](https://cloud.githubusercontent.com/assets/194400/22682805/c9f2af0c-ed0c-11e6-91e7-5c99c4a37fd3.png)

It could be positioned _anywhere_ and controlled by the person/people dependent on lighting needs.

**Comment by iteles** [comment]
Closing in favour of https://github.com/dwyl/quietspace/issues/11
