### ISSUE TITLE
2016 year in review

### ISSUE THREAD

**Issue by iteles** [dwyl/hq#159]
I'm pretty terrible at these, but we should write one and share it widely.

We've achieved so much and it would be great for dwylers to realise just what was done, despite the year ahead being so awesome.

Mostly, doing this soon will make sure I actually write things down *as they're happening* in 2017*.

**Comment by nelsonic** [comment]
@iteles _totally agree_ that you are the _best_ person to write this "_post_".
I just reviewed a few PRs ... you did _everything_ `else`...! ❤️  ✅ 
Maybe you can note down the outline/bullet-points in the car on Wednesday...?
If you need _anything_ from me, please let me know!

**Comment by iteles** [comment]
Pulling down the priority on this, whilst it is important and does have a ticking clock, it is not 'urgent' and can become a Year in Review based on our financials as well.

**Comment by nelsonic** [comment]
removing the priority, might as well change the year on it to 2017... cause the next time you will _have_ time to reminisce about the past will be in the "Christmas Holidays" (i.e. December 2017).
🎄 🎅  🎁

**Comment by markwilliamfirth** [comment]
Agreed that this needs to be done in preparation for #213 anyway

**Comment by Cleop** [comment]
Was this issue achived for #213 or is this something we should be preparing for Dec 2017 as @nelsonic mentioned?

**Comment by markwilliamfirth** [comment]
@Cleop this was never written up, but I've now moved them to the blog repo:
https://github.com/dwyl/blog/issues/22
https://github.com/dwyl/blog/issues/23
