### ISSUE TITLE
Water usage meter

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hq#16]
Is there an equivalent of this:
http://techcrunch.com/2015/09/15/fluid-is-a-smart-water-meter-for-your-home/
that we could get to monitor our water usage?

**Comment by iteles** [comment]
I've looked for this in the past and just spent 10 minutes on Google now but never found anything. There have been proposed gadgets like this in the past, but none weathered the storm and now none exist (that I can find).

The only option would be to get an actual water meter from Thames Water but that wouldn't be an economical option.

**Comment by nelsonic** [comment]
Again, not super urgent. but would be *really* good to start tracking our water usage with the aim of *lowering* it over time.

**Comment by iteles** [comment]
Yep, we pay about £530 a year in water charged.

**Comment by nelsonic** [comment]
I shower at the gym which has a one of those push-button "taps" and aim to shower in a single press (less than 2 mins) its a game ...
Ok lets close this for now and come back to it when we get to ***Phase 2***
