### ISSUE TITLE
CRM (or how we keep in contact with the people who we work with and/or are interested in working with us ...)

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hq#161]
Who has experience with CRM and time to flesh out what our requirements are?
> Make or Buy Decision: https://youtu.be/vxZSaDtQgrs

Please see: https://github.com/dwyl/contact

**Comment by markwilliamfirth** [comment]
@nelsonic should we make a new repo for the CRM?

**Comment by iteles** [comment]
Yes please!

**Comment by nelsonic** [comment]
# _Closing_ an issue without making _any progress_ towards getting it _done_ is _unacceptable_. 

A _blank_ repository:
![image](https://cloud.githubusercontent.com/assets/194400/26148725/99fb6218-3aef-11e7-8f3b-78338b53f053.png)
With a _single_ issue:
![image](https://cloud.githubusercontent.com/assets/194400/26148740/a46b3e58-3aef-11e7-9bb7-d71538a96520.png)
That links back to a _closed_ issue....
The requirements have _not_ been captured and yet the issue is _closed_?

My (_original_) ***Question*** was: who has _experience_ with CRM and time to flesh out features?
_Nobody_ responded so I'm guessing that _nobody_ has experience or _cares_ to learn.

I am a _certified_ Salesforce Developer. (_the number 1 CRM system, by far_)
I've used 4 commercial CRM systems in _several_ companies. 
I know _exactly_ what features a CRM system needs to have and how to build something _much better_ than existing options. 

I was _hoping_ other people have _some_ experience _beyond_ "_spreadsheets_" (_which are OK for a 2-person shop but a **nightmare** beyond 5 people!_) ... but apparently not.

No Business Succeeds without a CRM system. 
We either get _focussed_ on building this business,
or we call it a day and get jobs working for someone `else`.
Decide.

**Comment by markwilliamfirth** [comment]
@nelsonic issue was moved to CRM repo as discussion should be held there, not in operations repo. I have not fleshed out requirements as it is not a priority

**Comment by nelsonic** [comment]
Re-opening and self-assigning as this _absolutely_ still needs to get done.

**Comment by nelsonic** [comment]
Ok, I've made an attempt to capture background info and some requirements in: https://github.com/dwyl/contact 
I'm _removing_ the `P1` label and unassigning myself from this issue 
because I think we have other _higher_ priorities than CRM ...
@iteles if you feel that this _should_ be my/our highest priority please comment to that effect. thanks!

**Comment by iteles** [comment]
Closing this issue in favour of capturing further work in the contact issue.
Thank you for making progress on writing down your experience on this @nelsonic 🎉
