### ISSUE TITLE
Go Mammoth Dodgeball on Wednesdays in Shoreditch

### ISSUE THREAD

**Issue by naazy** [dwyl/hq#162]
Me @nelsonic @sohilpandya @Jbarget @roryc89 @Conorc1000 have all expressed an interest in joining a recreational dodgeball 🏀  league for fun. Is anyone else interested? 

**Deets:**
- £70 for 9 x 2 hour slots in Shoreditch so v reasonable at £7.80 a pop! 
- Starts 25 Jan. The game is every Wednesday sometime between 7 and 9pm 
- http://www.gomammoth.co.uk/dodgeball/shoreditch/?leagueid=1010

I _imagine_ that if you can't make a certain Wednesday then you can probs get someone to fill your space but am unsure.

**Register your interest HERE on this issue so we can sign up to be in the same team (we should probably sign up sometime next week).** 

Also **ALL WELCOME**! Feel free to spread the word to lovers/friends/frenemies/parents etc etc 🏃 :running_woman: 👴 👵 

https://youtu.be/hVj6ovI-eP8

**Comment by JMurphyWeb** [comment]
I am keen to get my long limbs involved - count me in.  I could only make it 3 times before Israel mind.

**Comment by nelsonic** [comment]
@naazy do you think we can get enough people together for a Team...? 😮  🤔 
_Fairly certain_ @markwilliamfirth will be interested too... 😜

**Comment by naazy** [comment]
@nelsonic We need 5 more people for a team. Anyone...? @dwyl/ateam

**Comment by tonydaly** [comment]
hell yiiiiis

**Comment by heron2014** [comment]
This is hilarious! I might be up for that!! :)

**Comment by Conorc1000** [comment]
Yes, im so up for this!

**Comment by naazy** [comment]
@thegsi is also keen!

**Comment by naazy** [comment]
I believe we still have some 'maybes'!  

@JMurphyWeb @Jbarget @tonydaly @heron2014 @nelsonic @roryc89 @Conorc1000 @sohilpandya @thegsi Please can everyone 100% interested confirm by saying 'HELLS YEAH' so we can figure out if we defo have enough people for a team! 

Thanks

**Comment by Jbarget** [comment]
YAY
Im keen, I can only make:

25th Jan
1st Feb
8th Feb
15th Feb

**Comment by naazy** [comment]
@Jbarget I think you still have to sign up for the whole 9/10 weeks so would still be like £70 or so. Dat cool? Or maybe you could go halvsies with someone who could take the last 5-6 weeeks?

**Comment by harrygfox** [comment]
Hey @naazy I want to do please please sign me up please and I promise I'll pay

**Comment by Jbarget** [comment]
ah just realised i cant do wednesdays :( - im a NAY :(

**Comment by harrygfox** [comment]
@naazy Gimme Barget's spot!

**Comment by naazy** [comment]
Done @harrygfox !

**Comment by JMurphyWeb** [comment]
Yay but Nay after 20th Feb

**Comment by Conorc1000** [comment]
Yay from me.

**Comment by heron2014** [comment]
I can't do this Wednesday but the rest of the dates are fine!

**Comment by nelsonic** [comment]
I can't do the first few, but I would ❤️  to be a part of the team once back at 100% functionality...
meanwhile does everyone have a DWYL T-Shirt... 😜

**Comment by naazy** [comment]
Ok so maybe @nelsonic and @JMurphyWeb could partner up and do @nelsonic could take over from Jack after 20th Feb?

**Comment by roryc89** [comment]
I'm there! :)

**Comment by naazy** [comment]
@thegsi is a NAY :cry:

**Comment by sohilpandya** [comment]
I'm in! 🎉 I have a reasonable arm so that'll help. 😉

**Comment by tonydaly** [comment]
@naazy I'm in

**Comment by naazy** [comment]
OK KIDS! Thanks for confirming: I believe the team is:

@JMurphyWeb / @nelsonic (Jack to do the first 3 and Nelson to do the next 6?)
@tonydaly 
@heron2014  
@roryc89 
@Conorc1000 
@sohilpandya 
@harrygfox 
meee 
(plus 1 👨 💘 )

so that's 9 full-time people. Go Mammoth recommend teams of 9 but I believe it's 8 people playing at once so there may be subs on and off sometimes but also I imagine there will be the odd weeks where people will need to duck out so should work out well

The total is £495 for 9 sessions for 9 full-time people.
 495 / 9 = £55 per full-timer (the equivalent of £6.10 a session)

Please could each person transfer me £55 with the exception of our part-timers (@JMurphyWeb who owes £18.30 (6.10 *3) and £36.60 (6.10 * 6) respectively) and tick the box next to your name once you've done this:

[ ] @tonydaly £55
[ ] @heron2014 £55
[ ] @roryc89 £55
[ ] @Conorc1000 £55
[ ] @sohilpandya £55
[ ] @harrygfox £55
[ ] @JMurphyWeb £18.30 
[ ]  @nelsonic £36.60 

(I will gitter y'all my deets)

I have reserved our places and **payment is due by either tomorrow 10pm (or early on Tuesday** i'm confused by the email 😕 ) so if most of you could try to wire the money over by then, that would be great! Thanks :)

**First session is this Wed at 7pm :) 🎉 **

**Comment by markwilliamfirth** [comment]
@naazy is it too late for me to join in?

**Comment by naazy** [comment]
@markwilliamfirth ahh ok so basically go mammoth says 9 or 10 people on a squad for only 8 people play at once so we could make it work I'm sure, assuming the odd person will miss the game every once in a while and we can do some subbing on days when everyone turns up! You'd be the 10th person @markwilliamfirth - thoughts? Let me know so I can recalculate what people owe if so 😄

**Comment by markwilliamfirth** [comment]
Yeah I'm definitely up for it! Count me in :)

To ease the whole payment situation Cashew is quite useful (https://getcashew.com/) - makes payments so much easier. Also if you use my referral code (MARKF) you get £1 for free!  😄

**Comment by naazy** [comment]
Perfect thanks for letting me know @markwilliamfirth - will check out cashew next time also! Looks great. I've updated the list of money per person and I'll gitter you my deets now. Also @tonydaly I owe you a wee refund!

**Comment by JMurphyWeb** [comment]
Thanks for organising Naaz! Will pay tomorrow.

**Comment by nelsonic** [comment]
@JMurphyWeb let me know how much I owe for my portion. 💸  (_please/thanks_!) ❤️

**Comment by naazy** [comment]
@nelsonic probably easier to just transfer me directly (see gitter dodgeball group for deets) and @JMurphyWeb can send the remainder. Thanks all!

**Comment by JMurphyWeb** [comment]
have payed @naazy

**Comment by naazy** [comment]
@JMurphyWeb @nelsonic @tonydaly @heron2014 @roryc89 @Conorc1000 @sohilpandya @harrygfox @markwilliamfirth

We're all signed up and have received some more info:

The rules: http://www.gomammoth.co.uk/dodgeball/articles/dodgeball-rules-guide/

There are 15 x 2-3min games per fixture and our game tomorrow is 8-9pm. (I thought we played everyday 7-9pm but I think we actually either play 7-8pm or 8-9pm - sorry for confusion)

According to the rules, there can only be a **max of 5 men** per mixed team so we'll have to do some kinda swapsies every 2-3 mins to make sure it's fair ... only slight issue is that if there are only 2 women (me and @heron2014) then we can only play with a team of 7 instead of 8 :cry:... And **tomorrow** @heron2014 can't make it so I'm the only woman which means a team of 6 😭  - maybe we could recruit another woman just for tomorrow? **Any ideas / anyone have a female friend/lover to who could play tomorrow? If not I can reach out to FAC/DWYL communities?**

**Comment by naazy** [comment]
7.45pm at Haggerston School
Weymouth Terrace
E2 8LS

**Comment by JMurphyWeb** [comment]
So much fun! Hope we are not in too much pain this morning 😃

**Comment by iteles** [comment]
Best team in the world :heart:

https://twitter.com/dwylhq/status/824401092977033220
<img width="648" alt="screen shot 2017-01-26 at 12 50 25" src="https://cloud.githubusercontent.com/assets/4185328/22331947/145181c2-e3c6-11e6-8f4f-8bdb20998bd6.png">

**Comment by RobStallion** [comment]
I'm a little late to the party but if it's not too late and if there is ever room I would love to join 💪
