### ISSUE TITLE
Give the readme a little love

### ISSUE THREAD

**Issue by iteles** [dwyl/hq#163]
It's looking bare right now!

<img width="917" alt="screen shot 2017-01-14 at 22 52 01" src="https://cloud.githubusercontent.com/assets/4185328/21958696/1f4757dc-daac-11e6-8900-6f6e0dae8577.png">

**Comment by nelsonic** [comment]
Yeah, it's about time... 😉

**Comment by iteles** [comment]
Start has been made 👍 Ongoing.
