### ISSUE TITLE
Dehumidifier - which one to buy?

### ISSUE THREAD

**Issue by iteles** [dwyl/hq#166]
I've found that there is *loads* of humidity at dwyl hq this winter and it's curling the pages of any books we leave out!

We need a 
+ Low energy consumption dehumidifier
+ Preferably one that *doesn't* chuck out cold air (i.e. Doesn't make the rooms colder)
+ Possibly more than one as there are at least 2 distinct rooms where this is a problem
+ Big enough deposit that it doesn't need to be emptied multiple times per day

Does anyone have any recommendations?

**Comment by Jbarget** [comment]
@iteles @nelsonic is this for unit 16 or the flat?

**Comment by iteles** [comment]
@Jbarget The flat! 

The heater #122 seems to be doing the trick for the office as far as I can see?

**Comment by carolrmc** [comment]
Hi Inês,

When we moved to Junqueiro we bought a Bionaire. It has a 5 litre capacity
and works day and night. It has been very good.
It keeps the whole flat dry!

hugs
c

**Comment by iteles** [comment]
Thanks @carolrmc, super useful to know! 
Big hugs :heart:
