### ISSUE TITLE
The Post JavaScript Apocalypse with Douglas Crockford (TONIGHT @SkillsMatter) ?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hq#167]
Some people on Gitter mentioned this: 
https://skillsmatter.com/meetups/8363-fullstack-nights-january

It's tonight at Skills Matter | CodeNode, 10 South Place, London, EC2M 7EB 
[map](https://citymapper.com/trip/signature?signature=eJyFkl1PwjAUhv9K01sBe%2FqxdlxiSDTiR0RjDDGkWRuyACvpOr1Y%2BO%2B2GxDwQnfVnr593z7nrMWF9niMmKR8gLBpvA6lq2IFJM9jxVYmblpcOOdNHZdYwEiAEhkbDMmIqIxygaOw0lubjqc39AHJ6QTvY3FjV%2BnOosWmrIOuiiShIH5FKUhJxdGdEUFV586BZlly3zrTuX%2FrzTrt65OY5oLSXkyZkCm2Pbwa85zED5ianXsEr6u6DKnkXRPssuzAFnjmKuOqSVMr%2FJkygvbhZCNz4O9ddHC7ZeGaKp0B7fLO6HimLukYkxd0oKSgh94Bgb%2FpQCqVdWKZ54zjfXrYzpeFXe5sHwiCJBK76uNwsx5uOhB8xtBibYy3dTdB4OhZb7bW1%2BjFDFCPjaYUkfnHAL3dp4uX845NZscmx%2FX5vP81S%2F9BKHsxJSCHBIaQvYIYUzlm8oqQMSHXj0%2Fvd%2FPbZPwVrXoUuv8Bu4awPA%3D%3D)

![the-post-js-apocalypse](https://cloud.githubusercontent.com/assets/194400/21988644/e6378d04-dbff-11e6-9e1a-4a8166cc026b.png)
Anyone going?

**Comment by nelsonic** [comment]
Went. Was good.
![tokimeku](https://cloud.githubusercontent.com/assets/194400/22030263/fd876bd4-dcd4-11e6-8867-3375d4a0d421.JPG)

![douglas-crocford-remove-impurities](https://cloud.githubusercontent.com/assets/194400/22030278/07d543a4-dcd5-11e6-921a-506eaf3d1dca.JPG)

![douglas-crockford-be-careful-out-there](https://cloud.githubusercontent.com/assets/194400/22030328/317f7490-dcd5-11e6-90f3-fcdc42149f23.JPG)

DC mentioned FP and Elm. 
Got to get some re-assurance that we're ahead of the curve: https://github.com/dwyl/learn-elm

also @JakubSvihla asked DC: "_which language should I learn to make the most money_...?"
which got a good laugh from the audience. 
and the _obvious_ answer is: https://github.com/dwyl/learn-elixir (_after `elm`..._) 😉

**Comment by mk4111** [comment]
Sad I missed this....!

**Comment by nelsonic** [comment]
@mk4111 we're sad you couldn't make it. don't worry tho, you didn't miss much.
alls I can say is: https://github.com/dwyl/learn-elm "DC" mentioned Elm 4 times in his talk. 😉

**Comment by nelsonic** [comment]
@mk4111 the _official_ video of the event: https://skillsmatter.com/skillscasts/8656-fullstack-nights-january you didn't "_miss_" anything. 😉
