### ISSUE TITLE
What is our Culture ? (Hofstede's cultural dimensions theory)

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hq#168]
https://en.wikipedia.org/wiki/Hofstede's_cultural_dimensions_theory
https://youtu.be/_BoQlz0zZc4

What can we _do_ to:

1. ***Eliminate*** (_or Minimise_) "**Power Distance**" by sharing responsibility/authority.
2. Encourage **Collectivism** (_avoid Individualism where people hoard knowledge instead of sharing_!)
3. ***Avoid Uncertainty*** about the future by sharing our goals/plans and estimating our efforts.
4. Be more ***Feminine*** (_family & work-life-balance oriented, not money or personal-gain focussed_)
5. Focus on **Long-term** (_or always have [long-range thinking](https://github.com/dwyl/phase-two) in mind in all our decisions_)
6. Be more **Restrained** (_delay gratification_)

If you can think of _practical_ ways to _implement_ any of the above, please share! 👍

**Comment by markwilliamfirth** [comment]
Not sure these points do align with the company culture. Also point number 4 potentially quite sexist there(!)

**Comment by iteles** [comment]
This is more of a *reference* issue, rather than something actionable *for now*.

**Comment by nelsonic** [comment]
Sadly, this thread is typical of my experience in @dwyl and the _negativity_ of "ghost". 👻 

1. Nelson has an idea to use a set of axioms to systematically codify culture. 💡 
2. "ghost" adds exactly _zero_ value and takes a dump on the idea. 💩 
3. Boss lowers priority so the idea becomes relegated to "_nice, but never going to happen_" pile. 👎 

This is how "startups" _fail_.
