### ISSUE TITLE
License for InVision

### ISSUE THREAD

**Issue by sohilpandya** [dwyl/hq#170]
Hi @nelsonic, 

Just had a chat with @harrygfox and he is only able to have 3 projects with the minimum paid [account](https://www.invisionapp.com/plans) that he has, Would it be better to have a DWYL account for it.

**Comment by harrygfox** [comment]
CUL is taking 3 projects, SL has 1, OA has 2 etc.

**Comment by nelsonic** [comment]
@sohilpandya great question. ❓ 
![image](https://cloud.githubusercontent.com/assets/194400/22116237/c84e0c18-de67-11e6-9c1e-4e1a4c39cd8e.png)
Do we need the "_Professional_" or "_Team_" plan...? 🤔 
And... can we have a _demo_ video of _how_ @harrygfox _uses_ InvisionApp to accomplish his work? 🎥

**Comment by harrygfox** [comment]
@nelsonic I've bought a Professional account for myself now so I can support all concurrent projects there

**Comment by sohilpandya** [comment]
Closing as it's resolved for now. 👍

**Comment by nelsonic** [comment]
@sohilpandya I would follow it up with a _tutorial_... 😉
