### ISSUE TITLE
dwyl podcast!

### ISSUE THREAD

**Issue by iteles** [dwyl/hq#171]
In line with our `open source` mentality, we should also talk about our journey in audio/video form!

**Comment by markwilliamfirth** [comment]
Closed in favour of new podcast repo https://github.com/dwyl/podcast

**Comment by iteles** [comment]
There is really no point in adding _another_ repo until we have made a decision to do this and determined a timeline.

**Comment by markwilliamfirth** [comment]
Nelson agreed with you with his emoji expressions and I agree too 👍 

Better to have it in a repo than hq issue as other people can find and contribute to it

also the video repo is a good example where there have been no timelines, but it is slowly growing

Please reopen if you disagree! (trying to clean up the backlog)
