### ISSUE TITLE
Stated aims for 2017

### ISSUE THREAD

**Issue by iteles** [dwyl/hq#172]
Our main aims for 2017 are:
+ [ ] Continue to delight our *existing* clients
+ [ ] Focus a sizeable portion of our resources on developing internal applications that will help us become more effective as an organisation (**open source*** of course)

Keeping it simple and focused.

**Comment by markwilliamfirth** [comment]
@iteles shall we put this in an md file rather than an issue?

**Comment by markwilliamfirth** [comment]
Links to mission.

**Comment by rub1e** [comment]
This is sooooo last year - ready to close @iteles?
