### ISSUE TITLE
How do you measure leadership?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hq#173]
https://blog.ycombinator.com/how-do-you-measure-leadership/

**Comment by iteles** [comment]
@nelsonic Could you please move this to https://github.com/dwyl/leadership ?
Don't want to take credit for your find  😉

**Comment by iteles** [comment]
@nelsonic Tried to transfer this issue to https://github.com/dwyl/leadership but it didn't give me the option to! Could you please open the issue there again?
I don't want to take credit for it 😉 and it's a good article!

**Comment by nelsonic** [comment]
Derp ... (_repo not found ..._)
![image](https://user-images.githubusercontent.com/194400/52013045-0100b100-24d4-11e9-9bab-15bc8ab752de.png)

GOTO: https://github.com/dwyl/leadership/issues/7
