### ISSUE TITLE
In Case of Fire: git commit, git push, then leave the building! (Wall Sign)

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hq#175]
![image](https://cloud.githubusercontent.com/assets/194400/22197464/07d7a80a-e14a-11e6-87bb-ec408edbba5e.png)

Super large version: http://abload.de/img/in_case_of_fireirrtb.jpg

We should print this off and put it on the wall @DWYL HQ. 

What _other_ posters should we have up? 🤔

**Comment by markwilliamfirth** [comment]
Closing as I think this might breach fire safety law - Nelson if you have more decoration suggestions for Focus Hub please post them in the new FH repo
