### ISSUE TITLE
Where should we be based as a *company*?

### ISSUE THREAD

**Issue by iteles** [dwyl/hq#178]
In light of Brexit and our aims of being a [remote-first](https://github.com/dwyl/remote) organisation, where does it make sense to base our company?

**Comment by markwilliamfirth** [comment]
@iteles would you be able to speak to Andrew about Portuguese corporation tax implications? Might be an idea although potentially too bureaucratic

**Comment by markwilliamfirth** [comment]
"Float"?!

#189 ?!

**Comment by nelsonic** [comment]
@markwilliamfirth lol. 😆  
(_maybe... not to be discussed `before` there is a super-successful product tho..._!)
***or*** we could just be based on a ***ship*** in **international waters** and **avoid _all_ bureaucracy**! ⛵️

**Comment by iteles** [comment]
Note I have emailed a lawyer I  know well (professional, not personal relationship) in Portugal and am awaiting a response on the implications.

**Comment by iteles** [comment]
Spoken to the tax lawyers and am emailing further details. Will understand what needs to be done if we decide to base ourselves here within the next week or so.

**Comment by iteles** [comment]
I don't think this issue has been resolved and I still need to write in the update from the lawyers. 
Currently sitting with me 👍

**Comment by iteles** [comment]
Currently waiting for the lawyers to give us the correct bank account details, invoice was issued in early April but I have now requested that it be sent to the correct financial dwyl address.

**Comment by iteles** [comment]
This is still in progress with both the bank and the lawyers 🙄

**Comment by iteles** [comment]
Chased again. Bank account is currently being opened and causing delays. 🙄

**Comment by iteles** [comment]
BIC has been throwing up roadblocks for 3 months. Switching to BPI.

**Comment by iteles** [comment]
For now, we will be based in the UK. We will reopen in 2018 around the possibility of moving the _legal base_ to Portugal whilst continuing our work in the UK.

**Comment by markwilliamfirth** [comment]
@iteles why was this decision made? What happened with the lawyers?

**Comment by iteles** [comment]
The lawyers just told us what the options were and what we would have to do to base the company in another country. For now, with the pound quite low and all our clients in the UK, they advised us this wouldn't make sense for dwyl.
When myself and @nelsonic eventually start to spend more time in Portugal and as our clients become less UK focussed, this will be revisited to see if it makes sense.
