### ISSUE TITLE
2017 London base

### ISSUE THREAD

**Issue by iteles** [dwyl/hq#179]
As mentioned in #178, we are planning to be a [remote-first](https://github.com/dwyl/remote) organisation, but in 2016 we will still need to have a London base of operations.

We could stay where we currently are on Palmers Road, but we should have a look around and see what else is available.

Step 1: Determine our requirements.
Step 2: Research.

Does anyone have thoughts on what you would like our *requirements* for a London base to be? Linked to #145

**Comment by nelsonic** [comment]
2016? (_long day_?) 😉

**Comment by Jbarget** [comment]
@iteles @nelsonic at the basic level im thinking there are 2 options:
These are just the pros and cons that come into my head, please add if you can think of more

## 1. working within a co-working space and hiring desks

### Pros
- usually on a monthly rolling contract so costs of rent are easily adjustable as to how much space is needed
- potential connections through other people working in the space
- maintenance and deep cleaning is not our responsibility
- probably a wider choice of location
- potential onsite facilities (gym?)

### Cons
- no 'ownership' of the space
- noise could be an issue, although we can be noisy too :) 


## 2. having a DWYL dedicated office with just DWYLites

### Pros
- We can make it our home away from home (decorations, facilities, social events)
- We could host events/meetups which could be good publicity
- Security in knowing we have desk space for a length of time

### Cons
- upkeep/maintenance (which seems to be a lot of the main issues at the moment)
- if DWYL is going remote then a long term contract would mean wasted £££ if the desks arent being used by DWYLites

**Comment by iteles** [comment]
@Jbarget Thanks for this!!

If you have a list of requirements for a DWYL work space in 2017 (you've been so excellent at helping maintain a semblance of order in the one we're in now!), that would also be super useful ❤️

**Comment by Jbarget** [comment]
@iteles can i list a bunch of desirable features of a workspace (i dont really have any requirements)

**Comment by iteles** [comment]
@Jbarget That would be perfect :heart:

**Comment by Jbarget** [comment]
In order:

1. As much natural light as possible
2. Standing desks
3. Monitors
4. Nice furniture
5. Recycling
5. Easy access to electricity
6. Greenery/decorations

All of the above would be superseded by cleanliness.

**Comment by nelsonic** [comment]
@Jbarget https://en.wikipedia.org/wiki/Two-factor_theory 😉

**Comment by markwilliamfirth** [comment]
Does anyone have any thoughts on location?

**Comment by Jbarget** [comment]
@markwilliamfirth I have dont have a preference for a particular location, my only criteria would be relative to where I live, W9. My current cycle takes 45-50 minutes each way. If It was more than that I would be less motivated to come in (mainly in the winter)

**Comment by Jbarget** [comment]
@iteles @nelsonic is it ok for me to push back tomorrow morning to 9:30am?

**Comment by markwilliamfirth** [comment]
If we decide to move to another location I think an office close to good underground and/or bus connections might be an advantage in terms of people travelling in and travelling to visit client sites. Currently there is quite a walk to Bethnal Green / Mile End and it only connects us to the Central line.

A more central location might also be advantageous for those from W and E postcodes to have short commutes?

**Comment by nelsonic** [comment]
@markwilliamfirth we need to gather _all_ the requirements for our location ...
a central location is a _good_ idea but need to be balanced with cost... 
we need to make QS work _really_ well, then we can think about alternatives. 👍

**Comment by nelsonic** [comment]
@markwilliamfirth was there a _task_ created to capture this work?

**Comment by markwilliamfirth** [comment]
This task is closed in favour of https://github.com/dwyl/hq/issues/180

Issue will be reopened if this becomes a requirement in future, however it is not currently a requirement or priority
