### ISSUE TITLE
Should we create a repo for UK tax information?

### ISSUE THREAD

**Issue by iteles** [dwyl/hq#18]
A fair number of the freelancers who worked with us during [#dwylsummer](https://github.com/dwyl/summer-2015) have asked for help in understanding what it is they need to fill out for [HMRC](https://www.gov.uk/government/organisations/hm-revenue-customs) and what they need to pay in taxes, etc.

This would be very UK specific so doesn't gel perfectly with our remote working culture, but seeing as there has been a verbal demand for it, should we put together a repo on this? I would propose that it would be updated once a year when we have to do our own taxes anyway (and have a disclaimer that we are not experts).

**Comment by iteles** [comment]
@nelsonic Thoughts?

**Comment by nelsonic** [comment]
Yes, *initially* it makes sense for it to be a Repo so we can gauge interest.
