### ISSUE TITLE
Should we stay at no. 16 Palmers Road in 2017?

### ISSUE THREAD

**Issue by iteles** [dwyl/hq#180]
Our current London office is in the co-working space at 16 Palmers Road.

After we have determined our *requirements* for a London space in #179, we will need to determine whether staying where we are is our best option.

@sofer Can you please confirm how much the rent + rates + winter bills (electricity, water, cleaner and internet) are for the *whole* of no. 16 so that we know how much we would need to cover additionally once current tenants move out?

**Comment by nelsonic** [comment]
@iteles re-writing _history_ isn't an `<option>` (_unless there's a time machine U forgot to mention..._) 😉

**Comment by sofer** [comment]
|Description|Monthly|
|----|----:|
|Total cost of lease with Founder London|£3,900|
|Total paid in rent by FAC for No.14|£2,200|
|Rates (16)| £300 (approx)|
|Other expenses (16)| £100 (approx)|
|Total costs of No.16| £2,100 (approx)|
|Total rental income in January|  £2,500|
|Total rental income from mid-Feb| £960|
|Impending shortfall| £1,200 (approx)|

**Comment by iteles** [comment]
@nelsonic oooooooooooh, it took me a while to realise what you were talking about 😆 

@sofer Thanks!

**Comment by Jbarget** [comment]
@iteles is the aim to replace the tenants from mid-feb?

If so I can post in a facebook group im part of where there seem to be co working spaces being offered which has a few thousand people in it and is active hourly.

**Comment by nelsonic** [comment]
@Jbarget thanks for being _interested_ in this discussion. if you want to help us, let us know when you are _free_ for a tasty meal so we can discuss further. (_don't worry we will post everything on GitHub too, just a few things we need to "bounce ideas" on first... hint_: https://github.com/dwyl/video/issues/13 `#plans`)

**Comment by Jbarget** [comment]
Sounds like a plan, next week?

**Comment by iteles** [comment]
@Jbarget Lunch on Wednesday?

**Comment by Jbarget** [comment]
can we do breakfast? ive booked in for lunch with the Premises committe

**Comment by iteles** [comment]
What time were you thinking?

**Comment by Jbarget** [comment]
9am?

**Comment by nelsonic** [comment]
@Jbarget that's do-able. 🕘 🍴
Wanna come to our house and I will make you _delicious_ breakfast from scratch? 😉 
(_same offer goes for **anyone** `else` interested in joining us!_)

**Comment by Jbarget** [comment]
@nelsonic @iteles can i push back tomorrow morning to 9:30am?

**Comment by nelsonic** [comment]
@Jbarget we are _available_ when ever you are free. 👍

**Comment by nelsonic** [comment]
Did we get a _recorded_ decision for this? or are we just closing issues for fun?
Who _made_ the decision? What were the decision considerations/criteria, pros/cons, cost/benefit etc?
When will the decision be _re-visited_?
What are the ***Key Metrics*** that need to be met with this decision? 
how do we _measure_ if it's a _good_ decision?

**Comment by markwilliamfirth** [comment]
@nelsonic this was a decision made by @iteles. In summary it was decided to stay at number 16 as this was beneficial for our close partnership with Founders & Coders.
