### ISSUE TITLE
Healing rsi pains

### ISSUE THREAD

**Issue by shouston3** [dwyl/hq#181]
For those suffering from any joint pains, I feel your pain (as of the last couple of weeks).

I have only just made a start on improving the ergonomics of my workspace, but would love to hear more about how others have optimised the comfort of their working environment.

For those who are looking to put a stop those sore hands and wrists at the end of the working day, the following is the action I have taken so far to ["healing my rsi"](https://blog.evanweaver.com/2012/09/05/a-programmers-guide-to-healing-rsi/) (<--- great read)

### Step 1: Get an ergonomic keyboard and mouse

(I'm not sure how useful the keyboard will be to those who don't touch type, but to those who do, after just one day you won't want to go back).

I went for the [microsoft sculpt](https://www.microsoft.com/accessories/en-gb/products/keyboards/sculpt-ergonomic-desktop/l5v-00006) keyboard and mouse.

Although it's a little bit of a spend, it's totally worth it.

It was incredibly quick and easy to set up and both the keyboard and mouse are really, really comfortable.

If you need to remap any keys, look at using [seil](https://pqrs.org/osx/karabiner/seil.html.en) or gitter me if you can't work it out [![gitter badge](https://img.shields.io/badge/gitter-shouston3-brightgreen.svg)](https://gitter.im/shouston3)

### Step 2: Try standing desks

I have found this to be really great for posture and just feeling great when you work, and should help with any back pains.

They probably aren't for everyone, but no 16 has a few of them lying around, so you might as well jump on one and see if they're for you.

### Step 3: Take regular breaks

Get a [pomodoro timer](http://tomighty.org/) and stick to it.

Not only is it good for your joints, it's also great for your productivity.

@JMurphyWeb, @otajor, @g-sam or anyone else let me know if there is any more ergonomic customisation hacks that should be included here.

**Comment by iteles** [comment]
@shouston3 Thank you so much for sharing these tips! 😍 
I've seen this crop up with quite a few people in the last few weeks (and I had the same myself a couple of years ago), so it's so good to see that each person won't have to re-invent the wheel with this.

We should find a more prominent home for this content soon too ✨

**Comment by g-sam** [comment]
My two cents:
– get Dragon for Mac. It's amazing.
– I found a vertical keyboard mounting most comfortable. The best way to achieve this is with the ErgoDox. Get the lightest keyswitches and take a look at [my key map](https://github.com/qmk/qmk_firmware/tree/master/keyboards/ergodox/keymaps/galson)!
– In terms of exercises I do the following every hour: rotate shoulders fifteen times both directions, shrug shoulders fifteen times, rotate forearms around elbows both directions fifteen times, rotate wrists both directions fifteen times,  stretch arms thoroughly.
– beware of strength training: it can make it worse. Same for bike riding unfortunately.
– I like to type standing up, but with the keyboard on a desk of normal height, so the arms are hanging down.

**Comment by markwilliamfirth** [comment]
@shouston3 you should blog about this! Let us know if you post anything on your blog and we'll share it, or if you'd like to be featured on the DWYL blog let me know 👍 

Links to:
https://github.com/dwyl/content/issues/3

**Comment by otajor** [comment]
> DWYL blog

Ooooh... 😮

**Comment by markwilliamfirth** [comment]
Closed in favour of https://github.com/dwyl/blog/issues/13
