### ISSUE TITLE
Listen to "evolving with your company"

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hq#184]
![img_3500](https://cloud.githubusercontent.com/assets/194400/22399085/622cce7e-e58d-11e6-9ad5-b815027d8b16.PNG)
http://ecorner.stanford.edu/podcasts/4860/Evolving-With-Your-Company

**Comment by nelsonic** [comment]
Does _closing_ the issue mean _everyone_ ***listened*** to the Podcast?
Or are we just "_spring cleaning_"?

**Comment by markwilliamfirth** [comment]
@nelsonic it was closed when grooming the backlog of ops issues

Please reopen if it is still an issue and assign people as appropriate

If it's just for sharing content then we'll be creating a new place for that #298
