### ISSUE TITLE
How do we keep the office clean?

### ISSUE THREAD

**Issue by iteles** [dwyl/hq#186]
There are lots of people coming and going from the dwyl office, we need to set the standard of cleanliness.

I suggest:
1. Start with excellent lighting (https://github.com/dwyl/hq/issues/156)
1. Establish the rules for how we want the space to look/feel and what a respectful team does
1. Mega tidy up to set the scene
1. Create list for the weekly cleaner so that there is no doubt what needs to be done
1. Unleash the dragons! (No, just kidding, but it felt right) 🐉 

Thoughts?

**Comment by markwilliamfirth** [comment]
new issue in qs
