### ISSUE TITLE
DWYL Internal Workshops

### ISSUE THREAD

**Issue by sohilpandya** [dwyl/hq#188]
After working with some talented people on the **City** project, @iteles and I discussed having internal workshops. I feel there is still so much knowledge that is held by individual teams within DWYL, ideally we would like all of this to be available online for everyone, but having workshops is a good starting point? (we can always film these and put them online)

**Ideas**
- Harry's workshop on BEM with a little more hands on time. (I loved it last time, but couldn't film it unfortunately)
- Sam's workshop on Node Debugger
- OA workshop on Postgres Migration
- EM codebase is fully modular, Process they went through to achieve that.
- many more that I may have missed.

**Comment by nelsonic** [comment]
Relates to: https://github.com/dwyl/video/issues/17 🤓  🚀

**Comment by markwilliamfirth** [comment]
These have been carried out since this issue was posted

e.g. #345 #368 

@sohilpandya please reopen this issue if there are more steps here!

**Comment by sohilpandya** [comment]
@markwilliamfirth, agree we've had a couple of them, but we need more!!! like on a regular basis! :)

**Comment by markwilliamfirth** [comment]
@sohilpandya agreed! If you have more ideas please post in https://github.com/dwyl/events (this covers all events including dojos, workshops, talks, etc)
