### ISSUE TITLE
"Exit Strategy" ...?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hq#189]
# What is DWYL's "_Exit Strategy_" ?

Today we were _asked_ what our "***exit strategy***" is for DWYL ...
This is not the _first_ time this question has been _asked_ ... 
(_in fact it's a **common question** among "**Tech Startups**"_)
so _maybe_ we should ***answer*** it somewhere ... so we can link people to it.
@iteles and I have discussed this question _extensively_ but, 
we have not _clearly communicated_ it to everyone `else` in the team/community... 
so this is our attempt to _clarify_.

## Start with the Definition of "_Exit_"

> "**Investopedia**" defines/describes a "***Business Exit Strategy***" as:
"_An entrepreneur’s strategic plan to sell his or her investment in a company he or she founded. An exit strategy gives a business owner a way to reduce or eliminate his or her stake in the business and, if the business is successful, make a substantial profit. If the business is not successful, an exit strategy enables the entrepreneur to limit losses._" 
see: http://www.investopedia.com/terms/b/business-exit-strategy.asp
and ***Exit Strategies*** for Your Business: https://www.entrepreneur.com/article/78512

By _that_ definition, we (_the co-founders of DWYL_) do ***not*** have an "_Exit Strategy_" 
(to ***sell*** the company to _anyone_...)

## Why did you _Start_ a Company if not to have an "_Exit_"...?

It's worth _understanding_ the _reason_ ***why*** we created DWYL in the _first_ place.

The _reason_ we are working in our _own_ company rather than _anyone_ else's 
is described _way_ more eloquently by Clay Christensen:
[![How Will You Measure Your Life? Clay Christensen](https://cloud.githubusercontent.com/assets/194400/22449227/c06eb4e6-e756-11e6-97b1-c07ab6c1879d.png "Click to watch!")](https://youtu.be/tvos4nORf_Y)

Summary of his book on the Harvard Business Review:
[![create a life with purpose](https://cloud.githubusercontent.com/assets/194400/22448966/d87339c4-e754-11e6-9b8b-df15d85df39c.png)](https://youtu.be/lpjLBIqDrvQ "how will you measure your life")

> 1. "_is there something that I can leave the world, that is **bigger than me**? 
that will **help other people become better people**..._"
> 2. "_**how** will I **measure** whether I am **achieving** that **goal**...?_"

We started DWYL to do what we love doing (_make things with our brains/hands that solve problems_)
and make the most of our _finite_ lives (_if you have never worked somewhere depressing, don't bother reading any further..._)

_Watch_ Advice to Entrepreneurs: https://youtu.be/QoqohmccTSc
[![50 Entrepreneurs share priceless advice](https://cloud.githubusercontent.com/assets/194400/22448216/b31024d0-e74f-11e6-914b-1279b9fab146.png)](https://youtu.be/QoqohmccTSc "click to watch")
> "_**Build things** for **yourself** that **you** would **want**_" ~ Steve Wozniak

## Don't you _Want_ to get/be "_Rich_"...?

> We did _not_ start a company to "_get rich quick_".
Else we would have taken jobs in _Investment Banking_ after graduating with our economics/accounting degrees!
This song summarises how we feel: https://www.youtube.com/results?search_query=Make+the+money (_excuse the bad language_)

Is there anything "_wrong_" with having a **_financial_ goal** for yourself and your loved ones?
of course not! In fact having a financial goal is _essential_! Without a _clear_ understanding of finance you will be stuck doing something you don't _love_ for _most_ of your life.

Perhaps a **_better_ question** is: 

### "_how much money do you **need** to live you **best** possible life...?_"

We've _discovered_ that as long as we have "_enough_" cash to pay all our bills, eat healthy food and live a fullfilled life with meaning/purpose the _number_ of dollars/pounds/euros/ren/yen/etc. we have in the "_bank_" ***really*** does not matter... 

## What does this _mean_ for DWYL?

We have _no intention_ of ***ever*** selling ("out").
We want to build something sustainable that creates value for people.
And as long as ***everyone*** in the team/community/company has "_enough_" money to live their ***best*** life, we will `continue` to be _happy_.

## “Having money isn't everything, _not_ having it is.” ~ Kanye ([_Good Life_](https://youtu.be/FEKEjpTzB0Q?t=3m8s))

![image](https://cloud.githubusercontent.com/assets/194400/22448489/c4a5ec46-e751-11e6-8a8d-57131fe9e734.png)

If you were _lucky_ enough to get to spend "_enough_" time with your loved ones throughout your life then feel free to take this for granted, but the rest of us who feel sadness or regret for not spending more time with loved ones who are no longer alive can _understand_ this:

![image](https://cloud.githubusercontent.com/assets/194400/22448889/41ed48c8-e754-11e6-8c0f-fa72a81aae11.png)

**Comment by nelsonic** [comment]
@iteles I'm thinking of _fleshing_ this out into a "post". where should it go? on my own notes or somewhere in DWYL? e.g: https://github.com/dwyl/start-here ?

**Comment by iteles** [comment]
@markwilliamfirth There are no linked commits or PRs so it's safe to assume this still needs doing :+1:

**Comment by markwilliamfirth** [comment]
@iteles thanks. I assume best to @nelsonic then

**Comment by nelsonic** [comment]
Clearly _not_ a high priority, so closing. 👍

**Comment by markwilliamfirth** [comment]
@nelsonic it needs to be recorded in an MD before closing (that was my question here https://github.com/dwyl/hq/issues/189#issuecomment-299815861)
