### ISSUE TITLE
i really like this coffee/storage table ...

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hq#19]
<img width="1016" alt="made-hooper-real-wood-table" src="https://cloud.githubusercontent.com/assets/194400/10130416/6f7b12fa-65c0-11e5-9edb-64a4d8f0999b.png">

http://www.made.com/hooper-storage-coffee-table-natural-ash
Just thought I'd mention it ...
I'd prefer to *make* one than buy it, especially at £159 ...
but if I price my *time* at "*market rate*" its kind of a steel considering how long it would take me to make it from scratch...

**Comment by iteles** [comment]
So beautiful :heart_eyes:

**Comment by nelsonic** [comment]
Yeah... agreed. We don't *need* it.
