### ISSUE TITLE
Financials | Dealing with receipts in different currencies

### ISSUE THREAD

**Issue by iteles** [dwyl/hq#190]
From dwylsummer, we end up with a lot of receipts in Euros.

How do we deal with these in our self assessments and end of year accounts?

**Comment by markwilliamfirth** [comment]
Links to #191

**Comment by markwilliamfirth** [comment]
@iteles did you pay the Euros in cash or was everything paid in card transactions?

**Comment by iteles** [comment]
Mostly cash @markwilliamfirth, we exchanged money in bulk as that's cheaper.

**Comment by markwilliamfirth** [comment]
The best way to deal with this is to convert the Euros back to Pounds at the rate at which your cash was exchanged when you converted it.

If you don't have this rate, you can use the official rate at the *start* or *end* of the trip. HMRC accepts either.

If you have used your own cash, simply expense the amounts. If you have drawn cash from the company account to exchange then this will need to be assigned to the "petty cash" account in Xero, showing how much cash had been withdrawn.
