### ISSUE TITLE
Expenses

### ISSUE THREAD

**Issue by markwilliamfirth** [dwyl/hq#191]
We need an efficient method of filing receipts and claiming expenses.

Requirements:
+ [ ] Links with Xero
+ [ ] Export Data (_with any uploaded images/attachments_)

If Expensify:
- [ ] Add to [Google Apps]( https://docs.expensify.com/advanced-admin-controls-domain-control/google-apps-sso)

**Comment by markwilliamfirth** [comment]
I have heard good feedback about Expensify, so I have signed up with finance+expensify@dwyl.io to test it out

**Comment by nelsonic** [comment]
***Expensify*** looks _good_ for our basic use-case. 
_Boggles_ my mind that they need to charge $5/user/month for this 
(_when Google charges $5 for calendar, email, docs & drive ..._)
https://use.expensify.com/pricing/
![image](https://cloud.githubusercontent.com/assets/194400/22464963/4f72ad78-e7b1-11e6-8ba9-31c1dc6d7301.png)
@iteles this is _why_ we need to focus on Product.
Beyond the "_integrations_" with other services https://developer.xero.com/documentation/api/expense-claims
and "_smart scans_"  (OCR) https://github.com/tesseract-ocr/tesseract/#about
a reasonably competent developer could build this app in a couple of sprints. 

But... in the _short_ term, I _agree_ that `if` ***Expensify*** has an API and/or it pushes the data directly in Xero, we should use it. thanks @markwilliamfirth 👍

**Comment by markwilliamfirth** [comment]
@nelsonic yes it connects directly with Xero. The $5 investment is likely worth the time if it promises what it says it does

@iteles I've connected it to Xero now and invited you. Maybe try one receipt and see how it works? Or give one to me to try?

**Comment by markwilliamfirth** [comment]
[Entryless](https://www.entryless.com/) is also a potential solution.

It's free, but takes several days to process receipts, so is not suitable for our immediate use case of filing the receipts by COB 1st February 2017

**Comment by markwilliamfirth** [comment]
I think in the interim we should use the standard Xero app and expensing feature and look into automating using expensify and entryless at a later date.
