### ISSUE TITLE
Spending in Foreign Countries

### ISSUE THREAD

**Issue by ghost** [dwyl/hq#192]
Links to #190 

We need an efficient way of spending in foreign countries. The current process is to convert personal cash into the local currency, spend this and then file the receipts as expenses.

We should investigate interbank rate cards as alternative solutions that may be cheaper and more efficient for company spending and/or filing of expenses.

Below are some starting points to research:

**Company card solutions:**
[Revolut for business](https://business.revolut.com/) - not out yet, but have signed up for early access

**Personal card (expensing) solutions:**
[Revolut](https://revolut.com/)
[Monzo](https://monzo.com/)
Interbank credit card (many options available) e.g. [Nationwide Select Credit Card](http://www.nationwide.co.uk/products/credit-cards/select/features-and-benefits?intcmp=nord)

@iteles what was the service you used to exchange money last time you went to Europe? Do you know what the date and exchange rate was?

**Comment by iteles** [comment]
Assigning this to myself and adding the question label so I can look for this on Thursday after our accounting deadline!

**Comment by iteles** [comment]
@markwilliamfirth In answer to the question, we've used ICE in the past but in the last year, we have simply used the money from our personal accounts in Portugal so haven't needed to exchange at expensive rates.

**Comment by iteles** [comment]
Dealt with, linked to #430
