### ISSUE TITLE
New Stickers for Wireless Headphones

### ISSUE THREAD

**Issue by markwilliamfirth** [dwyl/hq#193]
We need some new stickers that are suitable for putting on dwyl wireless headphones #147 

@iteles where did the previous stickers come from? How much were they? You mentioned the hexagon shape might be an issue - in your opinion, would circular stickers function better?

**Comment by iteles** [comment]
Absolutely have never seen this issue, SORRY! :(

We have always got our stickers from diginate.

I think they need to be either thinner (in terms of a flimsier material) or probably a very different shape that isn't forced to sit over and around the protruding 'bose' wording. Maybe something on the actual 'hairband' section as opposed to the cups is the only thing that could work?

**Comment by markwilliamfirth** [comment]
Closed in favour of https://github.com/dwyl/print-me/issues/28
