### ISSUE TITLE
WiFi not working in 16 Palmers Rd

### ISSUE THREAD

**Issue by markwilliamfirth** [dwyl/hq#195]
FOUNDER I Talk Talk network won't connect to the internet

**Comment by nelsonic** [comment]
@markwilliamfirth thankyou for reporting this, please get the account details from @sofer so we can call talk talk.

**Comment by markwilliamfirth** [comment]
@nelsonic factory reset the Talk Talk modem and router. He then readjusted the settings - this seemed to fix the issue.

We also called Talk Talk on the business line (0800 083 3003) from the Quietspace phone and they said they would run some tests to double check our network connection wasn't faulty.

The nighthawk router has a known vulnerability, so Nelson has connected the Linksys WRT3200ACM to solve the issue with a temporary solution. This is Nelson's personal router, so the avoid using a router with a vulnerability, Quietspace may need to purchase a new router.

**Comment by nelsonic** [comment]
As @markwilliamfirth says, I ***Factory Reset*** the **TalkTalk Router** which cleared any settings that had been applied by _whoever_ tried to "fix" the network but "broke" it...
![wifi-1](https://cloud.githubusercontent.com/assets/194400/22547669/9fb7d2ba-e93a-11e6-8e1f-7f01a9afb947.png)

![wifi-2](https://cloud.githubusercontent.com/assets/194400/22547672/a28594dc-e93a-11e6-92b1-e0c5e13f9dbc.png)

![wifi-3](https://cloud.githubusercontent.com/assets/194400/22547674/a4a499ca-e93a-11e6-9c5e-692c4d381865.png)

![wifi-4-speed-68](https://cloud.githubusercontent.com/assets/194400/22547690/b3be31be-e93a-11e6-9ef8-8fe15bd00a08.png)

If this happens again, please visit: http://192.168.1.1 
You will be prompted for the Admin Password for the Router, it's on the bottom of the "Super Hub".
Navigate to the "Manage" tab and perform another factory reset. 

> Note: at some point in the future we may decide to apply more advanced network settings. 
but for now this is fine.

**Comment by nelsonic** [comment]
@markwilliamfirth please _close_ the issue once we are satisfied that the Internet/Wifi is working adequately. thanks!

**Comment by markwilliamfirth** [comment]
@nelsonic I still think there's the question of needing a new router - should I open another issue for that?

**Comment by nelsonic** [comment]
@markwilliamfirth yeah, you can _link_ the _new_ issue to this one. 🔗 
But a new router does not have to be a `Priority-1` issue, it can be lower because the Wifi is _working_ again... 👍

**Comment by markwilliamfirth** [comment]
WiFi issue solved, new WiFi connection `Quietspace` and password has been created
