### ISSUE TITLE
Monitor Stands/desks for No. 16

### ISSUE THREAD

**Issue by sohilpandya** [dwyl/hq#196]
Having had a chat with both @Jbarget & @nelsonic, we feel that we need some stands/desks for the monitors in No. 16 as it currently looks a bit bad to hold them on cardboard boxes. 

![img_5303](https://cloud.githubusercontent.com/assets/2305591/22552445/e3f02cb4-e950-11e6-927e-0c33ca015925.JPG)

Some of the options: 
[Glass Monitor](https://www.amazon.co.uk/VonHaus-Monitor-Warranty-Computers-Laptops/dp/B0195D2V4U/ref=lp_296770011_1_17?s=computers&ie=UTF8&qid=1486044462&sr=1-17)
<img width="354" alt="screen shot 2017-02-02 at 14 08 56" src="https://cloud.githubusercontent.com/assets/2305591/22552522/30fb73a6-e951-11e6-91e4-3ad9bea7d8fd.png">
[Amazon adjustable stand](https://www.amazon.co.uk/gp/product/B00X4SCCFG/ref=s9_acsd_top_hd_bw_bK5DR5_c_x_5_w?pf_rd_m=A3P5ROKL5A1OLE&pf_rd_s=merchandised-search-2&pf_rd_r=1Q4A5ATZH5V50FXMG248&pf_rd_r=1Q4A5ATZH5V50FXMG248&pf_rd_t=101&pf_rd_p=54fda6e0-bb67-456d-ad5c-11ea98687cf1&pf_rd_p=54fda6e0-bb67-456d-ad5c-11ea98687cf1&pf_rd_i=296770011)
<img width="352" alt="screen shot 2017-02-02 at 14 09 31" src="https://cloud.githubusercontent.com/assets/2305591/22552543/405bd368-e951-11e6-879d-71e7276ca5ee.png">

**Comment by jackcarlisle** [comment]
[wooden stand](https://www.amazon.co.uk/G4RCE-Universal-Computer-Heighten-Notebook/dp/B01MY997IM/ref=sr_1_17?ie=UTF8&qid=1486044867&sr=8-17&keywords=wooden+monitor+stand)
<img width="1653" alt="screen shot 2017-02-02 at 14 15 32" src="https://cloud.githubusercontent.com/assets/12450298/22552763/22c117f4-e952-11e6-91bc-ceebf9d1264d.png">

**Comment by Jbarget** [comment]
the glass one seems that it would be easily put together/taken down and would stack away neatly too

**Comment by nelsonic** [comment]
@sohilpandya thanks for opening this issue. it's a "_Phase 1.5_" Discussion we need to have mid-feb with @iteles and @markwilliamfirth about QuiteSpace 👍

**Comment by iteles** [comment]
@sohilpandya Can you please re-create this in https://github.com/dwyl/quietspace?

**Comment by nelsonic** [comment]
@sohilpandya can you please _frame_ the question as: "how to de-clutter" the desks downstairs at QS and make them "_clearable_" for our "_clean desk policy_"? 😉
