### ISSUE TITLE
New Router for Quietspace

### ISSUE THREAD

**Issue by markwilliamfirth** [dwyl/hq#197]
Links to #195 and #135 

New router required for Quietspace, current router has a security issue.

**Comment by iteles** [comment]
Unassigning @nelsonic as this won't be a task for him to complete.

@nelsonic If you have one in mind already, let us know 👍

**Comment by nelsonic** [comment]
LinkSys WRT is the _only_ option for security as it uses Open Source firmware which we can update when a security patch is released. NetGear are widely considered to be "compromised". 
see: http://www.pcworld.com/article/3149554/security/an-unpatched-vulnerability-exposes-netgear-routers-to-hacking.html `#SecurityMatters`!! https://github.com/dwyl/learn-security

**Comment by markwilliamfirth** [comment]
**Issue migrated from hq to quietspace**
