### ISSUE TITLE
Separating office from HQ?

### ISSUE THREAD

**Issue by markwilliamfirth** [dwyl/hq#199]
Should we create a new repo for the office (no. 16)?

This means people can post office issues in there (such as WiFi etc). Might be better to separate from hq? Thoughts?

**Comment by iteles** [comment]
I think a Quietspace repo would be ace! 👍

**Comment by nelsonic** [comment]
Go on @markwilliamfirth you _know_ you want to: https://github.com/organizations/dwyl/repositories/new 😉

**Comment by markwilliamfirth** [comment]
new repo opened
