### ISSUE TITLE
4G (Mobile/Backup) Internet ?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hq#2]
Given how *unreliable* our VirginMedia Broadband has been, what are your thoughts on getting a 4G "Mifi" (portable Wifi Hub) as a backup for when Virgin is down or when we want to work outside...? @iteles

**Comment by iteles** [comment]
I'm a fan of this idea in principle if we can get a not-too-expensive hub and a data card _without_ a monthly contract (the idea being we buy x amount of data and it sits there indefinitely until we need to us it - if we find we use it regularly we can move to a monthly payment). 
You've already done some research on costs of this haven't you @nelsonic?

**Comment by nelsonic** [comment]
As a matter of fact I did do the research ... the conclusion was the 
![image](https://cloud.githubusercontent.com/assets/194400/9836383/77e0562e-5a0f-11e5-96bb-daf04268b5f7.png)

**Comment by iteles** [comment]
:ok_hand: : I reckon we should have one of these as a back-up, particularly if we're going to have more regular guests that require some internet stability. It'll pay for itself with the first guest we have.

I think you may have already done the research on the SIMs for data as well, but let me know if I can do that half :+1:

**Comment by nelsonic** [comment]
As a matter of fact I *did* do the *research* on which Mobile Broadband Sim to get.
Three came up cheapest: http://store.three.co.uk/view/searchTariff?deviceType=SIM_ONLY_MBB

The *question* is: should we get a 1month contract for £20 (20GB of data) or can we get less?

**Comment by iteles** [comment]
Are there any non time limited options? i.e. _x_ amount of data that just sits there indefinitely until we need it?

**Comment by nelsonic** [comment]
There are a couple of options for extending the time the bandwidth allows...
<img width="713" alt="3-payg-broadband" src="https://cloud.githubusercontent.com/assets/194400/9836840/71d99c8e-5a20-11e5-9a7f-01f6fa43084d.png">

**Comment by nelsonic** [comment]
Ended up getting one of these: http://www.currys.co.uk/gbuk/phones-broadband-and-sat-nav/broadband/mobile-broadband/ee-osprey-2-mini-pay-monthly-mobile-wifi-10132535-pdt.html
<img width="1179" alt="ee-mobile-broadband-10-pounds" src="https://cloud.githubusercontent.com/assets/194400/9838649/958cd526-5a5a-11e5-9f69-5130030fde38.png">

£10 up front with 15GB included. then we can cancel after 30 days and that's it.
We can always renew it if we need. 
Seemed like a sweet deal to me.

**Comment by iteles** [comment]
:ok_hand: Works perfectly as a backup. Close this issue for now?

**Comment by iteles** [comment]
Trialled this but found we didn't end up using it much in the UK.
The one we bought has been great for use in other countries 👍 

@nelsonic Can we close this issue?

**Comment by nelsonic** [comment]
Ended up getting the EE Router with a "Cancel Anytime Contract" which turned out to be a nightmare see: https://github.com/dwyl/hq/issues/107
