### ISSUE TITLE
Using Github Issues as a To Do List

### ISSUE THREAD

**Issue by markwilliamfirth** [dwyl/hq#203]
- [ ] Estimate task length and track productivity in order to know what's been accomplished by the end of the week

I noticed it was possible to view assigned tasks via:
https://github.com/issues/assigned

However, sometimes tasks are assigned, but waiting on certain things to happen first or not high priority. This view doesn't allow you to sort using the priority label.

Is there a way to view the list of tasks assigned to me in a priority order, that also allows me to mark a task as "waiting" (waiting for someone else to do something or an email response for example), whilst still retaining priority labels and being assigned to the task?

**Comment by iteles** [comment]
@markwilliamfirth You can add `label:priority-1` for example into the search box:
<img width="755" alt="screen shot 2017-02-07 at 12 25 14" src="https://cloud.githubusercontent.com/assets/4185328/22691055/84c4cff4-ed30-11e6-8eab-7eb530422cf7.png">

There is also an `external-dependency` label in this repo, I use it to filter out things I can't do anything about just yet or to check if I need to chase people by adding `-label:external-dependency` to that search box.

**Comment by nelsonic** [comment]
@markwilliamfirth please add your requirements as a "_user story_" to: https://github.com/dwyl/tudo/issues 😉

**Comment by markwilliamfirth** [comment]
But what happens when you're *my* dependency and I'm *your* dependency - should we create different labels for each other?

Let's say there is an issue that requires the both of us to carry out various tasks that each prevent the other prom progressing. Once I had completed my bit I would add the dependency label to remove it from my to-do list and to say that it is now dependent on someone else, but this label is the same label for you - so do we each need to create our own dependency labels? dependent on ines / dependent on mark?

**Comment by iteles** [comment]
Nope, once you've completed your bit, you assign it to whoever the next person who needs to work on it is and then that removes it from your list until they assign you again!

**Comment by markwilliamfirth** [comment]
What happens if I assign it to someone else and they don't complete the task and I forget about chasing it up because it's not on my to-do list anymore? 🤔

**Comment by nelsonic** [comment]
@markwilliamfirth _great question_! ❓ 
The virtue of having the task _visible_ for _everyone_ in the team means accountability is "_built-in_". ✅ 
A follow up question could be: "_what if the person unassigns themself from the issue/task without completing it or assigning to anyone `else`...? we should have a `DWYLBot` action for this event type which applies a "in-limbo" label (_or something similar_) a task should only ever be "_unassigned_" before it's being worked on and once it's finished. In the circumstance where the person is "***waiting for an external dependency***" an `awaiting-dependency` label should be applied and the `in-progess` label removed. the person should _always_ leave a comment describing _exactly_ what is required to continue with the issue/task once the dependency is met.

**Comment by markwilliamfirth** [comment]
Hmm this didn't really answer my question - it's only natural that sometimes things will be missed or left for a long time and need to be chased up and there isn't a way to effectively do this?

Are we able to set due dates on tasks? (aside from priority labels)

**Comment by nelsonic** [comment]
@markwilliamfirth the _best_ way to set a due date is to put the issue in a milestone that has a deadline. this is _really_ useful for helping people to _focus_ and not get distracted. 👍

**Comment by markwilliamfirth** [comment]
How do I add an issue to a Project from the issue view? There is no cog 😕 

<img width="221" alt="screen shot 2017-02-14 at 17 20 46" src="https://cloud.githubusercontent.com/assets/5732209/22940516/09a9e12e-f2da-11e6-8eef-8548ce436439.png">

**Comment by markwilliamfirth** [comment]
I've had a look at milestones and it doesn't have the functionality we're going to require to organise tasks. I think Github is useful for creating, tracking and delivering projects, but not for business and operational tasks. I think we need to look at alternatives or improving utilising the Github system to run the whole business as it appears to reduce productivity and efficiency when the tool is used outside of its normal intended use.

Providing the task management solution is also **public** and **accessible** to all then I do not see a problem with this? A more efficient task management system will increase productivity and aid prioritisation and planning. Bonus if it somehow connects to Github and updates issues there.

**Comment by iteles** [comment]
I don't think we can conclude this without actually trialling GitHub projects? 

The projects documentation shows you need to add the issues to a project through the project view and not through the issue itself: https://help.github.com/articles/adding-issues-and-pull-requests-to-a-project/

**Comment by markwilliamfirth** [comment]
Yeah I know - I had a look at projects too. You can only seem to do it in the project view, not the issue view. Which is really annoying

**Comment by markwilliamfirth** [comment]
@iteles do all tasks not need to be assigned to someone?

e.g. in the case of #257 even though it is a discussion is it not your responsibility, so it remains assigned with you?

**Comment by iteles** [comment]
@iteles You raise an excellent point here around clarifying our processes - it's the eternal battle!

Our current contributing guidelines state that you assign something to yourself when you undertake  to carry out the work for said thing.
In the case of #257, I feel that if it's assigned to me, no one else will feel the need to contribute unless they feel *super* strongly about it because "someone's already on this". Depending on the outcome of the discussion, it may not be me or even you who carry out the work itself.
I added the `priority-1` so we know to track it this week.

#201 is slightly different - social media is part of your remit so my initial reaction was to say 'this is your call, I'm happy either way', until I realised that my communicating the vision for the company is a blocker here, so I assigned it back to myself!

**Comment by markwilliamfirth** [comment]
Ah ok - I see assigning = responsibility

and that responsibility doesn't stop others from contributing and that the discuss label is an invitation to discuss

so i guess that's why we had the miscommunication

#201 I got the impression you were into branding and social media so I thought you were keen to do it. Feel free to assign to me if you want

**Comment by markwilliamfirth** [comment]
I feel like all tasks should have someone assigned and a priority assigned and if someone else is going to carry out the work the person assigned can be swapped? But maybe that's so different to the dev methodology that it seems weird...makes sense for ops though

**Comment by markwilliamfirth** [comment]
Another reason why GH issues isn't good for a to-do list (https://github.com/dwyl/start-here/issues/121)

It's a potential annoyance and distraction when people get GH notifications and email notifications for minor tasks that have nothing to do with their work. It also causes miscommunication because people read what's there and interpret it in their own way without all the background facts. The alternative is to make issue descriptions as detailed as possible to remove space for different interpretations however this is a big waste of time for small and quick ops tasks - GH issues is useful for project-based issues/bugs/etc.

I think we should use GH issues as a place for **discussions**. A place for issues - somewhere where we can record the history of something and discuss or update it over time.

However an issue =/= a to do. We should be using specialised to-do list software for our ops to-dos. Utilising a system that isn't built for the job is inefficient and issues will inevitably occur due to it.

**Comment by iteles** [comment]
@markwilliamfirth *Everyone* in our organisation uses github to track at least a significant *portion* of our to-dos. If we want to *ensure* transparency of the work we are doing (and importantly *lead by example*), we need to get better at making sure that that work is captured somewhere that the rest of our colleagues have access to *with the least friction*.

We will be systematically *solving* this problem over the coming 3 months with a combination of *time* and *tudo*.
