### ISSUE TITLE
Updating Companies House

### ISSUE THREAD

**Issue by markwilliamfirth** [dwyl/hq#204]
- [x] File Company Accounts FY15/16 #92 

- [x] Add Mark as a Director (AP01, Board minutes)

- [x] Update share distribution (Cap Table, SH01, SH02, Articles of Association, Board Minutes, Special Resolution) #262 

- [x] Discuss existing director status

**Comment by iteles** [comment]
@markwilliamfirth We do.

**Comment by markwilliamfirth** [comment]
@iteles awesome! 😄  Please send them to me!

**Comment by markwilliamfirth** [comment]
@iteles we need to do this before we can progress with #219

**Comment by markwilliamfirth** [comment]
@iteles research on directors and relevant information from Model Articles:

**Directors’ general authority**

3. Subject to the articles, the directors are responsible for the management of the company’s business, for which purpose **they may exercise all the powers of the company**.

**Directors may delegate**

5.—(1) Subject to the articles, the directors **may delegate any of the powers which are conferred on them** under the articles—
(a) to such person or committee;
(b) by such means (including by power of attorney);
(c) to such an extent;
(d) in relation to such matters or territories; and
(e) on such terms and conditions;
**as they think fit**.
(2) If the directors so specify, any such delegation may authorise further delegation of the
directors’ powers by any person to whom they are delegated.
(3) The directors may revoke any delegation in whole or part, or alter its terms and conditions.

**Directors to take decisions collectively**

7.—(1) The general rule about decision-making by directors is that **any decision of the directors must be either a majority decision at a meeting or a decision taken in  accordance with article 8**.

**Unanimous decisions**

8.—(1) A decision of the directors is taken in accordance with this article when **all eligible directors indicate** to each other by any means that they share a common view on a matter.
(2) Such a decision may take the form of a resolution in writing, copies of which have been signed by each eligible director or to which each eligible director has otherwise indicated agreement in writing.
(3) References in this article to eligible directors are to directors who would have been entitled to vote on the matter had it been proposed as a resolution at a directors’ meeting.
(4) A decision may not be taken in accordance with this article if the eligible directors would not have formed a quorum at such a meeting.

**Calling a directors’ meeting**

9.—(1) **Any director may call a directors’ meeting** by giving notice of the meeting to the
directors or by authorising the company secretary (if any) to give such notice.
(2) Notice of any directors’ meeting must indicate—
(a) its proposed date and time;
(b) where it is to take place; and
(c) if it is anticipated that directors participating in the meeting will not be in the same place, how it is proposed that they should communicate with each other during the meeting.
(3) Notice of a directors’ meeting must be given to each director, but need not be in writing.
(4) Notice of a directors’ meeting need not be given to directors who waive their entitlement to notice of that meeting, by giving notice to that effect to the company not more than 7 days after the date on which the meeting is held. Where such notice is given after the meeting has been held, that does not affect the validity of the meeting, or of any business conducted at it.

**Attendance and speaking by directors and non-shareholders**

40.—(1) **Directors may attend and speak at general meetings, whether or not they are
shareholders**.

**Legal responsibilities**

As a director of a limited company, you must:

follow the company’s rules, shown in its articles of association
keep company records and report changes
file your accounts and your Company Tax Return
tell other shareholders if you might personally benefit from a transaction the company makes
pay Corporation Tax
**register for Self Assessment and send a personal Self Assessment tax return every year**

I didn't know that last one was a thing? O_O

**Comment by markwilliamfirth** [comment]
@iteles what do you think?

**Comment by iteles** [comment]
@markwilliamfirth We discussed yesterday that we'd catch up on this on Friday 👍

**Comment by markwilliamfirth** [comment]
This was done
