### ISSUE TITLE
Mark to review all issues in HQ

### ISSUE THREAD

**Issue by markwilliamfirth** [dwyl/hq#205]
Part of onboarding

https://github.com/dwyl/hq/issues

**Comment by iteles** [comment]
This should be a fun part of creating the New Joiner Handbook (which also needs an issue) 🎉

**Comment by nelsonic** [comment]
@markwilliamfirth if you are curious to see the _best_ company handbook we have the Zappos one: https://www.zapposinsights.com/culture-book ... 😉
