### ISSUE TITLE
Email Address Management

### ISSUE THREAD

**Issue by markwilliamfirth** [dwyl/hq#207]
Is there a cheaper way of managing the company's `@dwyl.io` email addresses?

Currently using Google Suite

Alternatives? Zoho?

**Comment by nelsonic** [comment]
@iteles CRM ... 🏦

**Comment by iteles** [comment]
@nelsonic I think @markwilliamfirth is referring to the `@dwyl.io` domain ones

**Comment by nelsonic** [comment]
@iteles CRM ...

**Comment by iteles** [comment]
@markwilliamfirth Did we make the decision to stay with G Suite and its (currently) £46.20 a month, £554.40 a year bill?

**Comment by markwilliamfirth** [comment]
I thought the consensus was CRM?
