### ISSUE TITLE
Should we make finance@dwyl.io a user?

### ISSUE THREAD

**Issue by markwilliamfirth** [dwyl/hq#208]
Currently finance@dwyl.io is an alias that forwards to:
ines@dwyl.io
nelson@dwyl.io
mark@dwyl.io

Might it be more beneficial to store all finance-related emails in a finance@dwyl.io user account?

**Comment by nelsonic** [comment]
@markwilliamfirth we have a more _systematic_ way to solve this... remind me to flesh this out _after_ I've finished my work on: https://github.com/dwyl/aws-ses-lambda 👍
