### ISSUE TITLE
Financial Planning and Budgeting Session

### ISSUE THREAD

**Issue by markwilliamfirth** [dwyl/hq#209]
We need a planning session for the new year.

**Comment by nelsonic** [comment]
![one_million_dollars](https://cloud.githubusercontent.com/assets/194400/22719361/17726854-ed9d-11e6-966b-a8a080c32546.jpg)

**Comment by markwilliamfirth** [comment]
On hold until #229 complete

**Comment by markwilliamfirth** [comment]
Closed in favour of #324
