### ISSUE TITLE
Email tasks

### ISSUE THREAD

**Issue by markwilliamfirth** [dwyl/hq#210]
Is there a quick and easy way to transfer tasks in emails to Github issues?

**Comment by iteles** [comment]
Not that I know of, you'll need to google for this one!

**Comment by iteles** [comment]
@markwilliamfirth Is there a linked issue on whether we should create a way to do this or do you reckon it's not valuable enough for now?

**Comment by markwilliamfirth** [comment]
Was just a quick q - not a major issue
