### ISSUE TITLE
Mark's Onboarding

### ISSUE THREAD

**Issue by markwilliamfirth** [dwyl/hq#211]
Complete Mark's onboarding by adding him to any necessary accounts / giving access to files etc

Including:

- [x] Adding Mark to the bank [Blocker: Companies House update #204 ]

- [x] Populating the private dwyl drive folder (including insurance details)

- [x] Projects and DWYL team overview [In progress]

- [x] Add Mark as a DWYL LinkedIn admin

- [x] Add Mark as a DWYL Github organisation owner [2-factor has been enabled #220 ]

**Comment by iteles** [comment]
Uploaded the last of the invoices (finally, after 4 tries!) to google drive yesterday. I think we're done!! :tada:

**Comment by markwilliamfirth** [comment]
@iteles where are the logins and passwords for various things stored?

**Comment by iteles** [comment]
You'll see a new file in the dwyl (private) folder 👍
