### ISSUE TITLE
"The Future of dwyl" Delicious Dinner on 27th March 2017 @ 16 Palmers Road E2 0SY

### ISSUE THREAD

**Issue by markwilliamfirth** [dwyl/hq#213]
Breakfast / Lunch / Dinner?

We need to set a date for the next meetup and send out invitations

Date decided:
**27th March 2017**

**Total guests so far:** Around 20

Note that Eoin clicked yes, but confirmed he can't attend
I received an email notification saying Marie accepted although this shows declined(?)

**Ines to-do's:**
+ [ ] 2016 in review
+ [ ] Prepare overview of 4 arms 
  + [ ] Determine how much detail to go into each
  + [ ] Timelines/milestones for 2017 for each
+ [ ] FTEs and context for this
+ [ ] Clear out office for Jimmy

**Comment by markwilliamfirth** [comment]
@iteles @nelsonic suggesting 2nd April 2017 (AKA 2 years since incorporation). Any objections?

**Comment by iteles** [comment]
We have quite a few people away in April so let's try for something in late March instead please!

**Comment by markwilliamfirth** [comment]
@iteles can you share the company calendar with me please?

**Comment by sohilpandya** [comment]
Can we have a movie night soon? is this the right place to ask or should I just create an issue with some dates and movies? 

🙏

**Comment by markwilliamfirth** [comment]
@iteles how about evening of Tuesday 28th March for dwyl dinner and movie (@sohilpandya)?

**Comment by iteles** [comment]
@markwilliamfirth Could you please update the top comment with not only the final date but also the list of confirmed attendees as they come in? It would be good to know who is able to make it 👍

**Comment by iteles** [comment]
@markwilliamfirth Could you please let me know how many people are coming? We need to buy ingredients this weekend 😊

**Comment by markwilliamfirth** [comment]
@iteles approx 20

the guestlist is in the google cal invite - can you see it from your account? I hid it from people seeing, but since I share my cal with you I wonder if it allows you to see?

some people haven't responded to the save the date invite - do you need exact numbers?

Looking at current respondents 20 would be my estimate (including you, nelson and myself)

**Comment by markwilliamfirth** [comment]
I think we should maybe set the date for the next one now and publicise it at the event to everyone? We could make it a quarterly thing?

**Comment by nelsonic** [comment]
@markwilliamfirth agree. 👍 
_Monthly_? 🤔

**Comment by NataliaLKB** [comment]
Hey! @nelsonic invited me to this on Wednesday. Is it okay if I show up around 7? I will bring vegan/gluten free pumpkin squares!

**Comment by iteles** [comment]
@natalialkb We couldn't be more excited about you coming! :rasa:

**Comment by nelsonic** [comment]
How To Begin Your Presentation: https://youtu.be/e80BbX05D7Y
(_I know this event "already happened" but this is still valuable learning..._)

@sohilpandya have you had a chance to transfer the recorded video to the Lacie Drive? 👍

**Comment by iteles** [comment]
@nelsonic Is this a thinly veiled hint? 😛

**Comment by nelsonic** [comment]
@iteles no idea what you're talking about. 😜

**Comment by iteles** [comment]
https://twitter.com/dwyl/status/847407781443362818

**Comment by nelsonic** [comment]
FYI: @sohilpandya's recording of the evening is on YouTube: https://youtu.be/XX47atVcVZE 🎉
