### ISSUE TITLE
Company Amazon Account

### ISSUE THREAD

**Issue by markwilliamfirth** [dwyl/hq#218]
We currently have two amazon accounts that Inês and Nelson use. Can we make a company amazon account to have a consistent record of business purchases?

Should I make a new account?

**Comment by nelsonic** [comment]
@markwilliamfirth yes. second email address suggested. thanks. 👍

**Comment by iteles** [comment]
https://www.amazon.co.uk/b2b/info/amazon-business?layout=landing

**Comment by markwilliamfirth** [comment]
Completed

>We need a little more time to verify DWYL LTD.
The verification process can take up to three business days to complete. We will send you a confirmation email when your information has been verified.

**Comment by markwilliamfirth** [comment]
Welcome to Amazon Business. The information you provided has been verified and your account registration is now complete.

**Comment by iteles** [comment]
"There was a problem and we could not find an account with that email address"

**Comment by iteles** [comment]
Thanks for confirming the correct email for me @markwilliamfirth 👍
