### ISSUE TITLE
Telephone Number on the Site

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hq#22]
Many people _still_ prefer to speak to someone on the phone instead of email/chat.

Having a phone number people can call on our website (which people can call for free) 
and gets re-routed to our respective mobile phones and who ever picks up takes the call. 

Thinking 0800 number ... http://www.0800numbershop.co.uk/ its £9.99 pcm tho. 
@iteles  thoughts?

**Comment by iteles** [comment]
I would prefer a normal landline number. I feel like there's a bit of a negative (sleazy) association with 0800 numbers after all the 'hard sale' adverts on TV and such that use 0800.

In the UK most people have free minutes of some description (plus 0800 numbers are often not free to call from a mobile anyway) and from abroad it's impossible to call 0800 numbers so we'd have to expose a landline number anyway.

I agree one should be there though. (Linked to #23 )

**Comment by nelsonic** [comment]
FYI: http://www.theguardian.com/media/2013/dec/12/ofcom-free-0800-mobile-telecoms-overhaul
0800 is *always* free.
But sure, a "Local-Looking" number might look more "real". :wink:

**Comment by iteles** [comment]
Added a temporary mobile number for now. We can re-open if required!

**Comment by nelsonic** [comment]
We're going to _need_ an `0800` number when we "get serious" about this... 💭 
Maybe the _formalised goal + plan_ should come first though... 👍

**Comment by iteles** [comment]
Yes, it'll come with a revised website with a clearer focus.
