### ISSUE TITLE
Mark Enable Github 2-factor Authentication

### ISSUE THREAD

**Issue by markwilliamfirth** [dwyl/hq#220]
In order to increase security

**Comment by nelsonic** [comment]
@markwilliamfirth go to: https://github.com/orgs/dwyl/people and see who has it enabled.
who ever does not, assign them to this issue (_you can assign up to 10 at a time_)
I use Authy app on my phone for "One Time Codes" but Google Authenticator works too. 🔐

**Comment by markwilliamfirth** [comment]
@nelsonic after you click through how are you able to see who has it enabled?

I used the Duo app - all set up and done now 👍

**Comment by nelsonic** [comment]
@markwilliamfirth please _confirm_ if you are _able_ to see something like this:
![2-factor-auth-enabled](https://cloud.githubusercontent.com/assets/194400/22791396/2062f1b4-eee1-11e6-8817-2ba8fd719e18.png)

**Comment by markwilliamfirth** [comment]
@nelsonic I can see this:

<img width="1046" alt="screen shot 2017-02-09 at 16 28 46" src="https://cloud.githubusercontent.com/assets/5732209/22792494/dec3c9be-eee4-11e6-98f6-66ee86245e8a.png">

**Comment by nelsonic** [comment]
@markwilliamfirth ah... hold on... ⌛️ 
please refresh and try again. ♻️
