### ISSUE TITLE
Research Github Projects

### ISSUE THREAD

**Issue by markwilliamfirth** [dwyl/hq#223]
- [x] @iteles add Mark as organisation owner on Github #211 

Research how to utilise projects to help ops task management in Github

Links to #203

**Comment by iteles** [comment]
Done! Thanks for enabling the 2FA first :blush:

**Comment by markwilliamfirth** [comment]
Even though I'm an owner I can't seem to add an issue to a Project from the issue view?

Links to #203

**Comment by iteles** [comment]
Hard to diagnose without knowing what you've tried or having a screenshot of the missing/available options. Could you please elaborate?

**Comment by markwilliamfirth** [comment]
Screenshot is in #203 (referenced above), was reporting it here as an issue because I think it makes projects a weak option if we can't assign from issue view. Wasn't sure if it was linked to the milestones thing when I couldn't assign from issue view because I wasn't an owner before so thought I'd mention it
