### ISSUE TITLE
Policy for Granting @dwyl.io Email Addresses

### ISSUE THREAD

**Issue by markwilliamfirth** [dwyl/hq#224]
We should have a policy for who gets a `@dwyl.io` email address. @iteles is there a current process or any criteria that someone must fulfil to get one?

Suggested Criteria:

- Currently working on a paid internal or client DWYL project

**Comment by nelsonic** [comment]
@markwilliamfirth who are _committed_ to the long-term future of dwyl. 😉 
But this shouldn't be a problem once we sort out our CRM... 🤔

**Comment by iteles** [comment]
I'm with @nelsonic on this one. So far it's been if you're interested enough in the future of dwyl to _ask_ for one (usually because you _want_ to stick around based on what you know of our values and operating procedures), you get one.

**Comment by markwilliamfirth** [comment]
Hmm I'm not sure if we should do it that way. This puts the onus on the contractor to make the request.

I don't think we should have contractors having to use their personal email accounts

- It doesn't look professional
- It doesn't allow them to separate their work and personal lives
- It dilutes the DWYL brand

I think we should make contractors feel wanted and welcome by onboarding them with an email and identity as part of DWYL.

**Comment by iteles** [comment]
@markwilliamfirth Completely agree. Historically the contractors who have had them have used them infrequently and I didn't have the time to enforce consistent usage. It's time.

**Comment by iteles** [comment]
@markwilliamfirth Should this stay open until the policy is written up somewhere?

**Comment by markwilliamfirth** [comment]
Yep it's in the Google Drive - will eventually come to fruition in a md onboarding file on Github

**Comment by markwilliamfirth** [comment]
In case we wanted to add further evidence to the previous discussion...

<img width="778" alt="screen shot 2017-02-16 at 02 00 53" src="https://cloud.githubusercontent.com/assets/5732209/23003970/d3be86d8-f3eb-11e6-8438-d400e6a9a449.png">

^this guy didn't ask for a dwyl.io email, but got given a dwyl.io email and look where he is now 😆 

lol.
