### ISSUE TITLE
Home phone?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hq#23]
We have a phone *line* but no *device* ...
While I would prefer not to receive *spam* calls, we do need a phone people can call us on (*without exposing our mobile numbers publicly*...)

http://www.ligo.co.uk/buying-guide/top-10-best-cordless-phones/

http://www.amazon.co.uk/dp/B00DM7IL5E/
<img width="1092" alt="home-phone" src="https://cloud.githubusercontent.com/assets/194400/10161757/34ef36e6-669e-11e5-9420-2e901481b7d9.png">

**Comment by iteles** [comment]
None of the [other](http://www.amazon.co.uk/BT-Cordless-Machine-Nuisance-Blocker/dp/B00DC0PSW0/ref=sr_1_11?ie=UTF8&qid=1443867618&sr=8-11&keywords=home+phone+call+blocking) [options](http://www.amazon.co.uk/BT8500-Advanced-Blocker-Cordless-Handset/dp/B00LZTHUEO) seem to boast sound quality so this looks like the best alternative :+1:

**Comment by iteles** [comment]
Do you want _me_ to be in charge of getting this?

**Comment by nelsonic** [comment]
Brack Friday Bunduru: http://www.amazon.co.uk/gp/product/B00DM7ILAO
<img width="274" alt="gigaset-c620a" src="https://cloud.githubusercontent.com/assets/194400/11429958/155600f6-9477-11e5-96c8-c8b60d681299.png">
8am tomorrow.

**Comment by nelsonic** [comment]
amazon cheating:
![screenshot_2015-11-27-08-56-22](https://cloud.githubusercontent.com/assets/194400/11437324/d82af632-94e4-11e5-86f7-a7c5bbd79398.png)

**Comment by iteles** [comment]
Have we decided _not_ to get these?

**Comment by nelsonic** [comment]
Yes. decided against. *however* we still need to *decide* how we are going to receive phonecalls for the companies that want to call us.

**Comment by iteles** [comment]
Well. It looks like a virtual number will [cost us maybe £7 a month](https://www.virtuallandline.co.uk/). 

Are we paying for a phone line at our registered office address already?

**Comment by nelsonic** [comment]
Chez nous we have line rental from VMedia by *default*...

**Comment by iteles** [comment]
So in actual fact, the phones (with a redirect to our mobiles) would pay for themselves in 6 months vs an ongoing 'virtual number' cost.

I vote we get the phones as long as we can permanently redirect them to our mobiles.

**Comment by nelsonic** [comment]
Right, but that's just calling up Virgin Media and aksking them to put the re-direct on our number...

**Comment by iteles** [comment]
Then if it's something we get _free_ after the we buy the phones, we should go the phone route.

**Comment by nelsonic** [comment]
Re-open if required.
