### ISSUE TITLE
Volunteering Teaching (Prisons Code4000)

### ISSUE THREAD

**Issue by harrygfox** [dwyl/hq#230]
From gitter
@harrygfox said on 13th Feb:
> I’ve been in touch with Michael Taylor at [code4000](https://www.code4000.org/en) which is an initiative to help recidivism and employment prospects of cons in the uk. They are going to do this by teaching coding in prisons (via Skype).
> The UK criminal justice system is something I am personally passionate about in so far as making my time available to help those individuals sucked in to a broken system of punishment. I believe the only rightful purpose of a prison is to protect the general public from someone dangerous or to rehabilitate a criminal - this is not the justification in **most** cases of imprisonment, but the state justifies the ruination of innumerable lives all the same.

Is anyone interested in volunteering? Doing more? What's the appetite for involvement here?

https://www.code4000.org/en

**Comment by rjmk** [comment]
I've put my email in! Beyond mentoring, what sort of involvement opportunities are you envisaging?

**Comment by Conorc1000** [comment]
@harrygfox  I'd be keen to get involved in this 👍

**Comment by Jbarget** [comment]
@hdrdavies mentioned this over the weekend and Michael Taylor got back to me today

> Dear Justen,

> it would be great to have you onboard! Please start by joining our Slack channel - https://code4000.slack.com/shared_invite/MTM4NjI5NDMxNzE3LTE0ODY1NDQxMzEtODRmNzdlY2FmMw

> We currently need some hands on help to finish downloading the curriculum. Each week takes about 1-2 hours to download to a shared google drive (prisoners do not have access to the internet, and so we need to download all of the resources we have identified). If you could help us download a week's resources, please let me know on Slack!

> Thanks os much for reaching out - we really appreciate it!

> Kind regards,
Michael

it might be worth having one point of contact and finding out how many DWYL/FAC people are interested

**Comment by harrygfox** [comment]
@rjmk I'll find out today on a call and feedback here with all the options for getting involved

**Comment by naazy** [comment]
Also interested @harrygfox

**Comment by hdrdavies** [comment]
Already joined 😉

**Comment by harrygfox** [comment]
@rjmk @Conorc1000 @Jbarget @naazy @hdrdavies 

----

## The Programme

Is in its **pilot phase**. 16 students from [HMP Humber](http://www.justice.gov.uk/contacts/prison-finder/everthorpe) work in person with a _Course Facilitator_ to learn the fundamentals of web development over a number of weeks. The curriculum is (currently) a copy of the curriculum used by US programme, [The Last Mile](https://thelastmile.org/). The Last Mile (with whom Code 4000 have connections) have found that **every student** that has completed the course, completed work experience, and found full time employment has not returned to prison. Last Mile have no short-term intentions of entering UK prisons.

That means that this programme has the chance of reducing recidivism from 59% within a year to 0%.

## The Commitment

**Broad range of jobs**
Generally speaking the jobs that volunteers are asked to perform are in support of the _Course Facilitator._ Below is a list of things from least to most real-time involvement. 
- Procuring resources for the students
- Being active and helpful on Q&A forums
- Code reviews
- Designing exercises for a class
- Directly presenting over Skype to a class
- Mentoring an individual more closely
- In person delivery of classes


**However much you want it to be**
Very flexible. There is no minimum commitment from anyone and there is also the option for a **trial period of volunteering** before actually committing to something more regular. 

**Stick to your commitment**
If you choose to commit in any way, make sure you are _definitely_ going to meet it. The students are particularly vulnerable individuals who, in many cases, have been abandoned by the education system, and often their families and friends too. As tutors and mentors we should **not** be part of the problem.

## The Curriculum

(As mentioned above) is a version of The Last Mile's curriculum since they have found success with it. Code 4000 is open to conversations about changing the curriculum as well as including relevant things like UX/UI design, or Blockchain, or whatever you're passionate about. 

# Meeting Code 4000

Michael Taylor will be visiting HQ on 
### **Thursday 16th Feb at 3pm** 
@iteles @nelsonic particularly with a mind to meet the visionaries / flag-bearers.

**Comment by nelsonic** [comment]
@harrygfox `this` thursday? (_please send us a Calendar invite so we don't forget! thanks!_)

**Comment by nelsonic** [comment]
@harrygfox please see: https://github.com/dwyl/dwyl-site/issues/203 😞

**Comment by markwilliamfirth** [comment]
@harrygfox when is this guy coming back to London?
