### ISSUE TITLE
Wise Awards

### ISSUE THREAD

**Issue by markwilliamfirth** [dwyl/hq#231]
https://www.wisecampaign.org.uk/wise-awards/wise-awards-2017

Research past winners and construct application

**Comment by nelsonic** [comment]
@markwilliamfirth great idea. thanks for creating this issue/task! ❤️

**Comment by markwilliamfirth** [comment]
💡 Idea credit is due to @iteles - Ines received an email about it and mentioned it to me

Deadline is 23 Jun, so still some time to go though

**Comment by markwilliamfirth** [comment]
@iteles is this something we still want? Which category?

**Comment by iteles** [comment]
They have a fantastic network and it would be a great talking point.

Let's do the research and see which categories apply (if any) 👍

**Comment by markwilliamfirth** [comment]
@iteles these are the only three that I think might apply

WISE Tech Innovation Award
WISE Technology & Engineering in Health
WISE Woman in Industry

Although the rules say that you must nominate yourself - people can't nominate for others

**Comment by iteles** [comment]
@marwilliamfirth Could you please take a look through them and add a time estimate to this issue so we know roughly how much time we'd need to dedicate?

**Comment by markwilliamfirth** [comment]
@iteles I've estimated 4 hours

**Comment by iteles** [comment]
This wasn't done.
