### ISSUE TITLE
Text Expander

### ISSUE THREAD

**Issue by markwilliamfirth** [dwyl/hq#232]
Text Expanders are apps that help you write faster by storing codes for common phrases

A popular expander for Mac is aText. I used this at my old job and was using it now until my free trial expired :'(

Can we get a license for me? (£4.13)

Would advise others to try it out too.

**Comment by iteles** [comment]
:+1: Would be good to know how you feel it's improved your productivity too!

Let's do this tomorrow when we're co-located.

**Comment by markwilliamfirth** [comment]
Purchased
