### ISSUE TITLE
Encourage others to enable 2FA

### ISSUE THREAD

**Issue by markwilliamfirth** [dwyl/hq#234]
Links to #220

**Comment by iteles** [comment]
Was any progress made on this? It would be good to have a one-sentence comment when closing issues just so we know where we left things (unless commits against it speak for themselves)

**Comment by markwilliamfirth** [comment]
I don't think it's my place to tell people I don't know how to manage their accounts so I decided against it - does someone else fancy doing this?

**Comment by iteles** [comment]
Could the task instead be that we add it to our dwyler handbook?

**Comment by markwilliamfirth** [comment]
as an organisational policy for all employees and contractors to follow or just a suggested step to take?

**Comment by iteles** [comment]
As an organisational policy. 

Not having 2FA leaves the repos that that person has admin access to much for vulnerable to hacking and even deletion (and if they're working on dwyl repos, we'll need them to have write or admin access - we want people to take ownership as well).

**Comment by markwilliamfirth** [comment]
Ok cool - will be added to #242
