### ISSUE TITLE
Terminal broken?

### ISSUE THREAD

**Issue by markwilliamfirth** [dwyl/hq#235]
<img width="370" alt="screen shot 2017-02-14 at 19 41 31" src="https://cloud.githubusercontent.com/assets/5732209/22945873/a6b51f48-f2ed-11e6-94be-ad02ca870c38.png">

I did something weird to my terminal at the elm meetup and now it says iphone?

Is it meant to do that?

@nelsonic have you seen this before? Thought I'd ask before I spend [unknown length of time] trying to work it out by searching around 😬

**Comment by nelsonic** [comment]
@markwilliamfirth does it still say `Test-iPhone` _after_ you quite and re-start it?
if in doubt install https://www.iterm2.com/ 👍
