### ISSUE TITLE
Connect Bank Feeds On Xero

### ISSUE THREAD

**Issue by markwilliamfirth** [dwyl/hq#236]
https://go.xero.com/Banking/Account/#find

**Comment by iteles** [comment]
Did this finally come through? :tada:

**Comment by markwilliamfirth** [comment]
I just closed it because we did everything on our end...still waiting for it to appear

**Comment by markwilliamfirth** [comment]
@iteles the bank feed situation is now partially resolved - required some editing of the settings

Now you need to log in and connect it https://connect.banking.xero.com/BankCredentials/Create

(I can't log in because I don't have credentials yet)

**Comment by iteles** [comment]
Done 👍
