### ISSUE TITLE
CharlieHR

### ISSUE THREAD

**Issue by markwilliamfirth** [dwyl/hq#237]
@iteles and @nelsonic I've sent you invites to get set up on CharlieHR. Please could you complete the onboarding process today? This is high priority because I require your National Insurance numbers and other information to set up PAYE.

**Comment by iteles** [comment]
@markwilliamfirth Do we need to do this through CharlieHR?

I strongly favour reducing the number of applications we use rather than increasing it (as you may have noticed from my insistence on github as opposed to many other project management tools 😝 ).

Please outline the benefits of using CharlieHR for this so it's captured somewhere.

**Comment by markwilliamfirth** [comment]
It's free, easy and does everything I need it to do in terms of easily storing payroll info, p45, right to work documents, contact details, next of kin, etc

It's great! I know the guys that run it. Also have used it at EF and HP.

**Comment by markwilliamfirth** [comment]
I've filled in the stuff I know - now you guys need to do the remaining (non-urgent) stuff:

https://dwyl.charliehr.com/people/nelson-kenneth/checklist

https://dwyl.charliehr.com/people/ines-sampaio-da-novoa/checklist

**Comment by markwilliamfirth** [comment]
@iteles you need to upload your passport to drive

@nelsonic you need to upload you passport and ID card to drive (and charliehr if you want)

**Comment by iteles** [comment]
@markwilliamfirth We already uploaded my ID card to the drive which I use as my main form of identification, I don't even think I know where my passport is 😆  Do we need both? I can dig around for it if so.

**Comment by markwilliamfirth** [comment]
@iteles in case I ever have to book flights for you etc

**Comment by iteles** [comment]
Will dig it out in case we need non-EU flights 👍

**Comment by iteles** [comment]
Done for us both!
