### ISSUE TITLE
Route hello@dwyl.io to Mark

### ISSUE THREAD

**Issue by markwilliamfirth** [dwyl/hq#238]
Route emails from hello@dwyl.io to Mark

**Comment by nelsonic** [comment]
I'll "see" your re-rout and "_raise_ you" a let's "_whiteboard_" the features for our CRM on Monday Morning so we can _solve_ this issue once and for all. 😉

**Comment by markwilliamfirth** [comment]
Not a re-route, sorry, I mean keep it routing to ines and then filter to forward to me like with finance

**Comment by nelsonic** [comment]
@markwilliamfirth yeah, I got it, don't worry. 👍 
But forwarding email does not _solve_ the problem.
see: http://www.paulgraham.com/ambitious.html (scroll down to number 2) 😉

**Comment by iteles** [comment]
@nelsonic <3 But I'll suggest the afternoon as we'll be spending the morning with FAC10.

@markwilliamfirth Done for now so that you can keep using hello+?@dwyl.io for the verification emails you need 👍

**Comment by markwilliamfirth** [comment]
done
