### ISSUE TITLE
Set Up PAYE

### ISSUE THREAD

**Issue by markwilliamfirth** [dwyl/hq#239]
<img width="777" alt="screen shot 2017-02-20 at 11 00 56" src="https://cloud.githubusercontent.com/assets/5732209/23123282/aa42d792-f75f-11e6-875e-653fda564ca0.png">

Waiting to be verified

- [ ] Mark to look into PAYE submission deadlines

**Comment by markwilliamfirth** [comment]
<img width="655" alt="screen shot 2017-02-20 at 15 38 53" src="https://cloud.githubusercontent.com/assets/5732209/23131671/c2281336-f782-11e6-8630-5a13e9e83b53.png">

@iteles on xero please could you make me the subscriber or activate payroll on your end?

**Comment by iteles** [comment]
@markwilliamfirth I think we should keep our general finance email address as the subscriber.

Payroll activated for a discounted fee for the next 6 months:
<img width="452" alt="screen shot 2017-02-21 at 14 47 23" src="https://cloud.githubusercontent.com/assets/4185328/23169754/d8fc3f70-f844-11e6-8d65-fd90b76ed876.png">

**Comment by markwilliamfirth** [comment]
@iteles post should arrive according to the below

You’ll get 2 letters from HMRC, which will include your:

PAYE and Accounts Office references (within 5 working days)
activation code for PAYE Online (within 10 working days)
You’ll need these to send payroll information to HMRC.

**Comment by markwilliamfirth** [comment]
@iteles 

The letter we received in the post was the PAYE and Accounts Office references

We're still missing the activation code for PAYE Online
	
We received an email on the 17 Mar (4 days ago) saying that the activation code for PAYE Online had been sent. So it has probably now arrived at MDC - would you be able to collect this next time you cycle there?

Once we have the activation code we can set up PAYE.

**Comment by iteles** [comment]
Oh wait, I have this! I found the letter over the weekend and forgot to take it with me to give you yesterday. Will DM you.

**Comment by markwilliamfirth** [comment]
Completed
