### ISSUE TITLE
Remuneration

### ISSUE THREAD

**Issue by markwilliamfirth** [dwyl/hq#240]
- [ ] Ines / Nelson pay for 2016/17
- [ ] Profit predictions and remuneration / dividend planning for 2017/18

**Comment by markwilliamfirth** [comment]
Research #139

**Comment by markwilliamfirth** [comment]
@iteles @nelsonic do you have any objections to separating share classes (A, B, C) in order to allow differential payments of dividends?

**Comment by nelsonic** [comment]
@markwilliamfirth please give details on share classifications. thanks. 👍

**Comment by markwilliamfirth** [comment]
There is no difference. They are just separated which means unequal payment of dividends can occur

**Comment by iteles** [comment]
Let's figure out the use case for an unequal payment of dividends. Is it a tax efficiency?

**Comment by markwilliamfirth** [comment]
Dividends by nature must be paid equal to the distribution of shares of the same class. Therefore if you need to make unequal distributions of dividends or you need to increase dividend payments to account for unequal distribution of shares, the only way to do this is by separating share classes.

**Comment by iteles** [comment]
@markwilliamfirth 👍 Let's work out what the remuneration should be and confirm if there is a need for this.

**Comment by markwilliamfirth** [comment]
It will likely be required because my shareholding is significantly different to yours - also Nelson expressed an interest in potentially not receiving the same amount of dividends and whether that is true now or later on it's perhaps best to arrange the share classes in a suitable way now

**Comment by iteles** [comment]
@markwilliamfirth Just need you to talk me through a practical example please (can be verbal as long as I summarise the conclusions here)

**Comment by markwilliamfirth** [comment]
@iteles confirming it's ok to separate share classes?

**Comment by markwilliamfirth** [comment]
Spoke to iteles and confirmed separation of share classes

@iteles can you summarise the outcome of the remuneration decisions so we have a record

**Comment by iteles** [comment]
@markwilliamfirth Thanks for the nudge ;)
Yes, definitely, this option gives us more flexibility and we can easily change it if we need to later 👍

**Comment by markwilliamfirth** [comment]
@iteles I mean with regards to Portugal - don't we need this recorded somewhere?

**Comment by iteles** [comment]
No longer relevant.
