### ISSUE TITLE
Online Contract e-sign System

### ISSUE THREAD

**Issue by markwilliamfirth** [dwyl/hq#243]
**Mark**
As a web agency we sign a lot of contracts. With developers, with clients, etc.

Sometimes come contracts are left late or unsigned as the process is burdensome for both parties.

I propose we use some kind of online e-sign contract system to easily push out contracts to clients / developers and have an online record of them all - thoughts?

**Nelson**
We tested both EchoSign and DocuSign @groupon for getting hundreds of thousands of documents signed ... so I know a bit about the various services (and have kept this knowledge up-to-date). 👍

Decent summary of the available services:
https://www.werockyourweb.com/hellosign-vs-docusign-vs-echosign-vs-rightsignature/
SignNow appears to be the best value-for-money: https://snseats.signnow.com/purchase/business_plans/pricing

Strikes me as Odd that we would need to pay a monthly fee for the service though...
Seems obvious that there should be a pay-as-you-sign option... 🤔

**Ines**
he delays around contracts are more to do with the burden of putting them together or reading through them (i.e. my lack of time) although we've had one client recently with a mysteriously disappearing e-signature 😆

I've never had a client tell me they don't know how to sign a document in the past, so I've never even considered this an issue, but agree it's very much worth looking into!

Bumping down the priority for this reason.

I'm not sure we want to pay a monthly fee for something we use so infrequently though. Let's do some quick research and see what our options are?
We'll start to keep track of contract signatures so we know how many we're doing a month as well. 👌

**Comment by iteles** [comment]
We'll open this again if it ever becomes an issue.
