### ISSUE TITLE
Ines Tech for Good Meetup

### ISSUE THREAD

**Issue by markwilliamfirth** [dwyl/hq#245]
Potential speaking slot for Inês?

[#BeBoldForChange - The Women Using Tech to Empower Others](https://www.meetup.com/techforgood/events/237579805/)

Tech For Good

**Comment by markwilliamfirth** [comment]
@iteles what do you think?

"We've been quite overwhelmed with speaker submissions actually and to be honest I think it's unlikely we'll be able to give Ines a slot this time, but if she's happy to say a few words about the various projects dwyl/she are working on in the community announcements section that would be fab and I can add you to the list :)"

**Comment by iteles** [comment]
@markwilliamfirth Yes, let's do that! We'll have value to add even as an announcement 👍

**Comment by markwilliamfirth** [comment]
Awesome - sorted!

Make sure to sign up here:
https://skillsmatter.com/meetups/9202-beboldforchange-the-women-using-tech-to-empower-others

 Wednesday, 8th March at CodeNode, London

**Comment by iteles** [comment]
Yes, done a few days ago! 👍

**Comment by markwilliamfirth** [comment]
@iteles how was this?

**Comment by iteles** [comment]
I just did a little announcement for QuietSpace and offered it as a meetup location for an https://epic.foundation/ breakfast happening next week (they were looking for somewhere central so nothing may come of it).

Also had an interesting chat with a freelance charity worker about user-centred design and the need for CRMs that work for charities. Jess sent through this article: https://twitter.com/daisygrubber/status/839608596908371968

**Comment by markwilliamfirth** [comment]
Nice!
