### ISSUE TITLE
Blog Post about Developer Health

### ISSUE THREAD

**Issue by markwilliamfirth** [dwyl/hq#246]
Problems and solutions
Sam RSI post

http://blog.invisionapp.com/freelancing-with-depression/

**Comment by nelsonic** [comment]
Relates to: https://github.com/dwyl/start-here/issues/115

**Comment by iteles** [comment]
Definitely appetite for this:
<img width="538" alt="screen shot 2017-02-25 at 11 53 34" src="https://cloud.githubusercontent.com/assets/4185328/23330843/191657c6-fb51-11e6-99e9-bbc57815be53.png">
