### ISSUE TITLE
Mark blog post

### ISSUE THREAD

**Issue by markwilliamfirth** [dwyl/hq#247]
Why I decided to work at DWYL / Lessons learned working in startups

**Comment by markwilliamfirth** [comment]
@nelsonic I can't do this until
https://github.com/dwyl/dwyl-site/issues/202

**Comment by nelsonic** [comment]
We can always _create_ the content and `.then` _publish_ it on the website once the Blog a thing.
https://github.com/search?q=org%3Adwyl+learn `#ContentBackCatalog` 😉

**Comment by iteles** [comment]
@markwilliamfirth I think we talked about this a couple of weeks ago. Let's create a blog folder on site repo where we can add content as .md files for now 😊 
By the time we redesign the website and launch the blog, we should have a few pieces there to start with 👍

**Comment by markwilliamfirth** [comment]
I've already written 2000 words, I just don't want to put them on github at the moment. A lot of it is personal and probably not suitable for a company blog - still needs editing.

Regardless we need to know how long it will take to make a blog. There isn't much point in me prioritising writing if there is nowhere to publish.

**Comment by iteles** [comment]
@markwilliamfirth I respectfully disagree with this:
> There isn't much point in me prioritising writing if there is nowhere to publish.

We need to have a backlog of content in order to publicise the blog and having the timestamp in Github of when we actually write the posts will be an invaluable log (there's no point holding back on putting up content).

In terms of editing, let me know where I can help. I think getting the ball rolling on this is one of the most valuable things you could do right now whilst it's still fresh, which is why we discussed this on day one 👍

**Comment by markwilliamfirth** [comment]
I don't know if I agree with that - e.g. finances and contracts are far more important right now than blog writing. There is little point to building up a backlog of content if we have no plan for when or how it is going to be published. It's relatively easy to calculate an estimate for how long it will take to build a blog - I don't see what the problem is with doing this and why it hasn't been done?

Let's suppose this estimate is 10 developer days - when are we going to be able to fit in the time to accommodate this? If we suppose it will be at some point in April, then there is little point to currently prioritising fine-tuning content when there are other more important things that require attention.

**Comment by Cleop** [comment]
@markwilliamfirth - with the site now being built, now might be a good time to start reviving where you left off with this one. Not necessarily as the first blog post but just as one to be part of a collection...
