### ISSUE TITLE
Claim dwyl usernames

### ISSUE THREAD

**Issue by markwilliamfirth** [dwyl/hq#248]
**Important**
- [x] Github https://github.com/dwyl
- [ ] Facebook - https://www.facebook.com/dwylhq username too short [Claim sent]
- [x] Twitter https://twitter.com/dwyl
- [ ] Instagram - https://www.instagram.com/dwylhq/ taken [Claim sent]
- [x] YouTube - https://www.youtube.com/dwyl
- [x] Google Plus - https://google.com/+dwyl
- [x] LinkedIn https://www.linkedin.com/company/dwyl
- [x] Medium - https://medium.com/dwyl

**Additional**
- [ ] Snapchat - taken [Claim sent]
- [x] Tumblr - http://dwyl.tumblr.com/
- [ ] Pinterest - taken https://uk.pinterest.com/dwyl/ [Claim sent]
- [ ] Reddit - taken https://www.reddit.com/user/dwyl [Claim sent]

**Comment by markwilliamfirth** [comment]
@iteles can we delete the old YT channel? https://www.youtube.com/channel/UCItdEQk0-lGLm8JhOfoLxkQ

**Comment by nelsonic** [comment]
I wouldn't worry about tumblr, snapchat or redit ... as long as we've got YouTube... 😉 
Pinterest would be nice-to-have but again, not a priority.

Why do we need to `delete` the "old" YT channel? (_excuse my ignorance..._)

**Comment by markwilliamfirth** [comment]
The one I've made is linked to a Google plus business page for dwyl - when I was making the pages dwyl didn't appear so I made one - it seems like the old channel is not linked to a google plus page?

**Comment by iteles** [comment]
@markwilliamfirth But it has 2 subscribers and a timestamp of its creation which pre-dates the new one and shows evolution... Could we link the old one to the G+ page?

**Comment by markwilliamfirth** [comment]
@iteles can you make me a manager of the old page so I can see if I can edit it to do so?

**Comment by iteles** [comment]
@nelsonic This one's on you I'm afraid. Could you please give Mark manager permissions to https://www.youtube.com/channel/UCItdEQk0-lGLm8JhOfoLxkQ ?

**Comment by nelsonic** [comment]
@markwilliamfirth let me know when you have time to _pair_ on this. 👍

**Comment by markwilliamfirth** [comment]
@nelsonic not sure what you mean

You need to make me a manager of the channel or change the channel to be under the new gplus page (of which you are a manager)

This is why I suggested deleting the old one because this will be a headache to do...

**Comment by markwilliamfirth** [comment]
@nelsonic are you able to give me access?

**Comment by nelsonic** [comment]
@markwilliamfirth I _already_ granted you Admin access back in December. 😉 
Pair on figuring out what `else` I need to do to make sure you can administer the account...

**Comment by markwilliamfirth** [comment]
@nelsonic you need to make me the owner to move the channel

I think we should just remove the old one and keep the new - otherwise I will have to change the settings on the old one like I did for the new one and it's just repeating work. The new one already has more subscribers. The age of and the video on the old channel will have likely lowered the channel stats for that channel with regards to the youtube algorithm - I don't see a benefit to using the old one? The timestamp being old with no content made isn't a positive thing

**Comment by markwilliamfirth** [comment]
Google plus has been claimed: google.com/+dwyl

**Comment by markwilliamfirth** [comment]
YouTube and Tumblr have been claimed 🌟 
https://www.youtube.com/dwyl
http://dwyl.tumblr.com/

**Comment by sohilpandya** [comment]
@markwilliamfirth Awesome! the YT one is different to the current one, can we transfer the assets across? 😄

**Comment by nelsonic** [comment]
@markwilliamfirth is the YouTube attached to our existing channel or a new one? (_thanks BTW!_) 👍

**Comment by markwilliamfirth** [comment]
Reddit finally replied:

Dear Mr Firth,

This responds to your correspondence alleging that another person’s username infringes your trademark or otherwise improperly uses your trademark. We, at Reddit, respect intellectual property rights, including trademark rights. It is our general policy, however, not to intervene in a trademark dispute unless the complaining party holds a federal United States trademark registration for the affected mark.

We don’t intervene in the absence of a U.S. federal trademark registration because we have found that we are not well-positioned to determine the respective rights of the competing parties quickly and reliably in these situations. Presenting us with a trademark registration issued by another jurisdiction does not help us because, while we are aware that many nations and other jurisdictions in the world grant trademark registrations, the meaning and consequence of holding such registrations varies from jurisdiction to jurisdiction.

In light of the above, we urge you to deal directly with the person you believe is violating your rights. If you obtain a federal U.S. trademark registration for the mark or a U.S. court order relating to your rights against the alleged infringer of the mark, please don’t hesitate to contact us.

Reddit Legal Support

**Comment by markwilliamfirth** [comment]
Closed in favour of above issues
