### ISSUE TITLE
Company Name

### ISSUE THREAD

**Issue by markwilliamfirth** [dwyl/hq#249]
This issue has been moved here from the from old brand repo.

This issue is for tracking misuses of the company name in terms of casing, misspelling or mispronunciation as they occur. There is currently an anecdotal, but unrecorded history of branding issues related to the company name. The reason for this is to keep a record to determine whether or not this is a potential issue for our brand.

**Comment by markwilliamfirth** [comment]
Received an email from someone referencing "Dwyl" (even though it wasn't at the beginning of a sentence) despite my original email to them saying "dwyl".

15 Feb 2016

**Comment by markwilliamfirth** [comment]
Received a message from a friend who knew of the company, but spelled the name as "Dwill".

15 Feb 2016

**Comment by markwilliamfirth** [comment]
On Friday Hannah from Unbound pronounced it "die-will" (she was corrected) and then later pronounced it "dwell" on the video, later at the pub she pronounced it incorrectly again. Owen didn't think it was a pronounceable word and instead thought it should be pronounced "d-w-y-l". Another person thought it was "dwill-e-o" because of the dwyl.io domain in the logo

17 Feb 2017

**Comment by markwilliamfirth** [comment]
<img width="334" alt="screen shot 2017-02-27 at 09 45 41" src="https://cloud.githubusercontent.com/assets/5732209/23356417/9e9efb38-fcd1-11e6-8fcf-a54b7d31d37f.png">

**Comment by markwilliamfirth** [comment]
<img width="81" alt="screen shot 2017-02-27 at 10 32 05" src="https://cloud.githubusercontent.com/assets/5732209/23357993/0fb06c52-fcd8-11e6-948c-2030676bef90.png">

Harry in an email to Code4000

2017-02-26

**Comment by markwilliamfirth** [comment]
<img width="263" alt="screen shot 2017-02-27 at 13 01 52" src="https://cloud.githubusercontent.com/assets/5732209/23362280/fdb37e8a-fcec-11e6-9e23-29d65da0bfa2.png">

Had sent email with `dwyl` previously - he still spelled `Dwyl` when replying

2017-02-27

**Comment by markwilliamfirth** [comment]
After several emails, we were on a Skype call with Sam from Super Global today:

> Sam: "What are you guys actually called? Is it "d-w-y-l"? Is it "Do What You Love"? Is it  "dwill"?

> Inês: "We say "dwill""

> Sam: "Ah - great. I guess I should say that too then!"

**Comment by iteles** [comment]
But he pronounced dwyl correctly unprompted.

**Comment by sohilpandya** [comment]
Should we have an intro video on the site that starts with one of us saying: 
"Welcome to dwyl" 
🤔

**Comment by markwilliamfirth** [comment]
@sohilpandya great idea! If you can please make an issue in video or hq, add the brand tag and reference this issue. The purpose of this issue is just for recording the history

**Comment by markwilliamfirth** [comment]
<img width="312" alt="screen shot 2017-03-02 at 11 58 11" src="https://cloud.githubusercontent.com/assets/5732209/23506323/923c94e8-ff3f-11e6-8ce0-90a3eef54ee1.png">

2017-03-02

**Comment by markwilliamfirth** [comment]
<img width="500" alt="screen shot 2017-03-02 at 12 05 36" src="https://cloud.githubusercontent.com/assets/5732209/23506518/95ca92d0-ff40-11e6-827e-536e4b3ba80b.png">

2017-02-28

**Comment by markwilliamfirth** [comment]
<img width="386" alt="screen shot 2017-03-02 at 12 07 17" src="https://cloud.githubusercontent.com/assets/5732209/23506550/ce9dc226-ff40-11e6-9048-b42ab97ba321.png">

2017-03-01

**Comment by sohilpandya** [comment]
@markwilliamfirth I actually meant that! I was shouting `DWYL` hence it's all written with caps lock on. 😉

**Comment by markwilliamfirth** [comment]
<img width="592" alt="screen shot 2017-03-02 at 14 44 33" src="https://cloud.githubusercontent.com/assets/5732209/23511927/cb4dddd4-ff56-11e6-83b6-72a74d3bae43.png">

2017-02-28

**Comment by markwilliamfirth** [comment]
<img width="473" alt="screen shot 2017-03-02 at 17 48 58" src="https://cloud.githubusercontent.com/assets/5732209/23519910/8e96d7be-ff70-11e6-9127-052ec16d9db8.png">

2017-03-02

**Comment by markwilliamfirth** [comment]
<img width="475" alt="screen shot 2017-03-10 at 16 25 00" src="https://cloud.githubusercontent.com/assets/5732209/23803377/39c9057e-05ae-11e7-8552-008ef2a04f46.png">

onefinestay decapitalises, even at the start of a sentence

**Comment by markwilliamfirth** [comment]
<img width="305" alt="screen shot 2017-03-17 at 10 19 59" src="https://cloud.githubusercontent.com/assets/5732209/24038928/5553bb7a-0afb-11e7-9798-16bdc0690c45.png">

Email from prospective intern (hasn't interacted with dwyl before)

2017-03-17

**Comment by markwilliamfirth** [comment]
<img width="454" alt="screen shot 2017-03-17 at 14 55 01" src="https://cloud.githubusercontent.com/assets/5732209/24048782/d4bb901a-0b21-11e7-8d35-4243694b7398.png">

In the #TechForGood Meetup Community Announcements

2017-03-17

**Comment by markwilliamfirth** [comment]
<img width="547" alt="screen shot 2017-03-21 at 14 31 58" src="https://cloud.githubusercontent.com/assets/5732209/24152317/33b7b994-0e43-11e7-9ada-612c93bd1fa0.png">

2017-03-21

**Comment by markwilliamfirth** [comment]
<img width="795" alt="screen shot 2017-04-14 at 19 09 13" src="https://cloud.githubusercontent.com/assets/5732209/25051708/e948accc-2145-11e7-920b-71040672848a.png">

**Comment by markwilliamfirth** [comment]
<img width="283" alt="screen shot 2017-04-25 at 11 26 37" src="https://cloud.githubusercontent.com/assets/5732209/25380984/1653f78c-29aa-11e7-8f5d-2cc5ffec3eaa.png">

2017-04-25 - calendar invite from MV

**Comment by markwilliamfirth** [comment]
On Friday at a meetup:

Person: "Where do you work?"
Me: "dwyl"
Person: "dwell?"
Me: "dwyl - it's spelled d-w-y-l. It stands for Do What You Love"
Person: "Oh that's weird, if it's spelled like that I would have pronounced it '_dwhile_'

2017-05-05

**Comment by markwilliamfirth** [comment]
![image](https://cloud.githubusercontent.com/assets/5732209/26003146/cbbe7f16-3729-11e7-86ee-cecc1bcc5ebd.png)

2017-05-12

**Comment by markwilliamfirth** [comment]
<img width="600" alt="screen shot 2017-06-20 at 12 46 37" src="https://user-images.githubusercontent.com/5732209/27331709-8ad69a82-55b6-11e7-926b-e8eeb2c97553.png">

2017-06-20

**Comment by markwilliamfirth** [comment]
<img width="299" alt="screen shot 2017-06-23 at 14 17 53" src="https://user-images.githubusercontent.com/5732209/27483824-c9107ca4-581e-11e7-9b72-b167eb38c546.png">

2017-06-23

**Comment by markwilliamfirth** [comment]
<img width="287" alt="screen shot 2017-07-11 at 11 40 15" src="https://user-images.githubusercontent.com/5732209/28064757-bf0d8842-662d-11e7-876c-ee5f845f6a4a.png">

Rujuta

2017-07-11

**Comment by markwilliamfirth** [comment]
<img width="218" alt="screen shot 2017-07-11 at 14 32 08" src="https://user-images.githubusercontent.com/5732209/28070699-c113b838-6645-11e7-9a24-4b589d498d32.png">

Chris - Focus Hub tenant

2017-07-11

**Comment by harrygfox** [comment]
@markwilliamfirth gahhh those people that say dwhile...

**Comment by markwilliamfirth** [comment]
@iteles perhaps we should review this issue again and talk about brand guidelines given we are soon to be releasing the dwyl site?

**Comment by markwilliamfirth** [comment]
<img width="393" alt="screen shot 2017-10-02 at 13 09 11" src="https://user-images.githubusercontent.com/5732209/31076605-ed074c66-a772-11e7-8e1a-16924575d598.png">

2017-10-02

**Comment by markwilliamfirth** [comment]
<img width="1223" alt="screen shot 2017-10-03 at 11 46 04" src="https://user-images.githubusercontent.com/5732209/31121526-76eeda4e-a830-11e7-9ba6-26836d8ad042.png">

2017-10-03

**Comment by markwilliamfirth** [comment]
Closed in favour of https://github.com/dwyl/brand/issues/11
