### ISSUE TITLE
dwyl logo file

### ISSUE THREAD

**Issue by markwilliamfirth** [dwyl/hq#252]
@iteles do you know where the .ai (or equivalent) file of the dwyl logo is? I cannot find it in drive

**Comment by nelsonic** [comment]
@harrygfox might be able to help...

**Comment by harrygfox** [comment]
@markwilliamfirth in the "Branding and Marketing" folder there is the `.png` and `.svg` files for the dwyl heart that you see on the home page of dwyl.io

**Comment by markwilliamfirth** [comment]
@harrygfox thanks - we need the original teal logo though - maybe Joe Tanner has it if Ines doesn't?

**Comment by harrygfox** [comment]
If you have the precise colour code then the assets can easily be changed

**Comment by nelsonic** [comment]
@harrygfox I think it would be _helpful_ to have a vector image for the logo so we can make things in high res: https://github.com/dwyl/quietspace/issues/17 😉

**Comment by markwilliamfirth** [comment]
Thanks @harrygfox! Ideally, we shouldn't really be remaking the logo though...the original file should exist somewhere - or is the plain svg the original? The heart colour code should be #4DB6AC I believe

**Comment by iteles** [comment]
Success! I've found the original logo files and uploaded them to the Logos folder (under `original dwyl logo files`).

**Comment by markwilliamfirth** [comment]
awesome

**Comment by markwilliamfirth** [comment]
@iteles I just opened the file in AI and it's not the right file(!) It's the AI version of the old logo which looks like this:

<img src="http://www.foundersandcoders.com/assets/partners/dwyl-logo.png">

We still need to find the original logo file. Is it ok if I reach our to Joe Tanner?

**Comment by iteles** [comment]
@markwilliamfirth Like I said, it's the *original* logo. There's no AI file for the latest one - doesn't exist.

**Comment by harrygfox** [comment]
@markwilliamfirth why does it matter about remaking it? - it's the same logo to my mind.
@nelsonic `.svg` files _are_ vector images

**Comment by iteles** [comment]
We can change hex codes in SVGs pretty easily too :+1:

**Comment by markwilliamfirth** [comment]
@harrygfox I was under the impression there was a file for it, but there isn't  - so we need to make one anyway!

My original apprehension around "remaking" it was just around the concept of remaking a logo - it's not really something that should be done as the original file is the "true" logo and the remade one might be slightly different (but in this case we don't have an original so we need to make one).

**Comment by iteles** [comment]
The AI file you have a screenshot of above is the original logo, the only difference is that that exact heart has been flipped and rotated before we actually started using it as our brand. Every other .png and .svg and .jpg has come from that file, including the hex sticker AI files which have the heart as we now use it.

**Comment by markwilliamfirth** [comment]
Is there an AI file of it isolated, flipped and rotated?

**Comment by iteles** [comment]
The closest thing to that is the flipped and rotated heart with the dwyl.io writing underneath (the hex sticker). Agreed we should have both, preferably as svg's for easier manipulation without needing proprietary software 👍

**Comment by nodecoder** [comment]
Created an `.ai` file and uploaded it to dwyl > Branding & Marketing > Logos
![image](https://cloud.githubusercontent.com/assets/10835816/24082472/11b0916c-0cbe-11e7-8ca1-d13030d8008c.png)

**Comment by nelsonic** [comment]
closing as location of dwyl logo vector is now known. ⏫
