### ISSUE TITLE
Acquire dwyl.co.uk domain

### ISSUE THREAD

**Issue by markwilliamfirth** [dwyl/hq#254]
[Research](http://nominet-prod.s3.amazonaws.com/wp-content/uploads/2015/08/Expert_Overview.pdf)

**Comment by iteles** [comment]
@markwilliamfirth Have just forwarded an email we got on this 👍

**Comment by markwilliamfirth** [comment]
dwyl.co.uk has now been acquired and is now pointing to dwyl.com 👍 

Zoho email client set up with DNS MX records pointing to Carl as per agreement until 16 Mar 2018.
