### ISSUE TITLE
Email Spreadsheet

### ISSUE THREAD

**Issue by markwilliamfirth** [dwyl/hq#255]
@iteles is there somewhere I can find a spreadsheet of everyone's emails in dwyl?

Links to #213

**Comment by markwilliamfirth** [comment]
@iteles I have filled in as much [information](https://docs.google.com/a/dwyl.io/spreadsheets/d/1ECdbJm_hM9OvS9EOKVymknJ8nd1pDAe_WAPTOUcu5S4/edit?usp=sharing) as I can (without doing extensive research). Would you be able to add in what you know? (And then I can research and fill in the remaining gaps).

**Comment by iteles** [comment]
@markwilliamfirth I've filled in all the dwyl people and the others I happened to know. There's a huge number I don't know or recognise but the dwyl folks are the important ones for now, let's not spend any more time on this until we have our #161 👍

**Comment by iteles** [comment]
Have just updated the meetup column for March, there may be too many yeses in there...

**Comment by markwilliamfirth** [comment]
Nice
