### ISSUE TITLE
What feedback do we want to capture from our clients? What do we want to measure?

### ISSUE THREAD

**Issue by iteles** [dwyl/hq#257]
We have quite a few projects that have just been competed and we need to capture feedback from them.

Right now, our questionnaire is short (which it should continue to be), but doesn't capture any measurable information:
1. Did the overall project process and experience go as you expected? If not, why not?
2. What did you feel went well?
3. What could have been improved?
4. Was there anything that you weren't anticipating (good or bad!)?
5. Are you happy for us to write up a short case study on our work with you and display it on our website (we'll run it by you beforehand of course!)?

## What information should we be capturing?

**Comment by iteles** [comment]
Unassigning myself as I would like this to be a discussion rather than something coming just from me :blush:

**Comment by markwilliamfirth** [comment]
We can improve quantification by including questions where they rate us out of 10.

For example:
Rate from 1-10 the following:

Our ability to understand your needs as a client
The quality of the code
The choice of technologies used for the project
Did we communicate complex technological concepts in simple to understand ways?
How we responded to changes of scope and bugs

Not saying we should track the above, but they are just examples to draw inspiration from.

We should track the things we offer as a value proposition. Then we can say "100% of our clients have rated the quality of our code as 9/10 or above".

**Comment by nelsonic** [comment]
The feedback we want relates _closely_ to our **Case Study Template**...
which I can't seem to find on GitHub...
![image](https://cloud.githubusercontent.com/assets/194400/23826455/745027e0-0694-11e7-9f9f-93453de1e505.png)
https://github.com/search?q=org%3Adwyl+Case+Study&type=Issues

@markwilliamfirth please post the template we put together in our team meeting, thanks! 👍

**Comment by markwilliamfirth** [comment]
[This](https://docs.google.com/document/d/1X9OyqjKAeBmKO05i8KLVAlLHDEc-cLJ8iTExlWmJrjE/edit) is the one we wrote

Also found [this](https://docs.google.com/document/d/1IR3srDxNBt8kRq01dakhqgFR7kFRH3h6D4oFSfEtuYY/edit) in drive from 2015

**Comment by iteles** [comment]
@markwilliamfirth Why do we think this is complete? I personally have not yet fully captured what is here in a client feedback request form - have you? What's the latest on this?

**Comment by markwilliamfirth** [comment]
@iteles I thought case studies was the issue that replaced this one? Please reopen and assign to yourself if there is more to do on this one
