### ISSUE TITLE
Setting Dates for dwyl Summer

### ISSUE THREAD

**Issue by markwilliamfirth** [dwyl/hq#259]
- [ ] Dates for Nelson + Inês

- [x] Dates for the team + friends of dwyl to visit

**Comment by markwilliamfirth** [comment]
@iteles do you know approximate dates for this?

**Comment by iteles** [comment]
@markwilliamfirth https://github.com/dwyl/summer/issues/51 👍

**Comment by markwilliamfirth** [comment]
Inês leaving early July - tbc

**Comment by iteles** [comment]
Early July for Nelson and I.
