### ISSUE TITLE
Research Ethical Banking Alternatives

### ISSUE THREAD

**Issue by iteles** [dwyl/hq#26]
Linked to #25

Research Ethical banking alternatives
Assess internet banking level
Triodos
Charity bank
Cooperative bank

Compare to Santander and Barclays etc

**Comment by iteles** [comment]
We need to have the following information and then give them a call:
>Freephone : 0800 328 2181   
Landline : +44 (0)117 973 9339

- [ ] activities
- [ ] entity
- [ ] turnover and financial projections
- [ ] registered company and/or charity number (if applicable)
- [ ] the people connected to your organisation
- [ ] reasons for choosing Triodos Bank

https://www.triodos.co.uk/en/business/ethical-current-accounts/social-venture-account/pre-application-page-sv/

**Comment by nelsonic** [comment]
Its going to be a *lot* easier to have conversations with Triodos once we *have* some numbers for them...

**Comment by markwilliamfirth** [comment]
@iteles is this now higher priority?

**Comment by nelsonic** [comment]
@iteles not _yet_ ... Triodos isn't great for _many_ transactions. they are good for _few_ larger ones.
Re-visit after year-end. 👍

**Comment by markwilliamfirth** [comment]
http://www.ethicalconsumer.org/buyersguides/money/ethicalbusinessbanking.aspx

mentioned in https://github.com/foundersandcoders/international/issues/34

**Comment by iteles** [comment]
It really is a shame that the cooperative bank is so terrible :sob:

**Comment by markwilliamfirth** [comment]
Agree with the comment above

**Comment by markwilliamfirth** [comment]
I contacted Triodos to ask if I could demo their online banking and they said:

>We do not have a demo available for you to view of our internet banking. We can discuss the services offered but would not be able to show the actual contents.
 
>If there is anything else we can help you with please refer to our ‘How to operate your account’ booklet if you have a query about a savings account, call 0330 355 0355 or +44 (0)117 973 9339 if you are not in the UK, email contact@triodos.co.uk or send us a secure message using internet banking.

I did a bit of Googling and couldn't find much - must be better than Coop though?

And they rank better than coop in terms of ethics:

<img width="302" alt="screen shot 2017-09-20 at 13 32 21" src="https://user-images.githubusercontent.com/5732209/30643796-34b03646-9e08-11e7-9b3a-00d14b4c45f5.png">

Shall I open an account @iteles ?

**Comment by iteles** [comment]
@markwilliamfirth There's a whole application process to go through, but I think it would be great to have an account with them 👍

**Comment by markwilliamfirth** [comment]
Have sent an email to ask

**Comment by markwilliamfirth** [comment]
@iteles fees are here https://www.triodos.co.uk/downloads/bb-tariff.pdf?audience=Business

**Comment by iteles** [comment]
Thanks for Googling for those.

It seems the pertinent information is:
<img width="258" alt="screen shot 2017-09-28 at 16 23 45" src="https://user-images.githubusercontent.com/4185328/30975234-aaed50c0-a469-11e7-871d-1cd83c6e09c1.png">

More notably, the ones of these we use are:
+ Automated payments into account: all of our client payments, around 10-15 a month
+ Automated payments out of account: None at the moment
+ Faster payments: around 3-4 a month (one or two more quarterly when the VAT bill comes due
  + _Note: This is because we make all payments to dwylers out of a different account, seems kind of crazy to be paying for each and every one of these transactions_

In effect, we'd have to keep using it as a 'light touch' account and not an 'everything' account as the fees would get a little out of hand if we had to pay for every single transaction.

It's worth it to be banking with a more ethical bank, but I would appreciate you having a quick call with them on the internet banking (features and security) to make sure it's not _worse_ than the Coop and estimating how long the form will take to fill in before you start please.

**Comment by markwilliamfirth** [comment]
@iteles to be honest I don't think Triodos is a great solution, when everything is taken into account (internet banking, connections with Xero, branch access, cost, etc)

I think we should look into getting an account with one of the following:
Barclays
Metro Bank
NatWest
SVB
RBS

Do you have concerns about any of the above before I start looking into them?

**Comment by iteles** [comment]
😕 It would seem we have lost track of the topic of this issue somewhat.

http://www.ethicalconsumer.org/buyersguides/money/bankingcurrentaccounts.aspx
<img width="303" alt="screen shot 2017-09-29 at 09 24 58" src="https://user-images.githubusercontent.com/4185328/31007348-38872a44-a4f8-11e7-82a7-a1154f560036.png">
<img width="304" alt="screen shot 2017-09-29 at 09 24 30" src="https://user-images.githubusercontent.com/4185328/31007347-38847baa-a4f8-11e7-8a39-fbc9fd20f0de.png">

**Comment by markwilliamfirth** [comment]
@iteles I think it's important to keep in mind that if we opt for a sub-optimal solution this causes us issues and slows us down and prevents us from doing our work (which is socially impactful, etc) so that is something to consider

Perhaps Metro is the best contender if you think the ethicalconsumer.org score is the most important factor. I'll look into Metro first.

**Comment by markwilliamfirth** [comment]
@iteles let's go with metro?

<img width="732" alt="screen shot 2017-10-11 at 13 28 25" src="https://user-images.githubusercontent.com/5732209/31440528-3036c0a4-ae88-11e7-9c1b-47d61a901b80.png">
<img width="719" alt="screen shot 2017-10-11 at 13 28 31" src="https://user-images.githubusercontent.com/5732209/31440527-30226eba-ae88-11e7-805b-c9664e5149ba.png">

**Comment by iteles** [comment]
I had a little brainwave: At the moment, we're not automating any of our transfers into santander #264 which quite frankly is stupidity on my part.

Seeing as this is literally the only thing we do from the Coop account (transfer and check for Xero once every couple of weeks) and because banking applications are a pain and can take a lot of chasing, I propose that as a stopgap until we clear our higher priority tasks we just automate a transfer every 2-3 weeks (this can be adjusted) and do this then. Setting this up now 👍

**Comment by markwilliamfirth** [comment]
@iteles I don't think that answers this issue - this is more about moving to a different bank (that is also ethical) so we no longer have to use coop or santander, as both are not great for various reasons

I think Metro is a good solution - what do you think?

**Comment by markwilliamfirth** [comment]
[What you Need to Open a Business Account with Metro Bank.pdf](https://github.com/dwyl/hq/files/1438665/What.you.Need.to.Open.a.Business.Account.with.Metro.Bank.pdf)
[Business Bank Account IIS.pdf](https://github.com/dwyl/hq/files/1438666/Business.Bank.Account.IIS.pdf)

This is free to open so I'm going to suggest we just open it and try it out and then we can decide whether to make the move permanently once we've tested the internet banking etc

@iteles I'm going to assume you want to be an Account Operator(?)

@nelsonic please can you confirm if you want to be an Account Operator or not, if I don't hear back I'll assume that the answer is a no

**Comment by iteles** [comment]
Our combination of ethical banking providers is not _fantastic_ but is working for us _at  the moment_. Will reopen when there  is a pain point to address here.
