### ISSUE TITLE
dwyl VAT return | period ending 31st January 2017

### ISSUE THREAD

**Issue by iteles** [dwyl/hq#260]
### Deadline: 3 March 2017

+ [x] Finalise income for the period 1st November 2016 - 31st January 2017
+ [x] Determine VAT on expenses for that period
  + [x] F&C invoices (@iteles)
  + [x] Ice Cream Rocketship invoices
  + [x] Receipts/invoices
+ [x] Fill our VAT statement
+ [x] Pay VAT for the quarter

**Comment by markwilliamfirth** [comment]
Payment to come out of account via direct debit on 13 Mar

**Comment by iteles** [comment]
Reopening as VAT hasn't been paid.

**Comment by iteles** [comment]
Now paid 👍
