### ISSUE TITLE
Women Techmakers Global Event Series - London

### ISSUE THREAD

**Issue by markwilliamfirth** [dwyl/hq#261]
Wednesday, March 1, 2017

https://www.womentechmakers.com/iwd17

https://services.google.com/fb/forms/iwd17lonsummitapplication/

The event will feature panel discussions with female technology leaders, networking opportunities and more. 

women-techmakers-events@google.com

@iteles what do you think in terms of asking for a panel slot (might be too late) or simply attending?

**Comment by iteles** [comment]
I'm pretty sure they'll have locked down their programme by now!

But I could attend... if I miss dodgeball 🤷‍♀️

**Comment by markwilliamfirth** [comment]
Ok - let me know if you think it's valuable enough vs dodgeball (vs free time - also valuable ;) )

**Comment by iteles** [comment]
Ended up at F&C business meeting - a requirement given my director status!
