### ISSUE TITLE
Transfer to Santander

### ISSUE THREAD

**Issue by markwilliamfirth** [dwyl/hq#264]
Increase balance of operating account

**Comment by iteles** [comment]
Done!

**Comment by iteles** [comment]
Done 👍

**Comment by iteles** [comment]
Done again

**Comment by iteles** [comment]
Been like this since yesterday lunch time:
<img width="743" alt="screen shot 2017-08-19 at 12 43 02" src="https://user-images.githubusercontent.com/4185328/29486372-0ccd8ce0-84dc-11e7-8904-5d60eb6d0b43.png">

**Comment by iteles** [comment]
Finally sorted their problems. Done.

Have also update Xero with all the latest payments.

**Comment by iteles** [comment]
Done. Confirmed no further payments made from our clients since 21st Agust round of updates in Xero.

**Comment by markwilliamfirth** [comment]
@iteles thanks - just a note to say that the balance probably needs to be significantly increased to prepare for #370

**Comment by iteles** [comment]
Account balance significantly increased over the course of 3 working days given daily transaction caps.

**Comment by markwilliamfirth** [comment]
This will need to be increased again post payment

**Comment by iteles** [comment]
Done.

**Comment by iteles** [comment]
And again, as well as updating all payments in Xero.

**Comment by markwilliamfirth** [comment]
Balance is now in minus figures after recent order of Anker Mouse on Amazon

**Comment by iteles** [comment]
I have been temporarily separated from my fob and when I tried to call cooperative bank yesterday, it appears our telephone banking has been mysteriously deactivated.

I expect to be reunited with my fob tonight but in the meantime have made a temporary loan from my personal account to cover any payments to dwylers that _must_ go out this week.

**Comment by markwilliamfirth** [comment]
@iteles shall I open the metro account? #26

**Comment by markwilliamfirth** [comment]
There isn't enough in the account to pay payroll

**Comment by iteles** [comment]
Transferred and Xero updated with latest payments.

**Comment by iteles** [comment]
Actually, decided to reopen so that I can make another transfer tomorrow after payroll is complete for the next set of payments.
