### ISSUE TITLE
Company Blog Platform

### ISSUE THREAD

**Issue by markwilliamfirth** [dwyl/hq#265]
Medium vs In-house Blog - pros and cons of Medium

**Pros**
- Already set up https://medium.com/dwyl we could start publishing asap if we wanted to
- Access an easy-to-use and update front-end interface
- Much more feature rich (e.g. provides estimate for estimated time to read)
- Connect Twitter and Facebook networks to boost following from day one
- We can reach new audiences using tags, follows, and @mention features
- Stay connected and social with followers using the [highlighter](https://blog.medium.com/introducing-highlights-a4df69e8ed43#.ariu6a65i) feature
- Attract attention – followers are notified every time we publish a new post
- Schedule articles by picking a date and time to publish
- Medium will continue to improve and add features over time and become a huge platform for tech blogging, even bigger than it already is
- This time last year there were approx 625000 users (not sure how many there are now) and 30 million monthly visitors
- Completely free (vs. in-house bog will take dev time to build)
- [Built-in stats](https://help.medium.com/hc/en-us/articles/215108608-Stats)

**Cons**
- [Currently limited Google analytics](https://help.medium.com/hc/en-us/articles/215832277-Are-Google-Analytics-available-on-Medium-)
- No control. It’s a 3rd party platform, which means the rules could change at any point or it could end.

Given the above Medium appears to be a strong contender

**Comment by markwilliamfirth** [comment]
Calculating dev time estimate in https://github.com/dwyl/dwyl-site/issues/202#issuecomment-283029619

**Comment by nelsonic** [comment]
@markwilliamfirth _annoyingly_ the research into Medium captured by @sohilpandya in https://github.com/dwyl/adoro/issues/97 is not easy to find in our _ocean_ of GitHub issues.

Medium is an _amazing_ platform for people who _just_ want to publish content. 👍 
The features are _excellent_ (_I love "highlighter"_) and interface for content creation/editing is second-to-none. No contest there. 😍 

> We don't want to _just_ publish the content, we want the inbound links to increase our "Page Rank" which will mean people will find our Company/Products easier when they search on Google.

The _reasons_ we aren't (_already_) using Medium are:
+ 3rd Party Platform gives us limited control over the _future_ of our content
+ we do not build a _list_ of subscribers letting a 3rd party "_handle_" subscriptions/notifications.
+ Commenting is done on the Medium Platform. Their commenting system could be better.
+ Most importantly we get _zero_ "SEO Benefit" from using Medium which is one of the _major_ advantages of writing good content (_beyond communication_).

The monthly users on Medium are _meaningless_ to us, our content won't be relevant to 99.99% of their viewers.
What we want is _organic_ traffic based on the relevance/usefulness of our content.
We want to "_rank_" on Google for specific keywords (_@iteles has the list_) 
and we want those search terms to be _associated_ with our "_brand_" not with the Medium Platform.

Also: http://uk.businessinsider.com/inside-the-meltdown-of-evan-williams-startup-medium-2017-2

**Comment by markwilliamfirth** [comment]
@nelsonic your comment in the referenced issue Sohil created:

>[I] openly acknowledge that we are too thinly spread and need to focus on our revenue-generating product in the short-term. Meanwhile we still need to start publishing "Blog" Posts ASAP

Should we really spend X (awaiting estimate) days building a blog when we should be building product? Is the value of more control, a subscription list, superior commenting and SEO that important right now? Or is the primary focus pushing out content and focusing dec time on product?

**Comment by markwilliamfirth** [comment]
This isn't a technical decision, this is a business decision and links back to our vision and where we should be prioritising our time.

**Comment by Cleop** [comment]
@markwilliamfirth - were there any conclusions drawn from this? Would be useful to know where we stand on this for @harrygfox's designs for the website redesign, don't want him to design a blog page that may not be needed/ that may have to follow another website's design limitations.

**Comment by iteles** [comment]
@Cleop Speak to Nelson on this one and we can open a new issue.

**Comment by markwilliamfirth** [comment]
@Cleop sorry should have put in my closing comment - Nelson has a preference for in-house

**Comment by sohilpandya** [comment]
I'm also a big fan of in-house after someone convicnced me that it is the way to go. 🙄😳😊

**Comment by markwilliamfirth** [comment]
Hi everyone I think we need to reopen this discussion - yesterday @iteles told me on Gitter that the blog platform will require Nelson's involvement in order to build it, but he doesn't have availability to devote time to it until at least October.

I would like to suggest again that we consider using a medium blog as an alternative platform for now (and link it to blog.dwyl.com) until we have the resources to build our own. If we had done this back in February we would have already had 6 months of the blog driving traffic to our website, which is only beneficial. I think this is a good stop-gap. It is already set up (https://medium.com/dwyl), all we need to do is set up the subdomain and start posting.

After the in-house blog platform has been created we can close the old medium blog and delete and transfer the old blog posts to the new platform.

@iteles what are your thoughts on this solution?

**Comment by iteles** [comment]
I have requested that Nelson spend the next 5 weeks exclusively focused on dwyl's technology, allowing this organisation to move forward rather than hamster-wheeling around client work.

@markwilliamfirth Thanks for raising this again. Please clarify why there is a rush to get this completed prior to that 5 week timeframe.

**Comment by markwilliamfirth** [comment]
@iteles I am aware that dwyl has been talking about setting up a blog [since 6 June 2015](https://github.com/dwyl/dwyl-site/issues/5) and during my first week here it was also mentioned and has (obviously) been mentioned a number of times since then.

Unfortunately other more important things always seem to pop up and divert attention away from this.

My suggestion follows the logic that this is a beneficial short-term solution that takes no time to implement (and time is what we are lacking) and will benefit the company until time can be devoted to building our in-house blog at a later date.

I would be very happy if Nelson has time in 5 weeks, but I am also aware that other things pop up all the time and I don't know if this is a realistic timeframe, but if you think so we could book in time into the calendar to tackle the blog then.

**Comment by iteles** [comment]
I take your point.

The [SEO](https://github.com/dwyl/hq/issues/265#issuecomment-283110876) issues mentioned above are still a concern to me.

However, as it stands, you have already merged in Cleo's PR that sets up the blog post templates on our website: https://github.com/dwyl/dwyl-site/pull/298 :tada:

We're all developers. With very little work (adding in some comments in the code and testing some sample content and canonical URLs) we can set up a template for anyone writing a blog post to do it straight into HTML and get it onto the website already! Blog MVP-style

**Comment by markwilliamfirth** [comment]
@iteles what would be the features of the above proposed blog MVP? Does this include interaction and commenting, sharing, etc? Or just text?

**Comment by markwilliamfirth** [comment]
@iteles can you clarify the above?

**Comment by markwilliamfirth** [comment]
Closed in favour of https://github.com/dwyl/blog/issues/26
