### ISSUE TITLE
How can we improve inclusivity at dwyl?

### ISSUE THREAD

**Issue by markwilliamfirth** [dwyl/hq#266]
dwyl is already a great community of people. How can we further improve dwyl's inclusivity to ensure those who are more shy or haven't contributed before would be willing to contribute? What changes should we be making to create a more inclusive culture that allows the opinions of a wider range of people from different backgrounds to be heard?

Anyone with thoughts on this are warmly welcomed to comment their thoughts!

...(would be quite ironic if someone reads this and feels like they can't/dont' want to post...)

**Comment by nelsonic** [comment]
I don't _understand_ why this issue was _closed_ (_was it "resolved"?) ... thought it was a _great_ idea!  😕 
Granted, we have a _few_ issues open, but that's "OK" provided they are still relevant.

**Comment by markwilliamfirth** [comment]
It was closed because no one replied to the post - if anyone wishes to share their opinion on this topic then please do and please reopen!
