### ISSUE TITLE
Suggestion: Friday Workshop Half-Day

### ISSUE THREAD

**Issue by sohilpandya** [dwyl/hq#267]
Earlier on today I was given a little walkthrough of Phoenix by @jackcarlisle and I've got a little idea: 

**Can we have a fortnightly workshop that takes place at QS?**

- Each workshop would last 3 hours on a Friday 2pm - 5pm. 
- Everyone is taken through the topic (i.e. phoenix/swift/elm) where they build a simple app using the tech. 

I understand that it isn't going to make people pros in the given topic but it should give them a nudge in the right direction. It is also a good opportunity for us to film and publish the material online. 

If given the go ahead we can try to plan one for the 10th/17th March?

Q: should this be a DWYL only event or should we open it to the public? Might be a good to keep it open to invite people who might be interested in renting a desk? (Just a thought...)

**Comment by nelsonic** [comment]
@sohilpandya yes!
relates to: https://github.com/dwyl/video/issues/17
The workshops will be filmed and publicly available.
Only members of QuietSpace/DWYL will attend in-person. 👍

**Comment by sohilpandya** [comment]
Can we pencil a workshop in for the 17th March? 2pm - 5.30pm

@jackcarlisle @shouston3 @katbow @RobStallion @SimonLab up for doing a 3 hour phoenix workshop for the rest of us? (you'll be famous on the internet! 😉)

**Comment by katbow** [comment]
I'm down to co-run that with someone 😄 . Need some ideas on what we can build hmmm 🤔

**Comment by shouston3** [comment]
@katbow I'm up for co-running

**Comment by RobStallion** [comment]
@sohilpandya I think that this is a great idea. I'd be up for taking part as well @katbow @shouston3

**Comment by iteles** [comment]
Also linked to #198

**Comment by sohilpandya** [comment]
@katbow @RobStallion @shouston3 you've got 3 days to go.... 👍

**Comment by markwilliamfirth** [comment]
Is this definitely happening? Let me know and I can add it to the calendar

**Comment by sohilpandya** [comment]
It's happening 💯 looking forward to it. ☺

**Comment by sohilpandya** [comment]
So what time are we starting this? @nelsonic @katbow @RobStallion @shouston3

**Comment by sohilpandya** [comment]
OK, so it turns out it's not going to take place today. I apologies for the chaos 😢 

We've rescheduled this for Friday next week 2PM. @nelsonic will be running it.

**Comment by iteles** [comment]
@markwilliamfirth Could you reschedule the Phoenix workshop to next week and send it out to dwylers?

@sohilpandya Any reason why 14h00 - 17h00 and not 15h00 - 18h00? I think most of us officially begin the day at 10h00 and having it in the last 3 hours of the day might break the day up a little less 😊

**Comment by sohilpandya** [comment]
I just thought that we could start straight after lunch, I don't have a preference here, quite easy with the timings.
