### ISSUE TITLE
Mile End Climbing Wall Taster Session: Sunday 26th March 2017 (16:00 - 17:30)

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hq#268]
Seems like a _waste_ to live/work ***5 mins walk*** from the Mile End Climbing Wall and _not_ take the opportunity to go try it out...

https://www.mileendwall.org.uk/courses/view/taster-sessions/

I'm thinking of going to the "Taster Session" on Sunday 26th March 2017  16:00 - 17:30
If ***anyone*** `else` is free on that day and wants to join in, post a comment below! 👍 

> @claireinez what was _your_ conclusion on the beginners course?

# Read

+ http://www.healthfitnessrevolution.com/top-10-health-benefits-rock-climbing
+ http://www.nhs.uk/Livewell/fitness/Pages/rock-climbing-health-benefits.aspx
+ http://www.huffingtonpost.com/2014/08/30/health-benefits-rock-climbing_n_5708847.html

P.S we are _definitely_ going to have a climbing wall in ["Phase 2"](https://youtu.be/5P5akoQ_eNI) because climbing is excellent full-body & mind workout!

**Comment by claireinez** [comment]
It was really good though I wished I had done a basic intro session first as they explain things in more detail so would recommend!

**Comment by sohilpandya** [comment]
Let do it!

**Comment by nelsonic** [comment]
@sohilpandya there are spaces available on 26th March:
![image](https://cloud.githubusercontent.com/assets/194400/24126290/11e0256e-0dc5-11e7-9a2e-1c130fb57aed.png)

@jackcarlisle do you fancy joining us?
@iteles should I book you a space?

**Comment by iteles** [comment]
Why not? Always happy to go on a date with you both :laughing:

**Comment by jackcarlisle** [comment]
@nelsonic I would have loved to but I have to move all of my stuff out of my current house on Sunday! Rain check ☔️

**Comment by nelsonic** [comment]
@jackcarlisle do you need any help moving? have you already got a van? let us know if you want an extra pair of hands. 👍

**Comment by jackcarlisle** [comment]
@nelsonic thanks for the offer! @Conorc1000 has booked the zip van. Will let you know if we need some heavy lifting done 💪🏼

**Comment by nelsonic** [comment]
After a rather unfriendly error message:
![image](https://cloud.githubusercontent.com/assets/194400/24143391/6dd3b8ac-0e21-11e7-9eb2-832add626023.png)

> Unfriendly error messages are _worst_! let's fix it! https://github.com/dwyl/learn-phoenix-framework/issues/65

I _eventually_ managed to checkout:
![image](https://cloud.githubusercontent.com/assets/194400/24143526/e0ab6d70-0e21-11e7-97f9-f9ed11e32cc5.png)

Reserved for 3 people. ✅ 
If ***anyone*** `else` is interested there are still 3 more spaces available!  
(_please come it's going to be amaze!_) 🎉

**Comment by sohilpandya** [comment]
This Looks awesome! I'm going to be a pro soon! 😆

**Comment by sohilpandya** [comment]
OK, so I made it to the taster session and now I'm a convert! 

I ❤️  the idea of bouldering and climbing! 

Also, I'm a pro 😆 
![fullsizerender](https://cloud.githubusercontent.com/assets/2305591/24353646/6a8bb1f8-12e6-11e7-9ca4-b451a2643114.jpg)

**Comment by iteles** [comment]
Climbing is awesome! 

Closing this issue. We can open another one when we have a plan to go climbing :blush:
