### ISSUE TITLE
Do we need more mason jars?

### ISSUE THREAD

**Issue by iteles** [dwyl/hq#27]
Our supply of mason jars has seemingly disappeared over the summer, so I had a quick look at more mason jars (I prefer these for soup as well as smoothies).

I have a very strong preference for the **wide mouth** canning jars which Kilner no longer makes. The best deal I found for these was [this one](http://www.ebay.co.uk/itm/Ball-Mason-Canning-Jars-Clear-12-Pack-32-Oz-Quart-Lids-Bands-Wide-Mouth-Wedding-/141539974843?hash=item20f4709ebb) with 12 coming from the USA at £30.50.

**Comment by nelsonic** [comment]
Yes/No/Depends. 
relates to https://github.com/nelsonic/health/issues/17

**Comment by nelsonic** [comment]
I think there's an *easy* "*solution*" to this... 
http://www.amazon.co.uk/Litre-Coconut-Merchant-Organic-Virgin/dp/B00SNGY12G/
(*use the "free" jars we get from buying coconut oil...*)

**Comment by iteles** [comment]
@nelsonic I was under the impression this coconut oil wasn't great (very fragrant)?

Those jars don't provide a great seal but might be enough for keeping soup in the fridge for example, just not transport 👍🏻
