### ISSUE TITLE
F&C Invoicing Update

### ISSUE THREAD

**Issue by markwilliamfirth** [dwyl/hq#272]
dwyl pays a commission of 10% of charged-out rates back to Founders & Coders to help keep the lights on.

+ [ ] Update [F&C sheet](https://docs.google.com/spreadsheets/d/1V6kjy3IM8W5lFkr_4cGe2XXK1mMWuNvzwkObAgGifoc/edit#gid=0) for new payments

+ [ ] Mark devise new Xero system to inform Dan
  + Amount he needs to invoice
  + For which project and sprint

+ [ ] Developer invoices
  + Mark to upload developer invoices to Xero

**Comment by iteles** [comment]
@markwilliamfirth Are the dev invoices part of this or part of #229 ?

**Comment by iteles** [comment]
A further requirement (not urgent but may impact how you record things for F&C) - I would love to run a report off to see how much we've paid in commission for each person back to F&C. This would give the developers an idea of how much they have contributed given that there is a suggested contribution.

**Comment by markwilliamfirth** [comment]
@iteles uploading to xero is part of this, but sending to me is part of 229 (have updated 229)

**Comment by markwilliamfirth** [comment]
This keeps getting pushed back, but Dan's been waiting on this a long time and I think we should make this a priority @iteles 

<img width="786" alt="screen shot 2017-08-18 at 12 00 33" src="https://user-images.githubusercontent.com/5732209/29456289-e679c754-840c-11e7-8455-21d2e53895bc.png">

Dan's actually asked me about it 4 times, but each time my answer is that it hasn't been done yet as it isn't a priority

**Comment by iteles** [comment]
It _is_ a priority. 

There has literally been _one_ thing that is higher priority than this for months, which is something we discussed as a key part of what was needed on 31st January: https://github.com/dwyl/hq/issues/321

**That is still a higher priority.**

I also agree that seeing as this was opened as a priority 2 in March, we need to understand exactly why the priority of this wasn't respected and why it has taken us this long to get around to it.

A time estimation would be a great start to understand where it can be fit in.

**Comment by markwilliamfirth** [comment]
@iteles because there are 63 priority 2 issues in HQ alone (ignoring other repos e.g. focus hub etc)

The priority-2 label doesn't really mean much when there are so many. The only thing we can go by is the projects log and as you can see it keeps getting pushed back as more urgent things pop up and move in front of it

I think we need to agree a deadline for when it should be done by and stick to it

**Comment by iteles** [comment]
The deadline for this is after #321 is complete 👍

**Comment by iteles** [comment]
@markwilliamfirth I need to meet with @sofer on this in the next 2 weeks, so the priority on this needs to rise.

Is it realistic to please carry out step 1 of the checklist in the top comment of this issue (or any other methodology you see as more efficient over filling out that spreadsheet) **by the end of this week** so that we have an idea of roughly how much we need to settle and can also determine before I meet with Dan what actions are needed to guide the conversation that we have?
e.g. I need to respond to #373 , we might need to run off https://github.com/dwyl/hq/issues/272#issuecomment-286680668 etc

**Comment by iteles** [comment]
I'm assuming the answer to my question directly above this was 'no', rather than what was implied by the labels which is that it was both doable and in progress?

**Comment by markwilliamfirth** [comment]
@iteles this is in progress - I've already discussed this with Dan separately. if there is a deadline for this completion please let me know

**Comment by iteles** [comment]
I'm not sure I understand your comment @markwilliamfirth.

My question above was what was a realistic timeline for to "carry out step 1 of the checklist in the top comment of this issue (or any other methodology you see as more efficient over filling out that spreadsheet)".

**Comment by markwilliamfirth** [comment]
We're not actually going to solve this via the old spreadsheet - this requires getting Xero completely in order (which I've almost done) and then doing some weird Xero magic - the dependency is here because i'm currently in contact with Xero as our account balances don't match

**Comment by iteles** [comment]
@markwilliamfirth Very excited to hear Xero is almost completely in order! Is this related to #383 ? 
Where are you tracking your progress on that?

**Comment by iteles** [comment]
Any luck with Xero? They seem slow on the resolving of issues 😕

**Comment by iteles** [comment]
@rub1e Thanks for completing this in one day 🎉 

Figures have been sent to @sofer, invoice sent to us and paid 👍
