### ISSUE TITLE
About Contributing and Licenses

### ISSUE THREAD

**Issue by tunnckoCore** [dwyl/hq#273]
Heya, @dwyl/core and @dwyl/ateam  ! :star2: 

I'm just reading the dwyl/contributing one more time.. and just realized that most of the packages/modules/repos don't have CONTRIBUTING.md (or .github/* dir), nor license in the files and their README.md

I'm not lawyer and i even don't care about such things, because all of my online work is totally MIT since 2013 when i jumped in NodeJS. But i'm thinking that it is very important for some people. At least we must add CONTRIBUTING.md which linsk directly to [that awesome guide - dwyl/contributing](https://github.com/dwyl/contributing). The easiest and coolest thing of having exactly that named file in the root is that there appears link to it when you going to create a new issue.

I thought that in my contributing guide I have a link to it, but sadly I don't have. My [current contributing guide](https://github.com/tunnckoCore/stacktrace-metadata/blob/master/CONTRIBUTING.md) for last 5-6 or more months is mainly jonschlinkert's - [Idiomatic Contributing](https://github.com/jonschlinkert/idiomatic-contributing) and few parts of some other guides, which i linked at the bottom. The cool thing here is that I always add one very short dev-oriented part [in the readme's Contributing section](https://github.com/tunnckoCore/stacktrace-metadata#contributing). 

My CONTRIBUTING.md guide is pretty short and not so long, mainly oriented to a bit more experienced devs and people that **know** what they do - sorry but i don't need everyone to step into and spam if he can't _at least_ read 100-200 lines OR AT VERY LEAST just the headings and bold words or _VERY VERY_ LEAST the `Contributing` section. :)

So yea, just some thoughts. I'm just surprised that dwyl/contributing is almost nowhere linked.

**Comment by iteles** [comment]
@tunnckoCore We couldn't agree more!

This is a task in the backlog, we're just struggling for the time to get round to adding it everywhere. We were just discussing it last week, great minds think alike :wink:

**Comment by nelsonic** [comment]
@tunnckoCore we are adding a `CONTRIBUTING.md` to our repos as we go ... 
see: https://github.com/search?q=org%3Adwyl+add+contributing.md&type=Issues

**Comment by tunnckoCore** [comment]
Hm. Actually yea, it sounds like a good strategy since most of the repos are not actual packages but some learn-* and etc stuff. It's not like my case, where most of my repos are actual packages and i have included very general CONTRIBUTING.md at the very beginning, even in the [scaffold template step](https://github.com/tunnckoCore/charlike) using `npm.im/charlike` ;p

As side note: Not to mention that most of my packages are [at least with 400% coverage](https://twitter.com/tunnckoCore/status/841768516965568512) (tweet).

**Comment by tunnckoCore** [comment]
Btw, i'm going to update my contributing guide template to a bit more simplified version of dwyl's, because it is bit too much for me, but it is awesome because the images, emojis, headings and bolds.
