### ISSUE TITLE
Organisation-wide view so everyone knows what dwylers are working on

### ISSUE THREAD

**Issue by iteles** [dwyl/hq#275]
People are always interested in what everyone else in dwyl is working on.

It would be good to have a central location which is updated once but everyone can check.

Requirements:
+ Quick to update (including individual sprints for a quick view of critical project times  - i.e when not to interrupt)
+ Accessible by everyone in dwyl
+ Editable by anyone in dwyl
+ Data to capture:
  + Client and project name
  + Developers working on it
  + Sprint start and end dates

**Comment by markwilliamfirth** [comment]
@iteles does the resourcing sheet work for you to solve this problem?

https://docs.google.com/spreadsheets/d/1HejQid3ZqaIK2iYzsv4SrD40UGWYa7qm1YSvMdcWfME/edit#gid=1068312920

**Comment by iteles** [comment]
Solving this in https://github.com/dwyl/product-roadmap/issues/8
