### ISSUE TITLE
Adding detail to dwyl's activities

### ISSUE THREAD

**Issue by iteles** [dwyl/hq#277]
We have information on what dwyl is doing now and next scattered across multiple repositories (and in my brain). It's time to make a concerted effort to bring this together ahead of #213.

+ [ ] Transfer dwyl's mission and vision into this repo so that it's clear
+ [ ] Add detail to each of the 4 key segments of dwyl

**Comment by markwilliamfirth** [comment]
This was done here https://github.com/dwyl/phase-two/blob/master/plan.md
