### ISSUE TITLE
Potential new project | LDMW

### ISSUE THREAD

**Issue by iteles** [dwyl/hq#278]
This project would be in partnership with MW, our current clients for https://github.com/healthlocker. 

We have provided some technical information and are expected to find out whether this will go ahead this week (20th March onwards).

**Comment by shouston3** [comment]
I'd love to be involved with this project

**Comment by jackcarlisle** [comment]
I'm keen for this as well, would you be willing to try someone working on this remotely?

**Comment by iteles** [comment]
At this stage I have no idea what the budget or requirements are but good to know there's interest! I'll have a chat with you guys when I know more :blush:

**Comment by sohilpandya** [comment]
Anyone need an apple watch app in the future? 😆
