### ISSUE TITLE
Potential new project | CU evidence based research application

### ISSUE THREAD

**Issue by iteles** [dwyl/hq#280]
A repeat client has asked us to take a look into building an evidence-based research application to aid diagnoses for doctors.

This is a client with very little budget and a need for a fixed cost project where the application requires a fair amount of comprehension (and voice recognition).

+ [x] Initial call with PO to determine what needs to be done
+ [x] @iteles to put together short workshop proposal
+ [x]  Await answer from client on whether this can go ahead
+ [x] Hold workshop
+ [x] Create deliverable on what needs to be done and how long it would take
+ [x] Determine whether there is budget for this

**Comment by markwilliamfirth** [comment]
Evidence-based research application to aid diagnoses for doctors - so cool!

**Comment by iteles** [comment]
There are still two open items on this issue, opening again.

**Comment by markwilliamfirth** [comment]
I thought Simon is already working on this project - what's the update on this one?

**Comment by iteles** [comment]
What Simon (and I) are working on are the two open checkpoints in the list in the top comment 👍

**Comment by iteles** [comment]
Will go ahead on 17th July with @SimonLab and @Cleop
