### ISSUE TITLE
Group activity suggestions

### ISSUE THREAD

**Issue by katbow** [dwyl/hq#282]
Hey! I was thinking after the future of dwyl meeting about some activities we could all do together. @markwilliamfirth mentioned to me that I should make an issue here for them

Would anyone be interested in:
* A pub quiz/trivia night? Doesn't need to actually be at a pub, but could have a trivia night at dwyl hq! I've never done one before 😄 
* Escape room?! I'm not sure about the feasibility of this one as it might be quite expensive per person and is dependent on the group size that can participate.

**Comment by markwilliamfirth** [comment]
@katbow yes we should totally make both of these happen!! I'm on it 😄

**Comment by markwilliamfirth** [comment]
Closed in favour of
https://github.com/dwyl/events/issues/1
https://github.com/dwyl/events/issues/2
