### ISSUE TITLE
Rewrite and Review Supplier Agreement

### ISSUE THREAD

**Issue by ghost** [dwyl/hq#283]
Mark has written draft:
https://docs.google.com/document/d/1Le14_UyBBe-ADoCJS1yUvK266WE2ffETBnAVSadfM88/edit#

Inês to review

**Comment by markwilliamfirth** [comment]
Please note when I originally wrote the contract I defined working day as follows:

>“Working Day(s)” means eight (8) hours of accrued work by Supplier.

I have now updated this to:

>“Working Day(s)” means seven (7) hours of accrued work by Supplier.

**Comment by markwilliamfirth** [comment]
@iteles to review contract

**Comment by iteles** [comment]
Reviewed! And left comments.

Need to get this out to a client so please make it the top priority 👍

**Comment by markwilliamfirth** [comment]
@iteles I have replied to your comments in the doc

**Comment by iteles** [comment]
@markwilliamfirth Have resolved the majority of the questions and replied to your replies 😉

**Comment by markwilliamfirth** [comment]
@iteles I have replied to your replies to my replies 😉

**Comment by markwilliamfirth** [comment]
@iteles I think it is only clause 16 that requires attention now

**Comment by markwilliamfirth** [comment]
Mark to add no approaching clause

**Comment by markwilliamfirth** [comment]
@iteles this was actually already included (clause 33)

>No Party to this Agreement will, during and for a period of six (6) months following the expiry or termination of this Agreement, induce any employee of the other Party who was directly involved in the performance of this Agreement, to leave such other Party’s employment.

Let me know if you'd like it changing

Next step in this issue is for you to review clause 16 and let me know if you're happy with it

**Comment by iteles** [comment]
@markwilliamfirth Added a response, could you please check this out and we'll send it out to a client today?

**Comment by markwilliamfirth** [comment]
@iteles I responded back

**Comment by iteles** [comment]
And me :)

**Comment by markwilliamfirth** [comment]
@iteles I've updated - if you're happy then please send me the client details and I can create the first contract

**Comment by iteles** [comment]
If we're going to go this route, I think we want to start with OSS as the default as it better reflects our values. I've suggested:
> The code and documentation created by the Supplier for the Project will be covered by an open source license (https://opensource.org/licenses) to will be mutually agreed by both Parties. Should the Client decide that the Project will be closed source, all Intellectual Property Rights associated with the Project shall be owned by the Client. The agreed Intellectual Property Rights for the Project are outlined in Schedule 1. 

Will send you the details

**Comment by markwilliamfirth** [comment]
Have reworded slightly

>All Intellectual Property Rights associated with the Project shall be owned by the Client, except the code and documentation created by Supplier, to which the client hereby expressly agrees and understands that it will be assigned by default to an open-source license (https://opensource.org/licenses), which will be mutually agreed by both Parties. The Client may opt-out of making the Project open-source and thus retain complete Intellectual Property Rights, confirmation of the Project’s open/closed source shall be outlined in Schedule 1.

**Comment by iteles** [comment]
Open source doesn't have a hyphen, but other than that, this is fine. 
I would make the last section of the last sentence a sentence in its own right.

**Comment by markwilliamfirth** [comment]
Updated 👍

**Comment by iteles** [comment]
@markwilliamfirth This is really not as important as https://github.com/dwyl/process-handbook/issues/35

**Comment by markwilliamfirth** [comment]
Yep - it's behind it in priorities - was just updating github as it was on my other todo list

**Comment by markwilliamfirth** [comment]
This is a p1 now after various frictions that have occurred with MV

**Comment by iteles** [comment]
https://github.com/dwyl/hq/issues/321 is a **higher priority than this**. I'm not sure how useful it is to move everything else to a p1 until that is complete.

**Comment by markwilliamfirth** [comment]
- [ ] Include clause allowing time for dwyl team retrospective

**Comment by iteles** [comment]
?! A retrospective is an _essential_ part of the agile development process. It's never a question.
Are you proposing we add all of our ceremonies into our contracts?

**Comment by markwilliamfirth** [comment]
Interest on late payments

**Comment by iteles** [comment]
Is this a suggestion that charging interest on late payments should be added to our contracts with clients in light of the 2 client non-payment of invoices and 1 client who is paying us 3 months past the due date of invoices?

It would be a great idea to do a little research and suggest a sensible (spurs action but doesn't offend) interest rate 👍

**Comment by iteles** [comment]
Closing in favour of #459
