### ISSUE TITLE
Review and rewrite our Services Contract Template

### ISSUE THREAD

**Issue by iteles** [dwyl/hq#286]
Recent experience has taught us that we need to deal with two additional things in our contracts:
+ Projects cannot be put 'on hold' without warning - there needs to be a notice period if it's to be paused or end early
+ Bug fixing - we need to define how we deal with any bugs after a project officially finishes (@nelsonic to provide thoughts on this)

Making this a P1 for the LDMW contract

**Comment by markwilliamfirth** [comment]
I thought the reason we work in sprints is to allow the customer to end at any sprint period? Or do you mean halfway through a sprint?

**Comment by iteles** [comment]
@markwilliamfirth The reason we work in sprints is to allow a tight feedback loop with user testing and create maximum value in the product we're delivering. It also allows our clients the ability to extend for further sprints if they need them.

But if we're contracted for a period of x number of sprints, we can't afford to at a moment's notice have that cut off half way through our contract or we'd need to inflate our prices to cover the risk of the added uncertainty (which we don't want to do).

**Comment by markwilliamfirth** [comment]
Oops

I better change our about dwyl doc then

<img width="327" alt="screen shot 2017-04-20 at 10 23 33" src="https://cloud.githubusercontent.com/assets/5732209/25223510/76119058-25b3-11e7-97bc-1dac39da4a92.png">

what should this say?

**Comment by iteles** [comment]
It's not about walking away, I think that sends totally the wrong message.

> that allow any future developers or your in-house team to frictionlessly develop your application or website further

**Comment by markwilliamfirth** [comment]
@iteles what should the notice period be? 1 month? 2 Sprints?

@nelsonic do you have any thoughts about bug fixing? (see @iteles comment in original posting)

**Comment by nelsonic** [comment]
We are asking the _wrong_ question. 
All contracts should have start & end dates in them. 
Those dates should be respected.
"Pausing" a project should not be a thing unless there is a serious funding issue.
If there is a "funding gap" we should be made aware of it 2 weeks in advance in writing.
@iteles what happened to the "SLA" we created last year ? (_when we were meant to be on holiday_)
Fixing "bugs" should be covered in the SLA.
Accepting that something is a "bug" should only occur if feature does not function as specified.
If a specific browser and resolution was not specified in the original requirement then it's not a "Bug" if the app does not look _perfect_ at that resolution. (_for example_)
That is classified as "follow up" work and is paid at the standard rate.

**Comment by iteles** [comment]
Completely agree on the start and end dates (or at least the number of continuous working days).

There is no discussion around the definition of a 'bug'. I completely agree.
If you think about it from a client perspective - if they put together a clear user story and acceptance criteria and when we build it, it doesn't function as expected (e.g.  we build a feature which should only be available to one type of user but there's a permissions _bug_ and all users see it) - they need to know that they won't pay out more money for a 'mistake' we made just because it was nearing the end of the project. 
We _obviously_ want to manage this on our side and minimise the possibility of breaking changes in the final days of a project, but there's a case to provide an assurance to clients.

**Comment by nelsonic** [comment]
@iteles it sounds like the _symptom_ here is _incomplete_ acceptance criteria
and inadequate ["DoD"](https://github.com/dwyl/definition-of-done) for the project.

**Comment by markwilliamfirth** [comment]
@iteles advised 10 days notice period

**Comment by markwilliamfirth** [comment]
@iteles these are already accounted for in clauses 12 and 25 - please let me know if any changes are required in this issue: #283
