### ISSUE TITLE
Protecting master branch

### ISSUE THREAD

**Issue by Jbarget** [dwyl/hq#287]
It might be worth making `master` a protected branch especially for projects where pushing to master runs a webhook to heroku.

Not sure if known: Settings ---> Branches ---> 
![screen shot 2017-04-25 at 14 30 14](https://cloud.githubusercontent.com/assets/11725595/25387802/f87a549e-29c3-11e7-8682-8d2350a0d2a9.png)

**Comment by iteles** [comment]
@Jbarget Totally agree we should do this by default on all new repos! https://github.com/dwyl/learn-html5/issues/6

Linked to https://github.com/dwyl/contributing/issues/29

Is our contributing repo (linked from start-here) repo the best place to keep this info?

**Comment by iteles** [comment]
Moved into https://github.com/dwyl/contributing/issues/29 👍 Thanks @Jbarget !
