### ISSUE TITLE
Google Developer Expert (GDE)

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hq#29]
https://developers.google.com/experts/become-an-expert
Should we?

**Comment by markwilliamfirth** [comment]
@nelsonic ok to close?

**Comment by markwilliamfirth** [comment]
Moved to https://github.com/nelsonic/nelsonic.github.io/issues/422

**Comment by iteles** [comment]
@markwilliamfirth Please explain your reasoning here.

**Comment by markwilliamfirth** [comment]
@iteles GDE certification is attributed to the individual, not the org - so it is for Nelson to decide if he wants to apply for it or not

**Comment by iteles** [comment]
To me, the question `Should we?` along with the `help wanted` and `question` labels imply that Nelson was not thinking about this for himself but for people within the context of dwyl generally.

Interpretations vary I suppose.

**Comment by markwilliamfirth** [comment]
Looking at the criteria the only person who seems like they might be able to qualify is Nelson
