### ISSUE TITLE
5 key things for dwyl services sustainability

### ISSUE THREAD

**Issue by iteles** [dwyl/hq#290]
+ [ ] 1. Sales process and knowledge within team for repeatable and predictable sales
+ [ ] 2. Processes for all of our organisational tasks, so projects can be run without constant oversight
+ [ ] 3. Skilled dwylers in their field who have worked with us on projects before and we can both trust to run a project themselves and introduce new people to the way things are done
+ [ ] 4. Knowledge sharing system that actually _works_ so that every dwyler can speed up their learning
+ [x] 5. Competent and proactive ops person who can work quickly and prioritise effectively

**Comment by nelsonic** [comment]
@iteles are these ordered in _priority_ order? 
(_and could we update from `<ol>` to a checklist so we know when they are `done`_?)

**Comment by nelsonic** [comment]
@iteles _when_ do you have time to sit down and `define` our ***Sales Process***?
https://github.com/dwyl/learn-sales

**Comment by iteles** [comment]
Was my plan for today (Saturday) :+1:

**Comment by nelsonic** [comment]
@iteles Let me know when you're ready start. (_I'm at my desk working, but ready when you are!_) ⌛️

**Comment by markwilliamfirth** [comment]
Closing in favour of

1- https://github.com/dwyl/process-handbook/issues/45
2- https://github.com/dwyl/process-handbook/issues
3- http://dwyl.com/team
4- https://github.com/dwyl/
