### ISSUE TITLE
The Crystal Maze - Team building?

### ISSUE THREAD

**Issue by harrygfox** [dwyl/hq#292]
# Why?

here's why:
![](https://static.independent.co.uk/s3fs-public/thumbnails/image/2015/06/10/09/CrystalMAze.jpg)
![](https://www.thesun.co.uk/wp-content/uploads/2017/01/nintchdbpict000262996409.jpg?strip=all&w=960)
# The Crystal Maze Experience

Website: www.the-crystal-maze.com

# Where is it?
<img width="537" alt="screen shot 2017-05-05 at 14 19 49" src="https://cloud.githubusercontent.com/assets/7805691/25747239/b7c9b2ae-319e-11e7-826e-d77e27099143.png">

# Any Gifs?

Yes
![crystal-maze-epic-fail-o](https://cloud.githubusercontent.com/assets/7805691/25747293/ee20c662-319e-11e7-927f-2ff16f9beada.gif)

**Comment by markwilliamfirth** [comment]
If you're interested in attending please like the post above so we have an idea of how many people would want to do it!

**Comment by nelsonic** [comment]
@harrygfox that looks _amazing_!!!! 😮 
![amazing](https://media.giphy.com/media/3osxY7xVVSgMfAPZ16/giphy.gif)

**Comment by nelsonic** [comment]
@harrygfox _please_ finalise numbers by the end of next week and book it! 📆 
Make sure any current and "alum" @dwyl members are invited/aware 📣  🔈 💬 
so we can get as many people involved as _possible_ cause it's going to be _awesome_!!! 🎉

**Comment by nelsonic** [comment]
Seriously, I feel like I missed out on some _epic_ entertainment by not having a TV in the 90's!
It's OK cause I can "catch up" now on YT:
[![image](https://cloud.githubusercontent.com/assets/194400/25768314/1186698a-31fa-11e7-8c09-928d90d17867.png)](https://www.youtube.com/watch?v=TrDUdOgpNsI)
https://www.youtube.com/watch?v=TrDUdOgpNsI

**Comment by harrygfox** [comment]
@Jbarget @markwilliamfirth @naazy @nelsonic 
@jackcarlisle @JMurphyWeb @harrygfox @sohilpandya 

These are the names as of right now. That makes 2 teams of 4. 
_The Experience offers spaces for a maximum of 4 teams of 4._

**Comment by markwilliamfirth** [comment]
@harrygfox isn't it 8 per team?

**Comment by harrygfox** [comment]
@markwilliamfirth Yes you're right - updated message above

**Comment by Cleop** [comment]
Only just stumbled across this... Has this happened? (If so... photos?!) If not, when can this happen :pray: ?!!! I think there are more likes now than the initial 8.

**Comment by markwilliamfirth** [comment]
@Cleop hasn't happened yet - have pasted info below in case anyone is keen to lead on booking / arranging:

events@the-crystal-maze.com | 0207 278 2271 | www.the-crystal-maze.com
CrystalMaze@seetickets.com

https://thecrystalmaze.seetickets.com/tour/the-crystal-maze

We are very pleased to receive your team event enquiry. Please feel free to give me a call on 0207 278 2271. In the meantime, here is some more info on The Maze…
 
The bespoke takeover days at The Maze run Tuesday-Friday from 9am-2.00pm. All regular event facilities are included as standard such as; AV & presentation facilities and of course full catering (breakfast & lunch). There is adequate space in the bar area to seat all attendees. And we do of course have a fully stocked bar but there is strictly no drinking before going into The Maze.
 
The minimum group size per private event is 32 people and a capacity of 120 pax per private day. The maximum we can run through The Maze at any one time is 40 pax. The Maze will take roughly 1.5 hours to complete per group, but as you have the maze to yourself all morning there is the option of additional time in the game zones.
 
As you can imagine we have had 100's of enquiries for corporate/private events. If you have a specific date in mind, please let me know ASAP. What I can then do is check the diary and pencil you in temporarily while we work out the finer details.
 
You can find a downloadable PDF version of our Training & Team-Building Brochure by clicking here. It has all the info about the day including pricing on the penultimate page. You can also see a snazzy digital version by clicking the following link: https://issuu.com/littlelionentertainment/docs/the_crystal_maze_brochure

Harry Blaiberg - Head of Events – THE CRYSTAL MAZE

**Comment by markwilliamfirth** [comment]
Closed in favour of https://github.com/dwyl/events/issues/15
