### ISSUE TITLE
Why is being process-driven important?

### ISSUE THREAD

**Issue by iteles** [dwyl/hq#294]
Understanding the value of process is essential for people develop the impetus to follow it. 

>  We want to emphasize repeatability and consistency in everything we do, ensuring highly sustainable and repeatable results

+ Ensures consistency of quality with the least amount of conscious effort once internalised
+ Everyone on the team knows exactly what is happening (or how to check) what is happening without having to be co-located or interrupting their team mates.
+ Removes the dependency on specific individuals in the organisation who are the 'only ones who know how things are done' and paves the way for self-managing teams
+ Removes the need for specific people to constantly 'check up on' and 'nag' teams to follow process - neither the team or the person doing the nagging enjoy this interaction

Please feel free to add to this list!

**Comment by iteles** [comment]
Checklists (processes) in hospitals in the US brought down surgical death rates by 47%.
https://youtu.be/L3QkaS249Bc?t=15m17s

Even cowboys use processes!  
https://youtu.be/L3QkaS249Bc?t=17m36s

<img width="655" alt="screen shot 2017-05-13 at 08 37 39" src="https://cloud.githubusercontent.com/assets/4185328/26023605/0221d146-37b8-11e7-944b-551b746c7fb7.png">

**Comment by markwilliamfirth** [comment]
closed in favour of https://github.com/dwyl/blog/issues/25
