### ISSUE TITLE
New repo for ops / shareable content

### ISSUE THREAD

**Issue by markwilliamfirth** [dwyl/hq#298]
The HQ repo is meant to be the home of all of dwyl's operations and administration, but at the moment it's used for other things too:

e.g. podcast and book suggestions
https://github.com/dwyl/hq/issues/77

This means these issues can never be closed, which affects ops task tracking analysis

@iteles I think it might be a good idea for us to either open a new repo for ops or open a new repo for content that needs to be shared with the team - what do you think?

**Comment by iteles** [comment]
IMO, hq is the _right_ place for ops, admin and practices around running the _organisation_. 
In the case of the example above, this is related to running the company and can be closed as soon as someone makes notes.

You're right though, the blog issues for example can probably now be moved to the dwyl-site or a blog repo (let's figure this out when we redo the site in the coming couple of weeks) and there are other things that can be moved out of this repo, e.g. https://github.com/dwyl/hq/issues/287

If we have enough awesome resources that aren't related to other repos we have and need a home, absolutely!

We should do a quick sweep!

**Comment by markwilliamfirth** [comment]
@iteles 

what do we do in these cases?

https://github.com/dwyl/hq/issues/169
https://github.com/dwyl/hq/issues/144

and if there are future recommendations for reading / watching / sharing content?

**Comment by iteles** [comment]
Good examples, we should move that info into here: https://github.com/dwyl/start-here/blob/master/books-to-read.md and close the issues 👍

**Comment by markwilliamfirth** [comment]
closing as blog issues were moved out
