### ISSUE TITLE
The World's Most Comfortable Chair

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hq#30]
https://youtu.be/W3ei3XcB-uw?t=10s
http://themostcomfortablechair.com
_are you thinking what I'm thinking_...?

**Comment by iteles** [comment]
Things have moved on slightly! Worth researching this again methinks.

**Comment by nelsonic** [comment]
Agreed. We need to figure out if we can get _good_ (_ergonomic_) chairs without breaking the bank while still encouraging people to use the Standing Desks, take regular breaks and not eat in front of their computers... 

![image](https://cloud.githubusercontent.com/assets/194400/21576916/15bbc1ec-cf3c-11e6-88c0-6682f5805da6.png)

**Comment by markwilliamfirth** [comment]
Discussion moved to Focus Hub

**Comment by nelsonic** [comment]
_Where_ on Focus Hub...?
![image](https://cloud.githubusercontent.com/assets/194400/26148276/0b7f589c-3aee-11e7-94b9-0603cab763af.png)
How difficult is it to _link_ to the new issue?
_several_ people have mentioned the "_uncomfortable_" chairs @ FH as the "_reason_" they prefer to work elsewhere. we need to _fix_ this. Chairs (_or standing desks_) are a Hygiene Factor and should thus be a `Priority-1`.

I _agree_ that my link to the "Most Comfortable Chair" for the purposes of our _current_ Office.
A more _appropriate_ chair would be:
https://www.andrewsofficefurniture.com/lugo-mesh-operator-chair-white-base
![image](https://cloud.githubusercontent.com/assets/194400/26148427/881e57a4-3aee-11e7-8e9c-c3ebabe5e26f.png)

What is _required_ is:
+ [ ] Ask current (_paying_) members of FH if they are satisfied with the _existing_ chairs.
+ [ ] If not, ask them what the _best_ chair they have ever used is/was and why.
+ [ ] Decide if it's worth investing in the _best_  

if we invest, the asset(s) would remain property of the company (_even if we move from 16 Palmers Road_) we need to be _cautious_ of "_over spending_" the way (_most_) "_funded_" startups do.
But, under-spending on chairs is a **_huge_ false economy**!

**Comment by markwilliamfirth** [comment]
>several people have mentioned the "uncomfortable" chairs @ FH as the "reason" they prefer to work elsewhere. we need to fix this. Chairs (or standing desks) are a Hygiene Factor and should thus be a Priority-1.

@nelsonic if you think this is a priority-1 please make the issue, I don't think this is a priority and we don't currently have the budget for this

Chairs are part of our offering: https://github.com/dwyl/focushub/issues/30

**Comment by nelsonic** [comment]
Dedicated chairs issue: https://github.com/dwyl/focushub/issues/79
