### ISSUE TITLE
Other (Non Free) Coding Bootcamps are using our Learning Materials ... How do we feel about that?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hq#303]
We have known for a `while` that other "Coding Bootcamps" are using the @dwyl Learning Materials for their "curriculum" ... (_we have had quite a lot of "thanks" from members of some of the **Non-Free** coding academies when attending meetups etc._) But this is the _first_ time someone has gone "_on the record_" ...

see: https://github.com/dwyl/learn-tape/pull/13/files
![image](https://cloud.githubusercontent.com/assets/194400/25845249/1dd64a9a-34a5-11e7-899b-49948784046a.png)

"Iron Yard" charges it's students up to ***$13,900*** https://www.theironyard.com/tuition
![image](https://cloud.githubusercontent.com/assets/194400/25845270/35a07132-34a5-11e7-937f-4dda6cb3f279.png)

How do we _feel_ about our learning materials being used in a ***Non Free*** "coding bootcamp" ?

**Comment by iteles** [comment]
Our entire philosophy is based around open source and that learning how to code should be accessible. $14k for a bootcamp is not accessible. 
I completely object to this (and did not merge the PR when I had the opportunity to).

**Comment by nelsonic** [comment]
@iteles I merged the PR to "lock-in" this _reality_ for discussion purposes. 
We can _remove_ it in a future PR, don't worry, we _definitely_ don't want to _promote_ `PAID` Bootcamps!!

**Comment by markwilliamfirth** [comment]
Is it possible to change the open-source license or put a disclaimer etc that prevents the use of the materials for paid teaching?

**Comment by iteles** [comment]
@markwilliamfirth There are licenses that prevent commercial use for sure (@nelsonic also did a fair amount of research on this for https://github.com/dwyl/intellectual-property and it's definitely the way I think we should go for our products).

I'm not sure we want to prevent people from using our materials to _learn_ (after all, using one of our repos means that those same people could independently learn with our other repos), I'm just vehemently against actually _promoting_ these 'bootcamps' in our materials.

**Comment by markwilliamfirth** [comment]
Iron Yard has closed now - closing this issue
