### ISSUE TITLE
SPRING (Super Global) Project 

### ISSUE THREAD

**Issue by markwilliamfirth** [dwyl/hq#309]
"Sorry, didn’t meant to drop the ball on this one…and now we are off to Kenya this week!
 
Would love to meet and talk more. Are you available at the beginning of June by chance? I would potentially have my colleague Roo Rogers with me also (I think I mentioned him to you when we met – he leads a team that works and delivers all HCD content and modules for SPRING ventures).
 
Let me know what dates in June would suit. Preferrably sometime in week of 8th ?"

@iteles do we want to pursue this? They didn't come back to us with the info you requested 😞

**Comment by iteles** [comment]
@markwilliamfirth Let's ask them for the information we needed from them and let them get back to us... Assigning back to you as you're the main contact for this account 👍

**Comment by markwilliamfirth** [comment]
@iteles I can't remember what it was that was requested from them - do you have it in your notebook?

**Comment by markwilliamfirth** [comment]
@iteles what do you think about this? Alina sent a follow-up on 23rd May and Sam emailed yesterday

**Comment by iteles** [comment]
@markwilliamfirth I think we need a 20min follow up call with Alina now that she's been out there to get info on what the things they're expecting us to build is and what expectations they have of what can actually be built in that timeframe.

Ultimately, they sounded like they were going to struggle for budget. Was this your impression too?

Let's have a _quick_ call with them and lock down whether we can actually help or whether we can recommend someone like #344

**Comment by markwilliamfirth** [comment]
Sent a follow up to alina

**Comment by markwilliamfirth** [comment]
<img width="549" alt="screen shot 2017-06-22 at 19 58 19" src="https://user-images.githubusercontent.com/5732209/27450919-2dfa3474-5785-11e7-8735-9c628b056960.png">

bit odd

**Comment by iteles** [comment]
Seems ok, she mentioned there were a few different interested parties, her employment has probably just been shifted around for financial purposes 👍

**Comment by markwilliamfirth** [comment]
Have chased Alina

**Comment by markwilliamfirth** [comment]
We're not going to pursue this one
