### ISSUE TITLE
Book flights for Web Summit

### ISSUE THREAD

**Issue by iteles** [dwyl/hq#31]
Linked to https://github.com/dwyl/hq/issues/28

**Comment by iteles** [comment]
@nelsonic Note the various airports and times.

**Option 1: Sat evening flight to Dublin from LST**
<img width="380" alt="screen shot 2015-10-19 at 18 32 54" src="https://cloud.githubusercontent.com/assets/4185328/10585618/040496f0-7690-11e5-8234-20b498453b77.png">

**Option 2: Sat morning flight to Dublin from LST**
<img width="379" alt="screen shot 2015-10-19 at 18 30 31" src="https://cloud.githubusercontent.com/assets/4185328/10585619/0404cdfa-7690-11e5-97d8-ef1fbd61c474.png">

**Option 3: Sat evening flight to Dublin from LGW**
<img width="228" alt="screen shot 2015-10-19 at 18 25 33" src="https://cloud.githubusercontent.com/assets/4185328/10585620/040773fc-7690-11e5-970a-6bfd071af9d2.png">

**Option 4: Sat very early morning flight to Dublin from LHR**
(Note this is the price of the single tickets):
<img width="972" alt="screen shot 2015-10-19 at 18 23 57" src="https://cloud.githubusercontent.com/assets/4185328/10585621/0408336e-7690-11e5-9315-277b700a19fa.png">

**Option 5: Sat decent morning flight to Dublin from LGW**
<img width="383" alt="screen shot 2015-10-19 at 18 39 28" src="https://cloud.githubusercontent.com/assets/4185328/10585764/de52f2fc-7690-11e5-81a6-8dcf79afd0e6.png">

**Comment by nelsonic** [comment]
When do *you* want to go/return?

**Comment by iteles** [comment]
I like the idea of going a couple of days before to get settled in and be able to 2 days of focuses work outside our usual environment. Then one day after to see Dublin/ catch up with people.

**Comment by iteles** [comment]
Booked. Passport information entered but can't check in until 24th.
<img width="356" alt="ryanair flight reservation confirmation" src="https://cloud.githubusercontent.com/assets/4185328/10619395/60fee800-776d-11e5-80ea-7d63bf071390.png">

**Comment by iteles** [comment]
Done, checked in both ways.
