### ISSUE TITLE
RSN project

### ISSUE THREAD

**Issue by markwilliamfirth** [dwyl/hq#310]
A potential new project creating a new e-commerce and learning application for a crafts charity. 
+ [x] Review documentation
+ [x] Initial call with board member
+ [x] Initial call with CEO
+ [x] Write and send proposal to RSN

**Comment by markwilliamfirth** [comment]
@iteles latest from Susan:
Dear Mark
We are currently trying to appoint a project manager to oversee all this so please wait until we have the person in post.
Susan

**Comment by iteles** [comment]
@markwilliamfirth :+1: Updated the top comment to remove potential client name and to reflect the work that has been done so far.

**Comment by markwilliamfirth** [comment]
Update from Susan after enquiring about new PM:
Alas we wanted to appoint someone who then turned it down as the pre-advertised salary was less than she wanted!
Sorry bit frustrated by the above so, no nothing has moved forward.

**Comment by nelsonic** [comment]
@iteles depends on #321 👍

**Comment by iteles** [comment]
@markwilliamfirth Hiring a 'PM' full time for this seems like overkill for what _I_ understand to be the scope of this project 😳 

http://www.royal-needlework.org.uk/images/uploaded/Documents/Job%20Descriptions/IT%20Project%20Manager%20Royal%20School%20of%20Needlework.pdf

**Comment by markwilliamfirth** [comment]
@iteles do you think we should advise her of that? I get the impression that she doesn't like the idea of being (or have the time to be) the product owner and giving feedback / doing the testing

**Comment by iteles** [comment]
Removed priority label as we can't do anything about this until we hear back and seeing `p1` seems like an unnecessary stressor 😉

**Comment by markwilliamfirth** [comment]
I've sent a follow-up to Susan

**Comment by markwilliamfirth** [comment]
Susan: "Our new project manager starts on Monday and then she has to get her head around everything. Your proposal is in the bundle ready for her."

**Comment by iteles** [comment]
@markwilliamfirth Did we hear back from them?

**Comment by markwilliamfirth** [comment]
They said they're going to go with another company

**Comment by iteles** [comment]
That's useful information, did they say why?

**Comment by markwilliamfirth** [comment]
We missed the deadline for the resubmission of the detailed system requirements quote and the project manager received a number of quotes to compare from a bunch of other companies

[RSN System Requirements 19.06.17 (1).xlsx](https://github.com/dwyl/hq/files/1191165/RSN.System.Requirements.19.06.17.1.xlsx)

**Comment by iteles** [comment]
😕 Did we _know_ there was a detailed system requirements submission needed?

**Comment by markwilliamfirth** [comment]
Yes, this was sent to us after the RSN project manager took over, but by the time I had any time to devote to it Kat was already on holiday and unable to do quotes and I couldn't get through to Nelson so it wasn't possible to get new quotes and a newly written proposal together in time for the deadline

**Comment by iteles** [comment]
I will add better planning to the list for https://github.com/dwyl/process-handbook 👍 
This should be as simple as: when there is an established deadline, take 10 minutes to check the schedules of the people you need for holidays/particularly busy periods and form a plan B if needed. This should also help prevent things like the almost 3 week delay on getting this proposal out: https://github.com/dwyl/hq/issues/348

**Comment by markwilliamfirth** [comment]
I actually did ask Kat early on and she said she could do it, but then later said she couldn't when it came to it due to family commitments. I wouldn't say 348 are planning failures - I think they're capacity issues
