### ISSUE TITLE
dwyl tshirt for Noga

### ISSUE THREAD

**Issue by markwilliamfirth** [dwyl/hq#311]
Noga wanted a dwyl tshirt! Preferrably a green in medium size
do we have one in hq, @iteles?

**Comment by iteles** [comment]
No! No one wanted green ones so I had a single green made for me!

Unless @nogainbar wants a used t-shirt, it can't be green until our next batch 😞 
But I'm seeing her tomorrow so will bring all the mediums 👍

**Comment by iteles** [comment]
@nogainbar All our t-shorts are at Focus Hub this week! Please go take a look at the available colours and grab any you want!

We should also be getting some new ones made soon :blush:

**Comment by markwilliamfirth** [comment]
Closing as I believe Noga got this
