### ISSUE TITLE
Where to Capture your Learning when working on a @dwyl Project?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hq#314]
This question has come up again in (chat) so it's time to open a issue.

## Situation

So you are working on a @dwyl project and you're learning new things, 
_where_ `should` you be raising issues while you are learning and adding detail?

We have _several good_ examples of this from the _many_ client projects, here's one:
+ The Project: [github.com/numo-labs/aws-lambda-helper](https://github.com/numo-labs/aws-lambda-helper/graphs/contributors) ![star-count](https://cloud.githubusercontent.com/assets/194400/25893455/cafc8fac-356f-11e7-8793-9477eadba02e.png)
+ The Learning: [github.com/dwyl/learn-aws-lambda](https://github.com/dwyl/learn-aws-lambda) ![learn-lambda-star-count](https://cloud.githubusercontent.com/assets/194400/25893510/f83eed8e-356f-11e7-87e3-37e1342994a5.png)

We worked on _several_ AWS Lambda projects last year, if we had _scattered_ our knowledge across those various projects instead of _organising_ the knowledge in a _single_ "learn-..." repo, we would not have produced an _incredible learning resource for the community_!

## Why capture learning in a @dwyl repo?

There are _many_ reasons to capture learning in a @dwyl repo, I will summarise my "Top 5":
1. Learning is _never_ "***lost***" e.g: the client decides to make the repo `private`! 😢 
2. The learning is _much easier to **find**_ for _new_ people joining our team.
3. Keeping the learning _separate_ from the project forces us to make it "_generic_" and "_re-usesable_" rather than "_specific_". This greatly improves the "_on-boarding_" process for both the project you are _currently_ working on and _all future projects_!
4. More eyes will see your issue so if you are stuck and hoping to get `help` with something, putting your question/topic in a @dwyl issue will _instantly_ get more attention because _most_ of the 350+ people in the @dwyl community are _not_ watching _your_ project but _many_ of them _are_ watching the repo for the learning topic.
5. @dwyl is a "safe environment" where "_starter_" questions are _actively_ encouraged! 🎉 
It can often be "_intimidating_" to ask a question in a project (_or on StackOverflow_) because we _might_ not want to look "_unknowledgeable_" to our (_external_) Project Manger / Product Owner / Client / Stakeholders. But... if we don't capture the question and subsequent knowledge we are doomed to loose it so _all_ future team members will suffer! 😢

**Comment by Cleop** [comment]
@nelsonic thanks for this. Once you've created an issue on the appropriate dwyl learning repo and once you've added everything that is relevant to it. What should you do next?

- Leave the issue open?
- Close it? As your learning/ question is complete
- **Wait for it to be added to the README before it is closed?**... which creates the question - is all learning about a language useful in the README of a 'learn-X' readme. 

For example: 
https://github.com/dwyl/learn-elixir/issues/42 is an elixir related question however, I'm not sure how high priority using HTML entities might be for your average person learning their first elixir. Will adding all relevant language learnings to a README make them too long and put users off?

**Comment by nelsonic** [comment]
@Cleop if the knowledge is _useful_ to someone `else` in _any_ way, we should attempt to summarise it in the `learn-...` repo either with a _dedicated_ markdown file e.g: https://github.com/dwyl/learn-phoenix-framework/blob/master/heroku-deployment.md or adding to the readme: https://github.com/dwyl/hapi-auth-jwt2#generating-your-secret-key

Once the knowledge has ben _transferred_ to a `.md` file the _issue_ can be closed (_e.g: in the PR that creates the new knowledge_)

in your _specific_ example, HTML entities are _useful_ anywhere we need to display code on a web page. so writing a "quick" guide in a dedicated `.md` file e.g: `how-to-display-code-in-html-page.md` would be a _fantastic_ addition! 🎉 

The _reason_ for creating knowledge in `.md` files will be come _clear_ v. soon! 👍

**Comment by Cleop** [comment]
@nelsonic thanks!

**Comment by markwilliamfirth** [comment]
Moved to https://github.com/dwyl/process-handbook/issues/72
