### ISSUE TITLE
Activate Coop Bank Feed

### ISSUE THREAD

**Issue by markwilliamfirth** [dwyl/hq#317]
<img width="483" alt="screen shot 2017-05-15 at 10 16 43" src="https://cloud.githubusercontent.com/assets/5732209/26051750/09031fa2-395b-11e7-8946-4add91d1a68a.png">

**Comment by iteles** [comment]
:tada: Managed to get this done. At the time of writing, the feed isn't fully updated yet, but in the 5 minutes I was in Xero, the balance increased so it's going in the right direction :+1:
