### ISSUE TITLE
Invoices to Send Out

### ISSUE THREAD

**Issue by markwilliamfirth** [dwyl/hq#318]
LDMW pre-sprint 1 and sprint 1
Healthlocker sprint 10 (we need to add the heroku charges from past months to this)
oxabs everything up to sprint 30

Inês to confirm number of days charged out and when these need to be sent out.

**Comment by iteles** [comment]
@markwilliamfirth Thanks for this 👍 
All of the above need to be sent out tomorrow (Tuesday):
+ LDMW pre-sprint and sprint 1: sent you an email with what to put together for this
+ HL sprint 10: please add the charges as requested from the bank statement and send
+ HL sprint 11: original budget, ready to send out
+ HL sprint 11: new budget, ready to send out (ends Tuesday 16th so please send it out) - note, this is in the 'awaiting payment' section of xero but not sent yet for some reason
+ OxAbs: awaiting confirmation of days from developers

To be put together to be sent on Wednesday:
+ LDMW sprint 12 (also in email I sent)

**Comment by iteles** [comment]
@markwilliamfirth Oxabs invoice draft done and in drafts folder 👍

**Comment by markwilliamfirth** [comment]
@iteles is there no discount on LDMW?

**Comment by iteles** [comment]
@markwilliamfirth 5% 👍

**Comment by markwilliamfirth** [comment]
there's no discount on oa? @iteles

**Comment by markwilliamfirth** [comment]
@iteles 
<img width="463" alt="screen shot 2017-05-16 at 13 53 45" src="https://cloud.githubusercontent.com/assets/5732209/26106829/21e2e478-3a3f-11e7-95b7-aba17e920156.png">

Sprint 11 HL original budget has two roles with 0 quantity?

**Comment by markwilliamfirth** [comment]
@iteles github projects doesn't let me move this issue out of your done view from the issue view

**Comment by iteles** [comment]
That's correct @markwilliamfirth, HL asked for a budget extension so the time for those 2 people went into the 'new budget' invoice rather than this one. Kept in there for consistency

**Comment by markwilliamfirth** [comment]
I would flag that I'm not sure if it's best invoicing practice to write line items with 0 quantity, but presently it doesn't appear to cause any errors on our end.

These have been sent.
