### ISSUE TITLE
Candidate 1003

### ISSUE THREAD

**Issue by markwilliamfirth** [dwyl/hq#319]
https://github.com/dwyl/hq/issues/313
https://github.com/dwyl/hq/issues/140

- [x] Employment offer to be created by Mark

- [x] Inês to approve

- [x] Mark to send offer

- [x] Offer accepted

- [x] Candidate to sign contract

- [x] Mark to countersign contract

- [x] Mark to upload contract to CharlieHR

**Comment by iteles** [comment]
Offer _letter_ is great, please run the details to be added to the schedule by me 👍

**Comment by iteles** [comment]
@markwilliamfirth finished reviewing email (what I referred to as the details to be added to the schedule but is more of the email accompanying the letter) as requested 👍
