### ISSUE TITLE
Book accommodation for Web Summit 2015

### ISSUE THREAD

**Issue by iteles** [dwyl/hq#32]
Linked to https://github.com/dwyl/hq/issues/28

**Comment by iteles** [comment]
I would suggest this place: https://www.airbnb.co.uk/rooms/8085330

Of the 3 I'd narrowed it down to, this one is the only one still available (the one next to Google HQ which was more expensive is now taken). But also, there's a master bedroom which is also rented out for the duration of the web summit (so maybe another conference goer), the reviews are amazing, it's not difficult to get to the location of the web summit and there's a little desk and a sofa _in the room_ which are great for working without interruptions. 

<img width="855" alt="screen shot 2015-10-20 at 10 48 00" src="https://cloud.githubusercontent.com/assets/4185328/10603792/2fa48cb0-7718-11e5-8801-c5db51c39b2d.png">

It's the one at the top of this map with the artist flatmates:

<img width="568" alt="dublin airbnb map" src="https://cloud.githubusercontent.com/assets/4185328/10603836/6174cfca-7718-11e5-9415-a76de06f044e.png">

**Comment by nelsonic** [comment]
You've sent a pre-approval request for the one near google, right?

**Comment by iteles** [comment]
I asked for pre-approval, yes, but it's now booked from 2-5 November.

**Comment by iteles** [comment]
_Specifically_ sent the guy from the room above an email this morning asking if it was ok for us to let him know by the end of today and to not let anyone else book it before then. He agreed and I just got an email now saying 'sorry, the room is now only available from the 4th'. Annoyed.

#backtothedrawingboard

**Comment by iteles** [comment]
@nelsonic This is the only one left at a decent price (£306) with 26 minute commute to the place where web summit is, so **it'll go very soon**

**Comment by nelsonic** [comment]
Inês, what are you *waiting* for...?

**Comment by iteles** [comment]
Booked.
