### ISSUE TITLE
Potential new project | Surveys for teachers mobile application

### ISSUE THREAD

**Issue by iteles** [dwyl/hq#320]
A potential new project on daily 30 second surveys for teachers.

+ [x] Initial call with PO to determine what needs to be done
+ [x] Determine whether technical challenges can be overcome (@cleop)
+ [x] Put together proposal
+ [x] Follow up
+ [ ] Determine whether there is budget for this

**Comment by nelsonic** [comment]
@iteles depends on #321 👍

**Comment by Cleop** [comment]
For the technical challenge question see: https://github.com/dwyl/learn-progressive-web-apps/issues/12#issuecomment-302035025

**Comment by iteles** [comment]
Followed up on 28th July and they confirmed they built a small native iOS application with another organisation (smaller scope than originally predicted).
