### ISSUE TITLE
Invoice Template: What informations does it require?

### ISSUE THREAD

**Issue by edwardcodes** [dwyl/hq#322]
I´ve sent an invoice but it was very incomplete, what are the topics that i should follow? 
Thank you!

**Comment by edwardcodes** [comment]
What should i do to solve this problem?

**Comment by markwilliamfirth** [comment]
@edwardcodes on the invoice you sent in you didn't fill out the unit price or total columns. There are also conflicting references to euros and pounds (£ / GBP)

Do you have a UK bank account? Please can you confirm if your day rate is in pounds or euros?

**Comment by edwardcodes** [comment]
@markwilliamfirth I don't have an UK bank at moment, so my day rate should be in euros (I think).
Can you explain me how the unit price/total columns should be filled? Thanks

**Comment by edwardcodes** [comment]
Do I have to create an UK bank account?

**Comment by edwardcodes** [comment]
I think transferwise could be a very good option for people that live in other countries, is dwyl registered in transferwise?

**Comment by markwilliamfirth** [comment]
@edwardcodes please could you send me a copy of your contract / freelancing agreement to mark(at)dwyl.io?

**Comment by edwardcodes** [comment]
Hello, how can I invoice dwyl?

**Comment by rub1e** [comment]
Hey @edwardcodes , it's probably easier if I get the information off you and create the invoice myself - I'll send you an email shortly!

**Comment by edwardcodes** [comment]
Hey @rub1e Thank you for the explanation! Please use this email: edu_martins7@hotmail.com

**Comment by edwardcodes** [comment]
@iteles This issue can be closed, Thank you!
