### ISSUE TITLE
Check we are up-to-date with VAT

### ISSUE THREAD

**Issue by markwilliamfirth** [dwyl/hq#327]
03002003700

Online says £549.86, but may be error (PAYE £875.50 online vs £346.03 Xero confirmed by HMRC)

**Comment by markwilliamfirth** [comment]
£549.86 was surcharge for January submission
Paid 2017-03-16

Next VAT return deadline
2017-06-06

**Comment by nelsonic** [comment]
Thanks for checking this Mark! 👍
