### ISSUE TITLE
Speaking to people as a team (Conference Calling) do we need to Go Pro?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hq#33]
We are already using Google Hangouts for our Team/Client Standup/Daily meetings and for Product demos. But is the "_free_" service "_good enough_" or do we need to consider something a bit more "_professional_" e.g: https://www.uberconference.com/features

> What are the other alternatives?

**Comment by iteles** [comment]
Google hangouts has caused us quite a lot of connectivity/quality issues over the last year (e.g. https://github.com/dwyl/remote-working/issues/8#issuecomment-230434204). We'll need to try a few options in the new year.

**Comment by nelsonic** [comment]
@iteles is this a _task_ that can be well-defined and _delegated_...? `#DivideAndConquer` 😉

**Comment by markwilliamfirth** [comment]
@iteles do we have alternatives to Google Hangouts? Maybe best to define these before we instruct Unbound how to manage their remote standups?

**Comment by iteles** [comment]
@markwilliamfirth Good thinking, can we research a few? I know Skype is considerably worse than Hangouts an https://appear.in/ requires the installation of software.

The baseline requirement should be no specific software installation required.

**Comment by markwilliamfirth** [comment]
I don't think appear.in requires software - it's all online - WebRTC. The issue with it is not all browsers support it.

http://support.appear.in/article/61-im-not-using-chrome-firefox-or-opera-what-other-browsers-do-you-support

**Comment by iteles** [comment]
Sorry, should have clarified, we also need to look at usage on phones (that's where appear in requires an app) because our clients (and me!) are often on the go :+1:

**Comment by markwilliamfirth** [comment]
Linked to #392 #397

**Comment by iteles** [comment]
Closing in favour of #397 for now, to be reopened when Google Meet is no longer adequate for our purposes.
