### ISSUE TITLE
Directors' Loans / Available Capital

### ISSUE THREAD

**Issue by markwilliamfirth** [dwyl/hq#332]
This issue follows on from the discussion here https://github.com/dwyl/hq/issues/146

On 2017-05-02 @nelsonic mentioned that capital from @nelsonic and @iteles would be loaned to the business following remuneration, but on 2017-05-15 @iteles put forward the idea (https://github.com/dwyl/hq/issues/146#issuecomment-301472836) that _loans aren't a sustainable way to grow a company and provide for our community_ and that loaning money back into the business should be _on an as-needed basis_.

@iteles and @nelsonic we need to come to a conclusion about how much is being loaned back in 
 in order to determine our available capital or whether @iteles idea of loaning _on an as-need basis_ should be implemented

My personal belief is that the more capital we have to utilise the better this will be for our growth and it will help us achieve sustainability sooner. Let's discuss!

**Comment by nelsonic** [comment]
How does this issue help us _Ship Our Product_?
What _exactly_ do we need more capital for? 
Do we need a nicer office, more employees or a bigger marketing budget?
Or do we need to keep our heads down and write the code instead of answering questions about capital? (_which by-the-way, we have **more than enough of**_!)

**Comment by markwilliamfirth** [comment]
@nelsonic 

>How does this issue help us Ship Our Product?

Knowing the capital available to the company is essential for understanding the company's financial position and it allows us to deploy effectively and in a manner that will help us ship our product.

>What exactly do we need more capital for?

We need to know the status of available capital in order to do many things. For example: to hire staff #313 and set up employee benefits #331 

> Do we need a nicer office, more employees or a bigger marketing budget?

This hasn't been decided yet as we don't know how much capital we have to deploy. Hiring employees to work on our product will certainly be an incurred cost.

> Or do we need to keep our heads down and write the code instead of answering questions about capital?

On the operations side of things we need to understand budgets and resourcing and generate an effective business plan #328  and operational plan of action that will help us ship our product.

>(which by-the-way, we have more than enough of!)

The question isn't whether we need more or less. It's making it clear how much is available to the company - this is currently unclear.

**Comment by iteles** [comment]
@markwilliamfirth We're not coming to any conclusions about anything financial until #321 #229 and #209 are done as mentioned previously (here)[https://github.com/dwyl/hq/issues/146#issuecomment-301472836].

This is nowhere near a priority until we know whether it is needed and we won't know whether it is needed until the above is completed :+1:

We can reopen if required.

**Comment by markwilliamfirth** [comment]
(Reopening as this issue hasn't been resolved)

@iteles with reference to your comment (https://github.com/dwyl/hq/issues/332#issuecomment-302164578), this issue (https://github.com/dwyl/hq/issues/324) requires resolution before proceeding

**Comment by iteles** [comment]
This issue has been resolved. _If_ needed, we will come back to it. There's no need to have 'what if' issues open in the backlog 👍
