### ISSUE TITLE
Security Beyond the Repo

### ISSUE THREAD

**Issue by markwilliamfirth** [dwyl/hq#335]
Join us for a remote afternoon talk with Adam Baldwin, team lead at ^Lift Security and creator of Node Security. Adam is an information security professional with over 23 years of experience working with and securing technology. He's worked with some of the worlds largest governments and corporate entities to help secure their assets. Adam will be sharing his experiences about how he is assessing and protecting what he has built outside the repo, touching on network and physical security. Attendees will have a chance to ask questions in the Q&A session following the talk.

Friday 26th May 2017

5:00 PM - 5:30 PM

The event will be streamed at:
Focus Hub
16 Palmers Road
London
E2 0SY

**To Do:**

- [x] @sohilpandya to bring in speakers to Focus Hub on Monday

- [x] Work out whether we can stream sound to the TV and if so, test this

- [x] Test Hangouts Link for event

- [x] Send event reminder prior to event

**Comment by markwilliamfirth** [comment]
Linked to https://github.com/dwyl/hq/issues/198

**Comment by markwilliamfirth** [comment]
@sohilpandya did you manage to bring the speakers in? If not could you bring them in tomorrow?

**Comment by sohilpandya** [comment]
@markwilliamfirth I've bought a new speaker. Lol. So we can use that one 👍 

It's pretty good.

**Comment by markwilliamfirth** [comment]
Can stream sound to tv (http://lifehacker.com/how-to-send-your-computers-audio-to-a-chromecast-1750297581), but speaker is bluetooth so have connected to laptop

**Comment by markwilliamfirth** [comment]
webcam works, sound works, reminder sent 👍
