### ISSUE TITLE
ZEN Project

### ISSUE THREAD

**Issue by markwilliamfirth** [dwyl/hq#337]
>At the moment we have some 360 images as part of our library (have attached one here) and would like to upload them onto our website.  We want people to be able to scroll round the photo as if they were standing in that spot (that the photo was taken) – the idea is for people to be able to compare spaces before and after our interventions.  We would preferably have the 360 ability in place within 4 weeks and our budget is very limited for this approx. £500 (as it is only a bolt on).  We have budget for maintenance though so would be interested to know what you can offer with respect to that.

@iteles client is good, but budget is tight - how would you like to proceed?

**Comment by nelsonic** [comment]
@iteles depends on #321 👍

**Comment by markwilliamfirth** [comment]
@iteles should mention that Patrick was hoping for an answer soon

**Comment by markwilliamfirth** [comment]
@iteles we've left Patrick waiting 8 days

**Comment by iteles** [comment]
@markwilliamfirth He says he's attached one of these 360 images to his email, but I don't see any attachments. I'd like to know what format this image is in and see how big they are, how they work, etc.

Is it adding to an existing page? Or creating a new page in drupal and then adding this functionality?

Do they have access to both drupal and the code?

**Comment by markwilliamfirth** [comment]
I'll follow up

**Comment by roryc89** [comment]
If it's any help, I did a project with this feature before - https://realtalkclient.herokuapp.com/UnionSquare

**Comment by markwilliamfirth** [comment]
ooooooh

**Comment by Jbarget** [comment]
@roryc89 is it an open source thing?

**Comment by roryc89** [comment]
@Jbarget Yes. Here's the repo: https://github.com/realFacesTeam/Real-Faces

**Comment by markwilliamfirth** [comment]
Haven't heard from Patrick, so have sent a follow-up email

**Comment by markwilliamfirth** [comment]
![Uploading oe-zen-360-02.jpg…]()
![Uploading oe-zen-360-03.jpg…]()

@roryc89 are these the kinda images you've worked with before? Do you know how long it would take to implement something like this? I assume it could be done in a relatively quick time given you've built this functionality previously?

**Comment by roryc89** [comment]
It depends on how the images are taken. I had 6 photos displayed on the inside of a cube, with the user viewing from the centre and it was quite simple. The curvature on these photos suggests it would fit onto something curved like a cylinder or sphere.

My previous experience in this was from a few years ago and I haven't worked in anything similar since so will still need to read up.

For making the images 360 degree scrollable I would estimate a day. I think the main time sink would more likely be the integration with the rest of the app and fine tuning. This could be another 2 days but hard to know as I haven't seen the project.

**Comment by iteles** [comment]
Particularly because it's using drupal which is its own problem.

**Comment by markwilliamfirth** [comment]
@roryc89 thank you for your help! I've followed up with Patrick...waiting to hear back

**Comment by markwilliamfirth** [comment]
Chased Patrick again

**Comment by markwilliamfirth** [comment]
Have not received a response from Patrick after chasing 3 times
