### ISSUE TITLE
Set up correct categorisation in Xero

### ISSUE THREAD

**Issue by iteles** [dwyl/hq#339]
As someone who is interested in improving the efficiency of work processes and use of dwylers' time, I would like the expense categories in Xero to be set up according to what we need for end of year filing so that we don't have to revisit receipts multiple months after I have put them into the system and spend additional time trying to work out/remember/have to ask what category they should fall under.

As with everything, these categories should be documented in an `.md` file on this repo, with examples of what can/should be claimed under each category please ❤️ 

I'm making this a `priority-2` because #262 is the priority right _now_, but we've now been using Xero for 3 months and I reckon this will be a pretty quick win, so it would be good to get it done next 👍

**Comment by rub1e** [comment]
Not 100% clear on what the ask is here. Are you saying that the existing Expense categories in Xero (copied below) aren't what you need for EOY accounts, or that people simply aren't using those categories properly, meaning you have to add that info months later?

If the former, we can add custom "Account Profiles" in addition to the below. Let's chat 😃 

_400 - Advertising & Marketing
Expenses incurred for advertising and marketing
420 - Entertainment-100% business
Expenses incurred on entertainment by the business that for income tax purposes are fully deductable
424 - Entertainment - 0%
Expenses incurred on entertainment by the business that for income tax purposes are not fully deductable
425 - Postage, Freight & Courier
Expenses incurred by the entity on postage, freight & courier costs
429 - Office Supplies
Expenses incurred that relate to the general running of the business
445 - Light, Power, Heating
Expenses incurred for lighting, power or heating the business premises
461 - Printing & Stationery
Expenses incurred on printing and stationery
479 - Employers National Insurance
Payment made for National Insurance contributions - business contribution only
485 - Subscriptions
Expenses incurred by the business in relation to subscriptions, such as magazines and professional bodies
489 - Telephone & Internet
Expenses incurred from any business-related phone calls, phone lines, or internet connections
493 - Travel - National
Expenses incurred from any domestic business travel
494 - Travel - International
Expenses incurred from any international business travel
Assets
710 - Office Equipment
Office equipment that is owned and controlled by the business
720 - Computer Equipment
Computer equipment that is owned and controlled by the business
740 - Buildings
Buildings that are owned and controlled by the business
750 - Leasehold Improvements
The value added to the leased premises via improvements
760 - Motor Vehicles
Motor vehicles that are owned and controlled by the business_

**Comment by iteles** [comment]
Might be worth waiting until we've completed the Focus Hub accounts so we can see exactly which categories we need for HMRC without having to go digging (we're going to come across them next week anyway)!

**Comment by iteles** [comment]
Discussing this with Karen this week (if it fits into our agenda!) https://github.com/dwyl/focus-hub/issues/134

**Comment by iteles** [comment]
Agreed that we can keep the granularity and our accountants can pull this together now that we aren't doing this manually (and are doing it through Xero).
