### ISSUE TITLE
Who is this?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hq#34]
http://dowhatyouloveforlife.com/course/do-what-you-love/

**Comment by iteles** [comment]
I came across these guys a few months ago. There are *many* other people writing books and running courses using the exact words "do what you love". 

I've got my eye I these guys, subscribed and follow along for now.

**Comment by iteles** [comment]
Didn't mean to close your issue, GitHub mobile interface fail 😣

**Comment by iteles** [comment]
When exactly do you reckon we can close an issue like this?

**Comment by nelsonic** [comment]
Up to you.

**Comment by Jbarget** [comment]
how about now?
