### ISSUE TITLE
dwyl VAT return | period ending 30th April 2017

### ISSUE THREAD

**Issue by iteles** [dwyl/hq#340]
# Deadline: 7th June 2017

@markwilliamfirth Please _codify_ the steps for doing this into an `md` file in the _finances_ folder as you go :bush:

+ [ ] Finalise income for the period 1st February - 30th April 2017 (a decent portion of this will be done already through #229 )
+ [ ] Determine VAT on expenses for that period
  + [ ] F&C invoices
  + [ ] Ice Cream Rocketship invoices
  + [x] Receipts/invoices (@iteles needs 24-48 hours to find her wallet 😬 
+ [ ] Fill our VAT statement
+ [ ] Pay VAT for the quarter

(assigning priority 2 because the deadline is not until next week, but there is some work to be done here)

**Comment by markwilliamfirth** [comment]
@iteles I think this should say 6th June?

**Comment by markwilliamfirth** [comment]
@iteles can you send me the workings on all VAT returns filed to date? Required urgently to send to Carl

**Comment by markwilliamfirth** [comment]
<img width="386" alt="screen shot 2017-06-05 at 10 25 35" src="https://cloud.githubusercontent.com/assets/5732209/26778488/5dc009a4-49d9-11e7-91cf-1d9763785787.png">

**Comment by iteles** [comment]
@markwilliamfirth The workings are just an amalgamation (sometimes manual) of the F&C commission spreadsheet and the `Accounts dwyl a-team` spreadsheet, both of which are not meant for public consumption so not entirely convinced they'll be useful.

**Comment by iteles** [comment]
Also, I don't think this is required for the VAT deadline mentioned in this issue?

**Comment by markwilliamfirth** [comment]
@iteles carl said he needs it in order to complete bookkeeping, thus allowing us to submit the vat return

**Comment by iteles** [comment]
@markwilliamfirth FYI I found my wallet and am uploading the final receipts now

**Comment by iteles** [comment]
All of my loose receipts that wouldn't be in emails are in Xero across the approved and for approval buckets (this doesn't include Google invoices, Amazon, Github, tachyons donations or any of the other stuff that are in emails). The ones in euros (apart from the one in the 'to be approved' bucket) have been converted to GBP using the accurate historical rates http://x-rates.com/historical/

**Comment by markwilliamfirth** [comment]
This was submitted and paid, we'll be received a small refund from HMRC as we paid the upper estimate in advance to ensure the bank transfer had time to get there in order to avoid a surcharge
