### ISSUE TITLE
Payroll

### ISSUE THREAD

**Issue by ghost** [dwyl/hq#341]
Run payroll in Xero

**Comment by iteles** [comment]
Action for me: move money to payroll account 👍

**Comment by markwilliamfirth** [comment]
Partially blocked by https://github.com/dwyl/hq/issues/264

Naaz, Simon, Cleo, Mark complete

Inês, Nelson, HMRC outstanding

**Comment by markwilliamfirth** [comment]
October completed

**Comment by iteles** [comment]
Longer this week as I write up documentation and deal with calculating final payments.

I would normally expect this to be a 30 minute to 1 hour (tops!) task.

**Comment by iteles** [comment]
More noise.
