### ISSUE TITLE
EMF: Additional Sprints

### ISSUE THREAD

**Issue by Cleop** [dwyl/hq#343]
- **What:** want to do more work on the app
- **When:** either 2 sprints in July followed by a break in August to continue in September (when there may be capacity for a full team on the project) OR possibility of working August through to September. Depends on availability for both us and them.
- Consecutive sprints are preferred: more efficient, better for morale/momentum.

**- What kind of work?**
- **July** - search, would like to add matches to other activities not just organisations.
- User profiles, should become more user focussed not org focussed. The app is organised around organisations but we want the **people** within/across them to **be the drivers**.
- Feedback mechanisms, notifications, news
- **September**- Towards the end of the summer building an asset management system so we centralise all our docs, images, everything. Use this one central place to manage assets as a backend to the library. Building a REST API for the admin functionality. Want different interfaces to talk to the backend.

-**Who?**
- For first couple of sprints: 1 mid level sprint, 1 more senior sprint.
- EMF should have capacity to take care of UX work.

**Next steps:**

- [x] Let EMF know dwyl's availability for the end of July once the work for dwyl summer has been agreed.
- [x] EMF will let us know what the possibilities for July/August are based on staff holidays etc. and more confirmed details about the work to be done.
+ [x] Get back in touch with Alex in August

Alex is on holiday last week July/ first week August.

**Comment by iteles** [comment]
Delayed to September.

**Comment by markwilliamfirth** [comment]
@iteles is there any update on when this one is likely to start?

**Comment by markwilliamfirth** [comment]
Spoke to @iteles on Gitter - this date is currently still being confirmed (mid-September ish)

**Comment by iteles** [comment]
Confirmed to start on 18th September with @Cleop and @SimonLab 

@SimonLab will carry out an API spike in the previous week.
