### ISSUE TITLE
GSG Collaboration

### ISSUE THREAD

**Issue by Cleop** [dwyl/hq#344]
**What?**
- GSG have 4/5 devs from their pilot in need of work.
- Next cohort (16 people) July 9th, in need of work at the end of the year.
- Stack: node/ js / react
- Current opportunities for work from connections of umbrella organisation however need work on managing these, setting expectations and filtering for the right fit for building something grads are ready for (MVPs).

**Needs:**
- Soft skills support. Both as an intermediary between clients and devs but also wider soft skills for being employable e.g. proof reading and cover letter writing.
- Currently there is a separate 8 week freelancing programme funded by the Coca-Cola foundation about project management, communicating with clients etc. to help build these skills too.

**Tips for finding the right projects:**
- MVP projects (not expecting anything perfect, understanding it's a prototype, managing expectations, not built for security/scalability)
- Potentially charities/ government orgs the right kind of clients?
- Need a good Product Owner who understands what to expect from an MVP
- Need to establish what kind of ongoing support to offer. Need to ensure clear definitions are set for bug fixing vs. enhancements. Ensure to build bug fixing time into the sprint planning.
- Do a 1 hour workshop with potential clients to help people learn about managing digital products. Or a 2 hour project starter workshop to set expectations as you start. As well as documentation on what makes a good product owner.

**Collaboration with dwyl?**
- QA support?
- Need to be cautious with building remote teams properly and dealing with cultural/time zone differences
- dwyl will probably have more resources available for this kind of collaboration towards the end of the year.

 **Actions:**
- [ ] Share dwyl guides on soft skills / working with clients e.g. scrum mastering, why a web app not native with the GSG team.
Then check-in in a few months to see how things have progressed at both ends.

**Comment by markwilliamfirth** [comment]
@iteles should we check in now that it's been a few months?

**Comment by iteles** [comment]
We haven't followed up on this and things in GSG have moved on considerably, they have a fair amount of sorting out their business before any of this is possible and it could be 6-12months. I'll reopen this issue if they get back in touch.
