### ISSUE TITLE
dwyl Fridays - elixir code dojo?!

### ISSUE THREAD

**Issue by katbow** [dwyl/hq#345]
I would like to run an elixir code dojo on the next dwyl Friday! I think it would give us a great chance to work together to learn a little bit more elixir 🙂 .

The inspiration comes from [this repo](https://github.com/carwow/pokerwars), so I hope people like poker 😃

**Comment by sohilpandya** [comment]
That sounds amazing! Looking forward to this! @markwilliamfirth can we book this in?

**Comment by markwilliamfirth** [comment]
If people would be interested in this please like the top post!

**Comment by RobStallion** [comment]
Sounds great 😆🎊🎉

**Comment by andrewMacmurray** [comment]
yep definitely up for this

**Comment by JMurphyWeb** [comment]
Sounds good KB.

**Comment by iteles** [comment]
@katbow Is this for this Friday 9th June?

This is an absolutely WONDERFUL idea, very cool. Like we discussed, let's contextualise this - it's cart sorting and pattern recognition, not quite poker! 😉

**Comment by katbow** [comment]
@iteles I was intending it to be for the last Friday of the month which would make it 30th June. However if there are already plans that day, or this Friday is more convenient, I am happy to do it then!

**Comment by iteles** [comment]
Nelson and I won't be here 😭 But that shouldn't stop you! Please coordinate with @markwilliamfirth to get an invite out early 😊

**Comment by markwilliamfirth** [comment]
@katbow Inês and Nelson go away on 29th. We might make this 16th or 23rd - rather than end of month - will let you know soon, but it's definitely going ahead so please make the repo for the event! 👍

**Comment by katbow** [comment]
definitely happy to do it earlier on the 16th or 23rd in that case!

**Comment by iteles** [comment]
I would suggest 23rd as we already have dwylympics is on 14th already 😊

**Comment by markwilliamfirth** [comment]
@katbow I will email out about 23rd - do you have the repo up? I can send in the email so everyone can have a look in advance

**Comment by katbow** [comment]
@markwilliamfirth it's on my todo list this weekend 🙂

**Comment by katbow** [comment]
@markwilliamfirth not merged in yet, but will be [here](https://github.com/dwyl/elixir-dojo)

**Comment by markwilliamfirth** [comment]
@katbow I'm going to send this out today! Let's start at 4:00PM ish. How long will you need for the workshop? 1h? 2h? Would you like me to include a short blurb? If you can't think of anything I can write something 👍

**Comment by sohilpandya** [comment]
@markwilliamfirth can we try a 3 pm start? 3 - 5 pm would be good to try out?

**Comment by markwilliamfirth** [comment]
@sohilpandya we can't do 3pm :P https://github.com/dwyl/focushub/issues/55#issuecomment-300160354

@katbow any update on this? Inês mentioned there is a lot of HL stuff this week

**Comment by sohilpandya** [comment]
Oops

**Comment by katbow** [comment]
@markwilliamfirth 4 is good (although 3 would be cool 😉). I think it should be somewhere right in the middle, around 1.5 hours.

I don't have any extra blurbs, just what I've put in the [README](https://github.com/dwyl/elixir-dojo) 🙂!

**Comment by markwilliamfirth** [comment]
Awesome - will send out today

**Comment by markwilliamfirth** [comment]
Sent 👍

**Comment by katbow** [comment]
thanks everyone for coming ❤️ 🤗 ✨

**Comment by RobStallion** [comment]
Thanks for the great dojo 👍
