### ISSUE TITLE
Quodl | Small extension

### ISSUE THREAD

**Issue by iteles** [dwyl/hq#346]
This is the app we developed, taking a Teaching Excellence runner up spot in the Guardian Innovation awards. They're currently looking to see if they can find further funds for adding features and need an idea of what can be done in 2 sprints.

> It looks like both participation and score [in the application] predict overall performance on the coursework and exams, so this is potentially a great way of early identification of students who might need extra help.

+ [x] Book call with PO
+ [x] Provide PO with an idea of team availabilities
+ [x] Discuss requirements (call booked 20th June)
+ [x] PO to provide prioritised requirements
+ [x] Provide rough budget + timelines
+ [x] Decide on team

**Comment by sohilpandya** [comment]
**Call with Stian + Yinka**

- March 2017 Guardian Uni awards Runners up
- Getting more money to develop this further, it has been difficult but there has been a lot of pushback from IT dept. 
- April asked for more money
- Trialed in 5 undergrad lectures and lead by lecturers without Stian's help
- Done some Analytics for the app 
- Currently, speaking with IT dept regards to Data protection and compliance.
- Final business case submission on Wednesday, it's looking positive and bodes well. 😄
- Stian wants to know the timelines for the features that he's looking for.  


**Updates from today**
Stian would like:
- More on the gamification aspect as others are doing the quizzing aspect, but reinstating trophies is a major thing. 
- Analytics is another thing we need to discuss (What Analytics?) 
- Further Design work to make the gamification cool and more specific on that

**Rough start times**
SR: Tuesday 13th is the meeting, probably know it within the next couple of day. 
SP: 19th potential start date or planning?

**Comment by iteles** [comment]
+ Show due diligence and competitiveness of dwyl quote
+ PO will be prioritising backlog
+ dwyl to provide simple quote and timelines

**Comment by iteles** [comment]
Additional change to budget requested.

**Comment by iteles** [comment]
Began on 7th August with @sohilpandya @jackcarlisle as the full time team.
