### ISSUE TITLE
New Projector for Presentations

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hq#35]
In January 2015 we *Loaned* Our Projector to Founders & Coders since January (because the one they had was crappy) ... 

The model we loaned to FAC is **Optoma HD230X Full HD 1080p Home Cinema Projector**: http://www.amazon.co.uk/home-theatre/dp/B006ZIVKLY it was the *best* value 1080p 60hz projector at the time we bought it, but sadly we did not get much chance to use it... 

@tsop14 mentioned wanting to get a projector for FAC and @natalialkb suggested maybe we can "*donate*" *ours* to FAC and then we can go halfsies on getting a new one...

There is a newer model **Optoma HD141X** which is cheaper **£449** but appears to have similar specs
http://www.amazon.co.uk/Optoma-HD141X-Full-1080p-Projector/dp/B00M2YDBXK

<img width="963" alt="optoma-hd141x-amazon" src="https://cloud.githubusercontent.com/assets/194400/10717096/167227c0-7b46-11e5-96c3-a2796575e4aa.png">

We would *love* to have our Projector back or any other alternative as it will allow us to do #**dywl**movie**night** ... @iteles what are your thoughts on this...?

**Comment by iteles** [comment]
@nelsonic Agreed. You did a lot of research into this before buying it in the first place so it looks great to me!

My only question was whether we might want a portable projector but there has not been any need for one so far so this one looks ideal :+1:

**Comment by nelsonic** [comment]
Brack Friday Bunduru: http://www.amazon.co.uk/dp/B00M2YDBXK/ref=gbps_tit_m-4_9387_cd085ee2?pf_rd_p=764419387&pf_rd_s=merchandised-search-4&pf_rd_t=101&pf_rd_i=161428031&pf_rd_m=A3P5ROKL5A1OLE&pf_rd_r=1TZNAQ5NJ23XFBPQJH0X
<img width="329" alt="projector-deal" src="https://cloud.githubusercontent.com/assets/194400/11379851/8f672aac-92ea-11e5-810d-4e1469ce04f8.png">

**Comment by tsop14** [comment]
I would like to have this 🎁 before Christmas. Black Friday sounds 👌🏼
shall I order? Let me know as don't want to miss ze deals. 🤑

**Comment by nelsonic** [comment]
![screenshot_2015-11-25-09-01-11](https://cloud.githubusercontent.com/assets/194400/11392678/29ac1556-9353-11e5-99fd-2a6bb913c14f.png)
Not a bad discount.

**Comment by nelsonic** [comment]
£379.99 is quite a good discount. @tsop14 Want to go *halfsies*?

**Comment by tsop14** [comment]
Looks v good! Then you could even have it before thanks giving! 🍗
(tofurkey)

**Comment by nelsonic** [comment]
@tsop14 should I order it? **1h left** on the deal.

**Comment by iteles** [comment]
@nelsonic Given the time constraints, I texted the lovely @tsop14 as well :+1:

**Comment by iteles** [comment]
Confirmation from @tsop14:
![emma-confirmation-of-purchase](https://cloud.githubusercontent.com/assets/4185328/11397938/1e8bdcac-9375-11e5-9298-88b52d58b379.jpg)

**Comment by nelsonic** [comment]
<img width="1168" alt="projector-ordered" src="https://cloud.githubusercontent.com/assets/194400/11398155/bae638d0-9376-11e5-8f8f-38fd1fea1809.png">

Ordered. :+1:

**Comment by tsop14** [comment]
Sell sell sell!

Just kidding. Yay 😍

**Comment by iteles** [comment]
:laughing:

**Comment by nelsonic** [comment]
Thanks again Emma! 🎉 
(_closing the issue..._)
