### ISSUE TITLE
HL extension

### ISSUE THREAD

**Issue by iteles** [dwyl/hq#351]
Requirements from the client:
+ AGREED: 3 days to carry out as many tweaks as possible - @katbow 
+ TBC: 5 days of ePJS integration & Azure deployment - @nelsonic @katbow & @RobStallion 

+ [x] Write and send contracts (25 mins)
  + [x] for 3 day extension 
  + [x] for ePJS week
+ [x] Review 3 day extension backlog (1 hour)
+ [x] Chase for agreement on 5 days above
+ [x] Chase for signed contracts

**Comment by iteles** [comment]
Agreement received on 5 days. No contracts yet.

**Comment by iteles** [comment]
Work has begun with @robstallion and @katbow

**Comment by iteles** [comment]
Reopening as this required a further week of extension.
+ [ ] Budget to be sent
+ [ ] Contract to be added to
+ [ ] Chase for signed contract

**Comment by markwilliamfirth** [comment]
Signed contract recieved
Countersigned sent
👍

**Comment by iteles** [comment]
Woah, Katy's da 💣 !
