### ISSUE TITLE
Add Cleo to Payroll

### ISSUE THREAD

**Issue by markwilliamfirth** [dwyl/hq#354]
Add Cleo to Payroll

**Comment by markwilliamfirth** [comment]
@Cleop 

Please could you email me a completed copy of [this form](https://public-online.hmrc.gov.uk/lc/content/xfaforms/profiles/forms.html?contentRoot=repository:///Applications/PersonalTax_iForms/1.0/SC&template=SC.xdp)?

Please could you also contact HMRC regarding your change of name and let me know when this has been done?

**Comment by Cleop** [comment]
@markwilliamfirth - spoken to HMRC and changed my name this morning. The man told me that it will take a couple of days for it to be changed successfully across their whole system so hold fire on contacting them for approx 48 hours.

**Comment by markwilliamfirth** [comment]
@cleop yep you filled it out correctly! I have set you up on payroll in advance - notice won't be sent to HMRC until end of the month when payroll runs. Closing this issue as all steps have been done, but please reopen if you hear back about any issues with the name change going through (should be
 fine) 👍
