### ISSUE TITLE
The ZEN Grants Scheme for Cycling

### ISSUE THREAD

**Issue by ghost** [dwyl/hq#357]
The ZEN Grants Scheme is open - we can apply for grants of up to £2,000 to encourage sustainable travel at dwyl.

We can utilise this grant for free bike repairs for dwylers amongst other things.

In order to apply for the grant we need to fill out [this survey](https://www.surveymonkey.co.uk/r/ZENtravelsurvey). Please could as many dwylers fill this out as possible?

**Comment by iteles** [comment]
To make it a little easier for people who might not know all the office details:
<img width="517" alt="screen shot 2017-06-15 at 13 20 27" src="https://user-images.githubusercontent.com/4185328/27180974-7d7d54da-51cd-11e7-9002-bd02dd9e9d37.png">

**Comment by markwilliamfirth** [comment]
@Cleop @Conorc1000 @Danwhy @finnhodgkin @ZooeyMiller @harrygfox @jackcarlisle @Jbarget @katbow @naazy @nogainbar @RobStallion @roryc89 @shouston3 @SimonLab @sohilpandya 

A reminder to please fill this out if you haven't yet! It will give us a grant that all dwylers can use for sustainable travel e.g. cycling maintenance etc

**Deadline is 31st July**

**Comment by Jbarget** [comment]
done 👍

**Comment by RobStallion** [comment]
Did it a while back 👍

**Comment by sohilpandya** [comment]
Done 🎉

**Comment by finnhodgkin** [comment]
Pretty sure I did it a while back :+1:

**Comment by ZooeyMiller** [comment]
Thanks for the reminder, done.

**Comment by nogainbar** [comment]
Done! :)

**Comment by naazy** [comment]
Done :smile:

**Comment by shouston3** [comment]
Done

**Comment by naazy** [comment]
Done

**Comment by harrygfox** [comment]
donezo

**Comment by markwilliamfirth** [comment]
Got this message from Zen

>Please can you give me a ring so we can discuss the grant. I am a little unsure as to what your organisation does as when I previously spoke to Dan Sofer, I was under the impression that you were more of a training/education centre for start-up businesses and also a sister company of Coders and Founders. I’d also like to know more about what you would need a grant for as you mentioned bike repair services, but this is not something we usually offer.

@iteles are there any notes from what was agreed with Zen last time? I thought FAC use/used the grant for bike repair?

**Comment by markwilliamfirth** [comment]
[18675985-ZEN Grant Application Form (Aug 2017).PDF](https://github.com/dwyl/hq/files/1314735/18675985-ZEN.Grant.Application.Form.Aug.2017.PDF)
[18676017-ZEN Grant App Guidance (2017).PDF](https://github.com/dwyl/hq/files/1314736/18676017-ZEN.Grant.App.Guidance.2017.PDF)
[18712508-DWYL Action Plan.PDF](https://github.com/dwyl/hq/files/1314737/18712508-DWYL.Action.Plan.PDF)

**Comment by iteles** [comment]
@markwilliamfirth I seem to have missed this issue, sorry.
The deadline for this grant was 31 July (as you mentioned in an email to the team) so I assume we'll now have to wait for the next on in December. It would be good to check that they can reuse the forms from July that everyone filled out.

The money was sent over to the bike shop directly and Founders & Coders should be using it for the agreed things in the grant. 
@sofer, are you able to share the ZEN grant application with @markwilliamfirth please?

**Comment by markwilliamfirth** [comment]
@sofer please could you confirm the agreement with Zen? Zen said to me in an email that the grant cannot be used for bike repairs, which FAC has been doing

**Comment by sofer** [comment]
We burnt through ours by buying stuff from a local bike shop. It was a mixture of new stuff, replacement wheels (several got nicked from outside No.14), and the odd repair. It's all gone now,

**Comment by markwilliamfirth** [comment]
@sofer thanks - wanted to clarify how you managed to agree with Zen that the grant could be used for that purpose? They seemed quite adamant it couldn't. Was this a special agreement made over the phone? What did they say when you submitted the grant review to show where the money had gone?

**Comment by sofer** [comment]
Maybe they have changed the rules. It was all dealt with via email. I sent them a link to the spreadsheet maintained by the bike shop and links to tweets with pictures of new gear. There were never any issues.

**Comment by iteles** [comment]
No longer available as we had originally anticipated and we are no longer in the ZEN catchment area so cannot apply.
