### ISSUE TITLE
Scrum master Q & A

### ISSUE THREAD

**Issue by iteles** [dwyl/hq#358]
As a scrum master with some experience, I would like to share my knowledge in such a way that it can be documented and that people can ask questions to prompt genuinely useful knowledge sharing so that others can learn from it with less time and effort expenditure in future.

**Comment by iteles** [comment]
Personal notepad for now (I don't expect this comment to mean anything to people and will delete it once the knowledge has been documented).

+ Demo prep issue
+ Closing off previous sprint milestone
+ Primers to speed up (very easy to just slog through issues, challenge yourself but not so quickly you don't think things through)
+ https://github.com/healthlocker/healthlocker/issues/840#issuecomment-308668863

**Comment by markwilliamfirth** [comment]
[scrum-guide-us.pdf](https://github.com/dwyl/hq/files/1088533/scrum-guide-us.pdf)

**Comment by iteles** [comment]
This was carried out in June and as a result, multiple commits were added to the 'process-handbook' repo.
