### ISSUE TITLE
Top Shelf

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hq#36]
I call "*dibs*" on the top shelf of the fridge.
![1446129049016-72630117](https://cloud.githubusercontent.com/assets/194400/10821313/b3965dae-7e49-11e5-9b18-3ffd20643ed1.jpg)

**Comment by iteles** [comment]
:+1: Guess this means that I should cook all my meals for 1 in the near future?

**Comment by iteles** [comment]
I'll only add stuff to the top shelf if I _absolutely need_ to store a mason jar (for example) which doesn't fit on any of the other shelves (and if there's no other space for it). Other than that, it's yours.

Can we close this `priority-1` issue?   
You can always re-open it if I'm bending the rules (I won't do so without asking). :wink:

**Comment by nelsonic** [comment]
Ok. If you *absolutely have to*, but only healthy things. Closed.
