### ISSUE TITLE
New repo for communication and product emails

### ISSUE THREAD

**Issue by Cleop** [dwyl/hq#360]
Relocating: https://github.com/dwyl/dwyl-site/issues/16

- What's the appropriate content of emails?
- What's the optimum frequency?
- How shall we schedule content?
- Understanding why people sign up to get emails from us
- What alternatives are there to emailing people? Ie. blog, etc
- How do various means of communication compliment each other?
- Other general ideas on communicating with people who are interested in dwyl

Where / how will people sign up?
- The 'App' page on the website
- Other?

**Comment by markwilliamfirth** [comment]
We don't have a newsletter at the moment, but we are collecting emails for Time so this repo isn't needed for now - we can reopen if we decide to do a newsletter in future or if Time comes to fruition
