### ISSUE TITLE
Cyber Essentials Certification

### ISSUE THREAD

**Issue by ghost** [dwyl/hq#361]
https://www.cyberaware.gov.uk/cyberessentials/

Linked to #335

**Comment by nelsonic** [comment]
The Self-Assessment Questionnaire is insightful.

I responded _personally_, but it would be good if _everyone_ went through it ***and*** for us to have a 12/12 score on it for the _organisation_... 
![image](https://user-images.githubusercontent.com/194400/27279180-ccdcced2-54db-11e7-8cc7-0324c796e53c.png)

**Comment by rub1e** [comment]
Migrated to https://github.com/dwyl/learn-security/issues/57
