### ISSUE TITLE
dwylympics Photos & Videos

### ISSUE THREAD

**Issue by markwilliamfirth** [dwyl/hq#362]
https://github.com/dwyl/hq/issues/94#issuecomment-309455313

Anyone with photos and videos from dwylympics please drop them in here!

https://drive.google.com/drive/folders/0B0XeQ2t5WSK2ZUNSTFRraHRob3M

**Comment by iteles** [comment]
Uploaded the only ones I had.

**Comment by markwilliamfirth** [comment]
Reassigning @nelsonic as I remember he had drone shots

**Comment by nelsonic** [comment]
Drone video _unusable_, sadly. (_I'm not a very good pilot_)
