### ISSUE TITLE
dwyl.com emails

### ISSUE THREAD

**Issue by ghost** [dwyl/hq#365]
Hey everyone!

All of your emails have now been upgraded from .io to .com

You’ll still receive emails to your @dwyl.io suffix in your .com inbox. If you wish to also have the option to send emails from the .io email as well as the .com email please follow these instructions to activate that [here](https://support.google.com/a/answer/22370).

You should use your dwyl email for work purposes - all external communication with clients and for any communication about projects. This is important because some of our clients' contracts have confidentiality agreements. Your dwyl email also gives you access to [the shared dwyl Google Drive](https://drive.google.com/drive/folders/0B0XeQ2t5WSK2Tll4Sm0xcm1Pcmc).

In order to set up your email correctly, please could you:

- Add a profile picture to your gmail

- Add [this](https://docs.google.com/document/d/1ZRBwhb1oZtTNfRXRHy_j2jO8BLfPtS3CaugRmvhnzZM/edit?usp=sharing) signature to your gmail (feel free to omit information you do not wish to share)

- [x] @iteles 

- [x] @nelsonic 

- [x] @SimonLab 

- [x] @Cleop 

- [x] @Danwhy 

- [x] @RobStallion 

- [x] @finnhodgkin  

- [x] @rub1e

- [x] @harrygfox

**Comment by iteles** [comment]
I have two versions of my signature - one with my mobile and one without (because there are a few people I don't want to have my number!). 

@markwilliamfirth I've also elected not to put my 'job title' in as I don't tend to use it much. Is this problematic in terms of branding?

**Comment by markwilliamfirth** [comment]
@iteles I've updated to say feel free to omit information you do not wish to share 👍 

Main point here is just for us all to have consistent branding across emails and also to publicise our twitter and github more

**Comment by markwilliamfirth** [comment]
@naazy, @SimonLab, @Cleop, @Conorc1000, @Danwhy, @harrygfox, @jackcarlisle, @katbow, @nogainbar, @RobStallion, @roryc89, @shouston3, @sohilpandya

A reminder to please tick yourself off on the top comment here once you've completed this!

**Comment by Danwhy** [comment]
Done, but I can't edit the top comment

**Comment by markwilliamfirth** [comment]
@Danwhy thanks! Didn't realise some people couldn't edit the top comment. For those reading, if you're unable to please comment below and I'll tick you off.

**Comment by markwilliamfirth** [comment]
Hey everyone - please let me know when you complete this

**Comment by harrygfox** [comment]
I couldn't complete this - my dwyl email signature doesn't show up when I use 'send from' my main email

**Comment by markwilliamfirth** [comment]
@harrygfox I think there's a way round this in settings - let's do it next time we're both in Focus Hub

**Comment by rub1e** [comment]
Hey @/all, just checking in about `email signatures` ✉️ 

*I'm sure you all did this six months ago*, but just so I have the most **up-to-date information**, could you all send me an email from your `dwyl` account with your signature on it please? 🔣 

Obviously you **don't** *have to* include your `job title or phone number` if you don't want to. I've no idea where such notion came from - spooky 👻 

I'll tick you off the list once I've received your email 👍 👊 ✊

**Comment by rub1e** [comment]
@naazy @SimonLab Can you take a look at the above when you have a moment - would be nice to have all permanent dwylers ticked off...

**Comment by rub1e** [comment]
We've moved! I've updated the signatures document with our new address, but Google hasn't processed the move yet so the link to our Google Maps entry has been removed for the time being

I've also removed people not *currently* working on dwyl projects from the list in the top comment for ease 

I won't start chasing people until we have the correct 🗺  link, but if anyone sees this in the meantime do update your signature

**Comment by rub1e** [comment]
Chased all dwylers who have dwyl emails, will tick off as they prove to me they've done it. `Trust but verify`

Will add this to the #214 checklist

**Comment by rub1e** [comment]
What a good bunch we are - all ticked for now 😄 

Closing until we have someone new to induct, or if any other changes arise
