### ISSUE TITLE
dwyl fridays - elm dojo?

### ISSUE THREAD

**Issue by naazy** [dwyl/hq#368]
@katbow's elixir dojo #345 was such a hit last week (thanks @katbow ❤️ 😍) that I thought I'd suggest running an elm dojo for one of our dwyl fridays (hopefully with the help of the campbell brothers @Conorc1000 @roryc89?)

The next dwyl friday is over dwyl summer 🌤 🌻 🐳  so unsure if we would want to do it then or later in the year but thought i'd put this out there into the universe 🌏 now anyway 

Is there a general appetite for this? If so please add a ❤️ to the post

**Comment by iteles** [comment]
@naazy Still up for doing this next Friday?

**Comment by naazy** [comment]
Am keen @iteles although will have to be sometime this week instead 🤓 

Have recruited @Conorc1000 to get involved also.

Watch this space https://github.com/dwyl/elm-dojo

**Comment by iteles** [comment]
I think we might have to leave this til you're back in the UK as this week will be pretty tight with people taking a few days off here and there as well as some water sports mornings!

**Comment by markwilliamfirth** [comment]
@naazy I would suggest Sep 8th or Sep 22nd - which do you prefer? Let me know and I'll email out today

**Comment by naazy** [comment]
Let's go with the 22nd @markwilliamfirth :smile: :pray: Thanks

**Comment by markwilliamfirth** [comment]
@naazy how long do you need for this? Katherine's elm dojo was 1.5h for reference

**Comment by naazy** [comment]
Let's say 1.5 hours also then @markwilliamfirth 📿  Thanks

**Comment by markwilliamfirth** [comment]
This has been sent out
