### ISSUE TITLE
Key to Focus Hub

### ISSUE THREAD

**Issue by finnhodgkin** [dwyl/hq#369]
I sometimes arrive before anyone else and can't let myself in (no key). It's fine at the moment because I just pop to the park with a book. Probably wouldn't be so pleasant in the rain :sweat_drops: 

@ZooeyMiller has a key and I'm happy to cut a new one from his if that's okay. Thought I'd check first because I'm guessing dwyl are more security conscious than our friends next door...

(Is this the right place for this?)

**Comment by iteles** [comment]
@finnhodgkin I reckon we have spares! I'll try to find one a little later today!

**Comment by markwilliamfirth** [comment]
@finnhodgkin if @iteles doesn't have one let me know and I can get you one cut - any issues with FH in future you can post them here: https://github.com/dwyl/focushub/issues/new 👍

**Comment by iteles** [comment]
@markwilliamfirth We ran out of keys, so please get a few more cut 👍

**Comment by markwilliamfirth** [comment]
@finnhodgkin you still need one right?

**Comment by finnhodgkin** [comment]
Yes please! Thanks guys :heart:

**Comment by markwilliamfirth** [comment]
@finnhodgkin I've got one cut for you this morning, so just come and grab one! I'm in No. 16 today 👍

**Comment by finnhodgkin** [comment]
Cheers @markwilliamfirth I'll pop over in a few :+1:
