### ISSUE TITLE
 Utilisation Rate

### ISSUE THREAD

**Issue by ghost** [dwyl/hq#374]
Linked to https://github.com/dwyl/hq/issues/321

Utilisation Rate for each person in the team/company

@nelsonic can you confirm that this is the utilisation rate on client projects to the nearest half hour divided by a 35h week?

**Comment by markwilliamfirth** [comment]
@nelsonic 🙌 not sure if you saw the above q so thought I would post again

**Comment by nelsonic** [comment]
Yes, utilisation is based on statutory working hours (35h/week).

**Comment by markwilliamfirth** [comment]
@nelsonic statutory maximum working hours are 48 hours a week. The reason I asked to confirm if you meant 35 hours or not is because our contractor contracts are 7 hours a day and our supplier agreements provide for 7 hour days. Whereas our employee contracts are 40 hours a week.

**Comment by nelsonic** [comment]
Yes, EU Working Time Directive is 48h/week, 
so technically it would not be "_unreasonable_" for us to `expect` people to work 48h/week, 
however we don't; we prefer people to have a "work-life-balance_ 
and therefore only expect 35 hours of (_effective_) work per week.
The remaining 5h (to make up 40h/wk) should be spent on learning, spikes or internal work. 

AFAIK we only bill clients for **7h per day** (_and don't charge "over time"_).
Therefore developers should log 7h per day in order to determine their "utilisation" 
(7h x 5 days = 35h/week)

**Comment by iteles** [comment]
@rub1e Let's take a look at how best to get step one of this done this week please, it's been an open `priority-1` issue for the last 9 months. 😒 

+ [ ] Figure out what we need in terms of Xero/spreadsheets/info to get this done
+ [ ] Gather info and send out support queries where/if needed
+ [ ] Get it done (to be expanded on of course) 😊

**Comment by rub1e** [comment]
We can split Utilisation Rate (UR) into two:
* Resource - how much of their time are people actually spending working
* Billable - how much of the time are people actually spending working on billable projects

So, following https://github.com/dwyl/hq/issues/374#issuecomment-346059915, we'd start with contracted hours of 40h/wk, multiply it by 52 weeks, take off holiday allowance & public holidays, and the result would be our **baseline hours**.

So then the task is just to figure out how many hours the employee has worked (resource), and how many they've worked on client projects (billable) - and divide that by the baseline to get their utilisation rate.

#### Freelancers

The above works is a fairly simple estimation of how utilised people are *based on their contracted hours* - so obviously that works just fine for *contracted employees*.

But for freelancers, that's less obviously helpful as their **resource UR** should be 100% and their **billable UR** is the same, except for a few freelancers who've worked on internal non-billable projects.

So my question to you, @nelsonic, is how are you wanting to use the results of this?

Instinct is that something like *per-project profit* rate would be more usable data than UR when it comes to freelancers, but if you had something else in mind, or if I've got the wrong end of the stick, just let me know 😺

**Comment by rub1e** [comment]
I should have closed this a while ago - Nelson agreed verbally with https://github.com/dwyl/hq/issues/374#issuecomment-363835287, so this is closed in favour of #373
