### ISSUE TITLE
dwyl Case Study Format

### ISSUE THREAD

**Issue by ghost** [dwyl/hq#378]
Linked to #274 & #377 

- [x] Desk research on "competitor" agencies' approach to portfolios
- [x] Create rough 'n' ready mockups of portfolio slide templates
- [x] Confirm template
- [x] Create blank templates for reuse

~~Mark to review case study format and suggest a new, better format~~

**Comment by markwilliamfirth** [comment]
I think the current format on the new site is good enough for now

Viewable here:
http://127.0.0.1:8000/redesign/cs-emf.html

@iteles when would you like the review of the format to be done by?

**Comment by rub1e** [comment]
- [x] Desk research on "competitor" agencies approach to portfolios
- [ ] Create rough 'n' ready mockups of portfolio slide templates
- [ ] Confirm template
- [ ] Fill gaps in [case studies spreadsheet](https://docs.google.com/spreadsheets/d/14fFQDGqhmucMQfkshR_8zdeZuZlhn8Rf1mFyXhi4Yi8/edit#gid=0)
- [ ] Write up each case study

**Comment by rub1e** [comment]
Starting on mockups of templates, process to take max 1hr, output of slides with copy but minimal design

**Comment by rub1e** [comment]
With the format approved in Google Slides, is this issue ready to close @iteles ?

**Comment by iteles** [comment]
@rub1e Would love to see the write-up of your findings from your desk research in here first and then very happy to close!

**Comment by rub1e** [comment]
@iteles ah yes of course - I had started writing a longer issue in https://github.com/dwyl/process-handbook combining notes on format and content together just so it's not stuck at the bottom of a couple of different issues, and that seemed a sensible place for it. 

But I haven't pressed submit yet so can copy and paste it to wherever you think it belongs (soz, should have mentioned y'day!)

**Comment by rub1e** [comment]
## Notes from desk research into case studies

After looking at examples from other, similar orgs, we've identified some good and bad practices and sketched out a general approach to writing them up, whether for a pitch deck or the dwyl website.

### Things we like

* **Quotes from the client** (as long as these have been approved). Some clients like a hand with areas to focus on, so be helpful and proactive with suggestions
* **Stories**: a bullet-point list of the modules we used is useful to some people, but the best case studies tell a _story_. What journey did we go on? What did we learn? What will we go on to do differently?
* **Emotional connection**: why did we love the project? A good cause, an opportunity to learn, inspirational, receptive client open to open-source etc.?
* **Works for all audiences**: some of the most easily-digested case studies have an informative, at-a-glance title, a page/screen with topline info about the project and the challenges we faced, and then more detailed technical info further down. Providing busy people with essential info up-front, but also providing details for the techie stakeholders
* **Personality**: dwyl is one of the most human companies out there - personality should definitely come through
* **Positioning the business**: some case studies just talk about getting a brief and delivering it on time; that's great and all, but dwyl offers more than that - **dwyl**ers are problem-solvers, workshoppers, collaborators - more of a *strategic partner or trusted adviser* than just a group of people who write code.
* **Client context**: linked to the point above, it's good to show that we understand the context we're working in - that we understand our clients' businesses and know how our work fits in with their strategic aims. (Again, not just "we got a brief and we delivered the product".)

### Things we didn't like

* **Meaningless words**: if you write twaddle and nonsense, people will think you're a nonsensical twaddler. There is almost literally no reason to use the words *synergise* or *utilise* or *blue-sky*. dwyl is better than that.
* **Too many words**: big blocks of unbroken text are off-putting and probably don't get read anyway

**Comment by iteles** [comment]
>  dwylers are problem-solvers, workshoppers, collaborators - more of a strategic partner or trusted adviser than just a group of people who write code. 

❤️ So much this.

**Comment by iteles** [comment]
Question on our current format:
Are we making the solution evident enough?
I wrote the whole HL case study and then had to go back at the end to insert a paragraph in the 'Technology' section on what the application was because I realised I hadn't actually talked about it yet 😆

**Comment by rub1e** [comment]
@iteles As discussed, I think this was more an issue of me not talking about the product enough rather than a flaw in the format :wink:. (But I've put that in bold in the template instructions!)

**Comment by iteles** [comment]
Done and closed. We have a starting point and can open a less noisy issue for improvements when we come to the next one.
