### ISSUE TITLE
RAF Museum Centenary celebrations 'online collection'

### ISSUE THREAD

**Issue by iteles** [dwyl/hq#384]
We received an invitation to tender (1  of 10 organisations) for a project on working with the RAF Museum on their centenary celebrations in 2018. It would have consisted of allowing the museum to display information about all their exhibits across an array of different devices, for display in the museum, access through a mobile application for the public and mobile tablets for museum tour operators.

However, no issue was opened to discuss this work and when the initial brief was read, it wasn't  noted that there was a requirement to confirm an intent to tender. As such, when our detailed questions were sent to them by the question deadline, they were disregarded (in fact, they were answered but the answers were sent out to all the tenderers who had noted their intent to tender rather than us).

Next time.

**Comment by markwilliamfirth** [comment]
@iteles what happened with this one? Did you guys send questions in?

<img width="775" alt="screen shot 2017-09-05 at 12 39 21" src="https://user-images.githubusercontent.com/5732209/30057539-5d606e30-9237-11e7-872f-e1fb563cd6fd.png">

<img width="775" alt="screen shot 2017-09-05 at 12 39 32" src="https://user-images.githubusercontent.com/5732209/30057538-5d598548-9237-11e7-9619-f7776f4e475c.png">
