### ISSUE TITLE
Claiming expenses

### ISSUE THREAD

**Issue by naazy** [dwyl/hq#389]
@markwilliamfirth My understanding is that when a contractor claims expenses for something (e.g. MS office), they have to add the expense to their invoice.

What's the process for a **full timer** claiming an expense? Do we invoice also?

**Comment by iteles** [comment]
@markwilliamfirth This is a pre-approved expense as the OA team required a specific tool to enable them to carry out the project work. This was discussed and agreed with me ahead of time.

**Comment by markwilliamfirth** [comment]
@naazy just submit through Xero (I've sent you an invitation)

https://docs.google.com/a/dwyl.com/document/d/1SeXnzTD4P-Ley-RfcEpM4X5aYgjB8SN9mwywtXMPi-o/edit?usp=sharing

**Comment by markwilliamfirth** [comment]
Linked to #123 https://github.com/dwyl/hq/issues/191

**Comment by naazy** [comment]
Thanks @markwilliamfirth  👍

**Comment by naazy** [comment]
Closing issue because question has been answered ❤️
