### ISSUE TITLE
Register Trademark for Logo

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hq#39]
I know this is off-topic for our [**24h** **_#WebSummit**_ **Hackathon**](https://github.com/dwyl/dwyl.github.io/milestones/WebSummit), however I think the logo is pretty good and I would not put it past someone to copy it...

I did the last trademark reg so don't mind doing this one... let me know.

**Comment by iteles** [comment]
I would say that next week we need to sit down together and brain dump all of the many tasks that need to happen and haven't been catalogued in GH issues yet, then we can split them up according to our strengths.

We also need to define what we mean by priorities :wink: https://github.com/dwyl/tudo/issues/140
I've changed the priority here to priority-2 as we won't be doing this _this week_, hope that's ok :ok_woman:

**Comment by nelsonic** [comment]
@iteles are we going to invest some time in this...?

**Comment by iteles** [comment]
Errrrr... yes.

**Comment by nelsonic** [comment]
Cool. sounds like you've got this. let me know if you need anything from me. :wink:

**Comment by iteles** [comment]
Did you do any research into what is required for a trademark back when this issue was opened? Just let me know if you already have anything!

**Comment by nelsonic** [comment]
@iteles the process for registering a logo trademark is *similar* to the word.
But the peeps at London IP need to tell you what the deal is with the others who are ripping it off...

**Comment by nelsonic** [comment]
@iteles, as noted by @harrygfox our logo is _already_ being used by some other company in Australia... we need to _pay_ someone to take care of the paperwork to trademark it in the UK!
@jackcarlisle are you _interested_ in finding out a bit more about intellectual property (_helping us with this non-coding task_)...?
(_this might be relevant to you if you are going to get into "**Private Labelling**" on FBA and want to "protect" your brand_...)

**Comment by iteles** [comment]
Closing in favour #93 where the latest info on this has been captured.
