### ISSUE TITLE
R&D Projects Percentage Estimate

### ISSUE THREAD

**Issue by ghost** [dwyl/hq#391]
We need a percentage estimate per project for how much of the work might be eligible for R&D. Just an estimate at this stage.

Urgent because I am meeting with our accountants next week to discuss our claim and will need to review it beforehand and prepare in advance.

Linked to https://github.com/dwyl/hq/issues/112

**Comment by iteles** [comment]
Apologies @markwilliamfirth, I didn't see this in the sea of priority-1s assigned to me.

When is your meeting?

**Comment by markwilliamfirth** [comment]
@iteles it was meant to be today, but I cancelled it

**Comment by iteles** [comment]
In that case, I'm supposed to have been on offline these last 2 days and the next 2, so I will do this next week.

**Comment by markwilliamfirth** [comment]
@iteles are there any updates on this one?

**Comment by iteles** [comment]
Prepped some of this for our meeting with the R&D firm today. 
We will take a half day with @nelsonic in early January to go through all of our projects and do this with them onsite, so that there are no doubts around what is eligible for R&D claims or not.

This day will be booked in the next few weeks.

**Comment by iteles** [comment]
Changed the label as this is more accurate.

Steps:
+ [ ] Receive dates from R&D firm for technical onsite interview (they can't do one before January)
+ [ ] Book interview with @nelsonic 
+ [ ] Receive results from this interview which will also help understand which financial information they may additionally need.

**Comment by iteles** [comment]
Met with our consultants today and awaiting the spreadsheet for estimates.

**Comment by iteles** [comment]
This issue is full of `noise`.

Closing it in favour of the clearer #438, with reference to this issue for historic purposes.
