### ISSUE TITLE
Coop PDFs

### ISSUE THREAD

**Issue by markwilliamfirth** [dwyl/hq#393]
@iteles please could you send me the coop bank statements for 2017?

Linked to #339 #229

**Comment by iteles** [comment]
@markwilliamfirth I'm on unsecure wifi until tomorrow so can't send them until then.

You have them until the end of April 2017, so do you need them for the current financial year too?

**Comment by markwilliamfirth** [comment]
@iteles yep please send them all if you can!

**Comment by iteles** [comment]
Up until April 2017 re-emailed to you @markwilliamfirth .
I still don't have a secure internet connection (well, not one I trust with our banking data), so the rest will have to wait until Monday. Is that ok?

**Comment by markwilliamfirth** [comment]
@iteles yep

**Comment by iteles** [comment]
Back on a secure internet connection and email April 2017 to now to you today 👍
