### ISSUE TITLE
Reasons for Open Source vs Closed Source

### ISSUE THREAD

**Issue by ghost** [dwyl/hq#396]
Hi everyone!

I'm in the process of creating [a document](https://docs.google.com/document/d/1xCw6w2EUY2IGCdSN9w9mOaCR7znpJqAMbRNdTPNgKg0/edit#heading=h.srw3kuaiy86x) that outlines the following:

- Benefits of open source vs closed source
- Cons of open source vs closed source
- Benefits of closed source vs open source
- Cons of closed source vs open source
- Examples of successful commercial open source projects

If you have any points / ideas / knowledge on the above that should be in this doc then please share!

(10 assignee limit hit, but everyone is welcome to contribute)

**Comment by markwilliamfirth** [comment]
@iteles please could you review this document? I need to send it to Amanda as soon as possible (feel free to use google docs review features)

**Comment by markwilliamfirth** [comment]
https://github.com/nayafia/lemonade-stand

**Comment by iteles** [comment]
Closed in favour of the original issue, no need to duplicate: https://github.com/dwyl/dwyl-site/issues/77

**Comment by nelsonic** [comment]
It never ceases to _amaze_ me that 🙊 thought it was a _good_ idea to:
a) open a `duplicate` issue _without referencing_ the original. 😕 
b) ported over _none_ of the context (_given their **complete** lack of experience with OpenSource!_)
c) make the `draft` in **Google Docs**...! which _totally_ missed the point of OpenSource
and gave _zero_ examples of companies _using_ Open Source for "enlightened self-interest". 🤦‍♂️ 

Seriously, this is/was the _definition_ of "busy work". 💸 🔥 💔 
There is _so_ much _actual_ work with _real_ value to the company to get done ... 😫 

@iteles thanks for _closing_ this and returning attention to the _original_. :hammer:

Perhaps someone who has actually _written_ some code 📝 
and _published_ Open Source modules that others _use_ :shipit: 
should write the Blog post ... ? 🤔

**Comment by claireinez** [comment]
@nelsonic please would you reconsider your tone when discussing an ex-employee in public? It makes me very uncomfortable that you would talk about anyone like that in an open forum, let alone someone you worked with. Comments like the above come across to an outsider as unprofessional and reflect poorly on you and on dwyl, and I would really appreciate if you would keep that in mind when writing.

**Comment by nelsonic** [comment]
@claireinez, please excuse me letting out my "_frustration_" in `public`.

I _agree_ that it's _not_ desirable to "speak badly" about _anyone_.
Given that the person `deleted` their GitHub account, 
_most_ people in the _community_ have _no idea_ ***who*** is being referred to; which is a _good_ thing!

Let me be _clear_: I am not _attempting_ to discredit/disrespect the ***person***, 
simply to point out that _re-creating_ a task (_that already existed elsewhere_)
without adding any _value_ to the task description, is a _waste_ of time; 
I'm _sure_ you would agree purely on an _efficiency_ basis.

> What would you _recommend_ as alternative way of sharing this with people in the _company_/_community_ so that it does **not _re-occur_**? (_in light of the fact that we don't have a "private/internal forum" and believe in "openness" over gossip and two-facedness_) ?

The employee in question ***wasted*** _significant_ company resources
(_way beyond their "salary", considerable time/frustration of the CEO, whose time is badly stretched, having to re-do work ... taking **months** to **not*** deliver the **basic** tasks assigned ... 
all the while working on unrelated "**side-projects**" ..._) 

We could take the approach of "ignoring" it, but then **_nothing_ would _improve_**!

If you or _anyone_ in the community is _uncomfortable_ by what I have written it can easily be _deleted_.

> Ask _yourself_ the question: 
If it were _your_ company/"baby" (_and you had worked hard to make the money to self-fund it_),
and somebody _wasted_ your time/money instead of doing the _high priority_ work,
How would you _feel_...?
Would you "take it on the chin" as a "learning experience", keep quiet and "move on"?
If the person's total disregard at following (the CEO's) instructions lead you to _tears_ of desperation,


> Congrats on your new job at Deliveroo BTW!  🎉

**Comment by nelsonic** [comment]
"**unprofessional**" is someone hired to do a job (_generously paid **50% more** than their previous job_) 
***not delivering*** the (_well defined_) tasks assigned, causing _more_ work for everyone, while spending the majority of their "**company time**" on un-related "***side projects***". 

> _I'm trying **not** trying to "**disrespect**" the **person**, 
> I am pointing out that the **task** was **not performed**
> and that in future, people should not re-open issues just for the sake of it
> while not **delivering** the actual work._

`try` to put yourself in the shoes of a self-funded entrepreneur who has their time/money wasted by someone who is ***highly intelligent*** but doesn't _want_ to do the _work_ and instead _fights_ against their _boss_ at _every_ opportunity.

The person in question is one of the _smartest_ people I know.
But they have an "agenda" and are _really_ good at making _sure_ everyone knows _their_ side of the "story".
The side _you_ (_and other people in the community_) are _not_ aware of
are the _many_ nights of ***tears*** of _frustration_ & insomnia of the CEO while the person continuously "_fought_" against doing any _work_ for the company.
(_if you are **actually** interested in knowing the **full** detail, ask Inês, trust me, you will **cry** too_!)

Imagine if you placed an order with a **tasty paleo food delivery service**, 
you order a ***specific*** dish which you are _assured_ does not have nuts (_which you are allergic to_).
The dish you _ordered_ ***never arrives***, but instead they sent something `else` that _does_ contain the "allergen", you unknowingly consume it and end up in A&E suffering from anaphylactic shock.
_How_ would you _feel_?
Would you write a "review" online in a `public` place so others _knew_ about your _experience_?
Or would you keep quiet and let the offending service _continue_ to take unsuspecting people for a ride?

Imagine that you paid a "decorator" to re-paint your flat and they made lots of _promises_
but then after partially completing the job in a paint-colour that was _nothing_ like what you agreed,
and then walked away with your money and left a _mess_ for you to clean up.
Would you write on the `public` "trade" forum to _warn_ others about the "person",
or "write-off" the £'000's keep "episode" to yourself...?

> I could write _anonymous_ blog posts about the past year, but then **_nothing_ would _improve_**.
> What I _want_ is that this kind of _time-wasting_ busy-work ***never*** happens again. 

The person in question has `deleted` their GitHub account so my _fact-based_ comment, 
is not "tied" to them in any way and will not "_affect_" their "future prospects". 
I _genuinely_ wish the person all the very best of luck in the future 
and hope they find work they love doing!

If my _candour_ "reflects poorly" on dwyl, _anyone_ is **free** to `edit` or `delete` my comments. 
If I _offend_ people there are _two_ options:
a) I can turn up my self-censor and avoid writing/saying _anything minimally_ "controversial".
b) everyone should just _ignore_ what I write.

**Comment by iteles** [comment]
@claireinez I’m glad you felt that you were able to voice your concerns and bring this to our attention.
I understand your concern both for the somewhat anonymous party referred to here and for the direct tone adopted and how this reflects on the organisation as a whole.

There are certainly both different ways of phrasing the key message here around process learnings that need to happen and more appropriate forums in which concerns of the remaining nature can be expressed.

More than anyone, I very much empathise with @nelsonic's frustrations - even without the full context, as may be obvious, this is about much more than just a duplicated issue. This is not the forum for it.

Let’s keep it focussed on the learning from here on out 👍
