### ISSUE TITLE
Buying Sparkfun sound detector

### ISSUE THREAD

**Issue by naazy** [dwyl/hq#398]
In order to accurately measure the sound in the room, I believe we will need this sparkfun sound detector:
https://shop.pimoroni.com/products/sparkfun-sound-detector-with-headers

I've been trying to do it with an Electret microphone but i'm only able to make the sound detection work when i'm screaming into the microphone. This isn't ideal for measuring the sound in focushub. A number of sources including  https://electronics.stackexchange.com/questions/269005/how-to-hook-raspberry-pi-with-electret-microphone-to-detect-sound-levels-in-db and http://toribeiro.com/articles/2016-01/sound-level-meter-using-esp8266-arduino-sound-detector suggest that the best and most accurate way of detecting noise is to use a detector with an envelope output.

Have just purchased and got confirmation from @iteles that I'm okay to expense it

Linked to https://github.com/dwyl/learn-iot/issues/2 and https://github.com/dwyl/iot-decibel-meter/issues/11

**Comment by iteles** [comment]
Perfect, thanks @naazy !

**Comment by iteles** [comment]
@naazy Assigning this back to you so you can close it when it arrives.

You'll already know how to claim this from here: https://github.com/dwyl/hq/issues/389#issuecomment-330843952

**Comment by markwilliamfirth** [comment]
@naazy did this arrive?

**Comment by naazy** [comment]
Yes it has arrived @markwilliamfirth. Any chance you could reinvite me to xero? My invitation has expired :pray: thanks

**Comment by markwilliamfirth** [comment]
@naazy sent!
