### ISSUE TITLE
Can we automate payment of dwyler invoices?

### ISSUE THREAD

**Issue by iteles** [dwyl/hq#399]
* [x] Ask Xero why their batch exports don't work on the Santander system (this was because they don't support BACS at all)
* [x] Test batch payments using "Faster Payments" system in Santander on next pay run
* ~Resolve between Xero and Santander how to export batches from Xero and import into Santander~

At the moment, @markwilliamfirth has to go in every week and _manually_ pay all dwyler invoices. This process also involves an OTP which is even more time consuming.

This is hugely time consuming and a _total_ waste of Mark's time.

Is there a way we can automate these payments? Or make the process more efficient? Maybe through Xero? Or by using a different bank for paying out?

**Comment by markwilliamfirth** [comment]
https://teller.io/

https://help.xero.com/uk/Accounts_AP_AddBatch

**Comment by iteles** [comment]
If we're looking to consolidate with one bank (this seems wise) as per https://github.com/dwyl/hq/issues/26#issuecomment-339095090, is Metro bank also a good candidate for this issue?

**Comment by markwilliamfirth** [comment]
@iteles how do you mean? Metro also works with Xero

**Comment by rub1e** [comment]
Not really following what's going on here, but we can certainly bundle together payroll into a BACS export, then import it into Santander _as long as we have the appropriate Santander account_, (Connect Plus) and we might need to check with our "relationship manager" or whatever they're called.

**Comment by rub1e** [comment]
UPDATE: after going around the houses a bit, we've confirmed that we are *able* to do batch payments, but we need to apply for BACS sponsorship so we can use that system (yes, it might have been nice of Santander to inform us).

So now we need to apply and wait till we have a Service User Number (no, it's not actually documented anywhere in their help centre, since you ask) 😒

**Comment by iteles** [comment]
@rub1e This is exactly the kind of thing I was after, thanks for your diligence 🎉

**Comment by rub1e** [comment]
You spoke too soon! After a bizarre call during which I ascertained that the person who told me we could do BACS payments had probably misheard me and said we could do **BATCH** payments... we're back to manual payments.

I am, however, confident that I can set up a payment profile to do payroll all in one go, and possibly apply that to individual freelancer invoices. 

And then we can put this whole sorry time-draining affair behind us 🤞

**Comment by rub1e** [comment]
UPDATE: process as it stands is captured in the [process handbook](http://www.bbc.co.uk/sport/football/43397583)

It will be updated and this issue closed when we have resolution on importing batches

**Comment by rub1e** [comment]
The upshot is that we can do `multiple payments` in one go, but not export `batch payments`

This means that we can streamline the process to the extent that we pay everything in one go and so only require one `passcode`, but we can't just export the payments as a `csv` from Xero - we have to enter manually.

Closing until Xero supports batches for the `Faster Payments` system

**Comment by iteles** [comment]
@rub1e I agree, thank you for investigating rather than passing it back to me to investigate  👍 ❤️
