### ISSUE TITLE
Create plasticised welcome pack for guests/visitors

### ISSUE THREAD

**Issue by iteles** [dwyl/hq#4]
A few basic 'house rules' on keeping the office ship-shape plus a few notes on the surrounding areas so we don't have to keep telling guest/visitors where to buy milk, go for a meal, go for a walk, etc would be a good start!

**Comment by iteles** [comment]
Linked to #3

**Comment by nelsonic** [comment]
Good thinking *Brain*! :+1:

**Comment by iteles** [comment]
Linked to #131

**Comment by nelsonic** [comment]
Linked indeed... 😉 
I cannot tell if that's an _endorsement_ for the idea of a "New Joiner Welcome Pack" or just a logical linking... 🤔

**Comment by nelsonic** [comment]
I still think this is a _really_ good idea. _Why_ was the issue closed? is it _done_?

**Comment by nelsonic** [comment]
_Apparently_ this issue has been moved to: https://github.com/dwyl/focushub/issues/57
(_although that issue currently has **no description** so it's not clear at all_)
Linking back to an issue that looks _closed_ without any clarification is:
![image](https://cloud.githubusercontent.com/assets/194400/26147860/c4f200d8-3aec-11e7-8090-4bb3d181db18.png)

**Comment by markwilliamfirth** [comment]
@nelsonic was closed in favour of https://github.com/dwyl/hq/issues/131 and https://github.com/dwyl/focushub/issues/57
