### ISSUE TITLE
What is your One Metric That Matters?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hq#40]
Given your learnings on #OMTM [_yesterday_](https://twitter.com/iteles/status/662293924405518336)
what do you think yours should be for the next week?

**Comment by nelsonic** [comment]
I asked you this *early* on Saturday morning but you were not in the frame of mind to think about it...
Have you had a chance to consider what your **#OMTM** is for this week?

**Comment by iteles** [comment]
I think this week it should be a roadmap. The metric is its existence.
I know that it's not a metric _per se_, but it's the most important thing before any 'standard' _analytics_ metrics.

What do you think yours will be?

**Comment by markwilliamfirth** [comment]
Discussion continued #149
