### ISSUE TITLE
Christmas Party / Meal 🎄

### ISSUE THREAD

**Issue by Cleop** [dwyl/hq#400]
I really enjoyed the March dinner #213 and think it would be a good idea to have another get together / meal at Christmas 🎄 ☃️ 

My suggestion would be a meal at FocusHub on an weeknight evening in the first half of December 2017. We can either pick out an arbitrary date or run a doodle poll if people's availability is already looking patchy. My first arbitrary date suggestions are Weds 6th or Fri 8th Dec.

This is just an idea so feel free to chime in with suggestions of food or games or other!

**Comment by naazy** [comment]
Werewolf!

**Comment by markwilliamfirth** [comment]
@Cleop I've moved this event to the new events repo here: https://github.com/dwyl/events/issues/4

Everyone who sees this please go to the new issue and follow the new repo if you're interested in events!

**Comment by iteles** [comment]
Reopening this as very few people see closed issues.

**Comment by iteles** [comment]
Invite sent out! I hope everyone got it 😊

**Comment by iteles** [comment]
Done!
