### ISSUE TITLE
Impacts of hapi v17 for existing dwyl plugins

### ISSUE THREAD

**Issue by iteles** [dwyl/hq#401]
With hapi v17 coming out this week, we are beginning to receive questions from our community (see  https://github.com/dwyl/hapi-auth-google/issues/51 and https://github.com/dwyl/hapi-auth-jwt2/issues/248).

There are a few people in the dwyl community who are happy to contribute and submit PRs to make sure our plugins now work with hapi v17, but given how different v17 is to previous versions of hapi, in order to do so, dwyl should provide some insights into how this is best done. This will ensure their work in PRs is not wasted. Do we want to have a different repo/module for v17 and keep our current `master` branches as they are or do we want to have just one with release notes around which version to use for older versions of hapi for example?

@nelsonic Your insight on this would be much appreciated.

**Comment by nelsonic** [comment]
@iteles we will update and release a new _major_ version as required.
I am _happy_ to accept pull requests from the team/community especially people who are _currently_ working on a project that uses Hapi in production. 

>_**Related Question**: are we updating **client apps** to Hapi v.17 ...?_

**Comment by iteles** [comment]
@nelsonic We're not updating client apps to hapi v17 yet as we're mostly waiting for it to be stable and plugins we are using to be updated, e.g: https://github.com/emfoundation/ce100-app/issues/981
This decision will be revisited with our clients in 2 months or so.

We will only be maintaining one version of each module as required then and people can use older versions if they are not using hapi v17 yet.

**Comment by nelsonic** [comment]
@iteles is this still relevant?
