### ISSUE TITLE
QL | mini sprint

### ISSUE THREAD

**Issue by iteles** [dwyl/hq#402]
QL have asked us for a mini sprint on AWS migration and load testing/performance troubleshooting.

Proposed dates: 08-Nov to 10-Nov
Proposed team members: @Danwhy @sohilpandya @eliascodes, @iteles (scrum master & client liaison)

Task list:
+ [x] Discuss requirements with PO
+ [x] Agree number of days available with both dwylers & PO
+ [x] Agree team available with both dwylers & PO
+ [x] Confirm budget to PO
+ [x] Receive green light from QL

**Comment by iteles** [comment]
Green light received. This will be a few days this week 👍

**Comment by iteles** [comment]
@markwilliamfirth Elias doesn't have a freelancer agreement with us yet, could you please create one? I'll send you over an email with the details.

**Comment by iteles** [comment]
@markwilliamfirth The development work for this is now completed. I did a little sleuthing and couldn't find a freelancer agreement in our google drive.

Could you please update this issue with whether or not one was created and then close (I don't think there's that much point in creating one retrospectively but will leave that to you)?

**Comment by markwilliamfirth** [comment]
Sorted 👍
