### ISSUE TITLE
Script to protect master branch across all dwyl repos

### ISSUE THREAD

**Issue by iteles** [dwyl/hq#403]
As per https://github.com/dwyl/process-handbook/issues/74 we need to write a well-documented script (remember that people who own organisations are sometimes now 'managers' and haven't written any code for a while!) to protect `master` branches across all dwyl repos.

**Comment by Danwhy** [comment]
Having a look into this now. What kind of protections do we want, a requirement of at least one reviewed pull request to merge into master?

**Comment by Danwhy** [comment]
These are the available protections: 
<img width="832" alt="protection rules" src="https://user-images.githubusercontent.com/8939909/32666453-5f25a9fc-c62f-11e7-86ab-1ca52d571206.png">

**Comment by iteles** [comment]
Code Owners are a relatively new thing in github, but let's try this out. Once we have the script we can always alter it!

I was thinking this would warrant a new repo? dwyl/protect-master-branch for example.
(we could evolve this to be 'protect a specific branch in specific repos when we have more time).

<img width="737" alt="screen shot 2017-11-10 at 15 52 20" src="https://user-images.githubusercontent.com/4185328/32666413-3ae7be90-c62f-11e7-8898-dae65391c28c.png">

**Comment by Danwhy** [comment]
@iteles https://github.com/dwyl/protect-master-branch/pull/2 This is ready for review now, who should I assign it to?

**Comment by iteles** [comment]
@Danwhy 🎉 To @nelsonic please! He's snowed under this week, so will probably be a slow burner 😊

**Comment by iteles** [comment]
🎉  Done! https://github.com/dwyl/protect-master-branch
Any further enhancements to be opened as issues in that repo.

Thanks @Danwhy @ZooeyMiller @nelsonic 💖
