### ISSUE TITLE
GDPR Compliance | 25 May 2018

### ISSUE THREAD

**Issue by ghost** [dwyl/hq#404]
The GDPR will apply in the UK from 25 May 2018

**Comment by iteles** [comment]
Being investigated in: https://github.com/dwyl/learn-security/issues/25

**Comment by iteles** [comment]
@markwilliamfirth Could you please action the email we got from Google on this as well?
<img width="720" alt="screen shot 2017-10-14 at 17 01 46" src="https://user-images.githubusercontent.com/4185328/31577157-7d19cd32-b101-11e7-9702-54bb8121bf7d.png">

**Comment by iteles** [comment]
https://github.com/dwyl/learn-security#gdpr

**Comment by nelsonic** [comment]
@iteles _describing_ how to comply with GDPR is not the same as _compliance_. 
In the _first_ instance each app that we have built will need a communication channel for allowing _users_ to request removal of their data.
And from a _technical_ side we should be using _encryption_ ("_at rest_") to safeguard any personally identifiable information stored by the app.
Which App/Client has specifically requested _proactive_ GDPR-compliance?

**Comment by iteles** [comment]
If I thought we were compliant, I would have closed the issue. I have just added a couple of points as reference.

OA have requested it.

**Comment by iteles** [comment]
We will build this into our apps and the issue will be transferred.
