### ISSUE TITLE
Weekly finance checks & payments

### ISSUE THREAD

**Issue by iteles** [dwyl/hq#411]
Every week, there's a financial dance that occurs in dwyl. 
_Because_ it's done every week, it doesn't take a huge amount of time, but can still be further codified, made more efficient and automated/outsourced.

As it stands, this is included:

+ [x] Check coop account (export feed, upload into Xero) & update Xero with payments made by clients through reconciliation (20mins)
+ [x] Move money across for payments (5 mins)
+ [x] Chase unpaid invoices (10mins)
+ [x] Review dwyler invoices that need to be approved (linked #300) (20mins)
+ [x] Create bill in Xero
+ [x] Pay dwyler invoices (linked #300) (30 mins)
+ [x] Create upcoming client invoices (20 mins)
+ [x] Invoice clients (20 mins)
+ [ ] Reconcile Xero - dwyler invoices against client invoices

**Comment by iteles** [comment]
Completed this morning for this week, will open again next week.

**Comment by iteles** [comment]
Completed, took just under an hour with a few interruptions.

**Comment by iteles** [comment]
@rub1e I have chased TC for the outstanding money they owe us. Will leave the rest to you 😊

**Comment by rub1e** [comment]
@iteles with your permission, I'd like to add a wider "reconciling Xero" to the list of weekly tasks

Reason being: I'm trying to reconcile a bunch of old transactions and it's taking ages making sure the multiple payments match the right invoices (not to mention when invoices are paid at the same time as wages) - as ever the longer you leave it the harder it gets. So I'd like to enforce a weekly reconciliation session for myself, to save my future self the bother.

**Comment by iteles** [comment]
@rub1e Done my bits for this week and gittered you the caveats around who to chase for outstanding invoices and who has already been in touch about them this week 👍

**Comment by iteles** [comment]
@rub1e I believe this was completed for the week but just not updated?

**Comment by rub1e** [comment]
Yep, my bad, apologies - all ticked and issue closed now
