### ISSUE TITLE
Review Xero setup with book keeper

### ISSUE THREAD

**Issue by iteles** [dwyl/hq#414]
In order to clear some of the backlog in financial tasks and getting #381 in, I am reviewing our existing setup with our book keeper.

This should also help with #383 and #382, I'll update those issues as relevant.

**Comment by iteles** [comment]
Left the `in-progress` label here until I was able to write up the findings of the day.

The following will need to be dealt with:
+ Reconciliations have all been done as 'money spent' rather than reconciling between banks or with any actual bills
+ There are no freelancer invoices or invoices of any kind from 2017 in Xero - these will all need to be uploaded manually before #406 can be done
  + Invoices can be emailed directly to Xero which speeds up reconciliation
+ VAT returns can and should be submitted directly through Xero from now on so that Xero and HMRC match (this was done for our most recent VAT return by the ihorizon accountants 👍 )
+ Coop Bank feeds can be manually updated in less than 5 mins
+ Payroll was set up correctly though dividends were not and will need to be dealt with

Documentation will need to be written once processes for this are ironed out.

Will look into #383 and #382 in more detail themselves when bookkeeper is available again in late January.

**Comment by iteles** [comment]
**Actions:**
+ [ ] Get Xero set up so that invoices go straight there where possible
+ [ ] Write up process for submitting VAT returns
+ [ ] Obviously don't pay anyone dividends before the year is over and we know if we will be turning a profit 
+ [ ] Write up process for updating Coop bank feed
+ [ ] Write up process for reconciling Xero properly.

**Comment by iteles** [comment]
> Write up process for updating Coop bank feed

Adding the images here as I go along, to be written up in readme (I'll do this once I'm done with the process)

### Get export from Co-operative Bank
![image](https://user-images.githubusercontent.com/4185328/46742115-45a2db00-cc9e-11e8-86de-120e7c233c01.png)

![image](https://user-images.githubusercontent.com/4185328/46742164-6408d680-cc9e-11e8-9be7-610e94eb3674.png)

![image](https://user-images.githubusercontent.com/4185328/46742189-6d923e80-cc9e-11e8-9219-c09c0f88684d.png)


### Updating the export
Xero will not be able to read the export just as it is so we need to update the formatting to make it compatible with Xero. 

1. Open the CSV in `Numbers` (on Mac) or Excel (on Windows)
2. Delete all of the rows apart from the field titles row and the transactions rows
  + Note that if there are a lot of transactions, you may end up with a row that says `Page 1 of 1` _in between_ the transaction rows
3. Manyally merge the `Bank Reference` and `Customer Reference` columns together so that the column you end up with contains both the client name and the invoice reference if one was given:

#### Before:
![image](https://user-images.githubusercontent.com/4185328/46742426-e8f3f000-cc9e-11e8-98cb-3b2265f35693.png)


#### After:
![image](https://user-images.githubusercontent.com/4185328/46742501-0de86300-cc9f-11e8-899e-9fa7152035a0.png)


4. Manually merge the `Credit` and `Debit` columns so that debits appear as negative values (the credits remain the same)
  + Note: All the credit figures include VAT which we pay back to HMRC but you don't have to worry about this now as it's dealt with separately in the VAT and bank reconciliation processes

#### Before:
![image](https://user-images.githubusercontent.com/4185328/46742718-86e7ba80-cc9f-11e8-96b0-ebf3da59751b.png)

#### After:
![image](https://user-images.githubusercontent.com/4185328/46742770-a1219880-cc9f-11e8-995a-46e9611f0252.png)

5. Delete _all_ columns except:
  + Date
  + Customer Reference (which now contains the information from `Bank Reference` as per step 3 above)
  + Credit (which now contains the information from `Debit` as per step 4 above)
6. Export your 3 column table to CSV
![image](https://user-images.githubusercontent.com/4185328/46743240-8996df80-cca0-11e8-97f6-fea2fc1fa941.png)

### Import to Xero

In Xero, go to the '3 dot' menu on the Co-operative Bank account on the dashboard and click `Import a Statement`
![image](https://user-images.githubusercontent.com/4185328/46743404-e2667800-cca0-11e8-81ae-489fec31300d.png)

Follow the steps to upload  & import your CSV.

**NOTE:** The first couple of times you do this and then sporadically from then on, a table will appear at the bottom of the import page - **you _must_ make sure that Xero is interpreting the lines correctly**.

For example, in the screenshot below, Xero recognised that the first column was the transaction date correctly but couldn't recognise the second column:
![screen shot 2018-08-01 at 11 52 30](https://user-images.githubusercontent.com/4185328/46743677-7fc1ac00-cca1-11e8-98d8-dbd02d785a45.png)

Choose the correct column name from the drop-down menu (in this case, description of the transaction):
![screen shot 2018-08-01 at 11 52 45](https://user-images.githubusercontent.com/4185328/46743649-6e789f80-cca1-11e8-821a-9014bca0a551.png)

### Success!
![image](https://user-images.githubusercontent.com/4185328/46743845-d16a3680-cca1-11e8-9295-a71d5fb529d2.png)

**Comment by rub1e** [comment]
@iteles check you out - loving it!

If you want to just confirm you're happy with it, I can add it into the `md` file (unless you're keen for the green square... 😉 )

I'm thinking of just slicing this and the Xero reconciliation off into its own guide as the general `finances` one is getting pretty long!

**Comment by iteles** [comment]
Haha, no it's fine, I need to add some wording around the first bit, might as well do it straight into the readme.

YES, I think the finance.md needs some more organisation, happy for it to be a folder of mds on finance topics rather than a file. Let's open an issue in the right repo for it 👍

**Comment by iteles** [comment]
Moved writing up the reconciliations process to https://github.com/dwyl/process-handbook/issues/128 so we can now close this issue 👍
