### ISSUE TITLE
Change Category column in Xero back to 'Category' from 'Mindwave'

### ISSUE THREAD

**Issue by iteles** [dwyl/hq#418]
The Category column in Xero was inexplicably renamed to 'Mindwave' early in our usage of Xero and has been causing me confusion since - I have been asking 'why is everything allocated to Mindwave?' for months, when actually everything has just been left un-categorised (also not good, but that's another issue).

Now that we are actually _using_ categories as we should, we need to change the name of the Category column back to category to avoid confusion.

<img width="505" alt="screen shot 2017-12-22 at 23 24 47" src="https://user-images.githubusercontent.com/4185328/34314811-a0cc3298-e76f-11e7-90f8-b44dfd529955.png">

**Comment by rub1e** [comment]
Done

Settings > General Settings > Reports > Tracking

There you can manage the Categories

**Comment by iteles** [comment]
🎉
