### ISSUE TITLE
Extension of HL SLA

### ISSUE THREAD

**Issue by iteles** [dwyl/hq#421]
We have been asked to continue with our HL SLA under the same conditions as we had for the original 8 weeks, until the end of March.

+ [x] Create SLA extension contract
+ [ ] Turn it into 'SLA with retainer' contract template

**Comment by rub1e** [comment]
This will be templatified once it's signed / any amends are incorporated

**Comment by iteles** [comment]
Woah @rub1e, quick work of this `priority-1`  🎉 🙌 

Closing this one and opening a separate one on the template so it's not 'hanging' https://github.com/dwyl/hq/issues/422
