### ISSUE TITLE
dwyl invoicing | Multiple emails being sent 

### ISSUE THREAD

**Issue by iteles** [dwyl/hq#423]
Currently a bug in dwyl invoicing where multiple emails are being sent with each invoice that's generated.

<img width="438" alt="screen shot 2018-02-01 at 11 51 44" src="https://user-images.githubusercontent.com/4185328/35677125-56b44b7c-0746-11e8-92b7-a0b2df2ed772.png">

The good news is that it only seems to generate one invoice, but sends it multiple times.

Only started happening in the last week.

**Comment by rub1e** [comment]
Having explored, there's no obvious reason this is happening, and it didn't happen when I tried to reproduce the bug. 

It's not a known issue so I'll have to do a little digging, perhaps open an issue on their... `google plus` community :worried:

**Comment by iteles** [comment]
Three more have come through and don't present with this bug so I'm closing for now!

**Comment by rub1e** [comment]
Reopening as I've just figured out what's going on here... ish.

The invoice I just submitted was duplicated twice - one with me as owner, one with Ines, and one with Finance.

Don't know *why* this is happening, but it's a start!

**Comment by sohilpandya** [comment]
Hey Hey! Just letting you know it is still happening. :)

**Comment by rub1e** [comment]
There was a recent autocrat update and I've not seen the problem recently, so I'm closing until it comes back 🤞
