### ISSUE TITLE
Can CharlieHR be retired in favour of Xero

### ISSUE THREAD

**Issue by rub1e** [dwyl/hq#425]
* [x] Investigate if Xero can be employee-facing so people can do holiday stuff there instead of having two systems 
* [x] Investigate how we can manage both employees' and contractors' time off within a single system
* [x] Transfer staff holidays to `Xero`
* [x] Set `Xero` to track holidays properly
* [x] Transfer any existing booked days from freelancers to `HR.my`
* [x] Set up freelancers on `HR.my`

**Comment by iteles** [comment]
I entirely understand CharlieHR's need to take this step of charging for their product and even applaud how they are handling it. Much respect.

However, seeing as how this task is already on our list, I would like to explore it in an effort to minimise the number of systems we use (as @rub1e mentioned originally) - there's no way we can get rid of our accounting system for Charlie unfortunately!

Received today:
<img width="639" alt="screen shot 2018-02-27 at 17 45 42" src="https://user-images.githubusercontent.com/4185328/36745076-5dcb322c-1be6-11e8-86e3-2fc94cf829d0.png">

**Comment by iteles** [comment]
Free when you've already paid, hey? 😊 

Let's go through the process to make sure it's feasible and then yes 👍

**Comment by iteles** [comment]
Tested this morning, we need to set up 'Time Off Types'
<img width="426" alt="screen shot 2018-03-26 at 12 02 57" src="https://user-images.githubusercontent.com/4185328/37902888-cf76fc28-30ed-11e8-9446-4397dfd50ac5.png">

**Comment by rub1e** [comment]
> Can CharlieHR be retired in favour of Xero

Updated answer: as far as payroll employees go, yes we can easily migrate to Xero's `my payroll` module so people can book holiday and view their payslips easily.

But we can't give contractors access to `my payroll` so I'll investigate if there are any *free* `Xero integrations` which will let us manage people's availability for projects more efficiently and easily than the current `company calendar` system.

**Comment by iteles** [comment]
Paid for would be fine, but CharlieHR is proposing to charge us £50 a month (£600) a year, which is a little steep for how few of their features are useful to our particular use case.

**Comment by rub1e** [comment]
Yeah the ones I've looked at so far are all `pay per person` which obviously isn't viable for managing freelancers - the search continues!

**Comment by rub1e** [comment]
![image](https://user-images.githubusercontent.com/11595920/38362205-e4ac9e9a-38c7-11e8-8c51-13e2f70a0866.png)

Discovered https://hr.my/ 

* Free for life, unlimited users
* Logins for employees to request leave so employer can approve
![screenshot 2018-04-05 at 11 54 54](https://user-images.githubusercontent.com/11595920/38362526-11c7fd6a-38c9-11e8-8f60-29991f8e2254.png)
* Visual holiday tracker
* Email alerts for requester and approver
* (Crowdfunded)

The cons are it's *very fiddly* to set up 🔣 and precisely 4% as slick/pretty as `CharlieHR` 🚽 

That said, it ticks all of our boxes ✔️ and it works for the core functionality we need (keeping track of freelancers' holidays) 📆 

I just wouldn't use it for `payroll` is all

**Comment by iteles** [comment]
Okaaaaaay, but now it's set up, how simple is it for users?

**Comment by nelsonic** [comment]
There is no such thing as "_Free for life, unlimited users_". 
![image](https://user-images.githubusercontent.com/194400/38364756-bfec97cc-38d1-11e8-9f92-877a5d54b73a.png)

**Comment by rub1e** [comment]
![screenshot 2018-04-05 at 13 08 16](https://user-images.githubusercontent.com/11595920/38364962-895c2082-38d2-11e8-9e90-fcbde829367c.png)

**Comment by iteles** [comment]
@rub1e Had an email from @shouston3 noting he's had some trouble booking time off, please look into this with him (no mega rush, but this week or next would be good).

**Comment by rub1e** [comment]
@iteles this was because he was trying to log into Xero, having not read my email about our new holidays process

It's all sorted.

Though it hardly matters now, I suppose.

**Comment by rub1e** [comment]
Closing because I've updated Xero with everyone's holiday allowances, and I'll write up the process for that along with general setting up / amending staff on Xero process
