### ISSUE TITLE
Potential new project | Yacht charter

### ISSUE THREAD

**Issue by iteles** [dwyl/hq#426]
CI currently has a B2B platform with a subscription based business model giving agencies access to their thousands of yacht listings.

They would like to build out a B2C business as well, which will include both listings data coming from their current _API_ (JSON based) and editorial blog-type content for which they will require a CMS.

They would like this to be built with **Node** and have been looking at a few **CMS** options, most notably [Contentful](https://www.contentful.com/) and [Apostrophe](http://apostrophecms.org).
This will be extremely image-heavy.

They found us through LinkedIn!

Tasks:
+ [x] Initial call to determine basics
+ [x] Send through an idea of possible team structure and budget per sprint
+ [x] More detailed call with CI in-house devs **[booked for 6-Feb-2018]**
+ [x] Review team structure and confirm sprint budget following call
+ [x] Determine whether we want to send through a proposal or not
+ [x] @iteles to agree workshop kick-off date and draft agenda
+ [x] @rub1e to draft contract
+ [x] @iteles to review & sign
+ [x] @rub1e to send
+ [x] Debate & agree changes to contract
+ [x] @rub1e to redraft contract & send
+ [x] Receive counter-signed copy & file

**Comment by nelsonic** [comment]
Not "Curing Cancer" but reasonably strait-forward to build 
and will be good _experience_ for people working on it so worth considering. 👍

**Comment by iteles** [comment]
@nelsonic My current proposed team for this is:
+ Technical architect - will only be required for a couple of days at the beginning of the project and brought in sporadically as needed
+ Designer - required for a day or two at the beginning of the project for a User Experience review and advisory workshop and we can then see if any more time from them is needed
+ Scrum master (3 days per sprint) - is the client liaison, supports the product owner and the development team, ensures processes are followed and removes blockers
+ Quality Assurance/Code reviewer (4 days per sprint)
+ Senior developer (full time)
+ Advanced Junior developer (full time) 

Is this the team structure you would put forward?
The questions from the CI team appeared to be around the need for a senior developer.

**Comment by nelsonic** [comment]
@iteles team sounds good. 👍 
Ultimately we need _really_ good "_direction_" up-front to avoid wasting time. 🗺 
But after that it should be reasonably "_plain sailing_" ⛵️  (_couldn't resist the pun!_) 😉

**Comment by rub1e** [comment]
Make sure they give you a good *steer* on it mate - you don't want them *tacking* on any extra work

**Comment by iteles** [comment]
There is now the distinct possibility that CI will hire a full time front end developer to join their team who "will do the design, HTML, CSS and JavaScript" and have asked us to determine whether we are happy to work like this and revise our team accordingly (I assume their expectation is we will revise it down).

My view is that this is more likely to affect the levels of the team UP and require more scrum master time to mediate between the various parties per sprint, but overall require less sprints.

Worth noting this is more or less what we did with the Science Museum - we were given HTML/CSS templates (not JS) and worked with them.

**Comment by iteles** [comment]
Back to the proposal of having the UX review sit with us.
Revised team/budget sent.

**Comment by iteles** [comment]
Looks like this will go forward with @SimonLab and @Cleop as the proposed team.

Adding contracting to the task list above (and 2 hours onto the time estimate).

Date of workshop TBC.

**Comment by iteles** [comment]
Proposed loose agenda:
- Morning: Industry & user journey focus
  - Introductions
  - Introduction to CI & project (Chris)
  - Ways of working (Ines)
  - End user personas (Chris)
  - User journey (Chris, with lots of questions from the dwyl team)
- Afternoon: Further requirements & technical detail
  - Continuation of user journey with technical questions (as needed)
  - API integrations (Pete + dwyl)
  - Further technical questions (as needed)
  - Discussion of MVP/prioritisation of features & timelines
  - Github & product ownership review

Key aims:
- Understand end users and value we are looking to create (to aid UX review)
- Have a well-rounded idea of the user requirements and features
- Understand technical requirements
- Confirm initial thoughts on MVP/prioritisation
- Define timelines

**Comment by iteles** [comment]
Contract sent, awaiting signed return.

**Comment by iteles** [comment]
Currently debating competition clauses in the contract!

**Comment by iteles** [comment]
@rub1e Final clauses agreed (copied you in on the email), assigning this issue to you for re-drafting of the relevant contract sections and tracking getting it signed! 😊

**Comment by nelsonic** [comment]
@iteles when is this meant to start?

**Comment by iteles** [comment]
Signed contracts received yesterday 👍 

Schedule:
+ Friday 23-Feb-2018, kickoff workshop
+ Week beginning 26-Feb-2018, 2.5 days of UX assessment by @harrygfox 
+ Week beginning 5-Mar-2018, TBC number of days of design, carried out by @nogainbar 
+ Week beginning 12-Mar-2018 (but could be the week after), full time development begins.
