### ISSUE TITLE
Tidy up invoice.dwyl.com drop-down

### ISSUE THREAD

**Issue by iteles** [dwyl/hq#429]
As a dwyler who invoices via invoice.dwyl.com,
I would like there to be an updated list
So that I don't have to scroll through a bunch of names that no longer work with dwyl to find my own at the bottom.

<hr/>

@rub1e I made went through the spreadsheet and made the ones to delete red and I think we're missing the second-to-last name from the invoice 'app'.

**Comment by rub1e** [comment]
Done!

**Comment by iteles** [comment]
🎉
