### ISSUE TITLE
Source PNG App UI for Google-Docs-Based Wireframe Sketching

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hq#43]
there are _many_ tools for designing "_mockups_" but Google Docs can be used _just_ as effectively to create a walkthrough of any app/website idea.

What google docs is missing is UI elements
## I expect this to take 2 days.

**Comment by iteles** [comment]
:+1: Great task!

**Comment by markwilliamfirth** [comment]
@nelsonic ok to close?

**Comment by iteles** [comment]
This (and #44) are open as `va-task` and are pretty low priority. It would still be nice to have a simple way for people to design that doesn't involve proprietary software but pretty low priority for us at the moment. Added to the backlog.

**Comment by nelsonic** [comment]
How is having a "**UI Kit**" for rapid prototyping a _low_ priority...?  🤔 
This is ~~useful~~ _essential_ for _all_ projects we do! ❗️ 
Closing in favour of: https://github.com/dwyl/learn-tachyons/issues/9
(_having a "living" style guide is a much better way to go. wireframes are a compromise_)

**Comment by iteles** [comment]
They are only 'low priority' _because_ of our move to sketching in the browser with tachyons 👍  Well linked.
