### ISSUE TITLE
Creating expenses in foreign currency

### ISSUE THREAD

**Issue by rub1e** [dwyl/hq#430]
As a reconciler of expenses AND as a submitter of expenses, I would like to be able to raise expenses claims in foreign currency directly

* [x] Upgrade account in Xero to premium 
* [ ] Document process

Split out from #383

**Comment by iteles** [comment]
👍 To document our reasoning:
Xero Premium costs an additional £5.50 per month, £66 a year and it will cost us more than that in dwyler time to do the conversions ourselves for dwyler summer receipts alone!

**Comment by iteles** [comment]
FYI I'm making this a priority 2 as we have some receipts in €€ to put in from our last dwyl HQ trip to Portugal.

**Comment by iteles** [comment]
Upgraded!
<img width="482" alt="screen shot 2018-02-08 at 16 20 18" src="https://user-images.githubusercontent.com/4185328/35984358-286c34a4-0cec-11e8-8371-e4f77c0b4da9.png">

**Comment by rub1e** [comment]
I've added Euro & $$ to our account, but the option's not there for expenses - so I've sent in a support request

**Comment by rub1e** [comment]
Xero isn't currently set up to do `non-base` currency expenses 💸 , but we can get around this by creating bills instead of an expense claim.

However please note that Xero uses historical currency conversion rates 💹  for old receipts so the foreign money transaction 💶  matches up with the £ 💷 amount coming out of the bank account 🏦 

**This means that we need to group these expenses by date** - i.e. *create a new bill for each day of expenses*

In practice, however, it's not the end of the world if we create one single bill for a two week period like `dwyl summer` 🇵🇹  because the exchange rate isn't likely to have fluctuated enough to have a significant effect (and discrepancies can be accounted for using Xero's `rounding` function.

![screenshot 2018-03-26 at 13 56 50](https://user-images.githubusercontent.com/11595920/37907720-d5ed854e-30fd-11e8-9bac-879e201d3dea.png)
* Create a new invoice and select the relevant currency from the currency dropdown (see above)
* Using your phone's camera or the Xero app, take a photo of each receipt and name it according to the following convention:
  * {account}-{date}-{amount}-{description}
  * `account` will be e.g. `Braga` or `dwyl-summer` or `Thomas Cook`
  * Date is important (see above)
  * Description should be minimal - e.g. "food" 
* Just upload the files to the `file library`, rather than attaching them to an expense claim
![screenshot 2018-03-26 at 14 25 02](https://user-images.githubusercontent.com/11595920/37908967-8c026036-3101-11e8-91e7-e53b34e3c2bf.png)
* Once all receipts are stored, add each one from the file library to the blank bill you've created
  * This is why the naming convention is so important - you can populate each line of the invoice from the filename, rather than having to go into each PDF 😩

**Comment by iteles** [comment]
The 'Client' will be `dwyl-summer` or a client name, but will the account be `International Travel` across the board? Maybe a question for the accountants #451

**Comment by iteles** [comment]
We ended up with `{date}-{amount}-{description}--{client}`

But this process works! 👍
