### ISSUE TITLE
Social media strategy

### ISSUE THREAD

**Issue by rub1e** [dwyl/hq#431]
As *someone who commissions web development projects*, I would like to ensure **dwyl** makes it into my "consideration set" for my next project

As a *dwyler*, I would like to ensure the world is aware of the awesomeness of my job & what we do here (*hint*: we're **d**oing **w**hat we (**y**ou) **l**ove)

As a *potential dwyler*, I would like to be made aware of dwyl

* [ ] Discuss social media strategy
* [ ] Spec out ongoing plan and assign responsibilities
* [ ] Fulfil responsibilities! 😄 

Continuation of #244 as opened **February 2017**

**Comment by rub1e** [comment]
Our started for 10 comes from @iteles, who posts this tweet: https://twitter.com/realjefflarge/status/961330248280309760

![screenshot 2018-02-08 at 14 37 30](https://user-images.githubusercontent.com/11595920/35978446-ad82642e-0cdd-11e8-94a9-e3af0909dbca.png)

**Comment by rub1e** [comment]
I for one think this is a thoroughly sensible suggestion as far as Facebook is concerned, perhaps even Instagram (though that may be based on personal preference)

I do think we should learn from Jeff's mistakes and proofread any such message before we send it

**Comment by iteles** [comment]
Created but not a single things was ever done with it.

<img width="1084" alt="screen shot 2018-03-19 at 11 16 13" src="https://user-images.githubusercontent.com/4185328/37593549-43e5af98-2b6a-11e8-8ed7-490bd771c993.png">

**Comment by iteles** [comment]
Closing this for now. We need to focus on product and without wanting to use Facebook or Instagram https://github.com/dwyl/home/issues/29 , this is not a concern as long as we own the real estate so that others cannot use our name or pass themselves off as us.

**Comment by nelsonic** [comment]
Also Google+ ...? 
https://www.theverge.com/2018/10/8/17951890/google-plus-shut-down-security-api-change-gmail-android 💀
