### ISSUE TITLE
Make sure all historical invoices are findable and stored in Xero

### ISSUE THREAD

**Issue by rub1e** [dwyl/hq#437]
#There seem to be various gaps between the details we have about projects, the invoices we have in Google drive, and the invoices that have been uploaded to Xero.

As a doer of finance tasks, I would like to have a spreadsheet with details of work done and a unique reference for each invoice which I can then find in Xero. Basically I want the `invoice.dwyl.com` process to be applied retrospectively

Go through invoices in Google drive folders
* [x] Check if PDF is stored in Xero. If so, edit entry with appropriate category/client; if not, store in Xero
* [x] If PDF not available, update Client & Sprint no. based on the payment reference on the bank statement

**Comment by iteles** [comment]
Thanks for fixing the dubious job done by the accountants that were supposed to bring Xero up to date: https://github.com/dwyl/hq/issues/321#issuecomment-323071446
🙄👍

**Comment by rub1e** [comment]
This is now complete - every single unreconciled item in Xero is a receipt. Happy Days.

That's not to say that every single payment has an invoice stored on Xero (there were some missing invoices)...

... but at the very least, every relevant payment has a client reference (sometimes a sprint number too)

The best thing about it is that I can close this issue without writing a process down because all dwyler invoices now automatically go straight to the Xero inbox!
