### ISSUE TITLE
Review existing mock up tools and note preferred UI elements

### ISSUE THREAD

**Issue by iteles** [dwyl/hq#44]
We need to review existing tools and note what our favourite UI elements are.
This will inform what we need to include for #43.

For example, in [moqups](https://moqups.com/) there is both a female and a male avatar and an easy switcher between the two.
<img width="285" alt="moqups-avatar-switcher" src="https://cloud.githubusercontent.com/assets/4185328/11090114/3d0a364c-8867-11e5-8b5f-24115f9cfc30.png">

**Comment by markwilliamfirth** [comment]
@iteles ok to close?

**Comment by iteles** [comment]
This (and #43) are open as `va-task` and are pretty low priority. It would still be nice to have a simple way for people to design that doesn't involve proprietary software but pretty low priority for us at the moment. Added to the backlog.

**Comment by markwilliamfirth** [comment]
@iteles I think #43 and #44 should move to a new repo associated with this product rather than being in hq? "png-app"?

**Comment by iteles** [comment]
@markwilliamfirth Sorry, I didn't explain that very well. The idea isn't to build an app for this, in #43 it's just to find a tool (like google slides for example) that people who don't have the money for things like Sketch, Balsamiq, Proto.io, etc can use and this specific issue is to source some assets to make that process a bit quicker.

We could move these two issues to start-here if you would feel that was cleaner 👍

**Comment by nelsonic** [comment]
We _all_ need to "_get good_" at "_Live Prototyping_".
relates to: https://github.com/dwyl/learn-tachyons/issues/9

**Comment by markwilliamfirth** [comment]
@iteles should we create a design/UX/UI repo or maybe use the learn tachyons repo?
 (https://github.com/dwyl/learn-tachyons/) as it might be more appropriate than to put it in operations?

**Comment by iteles** [comment]
@markwilliamfirth Happy for this to be replaced with a 'live prototyping' issue in learn-tachyons 👍

**Comment by markwilliamfirth** [comment]
Closed in favour of https://github.com/dwyl/learn-tachyons/issues/15
