### ISSUE TITLE
Process for F&C commission

### ISSUE THREAD

**Issue by iteles** [dwyl/hq#443]
Following on from our conversations with Founders & Coders, the latest proposal is somewhat of a hybrid of what we've always done (10% commission) with a new cap agreed. 

Our latest proposal is that this is billed from F&C monthly. 

We need to figure out how to do the following most efficiently:
+ [ ] Keep track of people for whom the cap has not yet been reached (including new dwylers)
+ [ ] Keep track of the number of days worked and therefore the commission owed
+ [ ] Communicate this to F&C on a monthly basis (preferably without needing any active communication - I used to have just a shared spreadsheet for this)

**Comment by rub1e** [comment]
@iteles can I close this in favour of #460 ?
