### ISSUE TITLE
Update CharlieHR/Xero with everyone's start dates

### ISSUE THREAD

**Issue by iteles** [dwyl/hq#445]
I got a large number of emails from CharlieHR last month congratulating us for literally everyone's 'anniversary' at dwyl, when in fact it was the anniversary of when we set up CharlieHR 😉 

We should update these.

Dependent on #425.

**Comment by rub1e** [comment]
With CharlieHR now retired, start dates for staff are stored in Xero.

Ready to close @iteles ?

**Comment by iteles** [comment]
That'll do for now 👍

**Comment by rub1e** [comment]
All PAYE dwylers have their details in Xero, and all freelancers have a screenshot of their CharlieHR account in a folder called CharlieHR under `Human Resources` (though that will shortly be updated to something less sterile per #206 )

Ready to close @iteles ?
