### ISSUE TITLE
Transfer namecheap domains to iwmn

### ISSUE THREAD

**Issue by iteles** [dwyl/hq#448]
We manage all of our domains through iwantmyname, but I recently had to rent a couple through namecheap.
See https://github.com/dwyl/github-backup/issues/13

We need to transfer these over to iwmn so that we can manage them with the others and when they renew, they renew with iwmn instead of namecheap.

**Comment by rub1e** [comment]
Ha - I did wonder why we were cheating on iwmn! All I need is login details and it shall be done.

**Comment by iteles** [comment]
Login details shared 👍

**Comment by rub1e** [comment]
I just cannae do it capn, I doont have the pooowr... to transfer domains less than 60 days old

Made a note in my diary, will do it when it's unlocked

**Comment by rub1e** [comment]
Just attempted this and `iwmn` want £39 for *gitbu.co* - just want to check we're happy with that price?

**Comment by nelsonic** [comment]
@rub1e spending £39 to transfer the domain is "_not urgent_".

**Comment by iteles** [comment]
Meh. If there’s a cost let’s just keep them where they are and we can transfer them when they’re up for renewal.
