### ISSUE TITLE
Categorising payroll correctly in Xero

### ISSUE THREAD

**Issue by rub1e** [dwyl/hq#449]
This is part of #447 but important enough to warrant its own issue 🔑 

In order to check that all payments have been made correctly at the end of the year, we need `PAYE` split out into NICs, student loans, and PAYE tax payments. ➗ 

And, from April 2018, we also need to split out pension payments into Employer and Employee contributions

Currently, pay runs are reconciled to `Wages` and `PAYE`, and then before the end of the tax year in April, I'd go through each run and split out the different items all in one go. 

(This way of doing it was suggested by our bookkeeper.) Since trying it out, it actually seemed like more work than splitting the payments every month after the pay run is complete.

* [ ] Document payroll reconciliation process
* [ ] Go back over pay runs from this tax year and split payments as above
* [ ] Make "reconciling the pay run" the last step on the pay run process, and do it monthly going forward

**Comment by rub1e** [comment]
Reopening to add a note to cover `pensions` and pension scheme opt-outs

**Comment by rub1e** [comment]
I'm just going to be honest and say it: I never documented this process, and it's now taken me half an hour to figure out how I did it in the first place.

*The very moment* our accounts are submitted to our accountants, I'll document all the things I've neglected

-------------

For my own notes: pretty sure the whole process can be simplified by just going into the relevant pay run and opening the payroll summary report as that includes pensions, taxes, and wages all in the same place.

NB - look out for the Employer's Allowance deduction in the first two months of the year

**Comment by rub1e** [comment]
Issue updated with tasks

**Comment by rub1e** [comment]
* `Xero > Payroll > Pay employees`
* Select the month you need
* At the bottom of the page, click the `options` button and get the `Payroll Activity Summary` report
* Reconcile into:
  * `814 - Wages Payable - Payroll` - this is the "Net Pay" amount on the report
  * `825 - PAYE Payable` - this is the "PAYE" amount under "Employee Tax"
  * `826 - NIC Payable` - the **sum** of
    * "Employ**ee** National Insurance Contribution" under "Employ**ee** Tax"
    * "Employ**er** National Insurance Contribution" under "Employ**er** Tax"
   * `947 - Student Loan Deductions Payable` - "Student Loans" under "Deductions"

Do this every month. GO!

**Comment by rub1e** [comment]
> NB - look out for the Employer's Allowance deduction in the first two months of the year

In the first two months of the tax year, we have £3k of allowance taken off our NICs. 

*This isn't reflected on the `summary report`*, so you'll have to go into `Payroll > Taxes & Filings` to find this - you'll see Month 1 and Month 2 have £3k total under `Recoveries`

For the sake of clarity, I'm going to say that we should include the recovery as a negative line - so in months 1 & 2 we'll have two lines for `NIC Payable` - one showing the full amount charged and one (negative) showing the amount recovered via employment allowance:

![screenshot 2019-01-29 at 12 32 20](https://user-images.githubusercontent.com/11595920/51908521-fa821480-23c1-11e9-8d08-d124a9011a74.png)

**Comment by rub1e** [comment]
This is all up to date now, except for a couple of discrepancies which I'll have to access our online banking account to check (and which really underline the need to reconcile these things right after they're paid)

**Comment by iteles** [comment]
Done and payroll closed.
