### ISSUE TITLE
Write a github reference for non-technical people

### ISSUE THREAD

**Issue by iteles** [dwyl/hq#45]
**We use Github to manage our projects.** It's our [version control system](https://git-scm.com/book/en/v2/Getting-Started-About-Version-Control), our task list ([product backlog](https://www.atlassian.com/agile/backlogs/), where our [automated reviews take place](https://github.com/dwyl/repo-badges) and where our progress can be fully tracked.

However, whereas developers are often familiar with Github, clients are not. We need to have a document that clients can refer back to after a short training session (or as _the_ training session) on the most important things they need to know to work with issues and track progress on GitHub.

**Comment by nelsonic** [comment]
https://github.com/dwyl/github-reference 🎉 
(_the guide is still evolving but at least it exists so we can close this issue_)
