### ISSUE TITLE
End of Sprint Process

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hq#46]
## Steps
- **Review** The Stories Completed in the Sprint (_let the person who did the_ **_work**_ _do the talking_)
- Compare to original **_Time Estimates**_ for each Story 
- What Did We **_Learn**_?
- Close Sprint **Milestone** on GitHub
- **_Invoice**_ the Client (_ASAP_)

Part of the process of sprint review should be to talk through the stories that were _delivered_ and confirm the original time estimates were met (_or why the task took more time than originally predicted_).

Estimating and Tracking Time is the **_Single**_ most important factor to manage in a software project, its how we show the Product Owner / Client that we are providing value-for-money and helps us plan future sprints with _any_ degree of accuracy. This is where other teams fall down.

Which is why having a sprint review meeting in a _park_ is not the _best_ idea ... unless you are _constantly_ referring to the project board (_in our case the GitHub issues list_) its _very_ easy for people to get side-tracked. We/You need to **_constantly re-enforce**_ the team looking at the project management **_system**_ to ensure it gets used appropriately, otherwise chaos ensues rapidly...

Once the previous Sprint's _Stories_ have been reviewed you should **_Close**_ the **Milestone** on GitHub:
![please-close-completed-sprints](https://cloud.githubusercontent.com/assets/194400/11141396/dd7dcafa-89dc-11e5-9b08-014af837a38a.png)

As soon as the Product Owner (Client) is satisfied that the agreed stories for the sprint have been delivered, prepare and send the **_invoice before anything else**_.

**Comment by iteles** [comment]
:+1: This is great @nelsonic, thanks for adding such a clear list of things here!

We're really set up for this process to work fantastically in sprint 3 as well, I'm _excited_ :tada:

**Comment by nelsonic** [comment]
@iteles has this been _added_ somewhere? (_can we **close** it off_?)

**Comment by iteles** [comment]
Needs to be added to https://github.com/dwyl/ateam-master-reference/issues/15
Have linked the two.

**Comment by markwilliamfirth** [comment]
Closed in favour of https://github.com/dwyl/process-handbook/issues/73
