### ISSUE TITLE
Google GDPR compliance

### ISSUE THREAD

**Issue by rub1e** [dwyl/hq#462]
Google requires us to complete their `GDPR process` (cf. #404)

All we need to do is read their updated `Data Processing Terms` 📜 

And

Nominate and register a `Data Processing Officer` 👮‍♀️, which I suggest should be @iteles as she is 💯 on all data processing matters, whereas I can barely even spell `GDPR`

**Comment by rub1e** [comment]
Conveniently, I don't seem to have the required level of access to do this, which is odd because you increased my level to be able to access `support`

So @iteles either give me full double top secret level access 👁, or I'm afraid you'll have to do it yourself:

* Sign in to the `Google Admin console`.
* Click Nav icon.
* Select _Account_ and click _Company Profile_.
* Select _Profile_.
* Scroll to the **Security and Privacy Additional Terms** section (next to Data Processing Amendment), ensure that you or an appropriate person within your organisation reviews the DPA 2.0, and click Review and Accept.
* Click `I Accept`.
* Go back to `Company Profile`
* Click `Show More` and select **Legal & Compliance**.
* Under **Your data protection officer details**, enter contact information as required.
* Click `Save`.

**Comment by rub1e** [comment]
@iteles You're now officially the `GDPR` guru, this is done 👍

**Comment by nelsonic** [comment]
@iteles endorsing you for GDPR on LinkedIn now ... 😜
