### ISSUE TITLE
No Reply Amail Address noreply@dwyl.com (antipattern)

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hq#468]
![image](https://user-images.githubusercontent.com/194400/39763419-f16ba2f8-52d4-11e8-8b53-4b05936a3bcd.png)

sending email from a "no reply" is an _antipattern_ we need to avoid.

**Comment by rub1e** [comment]
Took me a while to remember, but there is a reason for this! Unsurprisingly it's `autocrat` related 🙄 

The email either comes from a generic address (which we can't specify) or the address of the last person to edit the spreadsheet. 

To avoid the email coming from a different address every time, [we chose](https://github.com/dwyl/hq/issues/302#issuecomment-357926026) to keep it set to the generic `no-reply`

![screenshot 2018-05-08 at 15 50 24](https://user-images.githubusercontent.com/11595920/39764736-2c870212-52d8-11e8-8b04-76914e6a09f7.png)

BUT we set the reply-to address as `finance@dwyl.com` (screenshot)

Clearly this isn't working so I'll leave a comment on the G+ page

**Comment by iteles** [comment]
@nelsonic Can I edit the title here to reflect the autocrat bug that the reply-to email address isn't working?

**Comment by nelsonic** [comment]
Autocrat indeed ... https://en.wikipedia.org/wiki/Autocracy
Who would call their project/software that ...? 😕 

I've searched the HQ issues for "requirements" for what we need(ed) for invoicing all I can see is: https://github.com/dwyl/hq/issues/302 ...
Which is not what I would describe as "requirements" ... 
any "_solution_" that forces us to send email as `noreply@dwyl.com` is _not_ "fit for purpose". 
Collecting the data is only _part_ of the requirement. 
This is not "_Automated_" at _all_; it's a _manual process_ with a form requiring manual input.
a form which leaks data https://github.com/dwyl/process-handbook/issues/97 
After the person _manually_ submits their invoice data, 
further _manual_ processing is required by an Admin ...
This "solution" has **_created_ more work** not _reduced_ it 
and resulted in a process/UX failure.

@iteles if you are _able_ to update the "from" email address to something that _is_ a valid email address, please do. but given that none of the people who _use_ the "invoicing system" have complained ... if you prefer to just _close_ this issue, please go for it. 👍

**Comment by iteles** [comment]
Closing this issue because the volume of invoices is very low and this isn't an issue for those people.

We _can't_ change the from address to anything stable other than 'no-reply' because that is a limitation of the software we are using.

The solution here is to use an invoicing system that is fit-for-purpose, which is a separate low priority issue to be opened ((given our current product focus, it will rise in priority as it comes closer in the product roadmap and as requests start to come in for it).

**Comment by nelsonic** [comment]
@iteles then we need to change the "_software_" we are using. 👎 
Any software designer/developer should know better than to use a **`no-reply`** email.
It's _terrible_ UX! 😠 

At the _very_ least we should write a  "_short_" (5 min read) blog post on this ... 💭
