### ISSUE TITLE
Code mini app to standardise & update labels across github repos

### ISSUE THREAD

**Issue by iteles** [dwyl/hq#47]
As a github user who is an owner of multiple repos, I want to be able to standardise my [issue labels](https://github.com/dwyl/hq/labels) across all the repos I manage _without having to do it manually every time I start a new repo_.

<hr/>

We create new repos for _dwyl_ almost weekly and having to manually add our standard priority labels to each repo is a huge waste of time. Also, if we change some of our standard labels, I would like them to update across all repos and issues to (which would be a nightmare manually).

This _could_ be a `va-tast` but honestly, it's so mindless that I wouldn't wish it on anyone and would much rather code something up to take care of it :+1: 

Tasks:
- [x] update https://github.com/dwyl/hapi-auth-github you will need it later. (_update any docs/instructions that are unclear_)
- [x] create new repo `labels` which will serve as the _canonical_ list of labels for our Org. The initial list can be sourced from: https://github.com/dwyl/contributing#labels
- [x] create a Hapi.js Micro-Service which does GitHub auth and accepts the name of a Repository where you want to apply the "standard" dwyl labels. Store the code for the mini-project in the `labels` repo with appropriate documentation.
- [ ] check the user has "_admin_" access to the required repo and perform the action or inform them they need more permissions.

**update** check: https://github.com/dwyl/labels/ for latest

**Comment by nelsonic** [comment]
@jrans / @jackcarlisle please think through the requirements noted above and let us know what is missing. Feel free to transfer this issue or link to sub-issues once the `labels` repo is created. 
This mini-project will help us sync up all our other projects. 
The hope is that we will be able to do this across organisations.

In the _future_ we will be able to _discuss_ any new labels as they are required as issues in `labels` and once they are agreed and created, they will be _automagically_ synched across all repos. (_this is a future requirement... for now we just want to copy labels from the `labels` repo to a single "target" repo_)

**Comment by jrans** [comment]
@nelsonic do we want to create our own? There is an [existing solution](https://github.com/destan/github-label-manager) which is very nice but doesn't default to copying dwyls nor github auth...

If we do, noting down this. https://developer.github.com/v3/issues/labels/

**Comment by nelsonic** [comment]
@jrans I would not describe http://www.dorukdestan.com/github-label-manager/ as a "solution". 
Yes, it _appears_ to help copy labels from one repo to another, but it's "_hacky_" at best...

the site is hosted on a non-https server which means if you _use_ it you are sending your GitHub Password ***in-the-clear*** over the interwebs and have _no idea_ what _else_ could happen with your credentials. Sure, you could _suggest_ that the "_nefarious_" actions could be taken if you authenticate using OAuth2, but GitHub will have a complete log of the actions taken by the "app" on your behalf and can roll-back if "bad" things happen. 

Good on Destan for approaching solving the issue, and good effort on your part for doing the preliminary research to see if there is an _existing_ solution, but I still think we can do a better _simpler_ job of this.

**Comment by nelsonic** [comment]
@jrans can we check off some of the requirements at the top ...?

**Comment by jrans** [comment]
@nelsonic Updated 👍

**Comment by nelsonic** [comment]
@iteles are you _delighted_ with the outcome of the mini-project or is there anything `else` you would add?
I guess we can always add feature stories/requests to the https://github.com/dwyl/labels/ issues... 👍
