### ISSUE TITLE
WebSummit?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hq#476]
@iteles I have been offered an "Alpha" ticket to WebSummit https://websummit.com
I haven't been for the last couple of years and I'm _tempted_ to go as I will _already_ be in PT. 
Are you considering going? (_do you still have "free" tickets?_)

> Note: this question is open to _all_ `dwylers`, 
_especially_ those who have never been.
> I just want to check with Inês _first_.

**Comment by iteles** [comment]
I _don't_ have a ticket and although I've had a look around and signed up to the 'Women in Tech' network (I had previously ***un***subscribed from the insane amount of useless emails they bombard people with), I haven't had any success yet for a WiT ticket.

I _wasn't_ considering going and I wouldn't pay money to go. But seeing as we're in Portugal already this year and _if_ we get free tickets then I'm happy to go for one day seeing as we've got friends pitching this year 🎉 

If I _can't_ get a free ticket, I think it's a waste of money and will just join you guys at the end of the day for a catch up 😊

**Comment by roryc89** [comment]
I may be going as Rebeca gets a free ticket. But not sure if I'll pay to attend or just be staying nearby.

**Comment by nelsonic** [comment]
Closing as the event has passed.
For a good video summary, see: https://www.youtube.com/channel/UCJtkHqH4Qof97TSx7BzE5IQ

**Comment by acegilz** [comment]
Anyone have a spare developer ticket? I would highly appreciate it.. missed the timing they are gone now

**Comment by iteles** [comment]
@acegilz I don’t think any of us have any/are going this year - this issue was for last year’s websummit!
