### ISSUE TITLE
Clarity around break even numbers

### ISSUE THREAD

**Issue by iteles** [dwyl/hq#477]
Following on from making a good dent into our end of year accounts #406 (yay @rub1e! And it's not even the month before the deadline or _anything_!) and linked to https://github.com/dwyl/hq/issues/321

With a hybrid PAYE employee/freelancer model, there is a little less clarity around how much the true cost of each person in the organisation is and how much we have to make sure we cover with our contributions to overheads in order to have a good runway here.

@rub1e Could we please calculate the following so that when we are selling work we can ensure _at a glance_ that we are not selling ourselves short?
+ _Actual cost_ per day per PAYE employee (including all the things we need to pay the government on a monthly basis, pensions and apportioned holiday allowance)
+ Required contribution to overhead per day to support _salaries_ (i.e. Ops and sales salaries)
  + We will need a separate column for contribution to overheads overall (i.e. including everything from rent to coffee to team activities), but we need further clarity on costs which will come once #406 is complete before we get this
+ Required contribution to overheads per if there is a 90% utilisation rate (i.e. if 10% of the time people are working on internal dwyl products or are between projects)
+ Required contribution to overheads per if there is a 80% utilisation rate 
+ Opportunity cost to not working on client projects (I can fill in this column).

**Comment by iteles** [comment]
@rub1e You're a *gem* 💎 
So nice to _finally_ have some clarity around this kind of number #321.

Let's walk through them tomorrow and then we can close?

**Comment by rub1e** [comment]
First thing to note is that employees cost a lot more than their headline pay figure, when pensions and taxes are included - c.10% more.

So, someone on e.g. £3k/month costs the company closer to £3.5k/month - and this needs to be factored in when doing this calculation (fortunately `Xero` calculates employees' total cost for us 😁)

So the calculation here would be:

* Take employee's total monthly cost 
* Divide by total working days (228) & multiply by 12 to get daily cost
* Do the same for salaries of Ops & Sales staff
* Divide daily overheads cost by number of regular employees
* Add this to each employee cost to get the desired break-even figure 

This is the basic process; it doesn't include stuff like training costs or boxes of green tea etc etc

**Comment by iteles** [comment]
SO SO happy to finally have this. You're a peach @rub1e 🎉 

Also, 😆 at the 🍵
