### ISSUE TITLE
Apple Keyboard Service Program for MacBook and MacBook Pro

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hq#479]
Apple has _finally_ admitted that MacBook and MacBook Pro keyboard is not 100% reliable.

https://www.apple.com/support/keyboard-service-program-for-macbook-and-macbook-pro
![image](https://user-images.githubusercontent.com/194400/41809108-9e68f162-76df-11e8-8671-b9694f2be53f.png)

Might have _something_ to do with the Recall petition:
https://www.change.org/p/apple-apple-recall-macbook-pro-w-defective-keyboard-replace-with-different-working-keyboard
![image](https://user-images.githubusercontent.com/194400/41809160-7d41dab6-76e0-11e8-803c-b8f5c8c48bec.png)

Means @iteles and anyone `else` with one of the newer MacBook or MacBook Pro Laptops 
can take their laptop in to an Apple Store and get it repaired.

**Comment by nelsonic** [comment]
@iteles I know you were _considering_ doing this repair in PT next week ...
Have you _booked_ an "appointment" to get the repair done?

**Comment by iteles** [comment]
Yes!

News on this: if you take them to the Apple Store, they take 7-10 days. If you book in with an authorized reseller _through_ the Apple website, it should only be 5-7.

I've booked in with an authorized reseller on Wednesday at 13h20 in Porto, seeing as I'll have my iPad with me and we have to be 'off dwyl' for the end of next week doing some work to pay for the dwylsummer house 👍

**Comment by nelsonic** [comment]
@iteles sounds good. iPad is a _good_ "stop gap".
we can collect the "Spare" MacBook Air 11' from Carca.
(_that I gave to @carolrmc but she doesn't `use`..._) 🙄 
So you can still have a _full_ laptop to get work done (_if you need_)

**Comment by nelsonic** [comment]
This is a _great_ read on the subject: https://ifixit.org/blog/10229/macbook-pro-keyboard 📖 
via: https://news.ycombinator.com/item?id=17413572

**Comment by iteles** [comment]
Working great! I'd heartily recommend it. 👍 

Took about 3 working days at an Apple reseller (booked through the Apple website) and I used a backup computer for those days.

**Comment by nelsonic** [comment]
@iteles closing as you have used this repair/replace service so the issue has fulfilled it's objective.
