### ISSUE TITLE
agile-the-dwyl-way repo?

### ISSUE THREAD

**Issue by iteles** [dwyl/hq#48]
I set up [`ateam-master-reference`](https://github.com/dwyl/ateam-master-reference) and I see this as a catalogue of our journey to creating the _team_, getting work, (not) having meetings, answering questions that come up, etc.

But when a team starts a project... that's a very different story. Then they don't need to know about all that stuff, they need to know about how to sprint plan, why they need daily standups, how to write issues, when to communicate with the people they're creating magic for.  
That deserves its own repo. A master reference for how to run a _dwyl_ project in an agile way. Where people can share their experiences and suggest improvements _just_ on running a project and not on all the much wider issues of ateam.

**Is there a better name for this repo?**

**Comment by nelsonic** [comment]
Agree in *principal* that this needs to repository of information needs to be collated. However the name ...

**Comment by iteles** [comment]
That's why I opened the issue...

**Comment by iteles** [comment]
Possible (stil not great) alternative names:
+ `dwyl-projects`
+ `working-a-dwyl-project`
+ `dwyl-project-journey`
+ `this-is-how-we-do-it`

**Comment by nelsonic** [comment]
![make sense](https://s-media-cache-ak0.pinimg.com/736x/d4/75/02/d4750242d2fcabb3cc325206c0c20eb5.jpg)

**Comment by iteles** [comment]
Helpful!

**Comment by nelsonic** [comment]
![agile dilbert](https://s-media-cache-ak0.pinimg.com/736x/a6/64/bf/a664bfae939ac4da62d6783442e560ee.jpg)

**Comment by iteles** [comment]
:laughing:

**Comment by iteles** [comment]
But seriously. I need to stop having to repeat myself to every person who asks me how to run a project using github.

**Comment by nelsonic** [comment]
Sadly these guys http://www.obviousgroup.co.uk/ have the SEO for the word "Obvious" ... 
Its tricky... should we try to *brand* the way of working as ***the dwyl way***?
or be a bit more subtle ... "***The Ask Me Questions On GitHub Method***" ...

**Comment by iteles** [comment]
dwyl's Github Method surely? :wink:

**Comment by iteles** [comment]
https://github.com/dwyl/ateam-master-reference

**Comment by nelsonic** [comment]
_Someone_ needs to _decide_ what the "Master Reference" is _for_...
Because it _appears_ to contain detail that _could_ (_should_) be in https://github.com/dwyl/contributing
