### ISSUE TITLE
VAT Return | May 2018 to end July 2018

### ISSUE THREAD

**Issue by rub1e** [dwyl/hq#483]
VAT return for the period of 01.05.2018 - 31.07.2018.

Deadline: 1st Sept 2018.

VAT return and payment deadline is 7th Sept but this task needs to be completed ahead of time so that we can ensure the correct funds are available in our outgoing account for this date.

Further complication is added by the fact that HMRC's account for us is massively unbalanced (see https://github.com/dwyl/hq/issues/461#issuecomment-398764763) - so ideally this should be started as soon as HMRC provide us with the VAT documents they said they'd send over.

* [x] Make sure all expenses / receipts are submitted and approved
* [x] Review VAT ledger when it arrives and agree with HMRC how much we're in credit
* [x] Submit the return
* [x] Call Santander to request an envelope so we can pay the postal order in (@iteles )
+ [x] Pay in the postal order (@rub1e )

(Hopefully this will mean our VAT account will finally be balanced for the first time since May 2017!)

**Comment by rub1e** [comment]
Update 15/8

* Spoke to HMRC and they're sending us a postal order (because we pay by automatic direct debit, this is easier than them taking our credit as part-payment of our next return)
* All invoices have either been inputted onto Xero and reconciled, or requested from @iteles 
* *most* expenses for this period have been inputted

**Comment by rub1e** [comment]
We've now received the postal order! 

Anyone know what to do with postal orders? Asking for a friend. Just looks like a cheque, so I guess I'll try to pay it in like one... 😟

**Comment by rub1e** [comment]
OH FFS! We've just sent in a change of address request - please do nothing until we've had confirmation of that change, otherwise it'll go to our old address!

**Comment by rub1e** [comment]
VAT Return submitted without any issues

I've added a task for @iteles to call Santander to get the paying-in envelope (https://github.com/dwyl/hq/issues/483#issuecomment-416941911), once that's in this can be closed

**Comment by iteles** [comment]
@rub1e I called and they said we don't need a paying in slip.

We can just sent in the cheque with a piece of paper/post-it containing the following information:
1. Sort code
2. Account number
3. Number of cheques to pay in

To the following address:
Santander Clearing Centre
Bridle Road
Bootle L30 4GB
UK

Please take a photo of the cheque before you send it! 
I also checked (no pun intended) and it can be sent signed for delivery 👍 (second class, no huge rush).

**Comment by rub1e** [comment]
Hahaha - this is after I pleaded with the helpdesk woman and told her my boss was on holiday and we really needed to pay this cheque in and she has the company card so PLEASE is there ANY WAY I can pay this in

Computer said no :laughing:

**Comment by iteles** [comment]
Cheque has finally been deposited into our account YAY!

After spending much of 2017 overpaying for VAT unnecessarily, we now finally have the money back from HMRC.

Thanks for sorting this @rub1e
