### ISSUE TITLE
New client process

### ISSUE THREAD

**Issue by rub1e** [dwyl/hq#486]
Draft process for when we start working with someone new (after work is commissioned)

* Write supplier contract
* Go to Settings > General Settings > Reports > Tracking and add them to the client list
* Add them to `contacts` (along with their banking info if you have it at this stage) 
* Create job folder (if one wasn't already created during proposal phase)

**Comment by rub1e** [comment]
Placeholder for now - will finish off when #428 complete

**Comment by iteles** [comment]
@rub1e Should this issue be in https://github.com/dwyl/process-handbook/ instead?

**Comment by rub1e** [comment]
Closing as superseded by: https://github.com/dwyl/process-handbook/issues/114
