### ISSUE TITLE
New Amazon Account?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hq#49]
We've been thinking/talking about this for a while, what steps do we need to have a new Amazon Account just for books (learning)? 
+ [ ] determine what the spending limit needs to be
+ [ ] set up the account to go to a dwyl email account
+ [ ] determine `who` should get access to the account ...

**Comment by iteles** [comment]
+ [ ] Decide which email account to register it to (linked to #38)
+ [ ] Get our Cooperative bank details #25 and link to that
+ [ ] Add Amazon Prime to the new account :+1:

**Comment by nelsonic** [comment]
We need a pre-paid credit card to associate with this account to prevent over-spending ... *because* this is the account we're going to give *everyone* access to... :open_mouth:

**Comment by iteles** [comment]
Oh. _That's_ what you mean.

**Comment by nelsonic** [comment]
Indeed. :+1:

**Comment by markwilliamfirth** [comment]
#218 linked

**Comment by iteles** [comment]
https://www.amazon.co.uk/b2b/info/amazon-business?layout=landing

**Comment by markwilliamfirth** [comment]
Closed in favour of https://github.com/dwyl/hq/issues/49

**Comment by iteles** [comment]
@markwilliamfirth You closed this issue in favour of itself? Assuming that was in error 😊

**Comment by markwilliamfirth** [comment]
@iteles well spotted! Closed in favour of https://github.com/dwyl/hq/issues/218 (also now closed)

**Comment by iteles** [comment]
Reviewing this now as part of https://github.com/dwyl/hq/issues/451#issuecomment-376135392 and it would seem that both of these points in the checklists were missed:
+ Determine who should have access to the account
+ Get a prepaid card to associate with this account to prevent overspending.

Will reopen if needed based on the outcome of #451.
