### ISSUE TITLE
Google Drive Cleanup

### ISSUE THREAD

**Issue by rub1e** [dwyl/hq#496]
We've loads of files which really don't seem to be needed any more - a cleanup is in order

I've been through the `dwyl private` folder and all subfolders and started starring items which I think @iteles  might take a view on

I suggest you just keep an eye out for the starred files just as you generally use google drive, rather than setting aside time to go through it properly, but obviously up to you!

* [x] Star candidates for removal in `dwyl private`  @rub1e
* [x] Review `dwyl private` starred files and delete and/or remove star and/or move to more appropriate folder @iteles 
* [ ] Star candidates for removal in the `marketing` etc folders @rub1e
* [ ] Review `marketing` starred files @iteles

**Comment by iteles** [comment]
![screen shot 2018-09-26 at 18 12 55](https://user-images.githubusercontent.com/4185328/46096758-f184fa80-c1b7-11e8-8372-ed06d158a4de.png)

1. A proposal we put together, but didn't finish, this one can be chucked
2. A talk I gave at CAST's annual event - we should keep this one in a talks folder but definitely shouldn't be in `private`
3.`dwyl-standard-terms` was our very first contract (before it went from a 2 page document written in english to a 17 page document written in legalese) and should be kept in the contracts folder for historical reference
