### ISSUE TITLE
Do we still have a Laminator?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hq#5]
If we don't ... This one seems quite good: http://www.amazon.co.uk/dp/B00KX2Y9BQ

**Comment by iteles** [comment]
I couldn't see one upstairs, my memory tells me the last one we had broke.

We _do_ have _a lot_ of **A4** laminating pouches though. Do we _need_ a laminator? I suggest we put this on ice until we have a garage office #7

**Comment by iteles** [comment]
We have a garage office.
How many times in the last year have you thought "We could do with having a laminator" @nelsonic ?
This one still seems like the best option to me: http://amzn.to/2cgMtks

**Comment by nelsonic** [comment]
@iteles we haven't _needed_ one because we haven't done _any_ marketing ... so yes, closing.
