### ISSUE TITLE
Organise the next dinner @dwylhq [December 2015]

### ISSUE THREAD

**Issue by iteles** [dwyl/hq#50]
As per the title!

**DATE:**
+ Saturday 12th December

**Confirmed:**
+ @NataliaLKB 
+ @beechware
+ @rorysedgwick  
+ @Jbarget 
+ @minaorangina 
+ @hdrdavies 
+ @katkelemen + 1
+ @rub1e 
+ @mk4111 
+ @Conorc1000 
+ @sohilpandya 
+ @nofootnotes 
+ @jrans 
+ @markwilliamfirth

**Comment by nelsonic** [comment]
12th December. :+1:

**Comment by iteles** [comment]
@tsop14 @rorysedgwick @NataliaLKB @markwilliamfirth @benjaminlees JOIN US! :tada:

**Comment by NataliaLKB** [comment]
12th December :+1:

**Comment by iteles** [comment]
I should have a mailing list for this stuff. Maybe a website. And a ballroom sized living room to accommodate everyone soon *insert unicorn emoji here*

**Comment by tsop14** [comment]
🦄🦄🦄🦄

Would love to but I can't. Boo. Good idea about ballroom +1

**Comment by iteles** [comment]
@tsop14 Boooooo, I hear you're crazy busy but we miss you! Hopefully see you soon :kissing_heart:

**Comment by iteles** [comment]
@SimonLab @heron2014 @rjmk @minaorangina @abdiahmed As the 'remaining' FAC5 contingent, come and represent!

**Comment by rjmk** [comment]
@iteles I can't do either of those dates! :cry: Have an awesome time ***without me***

**Comment by iteles** [comment]
@rjmk Sometimes your social butterfly-ness sucks. :sob:

**Comment by iteles** [comment]
@beechware and @NataliaLKB are our first confirmed **yes**es!

**Comment by rorysedgwick** [comment]
12th of December is good with me

**Comment by Jbarget** [comment]
Schweet! Sign me up

**Comment by SimonLab** [comment]
@iteles Sorry I won't be able to come (again!). I won't miss the next one, c'est promis!

**Comment by minaorangina** [comment]
I really need to switch on my Github notification emails ...  I'll be there with Christmas bells on! :smile:

**Comment by hdrdavies** [comment]
yes please! :sparkles:

**Comment by katkelemen** [comment]
yes, thanks for the invite! :)

**Comment by iteles** [comment]
Woohoo! @hdrdavies @katkelemen Let me know if you're bringing +1s please :)

**Comment by rub1e** [comment]
yes please, if I'm still invited...

What shall I bring? I can totally cook a vegan dish if necessary - like you take a chicken Caesar salad then remove the chicken, bacon bits, dressing, and parmesan

**Comment by nelsonic** [comment]
@rub1e lol! :laughing: 
bring that *extra-special* Vegan Turducken you've been perfecting... :+1:

**Comment by iteles** [comment]
@rub1e :stuck_out_tongue_winking_eye: Consider your ticket 'issued'!

**Comment by mk4111** [comment]
yes pretty pretty please!! :D

**Comment by Conorc1000** [comment]
I'd love to come, thanks.

**Comment by iteles** [comment]
@mk4111 @Conorc1000 :tada: Let us know if you're bringing +1s!

**Comment by katkelemen** [comment]
@iteles I might bring a +1, what else should we bring?

**Comment by nelsonic** [comment]
@iteles what about encouraging people to bring us a hand-made (*by them*) christmas decoration for our new [*tree*](https://github.com/dwyl/hq/issues/54) ...? :christmas_tree: :open_mouth:

**Comment by iteles** [comment]
![http://giphy.com/gifs/reaction-supernatural-wtf-d0MYTsbRnGKoU](http://giphy.com/gifs/reaction-supernatural-wtf-d0MYTsbRnGKoU)

**Comment by NataliaLKB** [comment]
YES! @nelsonic I will bring some for you guys for sure. :gift: :christmas_tree:

**Comment by iteles** [comment]
#Mind. Blown.

**Comment by sohilpandya** [comment]
Count me in too! :open_mouth: :smile:

**Comment by nofootnotes** [comment]
I'd love to come too! (Sorry, the gluten thing makes it a bit more difficult...)

**Comment by iteles** [comment]
OK friends! 

**We don't need anyone to bring anything**, but _if you do_ it would be really cool if it was something made by you (like an ornament for our tree or a card or whatever the most fun thing you found on Pinterest lately was) :grimacing: :christmas_tree: 

+ @NataliaLKB 
+ @beechware
+ @rorysedgwick  
+ @Jbarget 
+ @minaorangina 
+ @hdrdavies 
+ @katkelemen + 1
+ @rub1e 
+ @mk4111 
+ @Conorc1000 
+ @sohilpandya 
+ @nofootnotes 
+ @jrans 
+ @markwilliamfirth

**Comment by jackcarlisle** [comment]
* @jackcarlisle 
* @des-des

**Comment by Jbarget** [comment]
noooo :(

**Comment by nelsonic** [comment]
@Jbarget next dinner coming soon... :wink:

**Comment by Jbarget** [comment]
fab

**Comment by hdrdavies** [comment]
Very well executed too! @iteles @nelsonic

**Comment by nelsonic** [comment]
*Next time* we will have @nikhilaravi & Neeru, of http://www.onelifetwoways.com/ fame, will be helping us make it extra *special*...!

**Comment by nikhilaravi** [comment]
@nelsonic yes would love to do a south indian special! when???? 5th March is probably the earliest Saturday I can do! or Sunday 28th Feb? 

but sorry no one else gets to meet the twin :wink:

**Comment by nelsonic** [comment]
lol. yeah, @iteles is the best person to ask about dates...
Maybe we need a new issue to discuss the Feb Dinner...? who's creating it? :wink:
