### ISSUE TITLE
THIS. IS. DWYL. (Intro video for FAC)

### ISSUE THREAD

**Issue by rub1e** [dwyl/hq#501]
FAC invites everyone to come and introduce 🤝  themselves / their company to new cohorts, and obviously _dwyl_ should have pride 🦁 🦁 of place as FAC's most important and long-standing partner.

Since this is going to happen three times a year (or more depending on growth), it might be a nice idea for out-of-towners @iteles and @nelsonic to record a short video 🎥  introducing themselves, their vision for dwyl 👁‍🗨 , and their history with FAC. (Which we can then reuse)

We'll be doing our intro session on 7th November (to be confirmed), so if you guys fancy it, you have until then.

I'll let you two decide what `priority` to give this...

**Comment by iteles** [comment]
@rub1e :arrow_right: https://github.com/dwyl/video?

**Comment by rub1e** [comment]
Yeah I put it here uh deliberately cos, um, the README for that repo was unclear :eyes: 

Either that or I didn't see the repo 

https://github.com/dwyl/video/issues/44
