### ISSUE TITLE
Google Drive issues

### ISSUE THREAD

**Issue by rub1e** [dwyl/hq#502]
Last week @iteles and I were both lamenting how slow `Drive` can be - especially spreadsheets with formulae in them which seem to trigger a recalculation when you so much as change tabs, meaning you have to wait up to a minute every single time.

I've tried `pasting as values`, but when I did that to the Invoicing Spreadsheet, every single cell went blank and I had a panic attack.

So I'll find a solution for this for:

* [ ] Invoicing spreadsheet
* [ ] Company calendar

If anyone has any files which behave similarly, add them to this list and I'll look into it.

**Comment by rub1e** [comment]
* Just ran a test using the *amazing* Chrome Developer Tools `Performance` tab and both the `Company Calendar` and the invoicing spreadsheet take over 40s to load (and then extra time whenever you make a change). That's *mental*.

* The reason `paste values` wasn't working in the Invoicing sheet is because there is a resource-sucking `importrange` formula in the first cell. Based on all the complaints in the forums, this seems to be a very unstable function which often causes errors (i.e. it's not something I can fix myself so I'm not going to waste time on it)

* I've pasted the `vlookup` statements as `values`, looks like a few seconds' worth of performance gains but not much

* I've not yet figured out why the `Company Calendar` so slow given that there are no formulae. If I can figure out why this is in less than 10 mins of Googling, I'll update this.

**Comment by iteles** [comment]
@rub1e Pretty sure it's the conditional formatting: https://productforums.google.com/forum/#!topic/docs/cO1ojvtKA7w
![image](https://user-images.githubusercontent.com/4185328/48549595-1f3d1480-e8c8-11e8-88a1-2992f2586d7d.png)

**Comment by rub1e** [comment]
Yeah @iteles I think you're right

Closing this for now, will reopen if there's every anything we can actually _do_ about any of this
