### ISSUE TITLE
Add client reference to all historical invoices

### ISSUE THREAD

**Issue by rub1e** [dwyl/hq#506]
Per https://github.com/dwyl/hq/issues/373#issuecomment-439886776, invoices from before Jan 2018 are missing client references, and therefore don't appear in P&L reports we need to run.

There is no easy solution - just a matter of going into each invoice and adding a client ref line by line.

* [x] Add client refs to receivable invoices
* [x] Add client refs to payable invoices

**Comment by rub1e** [comment]
I might have been a bit optimistic with my half-day estimate... 😕 

Honestly, I didn't realise how little work our previous accountants had done - they've reconciled every single transaction without putting a client reference (sometimes any reference at all), even though this info is usually available on the bank feed (that's how you reconcile the payments!)

But the upside of this is that we'll be able to use Xero reports with confidence, and all of our historical finances will be in order. More of a `hygiene factor` than a _#win_, but still.

**Comment by iteles** [comment]
@rub1e Let’s start with just FY17/18 (which were not in the previous accountants’ purview - that should have been done correctly by us from the start)

**Comment by rub1e** [comment]
Progress update: FY17/18 now has client references on each transaction. (I'm collecting a list of ones where it wasn't obvious, or I have queries, and I'll check with @iteles at the end of the process)

Cracking on with the rest now.

**Comment by rub1e** [comment]
Done. 

Unfortunately, [as I said](https://github.com/dwyl/hq/issues/506#issue-382207475) there's no helpful process arising from this, because it's totally manual and not relevant going forward (because we've been diligently putting client refs on invoices since the end of 2017)

However I did notice an option to automate reconciliation of items on the bank feed, which will be useful for recurring payments like phone bills, subscriptions etc. - which I'll document if I end up using it.
