### ISSUE TITLE
TM01

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hq#507]
@rub1e please prepare my TM01 form. Thank you.

**Comment by rub1e** [comment]
?? Are you being terminated?

**Comment by nelsonic** [comment]
Yes please & thank you.

**Comment by rub1e** [comment]
OK - all ready - shall I push the button? And should it be effective from today?

**Comment by nelsonic** [comment]
@rub1e push which button?

**Comment by rub1e** [comment]
Oh, sorry - it's literally a button - the form is online at Companies House! I just need to put the `effective from` date and <kbd>Push The Button</kbd>

**Comment by nelsonic** [comment]
@rub1e please upload a screenshot(s) of what you see.
Please document the work _while_ you are doing it so that no "steps" are missed.
I will "press the button" on this when it's ready. All I asked was for you to _prepare_ it.

Also, this is _not_ a **`priority-1`** task, for clarity **`priority-1`** is described in https://github.com/dwyl/labels#labels as "drop everything and work on this".
This is a **`priority-3`**. It needs to be done _after_ the P&L is complete. 

Also, this has _nothing_ to do with **`finance`**. 
I opened this issue because of a **_fundamental_ disagreement** in how the company is run. 
Not because I _want_ to leave the company, but because I feel I have _exhausted_ myself trying to make it work when others _insist_ on making the _least_ effort toward technical excellence and perpetuating _mediocrity_.

The company is **not _losing_ money** while I am a director.
If anything each day that I'm a director, the company is **_making_ money**!!
There is a _decent_ "backlog" of **`priority-1`** tasks: https://github.com/dwyl/hq/labels/priority-1
By _far_ the most important of which is Preparing Management Accounts #321 
followed closely by writing a _clear_ business plan #328 
then consolidating our workflow #434 in order to _achieve_ that plan.

***Before*** I resign as a director of dwyl I want to _see_ the _complete_ profit and loss of the company and determine _exactly_ what proportion is attributable to my contribution. i.e. what hours/days of my time were charged to clients both on an _individual_ basis and as "lead" for projects that would have otherwise not have been _possible_ without my involvement. 

Once that is _done_ I will sign the TM01 and be on my merry way safe in the knowledge that the company can run and build client projects #488 _without_ me. 
I know ***exactly*** what I'm doing _next_ after writing up my "_**lessons learned** from 3 years **@dwyl**_".

**Comment by rub1e** [comment]
Process documented in this PR: https://github.com/dwyl/process-handbook/pull/135

To clarify, I can't actually _prepare_ the form because there's nothing to prepare - you just log into Companies House, enter the date, and hit submit.

**Comment by nelsonic** [comment]
@rub1e thanks for confirming. 👍 
Now just pending the clarity on balance sheet so I can submit the form.
