### ISSUE TITLE
Coconut Oil (Bracky Friday Bunduru)

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hq#51]
Amazon has a deal on Raw Virgin Coconut Oil which expires in 14h:
http://www.amazon.co.uk/gp/product/B00SNGY12G
![coconut-oil-amazon-deal](https://cloud.githubusercontent.com/assets/194400/11317891/f07d39ec-9035-11e5-944b-abd205fe6ff1.png)

I'm thinking of getting ***6 Litres*** because it lasts 18 months - https://www.google.co.uk/webhp?q=how%20long%20does%20coconut%20oil%20last

**Comment by iteles** [comment]
Was this the oil you mentioned wasn't particularly fragrant? Or pretty good for cooking still?

**Comment by nelsonic** [comment]
This is the oil I *loved* :heart: 
I don't expect anyone else to use it.
