### ISSUE TITLE
When did pensions contributions begin?

### ISSUE THREAD

**Issue by Cleop** [dwyl/hq#513]
#342 #474 show details about the pensions but I can't clearly ascertain from it when pensions began being contributed to.

I need to fill this information in for my tax return... 🙌 🙄

**Comment by iteles** [comment]
@Cleop April 2018 https://github.com/dwyl/hq/issues/342#issuecomment-374928044
You should have the details in the email we also sent you just before the pension scheme started (sometime in March 2018) and you should also see these logged in your payslips from April onwards.

**Comment by rub1e** [comment]
Closing in favour of https://github.com/dwyl/UK-HMRC-FAQs/issues/14
