### ISSUE TITLE
Has dwyl's name/ meaning changed?

### ISSUE THREAD

**Issue by Cleop** [dwyl/hq#519]
I've noticed a couple of places on github where dwyl which I've always formerly known to stand for 'do what you love' instead reads:

![image](https://user-images.githubusercontent.com/16775804/51915319-bcd9b780-23d2-11e9-823a-a9b67876fb57.png)

has this changed? is there an issue relating to the process of this decision?

To me, I think this is a more negative phrase. However I suppose it could link with saving time which could be in line with our product goals? But then again so could 'do what you love'... Or is it because there is competition for the use of 'do what you love' with other brands?

**Comment by nelsonic** [comment]
@Cleop _thank you_ for opening this issue. 
we had the "do what you love" (slogan) in the title for a long time (_long before others_<sup>1</sup>...)
until "ghost" decided to [remove it](https://github.com/dwyl/learn-nightwatch/issues/58) ... 🙄 

We briefly restored it last year and then _I_ updated it to the ["_other side of the **same** coin_"](https://dictionary.cambridge.org/dictionary/english/be-two-sides-of-the-same-coin). 
It might not be immediately obvious but "***don't waste your life***" 
is the "away motivation" version of "do what you love" (_toward motivation_)
see: https://en.wikipedia.org/wiki/Motivation#Neuroscience

My _reasoning_ for _de-limiting_ our organisation to "doing what you love" is simple: https://github.com/dwyl/start-here/issues/178
By making _everything_ we do about doing something we "_love_",
we will _never_ leave our comfort zone and do things that we _don't_ (_currently_) love 
but which are _really_ good for us, the environment or society.

If someone "_loves_" eating hamburgers and driving gas guzzling muscle cars,
should they mindlessly continue doing that all day at the expense of the environment, noise pollution and the long-term health of both themselves, their loved ones and the animals they are killing for _taste_?


I'm a fan of what NPM are doing with their _expanded_ initialisation https://www.npmjs.com
![image](https://user-images.githubusercontent.com/194400/51985127-0b4f8a80-2495-11e9-98f9-fc31fb121451.png)
It changes another 3 words beginning with **N, P & M** each day.

We can always change it _back_ to "_do what you love_"<sup>1</sup> once _everyone_ has read Cal Newport's book "So Good They Can't Ignore You" https://www.amazon.com/Good-They-Cant-Ignore-You/dp/1455509124 and learns that focussing on ***skills*** is the ***only*** way to **guarantee** finding/doing work we love. 

✨ 

<sup>1</sup> Also, sadly, "***We Work***" trademarked the slogan ... and they use it _everywhere_! they did it ***after*** Inês named the company but sadly, the **law** doesn't care who "invented" it, only who _registered_ it _first_ ... 😞 https://www.google.com/search?q=wework+do+what+you+love&tbm=isch

**Comment by iteles** [comment]
I'm a fan of the versatility so I didn't change it myself when I noticed @nelsonic had changed it. I currently use both interchangeably depending on what is more befitting of the situation and I think a stronger brand presence brought on by a product will clarify this (with the help of some user testing).

The WeWork trademark was also a 🙄 moment so as you mentioned @Cleop it was definitely a factor.

**Comment by Cleop** [comment]
Thanks for the clarification @iteles @nelsonic, I like the context of the 'away motivation' 👍

**Comment by rub1e** [comment]
> I'm a fan of what NPM are doing with their expanded initialisation

Honestly, the first time I noticed "Don't Waste Your Life", I refreshed the page to see if it would change to "Don't worry, you lump" or "Do while you learn".

Disappointed.

**Comment by nelsonic** [comment]
Worth linking to this issue/thread from "start-here" in case anyone ***`else`*** has this question ...? 💭
