### ISSUE TITLE
New Phone || Desk Charger || Battery Case for Inês?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hq#522]
https://github.com/club-soda/club-soda-guide/issues/438
![image](https://user-images.githubusercontent.com/194400/52089680-15fa4480-25a7-11e9-905f-93ace824575a.png)
not even **10am** and @iteles' phone is down to **7%** ... 🔋 
Maybe time to:
+ [ ] Get a "battery case" that extends the life of current iPhone
+ [ ] Get a desk charger 
+ [ ] Buy a Newer Phone (_with wireless charging_) ?

**Comment by iteles** [comment]
😆 I'll get a new desk charger thanks, I would just never use a batter case.

**Comment by nelsonic** [comment]
https://www.amazon.co.uk/DIGI4U%C2%AE-Ligntning-Charger-Station-Support/dp/B01LBAJ63Y
![image](https://user-images.githubusercontent.com/194400/52090566-ad609700-25a9-11e9-90a7-06867c25f004.png)
Lighting port is hight-adjustable so it works with any thickness of case. 💡

**Comment by iteles** [comment]
Ordered. Thanks for the intervention!

Should arrive 6-Feb directly to Portugal.

**Comment by nelsonic** [comment]
The _first_ step is admitting we are powerless over our iPhone dependency 
and that our lives have become unmanageable. 
https://en.wikipedia.org/wiki/Twelve-step_program
🙄
