### ISSUE TITLE
Annual Confirmation Statement 2019

### ISSUE THREAD

**Issue by rub1e** [dwyl/hq#526]
From HMRC:

> Every company must file a confirmation statement. It confirms the information we hold about your company is up to date. A statement must be filed at least once a year, but you may choose to file more often.

> It’s a criminal offence not to file your statement within 14 days of the end of the review period. If you don’t file, your company and its officers may be prosecuted. Your company may also be struck off the register.

**Our deadline is 16th April 2019**, but we can file sooner if we like - just be aware that if we file sooner, our schedule changes according to the new date (i.e. the next deadline is one year from the _new_ date) **unless** we change the date manually (see `Process` below)

* [x] File Confirmation Statement
* [x] Add process to handbook

**Comment by rub1e** [comment]
Oh! I just tried to do a dry run of the process to check if we needed any extra info... and I actually just finished it!

@iteles Assuming there are no changes that I'm not aware of, this is ready for filing. 

The only thing I want to check is why our Share Capital entry is down as "Updated" when it was actually updated last year and hasn't changed since

## Process
* Log into Companies House
* Hit "File Confirmation Statement" on the main page, and then `Start`
* Check if you want to change the date of your statement from the default (today's) date
![screenshot 2019-02-06 at 10 49 17](https://user-images.githubusercontent.com/11595920/52336471-ec08ae00-29fc-11e9-94af-8993f60e1a41.png)
* Confirm whether your company's shares were traded on a stock market this year
* Now confirm whether there have been any changes to the following:
  * Registered office address
  * Officers
  * Registers
  * SIC
  * Share Capital 
  * Shareholders
  * PSCs
![screenshot 2019-02-06 at 10 50 39](https://user-images.githubusercontent.com/11595920/52336596-3427d080-29fd-11e9-9c53-9a5145806e31.png)
* Now pay the £13 submission fee and you're done!

**Comment by iteles** [comment]
@rub1e I've checked and agree the share capital is the same so also not sure what that's about!

Worth considering #493 ?

**Comment by rub1e** [comment]
All good - your Companies House entry is already updated and that's what the Conf Statement is based on:

![screenshot 2019-02-06 at 12 13 10](https://user-images.githubusercontent.com/11595920/52340830-bc5fa300-2a08-11e9-8c01-ef1c0fd4a717.png)

**Comment by rub1e** [comment]
OK so shall I just file it once I've double-checked about the share capital?

**Comment by iteles** [comment]
@rub1e The names in the 'shareholders' section aren't updated though.

But other than that, yes. Do you need me to file for bank card payment purposes?

**Comment by rub1e** [comment]
Nah - you owe me a couple of expenses anyway and I'll sort that next week, so all good

Re names - good spot - the `Officers` section is correct, but the `Shareholders` isn't - a mildly interesting insight into how they've designed the platform. *Mildly*

**Comment by rub1e** [comment]
![screenshot 2019-02-06 at 14 10 59](https://user-images.githubusercontent.com/11595920/52347112-136d7400-2a19-11e9-8f11-8cff0f6554f9.png)

Boom

Will close when accepted

**Comment by rub1e** [comment]
Process is documented [here](https://github.com/dwyl/process-handbook/blob/master/Finances/annual-confirmation-statement.md)

**Comment by iteles** [comment]
@rub1e Excellent, happy to close this issue 👍
