### ISSUE TITLE
Change dwyl registered office address in readme

### ISSUE THREAD

**Issue by rub1e** [dwyl/hq#528]
We went through documents changing our registered business address on them when we moved last year, but I've just noticed a README with the old MDC address

* [x] Search through repos for MDC or Palmers road and update

**Comment by nelsonic** [comment]
@rub1e is there any way to ["DRY"](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself) this?
(_i.e. if we change address again in the future, we only need to update it in **one** place_)

**Comment by rub1e** [comment]
I'll have a think and then add it to https://github.com/dwyl/process-handbook/blob/master/moving-premises.md

Might even turn it into an actual checklist, rather than just bullets :man_facepalming:

**Comment by rub1e** [comment]
The only real way to DRY this is by not actually putting our office address down in so many places!

So **on github** we have our Registered Address... 

* in the [HQ README](https://github.com/dwyl/hq/blob/370cae031834a6b9d6a735b5f3b7f1643938009f/README.md), which really isn't _necessary_ - our company registration number suffices because Companies House displays our address publicly.
* In the `employment-agreement.md` [in HQ](https://github.com/dwyl/hq/blob/370cae031834a6b9d6a735b5f3b7f1643938009f/employment-agreement.md), which I suggest deleting entirely as it's out of date and doesn't belong there anyway

And **on the website**, it's in various places but they can all be changed in one go with a simple `find + replace`

**Comment by iteles** [comment]
@rub1e Agreed!

**Comment by rub1e** [comment]
![image](https://user-images.githubusercontent.com/11595920/54268555-5f10c180-4573-11e9-87ca-b380eada7f16.png)
And the only place that Palmers Road shows up is in FocusHub, so this is looking good!
