### ISSUE TITLE
Draft Excluders

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hq#53]
@iteles can you ask ZEN if they can provide or recommend a set of draft excluders for doors which have a 1cm gap at the bottom/top?

**Comment by iteles** [comment]
:+1:

**Comment by iteles** [comment]
Asked and awaiting an answer :ok_hand:

**Comment by iteles** [comment]
We spoke verbally about this but I forgot to update the issue As I mentioned when they got back to me in January, they can provide something, but it would need to be *screwed into place* which is why it wasn't taken further at the time. Shall we close and re-open when relevant again @nelsonic ?

**Comment by nelsonic** [comment]
@iteles screwing in the draft-excluders is a 10 min job. please order them based on your research. thanks! 👍

**Comment by markwilliamfirth** [comment]
ok to close?

**Comment by markwilliamfirth** [comment]
Closing based on summer / new door installation

**Comment by nelsonic** [comment]
We tend to _close_ issues when they are _done_, not because they are "_out of season_".
People still use the heaters while wearing T-Shirts so maybe the draft is still an issue...?
Might be worth transferring this to the FH repo instead?

**Comment by markwilliamfirth** [comment]
Issue has been moved

**Comment by nelsonic** [comment]
moved to _where_...? 😺
