### ISSUE TITLE
VAT Return | May to July 2019

### ISSUE THREAD

**Issue by iteles** [dwyl/hq#538]
VAT Return for the period 01.05.19 to 31.07.19

Deadline: 7th September 2019

* [x]  @iteles to check all expenses have been put through
* [x] @iteles to speak to Karen about changes in allowable expenses
* [x] @rub1e to check all bank feed items have been reconciled
* [x] File return
* [x] Check we've been debited and close issue

**Comment by rub1e** [comment]
We've been debited but leaving this open as we haven't been able to get hold of Karen yet

**Comment by iteles** [comment]
Let's have Karen as a separate issue 👍
