### ISSUE TITLE
Christmas Tree?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hq#54]
http://www.homebase.co.uk/en/homebaseuk/living-blue-spruce-christmas-tree-25-3ft-555470
<img width="1025" alt="living-christmas-tree-homebase" src="https://cloud.githubusercontent.com/assets/194400/11344446/49d4b554-9209-11e5-9c70-f5e36bd9f846.png">

@iteles wanna go pick up a Tree for the Veranda this Thursday...?

**Comment by nelsonic** [comment]
the 4 foot one is only an extra *fiver*... http://www.homebase.co.uk/en/homebaseuk/living-norway-spruce-christmas-tree-35-4ft-554840 
<img width="1019" alt="living-christmas-tree-homebase-large" src="https://cloud.githubusercontent.com/assets/194400/11344493/86179f72-9209-11e5-9a6f-20f9b5ed4b20.png">

**Comment by iteles** [comment]
:blush: Tempted to get one for _inside_ :wink:

**Comment by nelsonic** [comment]
Next to the Bean Bags...?
But a *real* tree or a *fake* one...?
and `if(real)` then `dead || alive` ?

**Comment by iteles** [comment]
A little research shows that a _real, living_ tree is apparently more :evergreen_tree: friendly!
http://envirodad.com/which-is-more-eco-friendly-real-trees-vs-artificial-trees/     
http://www.theguardian.com/environment/2006/dec/11/greenchristmas

We've been tree-free for so many years now that I think we're due one :yum:

**Comment by nelsonic** [comment]
The Guardian article recommends making a donation to [*Woodland Trust*](http://www.woodlandtrust.org.uk/christmas/index.htm) *instead* of buying a tree...

**Comment by nelsonic** [comment]
The point of buying a *living* tree is that its the *best of both worlds* it encourages trees to be planted and we get to *keep* and *nurture* it ... *and* we can *also* make the donation to the Woodland Trust!

**Comment by iteles** [comment]
No, the Guardian article recommends going tree-free as an _alternative_, but if we're getting a tree, a _living_ one is the way to go.

**Comment by nelsonic** [comment]
Quando vamos?

**Comment by iteles** [comment]
Amanhã ah noite?

**Comment by nelsonic** [comment]
Segunda ou Terça?

**Comment by iteles** [comment]
Terça realistically. Monday is the night before our sprint deadline...

**Comment by nelsonic** [comment]
http://www.amazon.co.uk/gp/product/B00Q4OK3OO
![amazon-living-christmas-tree](https://cloud.githubusercontent.com/assets/194400/11495161/d1bf3672-9800-11e5-83dc-6e453434039a.png)

Not long left on the clock. and we would have to be home to receive it. 
(or I could cycle it home in my pannier...?)

**Comment by iteles** [comment]
The reviews make it seem 50/50 as to whether we'll get a tree that's ok or not... Even the 4 star review says a chunk was missing from the top!

I think we'd have to hire a car and pick it up from FAC as we have meetings of one form or another every day this week :(

**Comment by nelsonic** [comment]
Cruson. today. on our way home.

**Comment by iteles** [comment]
Today? :sparkles:

**Comment by nelsonic** [comment]
You decide what time we leave...

**Comment by iteles** [comment]
![img_6847](https://cloud.githubusercontent.com/assets/4185328/11767695/d58d9b30-a1ac-11e5-8583-bbfaf38a464d.jpg)

We even got some new tree decorations from dwylers, like this beautiful wooden one from @katkelemen! https://twitter.com/dwylhq/status/676031478057312256
![kata-dwyl-tree-decoration](https://cloud.githubusercontent.com/assets/4185328/11767699/fcddd7f4-a1ac-11e5-9c68-cf90d8550685.jpg)

**Comment by nelsonic** [comment]
Closed? :christmas_tree: needs :droplet:
