### ISSUE TITLE
Hex.pm @dwyl user access?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hq#540]
@iteles do you know who has access to the @dwyl user for publishing packages? ❓ 

https://hex.pm/users/dwyl
![image](https://user-images.githubusercontent.com/194400/65838855-3f6a9c00-e2ff-11e9-8b8c-7dfc0a31e2ec.png)

I ask because I am in the process of writing a tutorial for how to publish Hex.pm packages https://github.com/dwyl/learn-elixir/issues/95 and would like to publish my sample/demo package under the @dwyl user.

The two packages published on Hex.pm under @dwyl's user are:
+ https://hex.pm/packages/elixir_auth_github > https://github.com/dwyl/elixir-auth-github
+ https://hex.pm/packages/pre_commit > https://github.com/dwyl/elixir-pre-commit

Both have @ZooeyMiller & @finnhodgkin as the main contributors. ❤️ 
The email address appears to be `hello@dwyl.com` so we might be able to just reset the password by email ... 🤔 

Hoping to use this tomorrow so any insight would be welcome. 🙏 
Thanks! 🌻

**Comment by iteles** [comment]
In touch with @finnhodgkin and @ZooeyMiller and working on this 👍

**Comment by nelsonic** [comment]
@iteles was able to reset the password using `hello@dwyl.com`:
![image](https://user-images.githubusercontent.com/194400/65877148-cf9df500-e382-11e9-908d-f9f61ea4947a.png)

(_might not need to bother Finn / Zooey ..._)

**Comment by nelsonic** [comment]
Updated profile picture:
![image](https://user-images.githubusercontent.com/194400/66103089-7fa27680-e5ac-11e9-9b3d-636787fbbd19.png)

Going to attempt to publish a package and then will close this issue. 📝

**Comment by nelsonic** [comment]
Works. Closing. ✅
