### ISSUE TITLE
Github Sponsorship for OS Tech we Use @dwyl

### ISSUE THREAD

**Issue by iteles** [dwyl/hq#545]
We have built and maintain a lot of open source modules which ~~is a very time and resource-consuming affair!~~ we do because we want to build a great quality product.
We use a lot of Open Source code that other people have spent ***millions*** of hours developing!
As such, it might be worth looking into [Github Sponsors](https://help.github.com/en/github/supporting-the-open-source-community-with-github-sponsors/setting-up-github-sponsors-for-your-user-account) (linked to #130) to see if it might be interesting for us to trial on a couple of modules.

I'd like to know:
+ How this works
+ What it looks like on a repo
+ What sponsorship tiers would be advisable
+ Whether there is any negative feedback on this that we should know about
+ What steps are required

**Comment by nelsonic** [comment]
No thanks. I don't believe in or _need_ handouts. Or want to _risk_ having a _corporate_ sponsor.
We (_should_) build a [**`product`**](https://github.com/dwyl/product-roadmap) that people _love_ using and are _delighted_ to _pay_ us for it.
Cash from a _great_ product will more than pay for all the work "we" have done and expect to continue doing. 
_Surplus_ cash from a successful product that _thousands_ of people love and _recommend_ to their family/friends will allow _us_ to sponsor the OS projects/tech that we use @dwyl https://github.com/dwyl/technology-stack
(_so the **idea** of **GitHub sponsorship** is not "bad", in fact it's **really good** for **us** to use as an **inbound tool**!_)

**Comment by iteles** [comment]
I think we see this differently in terms of what constitutes a 'handout'. Nevertheless, having no control over who we accept sponsorship from (i.e. running the risk of having a corporate sponsor whose values we disagree with) is a good enough reason to not set this up at the moment.

As for sponsoring the tech we use, we already do this (see https://github.com/tachyons-css/tachyons/releases/tag/4.7.0) and I don't think we need a specific issue open for this until we have a successful product!
