### ISSUE TITLE
Annual Confirmation Statement 2020

### ISSUE THREAD

**Issue by rub1e** [dwyl/hq#550]
Due before 20th Feb 2020

* [x] @iteles to confirm any updates in capital or officers
* [x] Follow process [here](https://github.com/dwyl/process-handbook/blob/master/Finances/annual-confirmation-statement.md) and file @rub1e

**Comment by iteles** [comment]
@rub1e Only change is a name change as discussed.

**Comment by rub1e** [comment]
I've submitted a name change and an address change - I can't submit the confirmation statement until they've been processed, but I've got a note in my calendar to check tomorrow. The conf statement deadline isn't for another 9 days so no danger of missing it.

Will update when submitted

**Comment by rub1e** [comment]
The changes have been accepted but they're not reflected in the Conf statement yet, and I don't want to submit it until they have been. I'll check it again on Monday and if it's still not current I'll give them a call - will still be a few days before it's overdue so no risk of missing deadline

**Comment by rub1e** [comment]
Done, and note in diary for 2021 (I've not opened an issue for it so it doesn't sit around for a whole year)

You owe me £13

**Comment by iteles** [comment]
Perfect, thanks, please drop it into Xero as an expense!
