### ISSUE TITLE
Internship?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hq#556]
We received this request via our contact form for a fully funded internship position:

![internship-request](https://user-images.githubusercontent.com/194400/82730261-49119b80-9cf6-11ea-87c1-87345e58ea04.png)

[Internships-guide-for-employers-COVID-19-FUND.pdf](https://github.com/dwyl/hq/files/4671727/Internships-guide-for-employers-COVID-19-FUND.pdf)

![image](https://user-images.githubusercontent.com/194400/82730340-c806d400-9cf6-11ea-808f-c6a1f8289846.png)

Seems like it could be worth considering as it's a "win-win" for the student and we could ask them to do some mutually beneficial work. 💭 

The overhead on our side is submitting a proposal to the University with a brief outline of what the student will do. 4 weeks is not very long but it's an opportunity to test out our "onboarding" and build a couple of features. If the person is conscientious and works well, we could hire them for a specific time frame. 

Thoughts?

**Comment by iteles** [comment]
With a very clear journey with expected outcomes per week (and a provision if @SimonLab has to take some time off unexpectedly 😉), I think this could be great! 
The  biggest proviso here for me is that this will only work _if_ the student is keen to learn and work hard rather than just tick an internship box - we've had the latter and it was not only a huge waste of everyone's time but a big morale drain too.

**Comment by nelsonic** [comment]
The person in question has made a few contributions to GitHub repos in the past year so at least they have the Git basics down. :octocat: Also being a CS Major 🧑‍💻 the will have solved more problems/challenges so won't get "stuck" on trivial things for _days_ without the instinct to keep trying or ask questions! 🤷 
My only reservation is that the person has not "starred" _any_ @dwyl repos and does not have any evidence of `Elixir` on their GitHub; they have used `Go`, `JavaScript`, `Python`, `C`, `Java` and `Shell` which demonstrates they are "polyglot" and can pick up `Elixir` _fast_ if they need to.

**Comment by iteles** [comment]
Next step: ask for a CV and dates they were considering for internship?

**Comment by nelsonic** [comment]
@iteles the person who sent the internship request email has a personal website which has their CV. My understanding from the PDF above is that the internship has to start before the end of June 2020. So I would propose that they start on Mon 29th June and it lasts for a month so it would basically be the month of July.
I have several thoughts on what they can learn/build. Will write up tomorrow morning. 💡

**Comment by nelsonic** [comment]
I have drafted the following reply:

<hr />

Dear `{Name}`,

Thank you for getting in touch!
We are always delighted when people discover our learning resources.
If you have not yet found your ideal internship for this summer, we would like to discuss the opportunity to work with you. We have a specific project in mind that we believe will play to your strengths. We see from your GitHub that you have dipped your toe into building an Elixir IoT project; that's great! The project we have in mind is an **IoT smart home display** with connected sensors for showing contextual information to the observer.

As per the Bristol internship requirements the internship should start "before the end of June 2020".  We would ideally start on **Monday 29th June**. This will give us enough time to get everything organised.

We look forward to hearing back from you.

Kind regards,

Inês & Nelson
Co-founders.


<hr />

I have created the following internship on the Bristol engage system (pending approval):

https://engage.bristol.ac.uk/employers/protected/PublishJob.aspx?id=515422
![image](https://user-images.githubusercontent.com/194400/83349283-919b0b80-a32b-11ea-8967-6254b8e0c6ea.png)

Text:

```
Summer internship to build an internet connected energy efficient smart display.
Expect to wire components, write Open Source code and documentation.

Working week: Monday - Friday.
Working hours: 09:00 - 17:00 (flexible)
Twice daily remote team meeting via Zoom.
Agile working practices.

Ideally suited to a Computer Science, AI or Electrical Engineering student.
(we will consider alternative degrees based on evidence of experience/aptitude)

Preferably you will already have some basic experience with hardware 
(e.g: Raspberry Pi and/or Arduino) and coding (e.g: Python or Elixir).

Expect to exercise your creative problem solving skills and learn a lot.
All components and training provided as required.
```

For context: the project I will assign to the intern is the "Welcome Display" for [@home](https://github.com/dwyl/home) I will fully define the task in due course. The gist is a Raspberry PI connected to a screen with a motion sensor controlled to a relay to switch. The screen will switch off when no motion is detected and turn on when someone walks past. 
It will display basic stats about the house by default. Depending on how fast we can iterate I would like to display _contextual_ info based on the person standing in front of the screen (TBD).

@iteles / @SimonLab please let me know if OK to send the above email. Thanks.

**Comment by iteles** [comment]
Looks great to me 👍🏻

**Comment by nelsonic** [comment]
@iteles thanks for checking/confirming. I have sent the email. ✉️

**Comment by nelsonic** [comment]
I've submitted the vacancy for approval:
![image](https://user-images.githubusercontent.com/194400/83350094-864ade80-a331-11ea-8366-6bc09876dee9.png)

I have stated we have 2 vacancies (_to encourage other potential applicants!_)
Given that I _really_ want to get the smart display built for [**`@home`**](https://github.com/dwyl/home) and will re-use the tech for the security system, plant watering etc.  I will dedicate the time to ensuring that the interns are supported. It's _very_ likely that @SimonLab will be on leave in July so I will probably be dedicating more time to my "Home Work" in any case.

**Comment by iteles** [comment]
Will be spending some time on this tomorrow.

**Comment by nelsonic** [comment]
@iteles we _specifically_ need to find out what the conditions for the funding are. 💭

**Comment by iteles** [comment]
We have two emails to send, one to our already accepted intern:
```
Apologies for the radio silence, we have a lot going on this month!

Rest assured, your internship spot is yours - you did the research, found us, reached out and took
initiative; that counts for a whole lot around here! 
We did open up a second internship spot which we’re currently still receiving applications for. Working, 
pairing and learning in remote teams is an invaluable skill which we plan to make a big part of your internship with us. 

We’ll be sending through some paperwork to you next week, so please keep an eye out for that. 
We're also working on making everything official through the University system.

In the meantime, please read through our contributing policy to have a sense of how we work:
https://github.com/dwyl/contributing (this is based on working with clients but the project you'll be working on is internal - it'll be tweaked but the basics will remain the same)

And feel free to also start going through our Elixir tutorials, opening issues if as you go!
https://github.com/dwyl/learn-elixir

Do you own a raspberry pi or have you had any experience with one before?

We'll be in touch next week with more!

Many thanks
```


We also need to send one to the applicants to acknowledge their applications:
```
Dear xx

Thank you for your application, we were excited to see your interest!

We will be reviewing CVs over the next few days and will likely send you any clarifying questions by the end of the week. We will be looking to make decisions by the end of next week at the latest or preferably earlier.

If you have any conflicts or have taken another internship in the meantime, please do let us know.

Many thanks
```

@nelsonic @simonlab Any thoughts on these?

**Comment by iteles** [comment]
@nelsonic Aside from vetting the above, can you please share the login details so I can see how it's to be put through the Bristol system?

**Comment by nelsonic** [comment]
@iteles the login details for the Bristol Engage system: 
https://engage.bristol.ac.uk/Employers/Login.aspx
username and password are in the dwyl **one pass**.

What we need to do is contact `careers-uobinterns@bristol.ac.uk` to _confirm_ that the internship that we posted qualifies for the "**COVID-19 SME Internship Fund**".
And if _not_, I think I only want to hire **one** intern (_using my/our own cash_)
because the person who contacted us (_above_) already has the skills needed to help with the system in Braga Home and I won't have to do to much hand-holding. 💭

**Comment by iteles** [comment]
![image](https://user-images.githubusercontent.com/4185328/84489955-63f28280-ac9a-11ea-905f-0ae3a75ee24f.png)

From the paperwork it looks like we need to _apply_ for funding thought the application process is unclear. https://engage.bristol.ac.uk/Uploads/Attachments/Internships-guide-for-employers-COVID-19-FUND.pdf

I'll email them now.

**Comment by iteles** [comment]
Emailed 👍🏻

**Comment by iteles** [comment]
I have chased but haven't yet heard back. I suggest we open up only one internship for now if we don't hear from them by the end of the week.

**Comment by nelsonic** [comment]
Closing as complete. ✅
