### ISSUE TITLE
Paid service to make calls to the UK from abroad?

### ISSUE THREAD

**Issue by iteles** [dwyl/hq#563]
Back in the day when I started university (in the long long ago), Skype used to have a service which essentially gave you a phone number belonging to a country of your choosing which meant you could receive calls cheaply from people calling from that country (as it would be a local call for them) and you could also call from Skype at a relatively low rate.

With Brexit, it has become _super_ expensive for us to call UK numbers whilst we're abroad (which we need to do on occasion to speak to services firms for example).

Does anyone know of a service that allows us to make calls (over VoIP for example) for a more reasonable fee?

**Comment by nelsonic** [comment]
@iteles you could use Amazon Connect for outbound calling which would be covered by the "Free Tier". 
But would incur a fee if you need a telephone number for inbound calls ... and the UI/UX meh. 


I've been looking into switching my UK phone to this provider: https://xpatfone.com/pricing-1

![image](https://user-images.githubusercontent.com/194400/150883825-d6eb14d7-0234-4de7-bbee-6cc301187132.png)

But they don't offer any Data. so my phone would become "dumb".

**Comment by iteles** [comment]
This is an app on your phone which on the one hand seems SUPER practical and on the other seems like an insane privacy concern (we could always keep this app on a spare 'old' phone though), it seems like it would be the best in terms of rates and for our volume of calls:

https://www.mytello.com/en_PT/rates/cheap-calls-to-england
![image](https://user-images.githubusercontent.com/4185328/153638823-7b4dac3a-d533-4b29-9158-8a14fc12a695.png)

![image](https://user-images.githubusercontent.com/4185328/153638458-ea23b582-d4dd-4e16-a1b8-a0fd3dcfb674.png)

Skype rates for comparison:
![image](https://user-images.githubusercontent.com/4185328/153638677-b4db5385-27fe-44b6-a6bb-7ac799918577.png)

**Comment by iteles** [comment]
@nelsonic I still think that MyTello https://github.com/dwyl/hq/issues/563#issuecomment-1036440229 appears to be the best value.

If we can put this on an old phone that has access to nothing, it'll be a useful resource.

**Comment by iteles** [comment]
@nelsonic Shall we put this on the phone with the blue cover we're currently using for white noise? 
Or do we have an old test one we should/can use instead?

**Comment by nelsonic** [comment]
@iteles we have several test (older) iPhones we can use, but "the one with the blue cover" (iPhone XR) has wireless charging so it's a good shout if you think we aren't going to use it (for calls) very often. 💭

**Comment by iteles** [comment]
OK, this is annoying. You still need a phone sim in the phone (it's not voip apparently) as it's a number you call.
OK if you have free minutes, not great otherwise. But let's use it for now, it's a short term solution before we find a better one and WAY cheaper than using our UK phones on roaming.

**Comment by iteles** [comment]
Currently using `MyTello` as above on a 'spare' old phone which has access to nothing else, which seems to be allowing calls over Wifi and _is_ voip after all post-setup. 
Closing for now as it's meeting the immediate requirements 👍
