### ISSUE TITLE
New Laptop?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hq#57]
My Mac Died... :cry: 
I'm thinking of going back to using more reasonably priced Laptop... with an Open Source OS...
Possible options are:
+ Grade A: http://www.ebay.co.uk/itm/Refurb-ThinkPad-X1-Carbon-i7-3667U-2-00GHz-8GB-240GB-SSD-W8-Pro-64-Bit-GradeA-/371453760246 £599
+ Grade B: http://www.ebay.co.uk/itm/Refurb-ThinkPad-X1-Carbon-i7-3667U-2-00GHz-8GB-240GB-SSD-W8-Pro-Ultrabook-/321924334704 £399
+ Shop: http://www.3000rpm.com/acatalog/Lenovo-x1-carbon-laptop.html
+ X230 with SSD: http://www.ebay.co.uk/itm/Lenovo-ThinkPad-X230-intel-Core-i5-2-6GHz-12-5-WEBCAM-Laptop-8GB-RAM-240GB-SSD-/231631028716 £269 (see upgrades list...)
+ X230 with 16GB HD: http://www.3000rpm.com/acatalog/Lenovo-Thinkpad-X230-Intel-i5-3320M-2.60Ghz-Laptop---16Gb---320Gb--12.5-Inch---Webcam---Windows-7-Pro.html
+ X220 CHEAP http://www.ebay.co.uk/itm/WINDOWS-7-IBM-Lenovo-X220-CHEAP-Laptop-Core-i5-4Gb-Warranty-FAST-320GB-Grade-B-/172014845107 £150

**Comment by nelsonic** [comment]
@iteles when you get back from your walk, please order this: http://www.ebay.co.uk/itm/Lenovo-ThinkPad-X230-intel-Core-i5-2-6GHz-12-5-WEBCAM-Laptop-8GB-RAM-240GB-SSD-/231631028716
Thanks! :+1:

**Comment by iteles** [comment]
<img width="625" alt="screen shot 2015-12-11 at 16 21 05" src="https://cloud.githubusercontent.com/assets/4185328/11749022/3d3321e6-a023-11e5-8a94-5ca1242f28b4.png">

**Comment by nelsonic** [comment]
Thanks! :wink:

**Comment by iteles** [comment]
Arrived :+1:
