### ISSUE TITLE
Sean

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hq#577]
Sean ( @Shamus-88 https://www.linkedin.com/in/sean-eady ) 
is an experienced marketing and biz dev manager 
who is currently undergoing a career transition 
from FMCG to digital product management.  

Sean is joining us as a UX Researcher/Designer & Product Owner 
to pick up some of the tasks @nelsonic has been lacking on. 
Nelson will be providing as much guidance/mentoring as necessary 
and answer any questions along the way. 
But the idea is for Sean to learn as much as possible 
about the role of PO/PM in a software/tech startup 
to determine if the role is for him long term; 
get some experience where the door is firmly shut 
to new entrants without _years_ of experience in the sector 
and then take it from there.

# Sean’s mission while @dwyl will be:

1. Read our docs & issues on GitHub and ask _lots_ of clarifying questions (as issues/comments on GitHub so that they are indexed by Google for future joiners). The more questions the better. There are no “stupid” questions. Just maintain a “beginner’s mind” and keep asking until everything is clear.
2. Devour as many relevant books on the subjects of interest from the @dwyl library including (but not limited to): Lean Startup, Lean Metrics, Start Small pStay Small, Organic/Inbound Marketing, UX design, Tools of Titans, Make Time, etc.
3. Build experience of UX design & Product Ownership by performing the dual role of UX analyst/researcher/tester & Product Owner while making copious notes. 
4. Help us study/analyse the competing products in the “personal effectiveness” space; sometimes referred to as “productivity”. There are **_many partial_ solutions**; none of them are the full package and open source. Remember: we “only” need **10k people** using our product for it to be sustainable. Beyond that we can afford to hire a team, expand features and build something amazing!
5. Research and capture the best landing pages that showcase features, benefits, testimonials of the best available apps. Document these extensively with screenshots and notes on GitHub.
6. Work with devs to build the fastest-loading Landing Page possible that smashes all pref, SEO & best practice metrics.
7. Help define the metrics we want to track and how we want to visualise them both for our own product development/management purposes and more importantly to show the people _using_ the product their own metrics. We want this to be one of our USPs. 
8. Daily Metrics Reviews even if the numbers are all Zeros or Growth curve is flat. It’s essential to have a constant reminder of what we are focussing on. Like the obese person who wants to get ripped, the progress is slow and often flat-lines. That’s not the time to stop checking numbers (and give up) it’s the time to think+work harder on the goal! 
9. Research the best product announcement/release notes. Help write our notes in non-technical person friendly way when we ship new features. [content creation]
10. Help define and execute low-cost organic product marketing including social posts, videos & product hunt lunch/updates.
11. Research and validate our pricing model for the App: https://github.com/dwyl/app/issues/277 (please comment)
12. Document _everything_ learned along the way building a digital product from (near) scratch. This will serve both as the training guide for the next person who takes on the role of Product Owner and as a showcase of knowledge/skills [calling card] for future employers or potential co-cofounders of subsequent ventures.
13. Along the way: develop coding skills as needed to add features to the product. 🧑‍💻 

Don’t worry, not all of these are expected/required on day 1.
This is just an outline of the possible tasks.
More can be explored as surfaced. 
The point is [“_chose your own adventure_”](https://en.wikipedia.org/wiki/Choose_Your_Own_Adventure)!
With the aim of either being _highly_ employable in the tech sector
Or having the skills to co-found your own venture ASAP. 
The more questions asked and documentation written, the faster learning. 

> "_You just have to have a never-ending thirst for learning. 
> if you want to get on top and stay on top.
> The only way to do it is to just constantly be learning.
> Or someone who is learning is gonna have a leg up on you in the knowledge game._" 
> ~ Jimmy Donaldson: https://youtu.be/Z3_PwvvfxIU?t=3641

And since everything we do is open it can always be referred back to it in the future. 🔗

**Comment by seaneady** [comment]
Thank you for the intro @nelsonic.

I am immensely excited to join Team DWYL and start learning and contributing towards the success of your future projects. 

I am also looking forward to getting to know everyone in the team and adding value where I can.

Here's to the next of many steps in the journey towards _doing what I love_.

**Comment by nelsonic** [comment]
@seaneady attended our Daily/Morning Standup Meeting on Zoom yesterday [Friday 20<sup>th</sup> Jan]. 👍 
And introduced himself to the team. 👋 

The plan going forward for the next few weeks 
is for Sean to continue learning UX: https://github.com/dwyl/learn-user-experience-testing/issues/27

Once he feels confident in his UI/UX skills to do a "beginners mind" review 
of the onboarding experience in the MVP: https://github.com/dwyl/mvp/issues/140
Related to: https://github.com/dwyl/product-roadmap/issues/43

Then he will help us with UX Research: https://github.com/dwyl/product-ux-research/issues
And read and improve both: https://github.com/dwyl/product-roadmap 
and https://github.com/dwyl/product-owner-guide

So that's the plan. 🚀

**Comment by seaneady** [comment]
Looking forward to it!

**Comment by nelsonic** [comment]
@seaneady thanks for testing out the MVP: ❤️ 

<img width="962" alt="image" src="https://user-images.githubusercontent.com/194400/214033669-dee46d64-bdf9-4f20-9db4-fe322bee4bb1.png">

Please try Authenticating with your `GitHub` or `Google` account and then capture your feedback in: https://github.com/dwyl/mvp/issues/140 🙏

**Comment by nelsonic** [comment]
Closing as Sean is happily working for Barrows: https://www.linkedin.com/in/sean-eady/ 👌
