### ISSUE TITLE
Blog: Fix Price vs. Time and Material Contracts?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hq#58]
_Good_ discussion on **Fix Price vs. Time and Material Contracts**:
http://programmers.blogoverflow.com/2012/08/fix-price-vs-time-and-material-contracts/

**Comment by iteles** [comment]
:+1:

**Comment by markwilliamfirth** [comment]
ok to close?

**Comment by iteles** [comment]
Nope. We need to add a `blog` label to this 👍

**Comment by markwilliamfirth** [comment]
@iteles who is to write the piece?
