### ISSUE TITLE
Rewrite and Review Contractor Contracts

### ISSUE THREAD

**Issue by iteles** [dwyl/hq#59]
Formalise freelancer contracts for commercial work

**Comment by nelsonic** [comment]
@iteles I've made a few edits to the Google Doc you shared with me this morning: https://docs.google.com/document/d/18rUBXbO42WM6KoX8imuHPgRt_UfpxiAO4aEEZsQituI

**Comment by nelsonic** [comment]
@markwilliamfirth we need to update this next week. 
@iteles please provide more detail in issue description.
thanks. ❤️

**Comment by rub1e** [comment]
Is the doc referred to in the comment above (https://github.com/dwyl/hq/issues/59#issuecomment-182645751) the right one to be starting with? Or is there a more up-to-date one I should look at?

**Comment by iteles** [comment]
@rub1e That's the right one Rubie, nothing was done on it _at all_ over the last 12 months despite the request 🙄

**Comment by rub1e** [comment]
I've added a few comments to the doc, but generally it seems to make sense. 

The next part is to have a chat about whether there's anything you think is missing based on your experiences over the past year

I also think it would be nice to keep these as PDFs and have people sign them electronically (not in terms of #243, certainly not a ££ solution, but some sort of process nonetheless). Leave that with me.

Let me know when you have time to chat about this @iteles 🤝

**Comment by iteles** [comment]
Have had a look through these comments and don't think there's anything else to add just yet.

Agree with signing these as PDFs 🎉

**Comment by rub1e** [comment]
As discussed, we're happy with these for the moment, but when we have time, sooner rather than later, we'll review these properly and then I suggest we use our solicitor or a service like https://www.lawbite.co.uk/ to do a formal review

**Comment by iteles** [comment]
Closing for now until we want to ramp up the team again.
