### ISSUE TITLE
More space for books

### ISSUE THREAD

**Issue by iteles** [dwyl/hq#6]
We have a library of books :heart: that is spread across rooms (and countries) and containing structures.
We need to formulate a plan A (with garage space) and plan B (no garage) to corral them into order so we don't have to hunt for books.

**Comment by nelsonic** [comment]
https://github.com/nelsonic/closet ... :wink:

**Comment by iteles** [comment]
Also, new hashtag, [#dwyllibrary](https://instagram.com/explore/tags/dwyllibrary/) :heart_eyes:

**Comment by nelsonic** [comment]
indeed... :wink: 
Lots of fun things to build in the next few weeks. 
Software *first*.

**Comment by daymos** [comment]
hello nelsonic, thanks for adding me to this organizazion. Can I ask you how to best use the repos here? Do you post challanges and people pick them up?

**Comment by nelsonic** [comment]
Hi @daymos welcome to **dwyl**!
We don't have challenges *yet*. but we will be releasing a few very soon so stay tuned. :+1: 
Meanwhile, try a few of the "**learn-...**" tutorials and let us know what you think!

**Comment by daymos** [comment]
ok, thanks!

**Comment by iteles** [comment]
Got this one sorted for now, thanks @nelsonic!

<img width="1604" alt="nelsonic-twitter-header-dwyl-library" src="https://cloud.githubusercontent.com/assets/4185328/18408853/7bf53922-7733-11e6-851a-25ae91df1d50.png">
