### ISSUE TITLE
Garage 

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hq#7]
## Todo:
+ [x] Draft letter
+ [x] Review letter
+ [x] Print letter
+ [x] Make offer they can't refuse
+ [x] Level Up!

**Comment by iteles** [comment]
On it!

**Comment by nelsonic** [comment]
Do we need to go out and *buy* a [***new printer***](https://github.com/dwyl/hq/issues/1) to get this printed...?

**Comment by iteles** [comment]
Are you still thinking of laminating this to prevent rain issues?

**Comment by nelsonic** [comment]
Right... :clock11: 
**No**. 
the laminator was *never* associated with this task. what gave you that idea?

**Comment by nelsonic** [comment]
@iteles i've re-worded the letter a bit ... please review to see if you agree.
https://docs.google.com/document/d/124fKjf8AshVJSw77g9lXi2Mj-s1ARznP9pMzwq7wtbM/edit
(*The "old" version is on the second page*)

**Comment by iteles** [comment]
@nelsonic It looks great. I still think that we should leave a space at the bottom to write 'Thank you! Ines & Nelson' in blue pen because I genuinely believes it helps them realise there are humans that their decision is affecting (rather than a council-like typed up letter).

If you're sure about the amount, I'm happy to print, sign and put in an envelope through the garage door.

**Comment by nelsonic** [comment]
If you're happy with it, please *do* print it, *sign* (on our behalf) and ship it! :package: 
I would offer *more* :moneybag: 
but I think the amount is already pretty generous... (*i.e: more than the value of their family car!!*)
I just want them to take the offer seriously.
I would even go as far as including a cheque for £100 just so they know we are *super seriously*...
But I think the letter is enough for now...

**Comment by iteles** [comment]
@nelsonic Absolutely. The cheque thing actually wouldn't come across very well.

**Comment by nelsonic** [comment]
Cash then? a couple of £50's...?

**Comment by iteles** [comment]
Pretty sure putting _any_ money in is more of an insult than an incentive.

**Comment by nelsonic** [comment]
How about a *severed finger* ...?
![cant refuse](https://411w15.econ.lsa.umich.edu/wp-content/uploads/2015/02/Brando.jpg)

**Comment by nelsonic** [comment]
Did you printed off the new letter? :package:

**Comment by iteles** [comment]
Printed, signed and shipped.

**Comment by nelsonic** [comment]
The *suspense* is killing me!! 
![suspense](http://www.forexfactory.com/attachment.php?attachmentid=1447031&d=1402628991)

**Comment by nelsonic** [comment]
![patience grass hopper](http://cdnstatic.visualizeus.com/thumbs/46/f2/cat,funny,grasshopper,mailman,meme,patience-46f2ba2a2de283363fdd70591e42c0e4_h.jpg)

**Comment by nelsonic** [comment]
![why patience](http://weknowmemes.com/wp-content/uploads/2011/10/why-is-patience-a-virtue-why-cant-hurry-the-fuck-up-be-a-virtue.jpg)

**Comment by iteles** [comment]
😂

**Comment by iteles** [comment]
Think we can close this now @nelsonic ?
