### ISSUE TITLE
Renew professional indemnity insurance

### ISSUE THREAD

**Issue by iteles** [dwyl/hq#72]
+ [x] Review how this needs to be done before January 2016
+ [x] Renew in January

**Comment by nelsonic** [comment]
@iteles I sent you the invoice for the insurance for last year. 
![qdos-professional-indemnity-insurance](https://cloud.githubusercontent.com/assets/194400/11888521/560ec248-a536-11e5-8cfd-77b19d2364a7.png)

It should be around the £150 mark to ensure for £1,000,000 ...

**Comment by iteles** [comment]
@nelsonic Thanks! I'll look into the process for renewal.

**Comment by iteles** [comment]
This can be done very simply and renewed online.
Should we wait for a confirmed start date before buying it?

<img width="903" alt="screen shot 2016-01-02 at 23 51 56" src="https://cloud.githubusercontent.com/assets/4185328/12076650/e2eaeb7a-b1ab-11e5-971a-03f459049743.png">

**Comment by nelsonic** [comment]
When I did it last year I spent a few minutes searching for a Promo Code for Qdos to get the price down.
But yeah, we only *need* to do it once the contract is finalised. :+1:

**Comment by iteles** [comment]
Done! (a little early as this was keeping us from bidding for a project)

Bought:
+ Professional Indemnity Insurance
+ Public Liability Insurance
+ Employers Liability Insurance

<img width="752" alt="qdos-insurances-bought-email-screenshot" src="https://cloud.githubusercontent.com/assets/4185328/12459515/0029eae8-bfa7-11e5-9427-030ff23cf468.png">

**Comment by nelsonic** [comment]
ouch... our *poor* bank account... :sob:

**Comment by iteles** [comment]
I know :-1:
