### ISSUE TITLE
Press Release for Raising our First Round of Investment 

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hq#73]
"dwyl raises 10M smiles at valuation of 1B hugs
To take on technology giant fixated on monetary gain."

We need to write a _Mock_ Techcrunch press release
And need _everyone's_ ideas for the best vocabulary.

**Comment by JoeTanner** [comment]
interesting

**Comment by nelsonic** [comment]
Closing as the joke is wasted on most people.
