### ISSUE TITLE
Raising Funds From The Crowd - Tuesday 12th Jan 

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hq#78]
https://www.eventbrite.co.uk/e/how-she-did-it-raising-funds-from-the-crowd-tickets-20275132467
@iteles this might be interesting...
originally shared by @nikhilaravi on Gitter... are you going BTW...?

**Comment by iteles** [comment]
@nelsonic , closing this as we weren't able to make it.

**Comment by nelsonic** [comment]
@iteles `#NextTime` ...?
