### ISSUE TITLE
Subscribed to Oxford Abstracts Newsletter

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hq#79]
I subscribed to test the UX ... http://www.oxfordabstracts.com/
![oxford-abstracts-newsletter-signup-confirmation-ux](https://cloud.githubusercontent.com/assets/194400/12224628/1712d7e4-b7ee-11e5-869d-909f05105fd7.png)

Not the best ... no branding.
No return link. and it required quite a lot of data entry...

**Comment by iteles** [comment]
👍🏻 We can discuss this with them tomorrow
