### ISSUE TITLE
Team Mark (LinkedIn Recommendation)

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hq#8]
http://markwilliamfirth.com/ ... :open_mouth: 
As discussed today, @markwilliamfirth is _considering_ working for http://www.joinef.com/
Not that he _needs_ any "help" getting a job, but it wont _hurt_ to leave him a recommendation.

**Comment by markwilliamfirth** [comment]
awhh :heart:

**Comment by nelsonic** [comment]
@markwilliamfirth is there any area of skill/experience you want us to highlight?

**Comment by markwilliamfirth** [comment]
@nelsonic anything you'd like!

**Comment by markwilliamfirth** [comment]
Closed in favour of https://github.com/nelsonic/nelsonic.github.io/issues/423
