### ISSUE TITLE
Order Raspberry Pi for testing Crawler

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hq#82]
@SimonLab requested a Raspberry Pi for Search URL Indexing:

![request-for-raspberry-pi](https://cloud.githubusercontent.com/assets/194400/12320921/39f134ec-baa3-11e5-9501-e8a62b9183c2.png)

This relates to the GM project but is an R&D cost.

**Comment by nelsonic** [comment]
@SimonLab this has been delivered today to the reception at Palmer's Road
![dwyl-amazon-raspberry-pi-order](https://cloud.githubusercontent.com/assets/194400/12320998/af50169a-baa3-11e5-8a56-2353b1b7206f.png)

**Comment by SimonLab** [comment]
Thanks @nelsonic just receive it at FAC! It seems Christmas is never too late!

**Comment by nelsonic** [comment]
Cool. Glad it arrived safely. 
please keep the pieces you don't need for the current project in the box in case we want to do some IoT in the future. :wink:

**Comment by nelsonic** [comment]
Ordered a *second* one for related R&D project. :wink: 
![dwyl-amazon-raspberry-pi-second](https://cloud.githubusercontent.com/assets/194400/12325075/8a860cf4-babf-11e5-83ad-7b848e22472c.png)

**Comment by SimonLab** [comment]
@nelsonic second raspberry received with a wifi antenna!

**Comment by iteles** [comment]
Excellent, thanks @SimonLab !
