### ISSUE TITLE
Forwarding for nelson@dwyl.io is broken

### ISSUE THREAD

**Issue by iteles** [dwyl/hq#83]
Fix!

**Comment by iteles** [comment]
Emailed Google support.

**Comment by nelsonic** [comment]
@iteles forwarding works.
Replying *as* does not: 
![dwyl-gmail-fails-to-reply-using-smtp-gateway](https://cloud.githubusercontent.com/assets/194400/12588092/f9c32d8e-c44e-11e5-93c4-11fc675c0350.png)
Its really not a big deal as I can just have my `@dwyl` email open in a diff browser. so please feel free to close the case with Google Apps Support...
