### ISSUE TITLE
Investigate Google/Bing Search API for Elliot-for-Water

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hq#84]
Yahoo was *considerably* cheaper than Google or Bing:
![search-pricing-chart-v2_0](https://cloud.githubusercontent.com/assets/194400/12424966/7d30e54c-beca-11e5-98ad-e6527a49d9fd.png)
see: http://www.programmableweb.com/news/yahoos-new-search-api-pricing-compared-to-google-bing/analysis/2014/11/24

Pricing & API: http://datamarket.azure.com/dataset/bing/search

**Comment by iteles** [comment]
:+1: Meeting on Tuesday 26th

**Comment by nelsonic** [comment]
Yeah, I just got curious and decided to Google... 
The Google Custom Search API used to be *much* cheaper...!
I'm tempted to suggest that we meta-search Google ... which is what we are doing: https://github.com/akitten/public-profile-page-url-finder

**Comment by nelsonic** [comment]
@iteles can we close this now? 
For anyone following at home interested http://www.elliotforwater.com/about came to us asking if we could help them re-build their project. We gave them plenty of advice but concluded they did _not_ need to re-build their _Rails_ app in Node on the basis that they already _have_ a decent MVP and need to _**focus on getting usage before** thinking of re-building for "**scalability**"_.
