### ISSUE TITLE
Jack to Enable 2nd Factor Authentication on GitHub Account for Security

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hq#87]
Hi, The reason you were not able to push directly to the dwyl/learn-aws-lambda repo is that you don't have 2-factor auth enabled on your GitHub account:

![jack-not-got-2nd-factor-auth-enabled](https://cloud.githubusercontent.com/assets/194400/12531872/c4cb8f20-c1fd-11e5-92ec-2a4ea6095113.png)

See: https://help.github.com/articles/about-two-factor-authentication/
Please enable it so your account is *safer*. 
That should give you write-access to all the dwyl repos.

**Comment by jackcarlisle** [comment]
@nelsonic Done! Sorry about that, I was completely unaware!
