### ISSUE TITLE
Write up our key values in a concise format

### ISSUE THREAD

**Issue by iteles** [dwyl/hq#88]
Our developers are an extension of us and especially as we spend less time hands on with the training, we need to find a quick and easy way to transmit our values, e.g. Not using un-tested modules or those with lots of dependencies, anti vendor lock-in, accessible to as many new developers as possible, etc. 

What is the best way to do this? A few colourful slides? An org-wide talk?
I'm leaning towards a workshop to determine what is valuable to each person. 

Linked to the branding work @joe_tanner has done

**Comment by markwilliamfirth** [comment]
Linked to https://github.com/dwyl/dwyl-site/issues/219

**Comment by markwilliamfirth** [comment]
Closed in favour of https://github.com/dwyl/values
