### ISSUE TITLE
Organise the next late lunch @dwylhq [Sunday 13 March 2016]

### ISSUE THREAD

**Issue by iteles** [dwyl/hq#89]
# Updated date! Sunday 13th March.

@nikhilaravi will be treating us to some http://www.onelifetwoways.com/ goodness! :fork_and_knife: 

_Linked to #50_

_Guest list so far (13-14 people):_
+ @iteles 
+ @nelsonic 
+ @nikhilaravi 
+ @des-des 
+ @minaorangina 
+ @hdrdavies 
+ @Jbarget 
+ @heron2014 + Hailey?
+ @NataliaLKB 
+ @tormod17 
+ @mantagen 
+ @rjmk 
+ @jackcarlisle 

To be confirmed from original list:
+ @sohilpandya 
+ @mk4111 
+ @rub1e

**Comment by nikhilaravi** [comment]
@iteles erm depends if people want to help me cook :wink: 

also everyone please post recipe requests from the website!

**Comment by iteles** [comment]
@NataliaLKB @benjaminlees @SimonLab @heron2014 @jrans @des-des @naazy @msmichellegar @jackcarlisle @beechware @rorysedgwick @Jbarget @minaorangina @hdrdavies @katkelemen @rub1e @mk4111@Conorc1000 @sohilpandya @nofootnotes @jrans @markwilliamfirth @thegsi @tormod17 @rug1 @katpas @RachBLondon @mantagen 

You get first dibs before we invite FAC7 :wink:  Let us know by the **12th** (by leaving a comment here) if you're interested in coming for a **delicious South Indian vegan brunch** on 28th Feb in Camberwell @dwylhq!

**Comment by sohilpandya** [comment]
Count me in! :yum:

**Comment by nofootnotes** [comment]
Aw I'd have loved to come but I'll be away then! Looking forward to hearing all about it though!

**Comment by mk4111** [comment]
yayayayayayayyyyyyyyy!!!! YES PLEASE!!!

If I can help in any way, pleeeaaase let me know :D <3

**Comment by des-des** [comment]
i'm in!!

**Comment by minaorangina** [comment]
I'm in too!  And @nikhilaravi very happy to chop stuff :hocho: :hocho: :hocho:

**Comment by sohilpandya** [comment]
@nikhilaravi my Dosa making skills aren't too bad either! :wink:

**Comment by tormod17** [comment]
@iteles  yes I would like to join this pot luck, if so I can bring some home made West Indian Pepper sauce. :+1:

**Comment by naazy** [comment]
Yay!! I'll be there thanks! @nelsonic @iteles 😚

**Comment by iteles** [comment]
@tormod17 For this one we're lucky to have @nikhilaravi offer to make us some awesome food (with help from lovely assistants of course - anyone who wants to offer to arrive a little earlier) BUT that West Indian pepper sauce sounds pretty epic! :wink:

**Comment by nelsonic** [comment]
Given that this time is *Brunch*... :fork_and_knife: 
if anyone fancies arriving early, we have a decent ***Tennis*** court nearby and rackets/balls ... :tennis: 
(*just trainers & sporty clothes required (tho we have spare :heart: :white_check_mark: T's if you forget...*) @nikhilaravi :question: :wink:

**Comment by nikhilaravi** [comment]
@iteles sounds great! - should we do a late brunch like 2/3pm so there's enough time to cook... (factoring in that it will take me at least 1 hour to get to your house and I don't want to get up super early on a sunday ;) ) @nelsonic I would actually love to play tennis but haven't yet figured out how to play tennis and cook at the same so I probably shouldn't volunteer for both :)

**Comment by nelsonic** [comment]
@nikhilaravi :sunny: till 17:39 on 28th > http://www.sunrise-and-sunset.com/en/sun/united-kingdom/london-borough-of-harrow/2016/february/28 so... food then play? 
or... I can come pick you up from your house by :blue_car: so you don't have to travel quite as much... 
or you can delegate some of the cooking prep to the wonderful talented people who will be *eating* it...? :stuck_out_tongue_winking_eye:

**Comment by hdrdavies** [comment]
I'm ***so*** in. :tada:

**Comment by NataliaLKB** [comment]
Count me in!! So excited. Thanks @iteles @nelsonic @nikhilaravi

**Comment by rub1e** [comment]
Soz will be at family lunch that day (more meat, less flavour)

**Comment by Jbarget** [comment]
@iteles @nelsonic is there room for a +1?

**Comment by Jbarget** [comment]
@iteles @nikhilaravi @nelsonic is that ok?

**Comment by iteles** [comment]
@Jbarget Sorry, yes!

**Comment by Jbarget** [comment]
@iteles fab, count me +1 (Natalie) in

**Comment by rjmk** [comment]
:sob: I'm not free that afternoon

**Comment by iteles** [comment]
@rjmk Of course you aren't :cry: Next one!

**Comment by nelsonic** [comment]
@rjmk join us when you *are* free... there will be loads of food and cool peeps!

**Comment by nikhilaravi** [comment]
AH so onelifetwoways is being interviewed for BBC Asian Network on Sunday 28th - would it be okay to move the brunch to the following weekend so Sunday 6th March??

Hopefully you can all come and maybe @rjmk won't have already made plans :wink: 

@NataliaLKB @benjaminlees @SimonLab @heron2014 @jrans @des-des @naazy @msmichellegar @jackcarlisle @beechware @rorysedgwick @Jbarget @minaorangina @hdrdavies @katkelemen @rub1e @mk4111 @Conorc1000 @sohilpandya @nofootnotes @jrans @markwilliamfirth @thegsi @tormod17 @rug1 @katpas @RachBLondon @mantagen @rjmk @msmichellegar

**Comment by Jbarget** [comment]
@nikhilaravi that sunday 6th march is mothers day so maybe the weekend after?

**Comment by rjmk** [comment]
@nikhilaravi I haven't made plans!

**Comment by heron2014** [comment]
@nikhilaravi good suggestion! We have node-girls next weekend that's why I am not able to come for a brunch next weekend.

**Comment by hdrdavies** [comment]
It would be far too rogue of me to miss a Mother's Day lunch....

**Comment by iteles** [comment]
I think doing it on Mother's Day would be sucky (even though Mother's Day for me is in May...). 

13th March, final offer!

**Comment by des-des** [comment]
good for me

**Comment by nikhilaravi** [comment]
@Jbarget thankyou!! 
@rjmk yes!!!!
@iteles yes 13th march would work! or 5th March would also be fine! :)

**Comment by naazy** [comment]
I'm in Japan on 13 March but enjoy! ⭐️

**Comment by heron2014** [comment]
13th works for me :)

**Comment by hdrdavies** [comment]
:+1: awesome!

**Comment by minaorangina** [comment]
I'm in! :smile:

**Comment by NataliaLKB** [comment]
I am free the 13th too!

**Comment by iteles** [comment]
@heron2014 Is Hailey coming too?

**Comment by minaorangina** [comment]
@iteles I don't know if she's free, but @tsop14 would probably like to come too?

**Comment by Jbarget** [comment]
@iteles im in but natalies out for 13th march

**Comment by iteles** [comment]
@tsop14 That would be so amazing!!

**Comment by heron2014** [comment]
@iteles no, she is not.

**Comment by katkelemen** [comment]
hey, I've just read this, I'll be away on the 13th, I'm really sorry to
miss this :( hopefully next time :)

**Comment by iteles** [comment]
@katkelemen Definitely next time, you know we like to do these regularly ;)

**Comment by tormod17** [comment]
I'm in for 13th.

**Comment by mantagen** [comment]
13th you say? Commonwealth day eve according to my calendar. No plans as of yet!

**Comment by rjmk** [comment]
In!

**Comment by jackcarlisle** [comment]
I'm in

**Comment by iteles** [comment]
Closed in favour of https://github.com/dwyl/hq/issues/91 to keep things cleaner!
