### ISSUE TITLE
LinkedIn Organisation?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hq#9]
Not a priority until we have a better-converting landing page where people will go and be *compelled* to sign up for more info... but as soon as that's done...

**Comment by markwilliamfirth** [comment]
This is very easy to do and can be done in a few minutes!

**Comment by nelsonic** [comment]
We also want to send out an email to everyone inviting them to *join* our LinkedIn Org and give them a recommendation in return... :wink: 
@iteles do we have all the email addresses for the people who participated in DwylSummer

**Comment by iteles** [comment]
@nelsonic Of course, everyone had to email me their [freelance agreement](https://github.com/dwyl/summer-2015/blob/master/freelance-agreements/freelance-agreement.md) (very 'concierge MVP' until we get electronic signatures up and running.

**Comment by nelsonic** [comment]
Ok. so... do you think its "*too early*" to start getting people to Send us in-bound traffic by having **dwyl** on their LinkedIn profiles...? if so, ***when***?

**Comment by iteles** [comment]
Within a month.    
_When_ within that month depends on the priority we allocate to getting our website looking like a worthwhile proposition. Let's work it out.

**Comment by nelsonic** [comment]
https://help.linkedin.com/app/answers/detail/a_id/710/~/adding-a-company-page

**Comment by nelsonic** [comment]
@iteles I don't appear to have an active email account on @dwyl.io ... :disappointed:

**Comment by nelsonic** [comment]
Trying: https://www.linkedin.com/company/add/show
![linkedin-dwyl](https://cloud.githubusercontent.com/assets/194400/12339798/ecaebe18-bb0e-11e5-9741-005faacdd724.png)

But since I don't have an "official" email address I can't register it. :cry:

**Comment by iteles** [comment]
@nelsonic As per our conversation, the account is active, but the forwarding in gmail appears to _not_ be working. I've emailed Google apps for work. In the meantime please use the direct login :+1:

**Comment by nelsonic** [comment]
![dwyl-linkedin-org](https://cloud.githubusercontent.com/assets/194400/12342038/516527d4-bb1e-11e5-92ec-75e3482bc599.png)

Now we need to invite *everyone* to join...

**Comment by nelsonic** [comment]
@iteles can you add a task to encourage *everyone* to join us on LinkedIn...?
