### ISSUE TITLE
Re-Start Audible Subscription?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hq#90]
@iteles I know you probably don't feel like you have _any_ time right now, but I have at least 40mins per day when I could be listening to Audiobooks (_my daily cycle commute_)...
What are your thoughts on re-starting the Audible subscription...?
There is _literally_ no way to get the price from the website without signing up!
But I think the lowest level of subscription should be enough for now...
Question is: do we need to re-sign-up to the US store to re-activate our existing collection...?

**Comment by iteles** [comment]
My thoughts in answer to your questions are as follows:
+ I probably won't be listening to any audiobooks:
  + I don't listen to anything but the cars on my daily commute because there have been multiple instances where if I couldn't hear the car that was just about to come out of nowhere hurtling towards me, I might not be here anymore
  + I have many _many_ hours of podcasts I can't seem to ever get round to already
+ If you have time and desire, then we should certainly restart it
+ The [lowest possible subscription is £7.99 for 1 book a month](http://audible-uk.custhelp.com/app/answers/detail/a_id/5527) - this is cheaper than the US version which is $14.99 a month (the next one up is £14.99 for 2 books a month)
+ Our existing collection never dies - just make sure you're logged into the US marketplace on the mobile app (or .com in a browser) but customer service has just confirmed _they can't transfer our library from US to UK but we can still access it by swapping between marketplaces_
+ Now we just need to decide whether we can be bothered to keep switching back and forth.

**Comment by nelsonic** [comment]
I want _really_ to listen to `this` book on Audible: 
https://www.amazon.co.uk/How-Measure-Anything-Intangibles-Business/dp/1118539273
recommended by @jessitron in https://youtu.be/X25xOhntr6s?t=29m34s

**Comment by nelsonic** [comment]
Want to listen to this one too: https://www.amazon.co.uk/Chasing-Scream-First-Last-Drugs/dp/1408857820 because of https://twitter.com/nelsonic/status/803072138467016708

**Comment by iteles** [comment]
@nelsonic Do you have *time* to listen to books on audible? Or is this more of a 'when we have [`time`](http://www.github.com/dwyl/time) thing?

**Comment by nelsonic** [comment]
@iteles not only do we _have_ time, we need to _make_ more time.
All the podcasts where authors are interviewed and you hear _about_ their book are nice,
but the _actual_ content is _in_ the book not _promoting_ it.
The only reason I've not listened to _moar_ Audiobooks in my time is because I didn't have more.
e.g: I listened to (_practically memorised_) https://www.amazon.co.uk/Mars-Women-Venus-Communication-Relationships/dp/0007152590 but pretty sure I would not have sat down and read it in book form ... I have a mental _list_ of all the books I _wish_ I had time to read and would use an Audible Sub to consume that content "on-the-go" (_e.g. walking to shops or doing house work_)
The times I've consumed the most Audio Books is when doing DIY (e.g: your standing desk)
or travelling when the audiobook is my "_background noise_", this is how I got through https://www.amazon.co.uk/Thinking-Fast-Slow-Daniel-Kahneman/dp/0141033576 which is _dense_!

I don't think I will read an _less_ (_physical_) books because technical books benefit from visual recognition, but I would *love* to increase my consumption of _practical_ knowledge.

**Comment by naazy** [comment]
@nelsonic I've got the Hari book on my audible and I'm allowed to share books for free (and you can accept it for free too if it's the first book you're accepting from someone). Texting it to you now! Enjoy!

**Comment by nelsonic** [comment]
@naazy thanks for offering to share the book. we _may_ take you up on it... 😉 
@iteles I will be spending 120h in the pool over the next few months and given that I have a waterproof MP3 player I feel it's time to re-start Audible to make the most of the time.
Please let me know what needs to be done for this. thanks.

**Comment by iteles** [comment]
Done! I've used the dwyl amazon name as there's a 3 month free trial for Prime members and signed it up to the **.co.uk** marketplace.

**Comment by nelsonic** [comment]
@iteles thanks for doing that. 👍  🎉 
I will be converting the books from `.aax` (DRM) to `.mp3` so I can play them on my waterproof MP3 player. Let me know if you want the `.mp3` for anything I can share via google drive or "airdrop". 🏊

**Comment by nelsonic** [comment]
@iteles please inform me which email address you used to sign up for the "**3 month free trial for Prime members**" ...
Your account:
![image](https://cloud.githubusercontent.com/assets/194400/25162404/60d85e1e-24ba-11e7-9f3c-bc40b649e59f.png)
Is not signed up to a plan and has "**0 Credits**"

The `dwyl.io`
![image](https://cloud.githubusercontent.com/assets/194400/25162449/a401bfd2-24ba-11e7-823b-ec1585189c14.png)
Also has "**0 Credits**" ...

As soon as I know the account details I'm going to listen to "Mastery" by Robert Greene
https://www.amazon.co.uk/Mastery/dp/B00A6TJQSM/ (_in case I forget_...)

**Comment by iteles** [comment]
@nelsonic I see the problem: you're trying our old account but I signed up with the dwyl Amazon account as per my comment above - I'll send you the details 👍

**Comment by nelsonic** [comment]
Possible next book: https://www.amazon.co.uk/Just-Listen-Absolutely-Professional-Management/dp/0814436471
