### ISSUE TITLE
Organise the next late lunch @dwylhq [Saturday 19th March]

### ISSUE THREAD

**Issue by iteles** [dwyl/hq#91]
OK folks, I promise this is the last change to the lunch date! **It will definitely be going ahead on Saturday 19th!**

Lunch will start at 14h30!

And as promised, we will still be treated by the lovely @nikhilaravi of [BBC (and dwyl) fame](http://www.bbc.co.uk/programmes/p03lx5qh?ns_mchannel=social&ns_campaign=bbc_asian_network&ns_source=twitter&ns_linkname=radio_and_music) :wink: 

**Who's in?**

_Guest list so far (11):_
+ @nikhilaravi 
+ @nelsonic 
+ @iteles
+ @minaorangina 
+ @NataliaLKB 
+ @Jbarget + 1
+ @mk4111 
+ @SimonLab + 1
+ @msmichellegar 
+ @des-des 
+ @tsop14 !!

**Comment by iteles** [comment]
@NataliaLKB @benjaminlees @SimonLab @heron2014 @jrans @des-des @naazy @msmichellegar @jackcarlisle @beechware @rorysedgwick @Jbarget @minaorangina @hdrdavies @katkelemen @rub1e @mk4111 @Conorc1000 @sohilpandya @nofootnotes @jrans @markwilliamfirth @thegsi @tormod17 @rug1 @katpas @RachBLondon @mantagen @rjmk @msmichellegar @tsop14 and everyone else, apologies for the changes in dates, this is for sure the final change!

**Comment by Jbarget** [comment]
I'm in + 1 please!

**Comment by mk4111** [comment]
Hi! So no 13th anymore?

**Comment by nikhilaravi** [comment]
@iteles Yay!!  

Menu so far! Please make suggestions from the blog/anything you have seen me eat at FAC...

[Coconut Vegetable Stew](http://www.onelifetwoways.com/blog/2016/1/8/creamy-coconut-stew)
[Kale Cranberry and Coconut Rice](http://www.onelifetwoways.com/blog/2016/1/20/kale-cranberry-coconut-rice)
[Cucumber Yoghurt](http://www.onelifetwoways.com/blog/2016/1/20/cooling-cucumber-yoghurt)
[Carrot, Cardamom and Almond Milk Latte](http://www.onelifetwoways.com/blog/2015/12/20/carrot-cardamom-almond-milk-latte)

And Sambhar and Dosas too (if my mum is free to help me make the batter!).

**Comment by NataliaLKB** [comment]
I am in!

**Comment by hdrdavies** [comment]
I can't make it anymore... :cry:

**Comment by minaorangina** [comment]
I'm in too :smile: :fork_and_knife: :heart:

**Comment by SimonLab** [comment]
will be there too, @nikhilaravi any healthy, delicious South Indian booze on the menu :wine_glass:?

**Comment by nikhilaravi** [comment]
@hdrdavies thank you! Sad you wont be able to make it to the brunch :(  

haha @SimonLab no....

**Comment by msmichellegar** [comment]
It's in my diary! I'm in!

**Comment by nofootnotes** [comment]
Aw no, I can't make it! I hope it is well-documented!

**Comment by mk4111** [comment]
please count me in!! :D

**Comment by iteles** [comment]
@SimonLab Are you bringing a + 1 or just your fine self?

**Comment by des-des** [comment]
Im in!

**Comment by tsop14** [comment]
Me too! What time?? Yay.

**Comment by SimonLab** [comment]
@iteles yes the + 1 is coming

**Comment by NataliaLKB** [comment]
Can I bring a +1? 

Also, I may have to leave early as I am kinda sorta moving this weekend :grimacing:

**Comment by iteles** [comment]
@nataliaLKB Please bring your +1!
And as long as you don't leave before you've eaten, no problem ;)

**Comment by msmichellegar** [comment]
I actually won't be able to come after all, have just been coerced into Mode For Me activities. Sad to miss the cuisine @nikhilaravi 😩

**Comment by nikhilaravi** [comment]
aww sad you couldn't come @msmichellegar! :(
