### ISSUE TITLE
dwylhq accounts

### ISSUE THREAD

**Issue by iteles** [dwyl/hq#92]
Do a full revision of dwyl's accounts to date asap to aid conversations on day rates and for things like printing hoodies! https://github.com/dwyl/print-me/issues/17

**Comment by nelsonic** [comment]
Have you had a look at this: https://open.buffer.com/introducing-open-salaries-at-buffer-including-our-transparent-formula-and-all-individual-salaries/ ?

**Comment by iteles** [comment]
I have! I have it on my list for preparing the accounts this weekend :)

**Comment by markwilliamfirth** [comment]
@iteles are the accounts public?

**Comment by nelsonic** [comment]
@markwilliamfirth, _sadly_ the accounts are `#NotYetPublic` which is an `#EpicFail` 😢 
But the _reason_ for this is that @iteles is _totally **snowed under**_ with just _running_ the day-to-day of running a (_people-focussed but profitable_) web agency, attending to the needs of the team members and clients while still finding time speak to (_exciting_) potential new clients and giving conference talks etc... It's not a good "_excuse_" but it's the _reason_ we are _behind_ on our goals.
But if you are interested in seeing our "_numbers_" spreadsheets we can share them with you, they just need to be _organised_ to not _expose_ the "sensitive" details (PII) of any people. (_yes, storing sensitive data in a google spreadsheet is not a great idea... we need to `fix` it!!_) `#HelpWanted`

**Comment by iteles** [comment]
@markwilliamfirth What @nelsonic said - the intention is absolutely that. I just haven't had the headspace to put them in a format which is ready for public consumption.

**Comment by markwilliamfirth** [comment]
Completed. Corporation tax has been paid to HMRC.
