### ISSUE TITLE
dwylympics

### ISSUE THREAD

**Issue by nikhilaravi** [dwyl/hq#94]
@naazy and I were discussing this at Lunch today. As summer is approaching we thought it would be fun to have an afternoon of school sports day themed fun:

- egg and spoon race (eggs)
- wheelbarrow race
- three legged race (bandanas)
- slow cycling (half ppl to bring bikes)
- articulate relay (@jbarget to bring articulate)
- quoits
- crawling version of Marco Polo (cordon/rope/gaffa tape, blindfold)
- blind fold obstacle course (cardboard boxes, connect4?, blindfolds)
- boule (1 ball per person - tennis balls? or whatevs? 🎾 )
- skipping contest (skipping ropes)
- limbo (skipping rope)
- catch the water balloon **(water balloons + 2 buckets)** 

- water gun string race (plastic cups, @naazy to bring string)
![a27b48efac218e82c1efe539698a25f3](https://user-images.githubusercontent.com/11833296/26896380-5f568e16-4bbc-11e7-97b1-cb4254b67bef.jpg)

- presentation ceremony

Fillers
musical statues?
tug of war?

fruit + snacks
pizza?

**Comment by naazy** [comment]
- rounders!

**Comment by naazy** [comment]
(we could to a tofu and spoon race for the vegans ;))

**Comment by iteles** [comment]
@nikhilaravi @naazy Is this happening on evening of 16th August?

**Comment by naazy** [comment]
Works for me! I have posted on the gitter to ask if it works for other people!

**Comment by markwilliamfirth** [comment]
@naazy dwyl sports day round 2 in May/June?

**Comment by Jbarget** [comment]
lets figure out a date! With this delightful sun at the moment it would be great to find a day where its similar that works for everyone. mid June?

**Comment by naazy** [comment]
Should we make a doodle @Jbarget ?

**Comment by markwilliamfirth** [comment]
At the moment June 10th - July 15th no one has booked off

@naazy is this a lunchtime thing or weekday afternoon thing or weekday evening thing or weekend thing?

**Comment by naazy** [comment]
@markwilliamfirth I think weekday evening works best

**Comment by naazy** [comment]
ps please can we introduce a waterfight this year? 💧:droplet: 🔫 🚰

**Comment by markwilliamfirth** [comment]
Just remembered that Nelson and Inês are going away early July (even though it's not booked off yet). Looking at the shared calendars I would suggest these dates in June to pick from:

14
15
19
21
26
28
29

totes up for a waterfight 💪

**Comment by Jbarget** [comment]
June 14?
Mid-week Wednesday fun?

http://www.accuweather.com/en/gb/london/ec4a-2/june-weather/328328?monyr=6/1/2017

**Comment by markwilliamfirth** [comment]
@naazy up to you! Might still be worth doing a doodle as I don't have access to everyone's calendars, but (as much as I love a good doodle) doodles sometimes cause more problems than they solve so might be best just to pick a date and tell people asap! 14 June is a good suggestion looking at the weather link Justen posted

**Comment by Jbarget** [comment]
@markwilliamfirth completely agree about the doodle

**Comment by naazy** [comment]
@markwilliamfirth @jbarget Yes I think let's suggest June 14th and the
people can protest if it doesn't work for them 😊 - that's what we did last
time and most people were able to attend

**Comment by markwilliamfirth** [comment]
@naazy great! If you can create a short event brief with a description, start/end time and if people need to bring anything then I can add it to the dwyl calendar and send an email out! How did you publicise last time? GitHub and Gitter?

**Comment by naazy** [comment]
Just on gitter I think @markwilliamfirth . Sure thing will send over the deets soon 🎾  :)

**Comment by Jbarget** [comment]
May we introduce to you - DWYLympics

DWYL is all about collaboration, every day, every hour. Not today. The DWYLympics is a different beast altogether. This is all about competition.

Ever wanted to beat your collaborator at something?
Hate your QA for making you make multiple commits after submitting a PR?
Find that person whistling in the office annoying?
Someone who leaves the toilet seat up at Focus Hub?
That scoundrel who took your milk that time?
Who's that who plays their music too loudly through their headphones?

Prepare to let all your frustrations out over the course of a (hopefully) warm evening in Victoria Park. We want ferocity, jealousy, bad losers, good winners, people that will stop at nothing to achieve the best and completely destroy the competition.

Prizes awarded. Prepare for battle.

**Comment by Jbarget** [comment]
@markwilliamfirth ^^^ that should do it

**Comment by naazy** [comment]
really wonderful @Jbarget :clap: - should we say 6.30pm Vicky park?

**Comment by markwilliamfirth** [comment]
@Jbarget you have a way with words - very nice 🔥

**Comment by markwilliamfirth** [comment]
Email sent! @naazy @Jbarget let me know how else I can help with prepping for this!

**Comment by markwilliamfirth** [comment]
<img width="255" alt="screen shot 2017-05-31 at 15 30 50" src="https://cloud.githubusercontent.com/assets/5732209/26636989/28875f6a-4616-11e7-9c2e-d61e35235a72.png">

:(

**Comment by iteles** [comment]
@markwilliamfirth You weren't part of the room back then 😊 
<img width="266" alt="screen shot 2017-05-31 at 15 42 13" src="https://cloud.githubusercontent.com/assets/4185328/26637606/cc617ef8-4617-11e7-89e9-383e3f4fa39b.png">

**Comment by markwilliamfirth** [comment]
Is there a reason it was spelled with an 'i' last year? Or is that just a spelling error?

**Comment by iteles** [comment]
Oh you're right, it was the spelling! 
No reason, no one asked @harrygfox to make the logo, he just whipped it up. I think because of the dwyl 'y', it seemed more intuitive to write it with an 'i' (that's what I searched for intuitively) but you're right, it should be spelt with a 'y' 😊

**Comment by markwilliamfirth** [comment]
<img width="251" alt="screen shot 2017-05-31 at 15 57 44" src="https://cloud.githubusercontent.com/assets/5732209/26638396/e96c5656-4619-11e7-8fa2-259fed0d054d.png">

even when i search with the i version it doesn't come up - must be as you said because I wasn't in the room back then

**Comment by naazy** [comment]
Have had a wee brainstorm and edited the top comment with some very rogue games. Feel free to add/edit (ps LOL at @markwilliamfirth's limping comment)

**Comment by markwilliamfirth** [comment]
@naazy loving this. Is there anything we might need to order from amazon in advance? Water balloons?

**Comment by Jbarget** [comment]
@markwilliamfirth @naazy and I are meeting tonight to plan it all 👍 

will keep you updated :)

**Comment by sohilpandya** [comment]
EXITING TIMES!!!

**Comment by markwilliamfirth** [comment]
- [kit](https://www.amazon.co.uk/gp/registry/wishlist/9V1CWO97HNKI/ref=cm_wl_list_o_0?)
- pizza + snacks

**Comment by markwilliamfirth** [comment]
@Jbarget are the water balloons etc biodegradable? If dwyl is buying it needs to align with http://www.dwyl.com/values

**Comment by Jbarget** [comment]
@markwilliamfirth before you order can we sync up to check we're ordering everything correctly?

**Comment by markwilliamfirth** [comment]
@Jbarget if you update the event kit [wishlist](https://www.amazon.co.uk/gp/registry/wishlist/9V1CWO97HNKI/ref=cm_wl_list_o_0?) with what you and @naazy want I can order everything for you today! Just wanted to double check with you that we were being environmentally friendly

**Comment by Jbarget** [comment]
updated, NB. dont buy the bandanas we're gonna source those elsewhere

**Comment by markwilliamfirth** [comment]
@Jbarget @naazy I have bought the water balloons, rope quoits / wooden pegs throwing game and water guns x3 - should arrive tomorrow. Wasn't able to order non-prime or the cups as they wouldn't arrive in time - so if you want those you may need to source from elsewhere along with the bandanas

**Comment by markwilliamfirth** [comment]
@Jbarget @naazy Managed to find the boules for next day delivery elsewhere so have ordered 2 sets

So only thing I couldn't order was cups (and bandanas)

**Comment by naazy** [comment]
Great! Any thoughts on where we can get biodegradable cups @markwilliamfirth ? i can check out hoxton street this lunch for bandanas or something we can fashion as bandanas 😄

**Comment by Jbarget** [comment]
https://www.amazon.co.uk/Disposable-bioplastic-biodegradable-compostable-transparent/dp/B01N6XKQM3/ref=sr_1_6?rps=1&ie=UTF8&qid=1497343494&sr=8-6&keywords=biodegradable+cups ?

**Comment by markwilliamfirth** [comment]
@Jbarget they say 15th June
<img width="540" alt="screen shot 2017-06-13 at 10 04 46" src="https://user-images.githubusercontent.com/5732209/27074698-c9565ac8-501f-11e7-8294-68aa0917e8c6.png">

**Comment by Jbarget** [comment]
ugh, they lie about prime. No worries, @naazy lets chat and figure out what we need to get. I can go to Tiger on my way home

**Comment by markwilliamfirth** [comment]
Great job guys! 🏅 🏅 https://twitter.com/dwyl/status/875359884115673088

Until next year 👍

**Comment by iteles** [comment]
We need the photos to go somewhere! I don't have many but I think Nelson has quite a few

**Comment by markwilliamfirth** [comment]
@iteles https://github.com/dwyl/hq/issues/362 👍
