### ISSUE TITLE
Dwyl bounce

### ISSUE THREAD

**Issue by nikhilaravi** [dwyl/hq#95]
Who is keen for table tennis at Bounce one evening? If necessary I am prepared to create a doodle...

**Comment by markwilliamfirth** [comment]
I don't know if this is going to happen still, but I'm totally up for this when it does

**Comment by nelsonic** [comment]
@markwilliamfirth please _make_ it happen. Mid October...?

**Comment by iteles** [comment]
I vote early November! And it SO needs to happen!

**Comment by nikhilaravi** [comment]
aw sad to miss it :( 🎾

**Comment by nelsonic** [comment]
@nikhilaravi we will be _sure_ to do it (_again_) when you are in town, just let us know when you're back! hope you are well! ✨

**Comment by markwilliamfirth** [comment]
@nikhilaravi when are you back in London?

**Comment by nikhilaravi** [comment]
@markwilliamfirth back shortly from May 19th -23rd but properly back end of June! So excited for big dwyl reunion! 😍

**Comment by markwilliamfirth** [comment]
@nikhilaravi woooo! Will any of your evenings May 19th - 23rd be free (for dwyl bounce!)? We might be in Portugal end of June 😬 ...

**Comment by nikhilaravi** [comment]
ah okay I'll let you know! I'm just coming back for my MA ceremony so not sure yet what the plan is! When will you be going to Portugal? Maybe I can meet everyone there ? ;) hehe

**Comment by iteles** [comment]
@nikhilaravi There's no Bounce in Portugal, but there are plenty of other things :wink:
We'll be figuring out dates *very soon* #259

**Comment by markwilliamfirth** [comment]
@nikhilaravi still being decided! Leaving UK for Portugal sometime between June - August

Just raised an issue ;) ( #259 )

Yes you could! 😄 

Although if you decide want to bounce in May let me know and I'll tell people to hold the date and book it!

**Comment by nelsonic** [comment]
@iteles / @nikhilaravi no "bounce" ...? we have _two_ pingpong tables and can easily rustle up a third. _surely_ that's "_enough_" to start our own Bounce in PT? 😜

**Comment by markwilliamfirth** [comment]
@nikhilaravi hello! Are any of your May evenings free? If not, when are you back in June? We're not off to dwyl summer until July

**Comment by markwilliamfirth** [comment]
Closing in favour of https://github.com/dwyl/events/issues/3
