### ISSUE TITLE
Twitter

### ISSUE THREAD

**Issue by markwilliamfirth** [dwyl/hq#96]
Claim https://twitter.com/dwyl
https://support.twitter.com/forms/trademark
https://www.ipo.gov.uk/tmcase/Results/1/UK00003103535
https://drbeta.companieshouse.gov.uk/company/09525434
Has to come from company email address

**Comment by nelsonic** [comment]
@iteles can you create an @dwyl.io email account for @markwilliamfirth so he can claim the twitter handle...?

**Comment by markwilliamfirth** [comment]
@nelsonic omg it's like I'm part of the crew xD

**Comment by nelsonic** [comment]
![pirate crew](https://cloud.githubusercontent.com/assets/194400/14290092/9420da06-fb55-11e5-9898-c02a6b48af2a.jpg)

**Comment by iteles** [comment]
Done! Check your email @markwilliamfirth :relaxed:

**Comment by markwilliamfirth** [comment]
<img width="709" alt="screenshot 2016-04-16 14 48 00" src="https://cloud.githubusercontent.com/assets/5732209/14581339/4091a344-03e2-11e6-8db8-3829b159a822.png">

**Comment by nelsonic** [comment]
Hi @markwilliamfirth, thanks again for doing that, how do we follow up on this request...? ❓

**Comment by markwilliamfirth** [comment]
@nelsonic they rejected it :'( I will submit again this weekend

**Comment by nelsonic** [comment]
Oh... wow. I wonder why...? did they give any feedback? (*thanks!*)

**Comment by nelsonic** [comment]
@iteles / @markwilliamfirth we should consider following up on this next time we are at an event at Twitter...?

**Comment by markwilliamfirth** [comment]
@nelsonic funny you say that I resubmitted the other day and it got rejected (again) so resubmitted again quoting the Twitter rules this time...still waiting to hear back

**Comment by iteles** [comment]
@markwilliamfirth 🙏 Thank you!

**Comment by nelsonic** [comment]
@markwilliamfirth 🍭 
(_did you mention to them that we have the ®️ ? 😉 _)

**Comment by markwilliamfirth** [comment]
Wording I used was:

"Dear Twitter Support, The username @DWYL is an inactive account. Under the username squatting policy and the Twitter rules (https://support.twitter.com/articles/18311), Twitter has the right to remove "Accounts that are inactive for more than six months". On the Username Squatting page (https://support.twitter.com/articles/18370), it states,"Note that we will not release squatted usernames except in cases of trademark infringement." The inactive username @DWYL infringes the trademark "DWYL", which is a registered trademark under the United Kingdom Intellectual Property Office (https://www.ipo.gov.uk/tmcase/Results/1/UK00003103535). The Twitter trademark violation policy states that Twitter, "may also release a username for the trademark holder's active use". This is creating confusion with our trademark as DWYL Ltd uses the username "DWYL" on many other websites, forums and online communities. Please release this username so that DWYL Ltd may use it to prevent confusion for users of the twitter platform."

Whether they accept it or not is another thing...problem is the @dwyl account technically isn't infringing on the violations unless we can prove it's causing confusion for users...

**Comment by nelsonic** [comment]
@markwilliamfirth thanks! ✨ 
Yeah, agree, the trademark thing is just so they know we aren't going to "_let it go_"... 😉

**Comment by markwilliamfirth** [comment]
Hello,
 
We've researched the reported account and determined that it is not in violation of our Terms of Service. The account is not being used in a way that is misleading or confusing, nor is it inactive at this time.
 
Please note that you may not be able to tell whether an account is currently inactive, as not all signs of account activity are publicly visible. For more information, please see our inactivity policy: https://support.twitter.com/articles/15362-inactive-account-policy.

Also, Twitter does not have a reservation policy for usernames and we do not suspend or release accounts unless they are in violation of our Rules (https://twitter.com/rules).
 
Thanks,

Twitter 

........ugh

**Comment by nelsonic** [comment]
>"_nor is it inactive at this time._" 

![minions-whaaaaat](https://cloud.githubusercontent.com/assets/194400/18184171/b415341a-708f-11e6-893e-9167faa6b61e.jpg)

https://twitter.com/dwyl
![twitter-dwyl-inactive](https://cloud.githubusercontent.com/assets/194400/18184233/fe64a6e0-708f-11e6-8147-e013fe959585.png)

Twitter are _Jokers_!

**Comment by markwilliamfirth** [comment]
I'm replying to them, seems like they keep hitting us with a template response

**Comment by nelsonic** [comment]
@markwilliamfirth thanks for being persistent... I don't _understand_ why they don't have _time_ to review your email properly... it feels a bit:

![computer says no...](http://i.imgur.com/XkU4Ajf.png)

**Comment by markwilliamfirth** [comment]
They ignored my email... -_-

Submitted a report again focusing on username squatting and referencing the confusion for users. Detailed DWYL's presence on Github (280 users, ~150 repos) and online communities where it is referred to as "@dwyl".

**Comment by nelsonic** [comment]
@markwilliamfirth _thanks_ for _persisting_ ... sadly with _some_ companies unless something will cause them to make or lose _money_ it's a low priority for them... 😞

**Comment by iteles** [comment]
Wow. You're a :star: for not giving up @markwilliamfirth!

**Comment by markwilliamfirth** [comment]
-_-

"Hello,
 
We've researched the reported account and determined that it is not in violation of Twitter's Trademark Policy. The account is not being used in a way that is misleading or confusing with regard to its brand, location or business affiliation.

Twitter does not have a username reservation policy. Users are free to select any name for their account, provided they do not violate Twitter's Terms of Service or Rules.

For more information about Twitter's Trademark Policy, please see:

http://support.twitter.com/articles/18367 
 
Thanks,
 
Twitter"

**Comment by markwilliamfirth** [comment]
@nelsonic @iteles at DWYL Summer plz can you ask participants to tweet @dwyl (not @dwylhq) with dwyl/coding related things.

I can use the tweets to create evidence of twitter user confusion. There are also some already on Twitter that I will compile.

I feel like this is the only way we're going to win. The handle needs to be confusing for users and the only way we can prove that is with "confused" users tweeting the 'wrong' handle.

**Comment by markwilliamfirth** [comment]
Doesn't need to be a lot of tweets, would actually be good if you could get a few people to send them on different days - spread out, so it looks less like we're faking it

**Comment by markwilliamfirth** [comment]
tweets featuring the dwyl logo would be ideal - linking the logo/brand and handle

**Comment by iteles** [comment]
So they just sent you the same email again? Seriously.

**Comment by iteles** [comment]
https://twitter.com/HayleySODA/status/755724195955433473 (I replied apologising for it being confusing!)

**Comment by nelsonic** [comment]
Let's re-visit this once we have a bit more "Trademark Justification"... 👍 
relates to: https://github.com/dwyl/hq/issues/39 and https://github.com/dwyl/hq/issues/41

**Comment by iteles** [comment]
Another case of mistaken identity: https://twitter.com/IamStan/status/791943530386075649

**Comment by markwilliamfirth** [comment]
@iteles this^ is perfect and exactly what we need. I will gather the evidence 🔍 and apply again :)

**Comment by markwilliamfirth** [comment]
I have sent in another submission:

<img width="698" alt="screen shot 2017-02-09 at 14 53 24" src="https://cloud.githubusercontent.com/assets/5732209/22788365/8d4be042-eed7-11e6-96d0-4b31980e8f29.png">

>Dear Sirs,

>I am writing to you from DWYL LTD, incorporated and registered in England and Wales with company number 09525434 whose registered office is at DWYL LTD, 104 Mary Datchelor Close, London, SE5 7DY, United Kingdom.

>I am writing to you to report the @DWYL account. This account is using the DWYL LTD trade mark in a manner that is confusing other users with regards to our brand affiliation. This is a violation of the Twitter Inc. trademark policy.

>DWYL LTD is a software company based in London, United Kingdom. We are currently working on software projects that involve contributions from over 300 people around the world. DWYL LTD is a remote-first organisation and has a presence in over 30 countries. DWYL LTD has an extensive presence online, using the username "DWYL" on many other websites, forums and online communities, most notably on Github (https://github.com/dwyl), where it has the username @DWYL. The @DWYL tag is used extensively on this website to refer to DWYL LTD. Due to the popular use of this handle, confusion has occurred on the Twitter platform where users have referred to @DWYL, thinking they are referring to DWYL LTD, when in fact they are referring to an inactive user account.

>Evidence of the confusion can be found from a number of users across the Twitter platform. I have included several links here for evidence of its occurrence:
>https://twitter.com/HayleySODA/status/755724195955433473
>https://twitter.com/IamStan/status/791943530386075649
>https://twitter.com/annabeltempest/status/598943030750670848
>https://twitter.com/MsKatbow/status/829699239643066369

>Confusion has occurred consistently over time and is expected to increase with frequency as DWYL LTD continues to grow its online presence. We are expected to have over 1000 online contributors to DWYL LTD Github projects by Q4 2017.

>DWYL LTD has had several clients report to us that they were unable to find us on Twitter after searching for @DWYL and being unable to find the correct user. This is very confusing for our clients, some of which include the London Science Museum and Thomas Cook. Some clients are successful in finding our current username, @dwylhq, but they have also reported to us that they were confused at first when searching for DWYL LTD on Twitter.

>The Twitter username squatting policy and the Twitter rules state that Twitter has the right to remove "Accounts that are inactive for more than six months". The inactive username @DWYL infringes the trade mark "DWYL", which is a registered trade mark under the United Kingdom Intellectual Property Office with trade mark number UK00003103535  (https://www.ipo.gov.uk/tmcase/Results/1/UK00003103535).

>DWYL LTD is requesting Twitter Inc to release the @DWYL username for the use of DWYL LTD due to the current violation of the Twitter Inc trademark policy. Releasing the username for the use of DWYL LTD will prevent confusion for current and future users of the Twitter platform.

>Yours sincerely,

>Mark W. Firth
>Chief Operating Officer | DWYL LTD

Will update as things progress! 👍

**Comment by markwilliamfirth** [comment]
<img width="735" alt="screen shot 2017-02-15 at 21 49 50" src="https://cloud.githubusercontent.com/assets/5732209/22997037/c60de75e-f3c8-11e6-8610-9132f3d0a96d.png">

RAAAAAAGGGGEEEEE 😠

**Comment by nelsonic** [comment]
It's _clearly_ a canned response ...
![computer says no](http://i.giphy.com/JliGmPEIgzGLe.gif)
We need to speak to a _human_ about this.
Also, I get the feeling that a [US Trademark](https://github.com/dwyl/hq/issues/228) will _help_ ...

**Comment by markwilliamfirth** [comment]
Yeah at this stage I feel like we're only gonna get it if we

- Use our connections to speak to someone on the inside
or
- Acquire the .com and US trademark and then send a letter from a lawyer

**Comment by markwilliamfirth** [comment]
To close this issue:

I replied with one line saying, "I would like to dispute this decision and discuss the outcome with a representative of Twitter."

20 minutes later they changed the username

They changed to @DWYL - we had to submit a support request to change it to lowercase letters as they don't allow you to change it to something less than 5 characters (even if it's only casing you're changing)

We now have the @dwyl handle - closed
