### ISSUE TITLE
dwyl annual returns

### ISSUE THREAD

**Issue by iteles** [dwyl/hq#97]
Due 28 days after the financial year ends: https://www.gov.uk/file-an-annual-return-with-companies-house

**Comment by nelsonic** [comment]
Want to do this this evening?

**Comment by iteles** [comment]
Sure! I was going to do a whole day of financials tomorrow but if you have time this evening it would be good to get it out the way.

**Comment by iteles** [comment]
Completed.

**Comment by nelsonic** [comment]
@iteles did you do this for ideaQ ? (*if not let me know soon...*)

**Comment by iteles** [comment]
@nelsonic No, I don't have the pw for companieshouse - if you let me know what it is, I have the authentication code on hand and can do it now in 5 mins.

We didn't get any notifications by post *or* email to get them done (like we did a few times for dwyl) so I thought the deadline might be different.

**Comment by nelsonic** [comment]
Replied via chat. 👍 
Thanks for sorting. ✅

**Comment by iteles** [comment]
Done!
