### ISSUE TITLE
Decide whether it's worth applying for the British Library's Innovating for Growth programme

### ISSUE THREAD

**Issue by iteles** [dwyl/hq#98]
£10,000 of business support over the course of 3 months.

http://www.bl.uk/britishlibrary/~/media/bl/global/business%20and%20ip%20centre/documents/innovating%20for%20growth%20a4%20digital%20brochure%202016%20v2.pdf

**Comment by markwilliamfirth** [comment]
Apply before Friday 8 December 2017 to be a part of our Jan-March 2018 cohort.

**Comment by iteles** [comment]
A deadline. No information to summarise the scheme, pros and cons, no actual work to save others in the organisation work done. 

Closing as no longer relevant.
