### ISSUE TITLE
Investigate new registered offices

### ISSUE THREAD

**Issue by iteles** [dwyl/hq#99]
Ones that allow for just mail so that we can change the registered office address on our website (too public facing at the moment).

**Comment by markwilliamfirth** [comment]
Btw - even if you change the business address, the details of your old address will still be visible in the history of the public Companies House database.

**Comment by iteles** [comment]
@markwilliamfirth Helpful to know, but at least people will have to dig a little!

(this is not the place to discuss, but we should all have a breakfast catch up soon!)

**Comment by markwilliamfirth** [comment]
@iteles agreed! 👍

**Comment by nelsonic** [comment]
@markwilliamfirth yeah, people being able to _look up_ our "old" address on Companies house isn't a major issue, its more that the address should be something a bit more "Professional", _preferably_ with a mail scanning service so we can receive paper correspondence _remotely_... 😉

**Comment by markwilliamfirth** [comment]
Closed until decision made about QuietSpace
